.set LOCALID_NURSE, 1

SaffronPokecenter_MapScripts::
map_script MAP_SCRIPT_ON_TRANSITION, SaffronPokecenter_OnTransition
	.byte 0

SaffronPokecenter_OnTransition::
	setrespawn HEAL_LOCATION_SAFFRON_CITY
	end

SaffronPokecenter_EventScript_Teacher::
	msgbox SaffronPokecenter1F_Text_Teacher, MSGBOX_NPC	
	end

SaffronPokecenter_EventScript_Fisher::
	goto_if_set FLAG_RETURNED_MACHINE_PART, SaffronPokecenter_EventScript_FisherReturnedMachinePart
	msgbox SaffronPokecenter1F_Text_Fisher, MSGBOX_NPC	
	end
SaffronPokecenter_EventScript_FisherReturnedMachinePart::
	msgbox SaffronPokecenter1F_Text_Fisher_ReturnedPart, MSGBOX_NPC
	end

SaffronPokecenter_EventScript_Youngster::
	msgbox SaffronPokecenter1F_Text_Youngster, MSGBOX_NPC
	end

SaffronPokecenter1F_Text_Teacher:
	.string "What are JOHTO's POKéMON CENTERS\n"
	.string "like?\p"
	.string "…Oh, I see. So they're not much\n"
	.string "different from the ones in KANTO.\p"
	.string "I can go to JOHTO without\n"
	.string "worrying, then!$"

SaffronPokecenter1F_Text_Fisher:
	.string "I just happened to come through\n"
	.string "ROCK TUNNEL.\p"
	.string "There was some commotion at the\n"
	.string "POWER PLANT.$"

SaffronPokecenter1F_Text_Fisher_ReturnedPart:
	.string "Caves collapse easily.\p"
	.string "Several caves have disappeared in\n"
	.string "the past few years, like the one\l"
	.string "outside CERULEAN.\p"
	.string "As a pro HIKER, that's common\n"
	.string "knowledge.$"

SaffronPokecenter1F_Text_Youngster:
	.string "SILPH CO.'s HEAD OFFICE and the\n"
	.string "MAGNET TRAIN STATION--they're the\l"
	.string "places to see in SAFFRON.$"
