Route25BillsHouse_MapScripts::
	.byte 0

Route25BillsHouse_Text_GrandpaIntro:
	.string "Hm? You know BILL? He's my\n"
	.string "grandson.\p"
	.string "He's in JOHTO. He does\n"
	.string "something\p"
	.string "with PCs, so I'm house-\n"
	.string "sitting.$"

Route25BillsHouse_Text_AskToSeeMon:
	.string "If you have that POKéMON, may I\n"
	.string "see it, please?$"

Route25BillsHouse_Text_ExcitedToSee:
	.string "You will show me? How good of\n"
	.string "you!$"

Route25BillsHouse_Text_YouDontHaveIt:
	.string "You don't have it?\n"
	.string "That's too bad…$"

Route25BillsHouse_Text_ShownPokemon:
	.string "Ah, so that is {STRING}?\p"
	.string "Isn't it cute! That's so kind\n"
	.string "of you.$"

Route25BillsHouse_Text_Appreciation:
	.string "Thanks!\p"
	.string "This is a token of my\n"
	.string "appreciation.$"

Route25BillsHouse_Text_ComeAgain:
	.string "Come visit again sometime.$"

Route25BillsHouse_Text_ShownAll:
	.string "Thanks for showing me so many\n"
	.string "cute POKéMON.\p"
	.string "I really enjoyed myself. I'm\n"
	.string "glad\p"
	.string "I've lived such a long life.$"

Route25BillsHouse_Text_WrongPokemon:
	.string "Hm?\p"
	.string "That's not the POKéMON that I\n"
	.string "was told about.$"

Route25BillsHouse_Text_Lickitung:
	.string "My grandson BILL told me about\n"
	.string "a POKéMON that has a\p"
	.string "long tongue.$"

Route25BillsHouse_Text_Oddish:
	.string "Ah, my grandson mentioned a\n"
	.string "round,\p"
	.string "green POKéMON that has leaves\n"
	.string "growing on its head.$"

Route25BillsHouse_Text_Staryu:
	.string "Do you know of a sea POKéMON\n"
	.string "that\p"
	.string "has a red sphere in its body?\p"
	.string "You know, the one that's shaped\n"
	.string "like a star?\p"
	.string "I heard that it appears at\n"
	.string "night.\p"
	.string "I would surely like to see it.$"

Route25BillsHouse_Text_Growlithe:
	.string "BILL told me about a POKéMON\n"
	.string "that is\p"
	.string "very loyal to its trainer.\p"
	.string "It's supposed to ROAR well.$"

Route25BillsHouse_Text_Vulpix:
	.string "I heard about a cute POKéMON\n"
	.string "that has six tails.\p"
	.string "I would love to hug a cute\n"
	.string "POKéMON like that.$"

Route25BillsHouse_Text_Pichu:
	.string "Do you know that hugely popular\n"
	.string "POKéMON?\p"
	.string "The POKéMON that has a yellow\n"
	.string "body and red cheeks.\p"
	.string "I would love to see what it\n"
	.string "looks\l"
	.string "like before it evolves.$"

