FallarborTown_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "Je vous souhaite la bienvenue au BATTLE TENT\n"
	.string "SITE DE FALLARBOR !\p"
	.string "Je suis votre guide pour le Tournoi KO Fixe !$"

FallarborTown_BattleTentLobby_Text_TakeChallenge:
	.string "Alors, souhaitez-vous relever le défi\n"
	.string "du Tournoi KO Fixe ?$"

FallarborTown_BattleTentLobby_Text_AwaitAnotherChallenge:
	.string "Nous attendons votre défi à\n"
	.string "une autre occasion !$"

FallarborTown_BattleTentLobby_Text_ExplainFallarborTent:
	.string "Dans le BATTLE TENT de FALLARBOR,\n"
	.string "nous organisons le Tournoi KO Fixe.\p"
	.string "Tous les participants entrent avec une équipe de\n"
	.string "trois POKéMON.\p"
	.string "Les trois POKéMON doivent être alignés\n"
	.string "dans l'ordre dans lequel ils apparaîtront.\p"
	.string "Pendant le combat, les POKéMON apparaîtront\n"
	.string "un à un dans l'ordre prédéfini.\p"
	.string "Une fois qu'un POKéMON entre en combat, il doit\n"
	.string "rester jusqu'à la fin du match.\p"
	.string "Si un match n'est pas décidé en\n"
	.string "trois tours, il sera jugé.\p"
	.string "Si vous souhaitez interrompre votre défi,\n"
	.string "veuillez sauvegarder la partie.\p"
	.string "Si vous ne sauvegardez pas, vous ne pourrez pas\n"
	.string "continuer votre défi.\p"
	.string "Si vous réussissez à battre\n"
	.string "trois DRESSEURS d'affilée,\l"
	.string "nous vous offrirons un beau prix.$"

FallarborTown_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "Avant de vous montrer le BATTLE\n"
	.string "TENT, je dois sauvegarder. Est-ce d'accord ?$"

@ Unused
FallarborTown_BattleTentLobby_Text_WhichLevelMode:
	.string "Nous proposons deux niveaux de défi,\n"
	.string "Niveau 50 et Niveau Libre.\l"
	.string "Quel est votre choix ?$"

FallarborTown_BattleTentLobby_Text_SelectThreeMons:
	.string "Très bien, veuillez maintenant choisir\n"
	.string "vos trois POKéMON, s'il vous plaît.$"

FallarborTown_BattleTentLobby_Text_NotEnoughValidMonsLv50:
	.string "Mon cher challenger !\p"
	.string "Vous n'avez pas les trois POKéMON\n"
	.string "requis pour participer.\p"
	.string "Ils ne doivent pas non plus tenir les mêmes\n"
	.string "types d'objets.\p"
	.string "ŒUFS{STR_VAR_1} inéligibles.\p"
	.string "Quand vous serez prêt,\n"
	.string "revenez nous voir.$"

FallarborTown_BattleTentLobby_Text_NotEnoughValidMonsLvOpen:
	.string "Mon cher challenger !\p"
	.string "Vous n'avez pas les trois POKéMON\n"
	.string "requis pour participer.\p"
	.string "Pour participer, vous devez apporter trois\n"
	.string "POKéMON différents.\p"
	.string "Ils ne doivent pas non plus tenir les mêmes\n"
	.string "types d'objets.\p"
	.string "ŒUFS{STR_VAR_1} inéligibles.\p"
	.string "Quand vous serez prêt,\n"
	.string "revenez nous voir.$"

FallarborTown_BattleTentLobby_Text_GuideYouToBattleTent:
	.string "Je vais maintenant vous guider vers\n"
	.string "le BATTLE TENT.$"

FallarborTown_BattleTentLobby_Text_DidntSaveBeforeQuitting:
	.string "Mon cher challenger !\p"
	.string "Vous n'avez pas sauvegardé la partie avant\n"
	.string "d'éteindre, n'est-ce pas ?\p"
	.string "Malheureusement, cela a entraîné\n"
	.string "votre disqualification\l"
	.string "de votre défi.\p"
	.string "Vous pouvez bien sûr recommencer\n"
	.string "un nouveau défi.$"

FallarborTown_BattleTentLobby_Text_BeatThreeTrainers:
	.string "Splendide ! Vous avez battu\n"
	.string "trois DRESSEURS d'affilée !$"

FallarborTown_BattleTentLobby_Text_WaitWhileSaveGame:
	.string "Veuillez patienter pendant que je sauvegarde la partie.$"

FallarborTown_BattleTentLobby_Text_PresentYouWithPrize:
	.string "En commémoration de votre série de 3 victoires,\n"
	.string "nous vous offrons ce prix.$"

FallarborTown_BattleTentLobby_Text_ReceivedPrize:
	.string "{PLAYER} a reçu le prix\n"
	.string "{STR_VAR_1}.$"

FallarborTown_BattleTentLobby_Text_BagFullReturnForPrize:
	.string "Oh ?\n"
	.string "Votre SAC semble plein.\p"
	.string "Je vous invite à faire de la place et\n"
	.string "à revenir pour votre prix.$"

FallarborTown_BattleTentLobby_Text_ThankYouWaitWhileSaving:
	.string "Merci beaucoup pour votre participation !\p"
	.string "Veuillez patienter pendant que je sauvegarde la partie.$"

FallarborTown_BattleTentLobby_Text_AwaitAnotherChallenge2:
	.string "Nous attendons votre défi à\n"
	.string "une autre occasion !$"

FallarborTown_BattleTentLobby_Text_LookingForwardToArrival:
	.string "Nous attendions avec impatience\n"
	.string "votre arrivée.\p"
	.string "Avant de vous montrer le BATTLE TENT,\n"
	.string "je dois sauvegarder la partie. Veuillez patienter.$"

VerdanturfTown_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "Je vous souhaite la bienvenue au BATTLE TENT\n"
	.string "SITE DE VERDURANDE !\p"
	.string "Ici, la confiance du DRESSEUR envers\n"
	.string "les POKéMON est mise à l'épreuve.$"

VerdanturfTown_BattleTentLobby_Text_TakeChallenge:
	.string "Souhaitez-vous relever le défi du\n"
	.string "BATTLE TENT de VERDURANDE ?$"

VerdanturfTown_BattleTentLobby_Text_ExplainVerdanturfTent:
	.string "Dans le BATTLE TENT de VERDURANDE,\n"
	.string "il y a une règle cruciale à respecter.\l"
	.string "\p"
	.string "Les DRESSEURS ne peuvent que changer\n"
	.string "leurs POKéMON.\p"
	.string "Les DRESSEURS ne peuvent pas donner d'autres\n"
	.string "ordres à leurs POKéMON.\p"
	.string "Les POKéMON agissent selon leur nature\n"
	.string "et combattent seuls.\p"
	.string "Vous devez faire confiance à vos\n"
	.string "POKéMON et les observer.\p"
	.string "Si vous avez l'honneur de battre\n"
	.string "trois DRESSEURS d'affilée,\l"
	.string "nous vous offrirons un prix.\p"
	.string "Si vous souhaitez interrompre votre\n"
	.string "défi, veuillez sauvegarder la partie.\p"
	.string "Si vous ne sauvegardez pas avant d'interrompre,\n"
	.string "vous serez disqualifié.$"

VerdanturfTown_BattleTentLobby_Text_ReturnFortified:
	.string "Quand vous aurez fortifié votre cœur\n"
	.string "et vos POKéMON, vous devrez revenir.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_WhichLevelMode:
	.string "Il y a deux niveaux de difficulté,\n"
	.string "Niveau 50 et Niveau Libre.\l"
	.string "Quel niveau choisissez-vous ?$"

VerdanturfTown_BattleTentLobby_Text_NotEnoughValidMonsLv50:
	.string "Soupir…\p"
	.string "Vous n'avez pas les trois POKéMON\n"
	.string "requis pour le défi.\p"
	.string "Pour participer, vous devez fournir trois\n"
	.string "POKéMON différents.\p"
	.string "Ils ne doivent pas non plus tenir\n"
	.string "le même type d'objet.\p"
	.string "ŒUFS{STR_VAR_1} inéligibles.\p"
	.string "Revenez quand vous serez prêt.$"

VerdanturfTown_BattleTentLobby_Text_NotEnoughValidMonsLvOpen:
	.string "Soupir…\p"
	.string "Vous n'avez pas les trois POKéMON\n"
	.string "requis pour le défi.\p"
	.string "Pour participer, vous devez fournir trois\n"
	.string "POKéMON différents.\p"
	.string "Ils ne doivent pas non plus tenir\n"
	.string "le même type d'objet.\p"
	.string "ŒUFS{STR_VAR_1} inéligibles.\p"
	.string "Revenez quand vous serez prêt.$"

VerdanturfTown_BattleTentLobby_Text_SelectThreeMons:
	.string "Bien. Maintenant, vous devez choisir vos\n"
	.string "trois POKéMON.$"

VerdanturfTown_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "Je dois sauvegarder avant de vous montrer\n"
	.string "le BATTLE TENT. Est-ce d'accord ?$"

VerdanturfTown_BattleTentLobby_Text_NowFollowMe:
	.string "Bien.\n"
	.string "Maintenant, suivez-moi.$"

VerdanturfTown_BattleTentLobby_Text_ResultsWillBeRecorded:
	.string "Je me sens honoré d'avoir vu\n"
	.string "les exploits de vos POKéMON.\p"
	.string "Les résultats seront enregistrés.\n"
	.string "Je vous demande de patienter un instant.$"

VerdanturfTown_BattleTentLobby_Text_AchievedThreeWinStreak:
	.string "Pour réaliser une série de 3 victoires…\p"
	.string "Les liens entre votre cœur et\n"
	.string "vos POKéMON semblent forts et sincères.$"

VerdanturfTown_BattleTentLobby_Text_FeatWillBeRecorded:
	.string "Votre exploit sera enregistré.\n"
	.string "Je vous demande de patienter un instant.$"

VerdanturfTown_BattleTentLobby_Text_PresentYouWithPrize:
	.string "Pour votre série de 3 victoires,\n"
	.string "nous vous offrons ce prix.$"

SlateportCity_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "Bienvenue au BATTLE TENT\n"
	.string "SITE DE POIVRESSEL !\p"
	.string "Je suis votre guide pour le Tournoi\n"
	.string "Échange de Combat.$"

SlateportCity_BattleTentLobby_Text_TakeChallenge:
	.string "Souhaitez-vous relever le défi\n"
	.string "Échange de Combat ?$"

SlateportCity_BattleTentLobby_Text_ExplainSlateportTent:
	.string "Ici, au BATTLE TENT de POIVRESSEL,\n"
	.string "nous organisons des événements Échange de Combat\l"
	.string "avec des POKéMON de location.\p"
	.string "D'abord, trois POKéMON vous seront prêtés\n"
	.string "spécialement pour cet événement.\p"
	.string "Avec les POKéMON de location fournis,\n"
	.string "vous devez mener un COMBAT SOLO.\p"
	.string "Si vous gagnez, vous pouvez échanger\n"
	.string "l'un de vos POKéMON de location.\p"
	.string "Répétez ce cycle de combat et d'échange—si vous gagnez\n"
	.string "trois fois de suite, vous recevrez un beau prix.\p"
	.string "Si vous souhaitez interrompre votre\n"
	.string "défi, veuillez sauvegarder la partie.\p"
	.string "Si vous ne sauvegardez pas avant d'interrompre,\n"
	.string "vous serez disqualifié.$"

SlateportCity_BattleTentLobby_Text_LookForwardToNextVisit:
	.string "Nous attendons votre prochaine visite avec impatience.$"

@ Unused
SlateportCity_BattleTentLobby_Text_WhichLevelMode:
	.string "Quel niveau souhaitez-vous défier ?\n"
	.string "Niveau 50 ou Niveau 100 ?$"

SlateportCity_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "Avant de commencer votre défi,\n"
	.string "je dois sauvegarder les données. Est-ce d'accord ?$"

@ Unused
SlateportCity_BattleTentLobby_Text_HoldMonsForSafekeeping:
	.string "D'accord, je garderai vos POKéMON en sécurité\n"
	.string "pendant que vous participez.$"

SlateportCity_BattleTentLobby_Text_StepThisWay:
	.string "Veuillez me suivre par ici.$"

SlateportCity_BattleTentLobby_Text_ReturnRentalMonsSaveResults:
	.string "Merci d'avoir participé !\p"
	.string "Je vais vous rendre vos POKéMON en échange\n"
	.string "de nos POKéMON de location.\p"
	.string "Je dois aussi sauvegarder vos résultats.\n"
	.string "Veuillez patienter.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReturnMonsExchangeRentals:
	.string "Je vais vous rendre vos POKéMON en échange\n"
	.string "de nos POKéMON de location.$"

SlateportCity_BattleTentLobby_Text_WonThreeMatchesReturnMons:
	.string "Félicitations !\n"
	.string "Vous avez gagné trois matchs d'affilée !\p"
	.string "Je vais vous rendre vos POKéMON en échange\n"
	.string "de nos POKéMON de location.\p"
	.string "Je dois aussi sauvegarder vos résultats.\n"
	.string "Veuillez patienter.$"

SlateportCity_BattleTentLobby_Text_AwardYouThisPrize:
	.string "En reconnaissance de votre série de 3 victoires,\n"
	.string "nous vous remettons ce prix.$"

SlateportCity_BattleTentLobby_Text_NoRoomInBagMakeRoom:
	.string "Oh ?\n"
	.string "Vous n'avez plus de place pour cela.\p"
	.string "Veuillez faire de la place dans votre SAC et\n"
	.string "revenez me voir.$"

SlateportCity_BattleTentLobby_Text_BeenWaitingForYou:
	.string "Nous vous attendions !\p"
	.string "Avant de reprendre votre défi,\n"
	.string "je dois sauvegarder la partie.$"

SlateportCity_BattleTentLobby_Text_DidntSaveBeforeQuitting:
	.string "Je suis désolé de vous dire que vous n'avez pas\n"
	.string "sauvegardé avant de quitter la dernière fois.\p"
	.string "En conséquence, vous avez été disqualifié\n"
	.string "de votre défi.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReturnPersonalMons:
	.string "Nous allons vous rendre vos POKéMON personnels.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReceivedPrize:
	.string "{PLAYER} a reçu le prix\n"
	.string "{STR_VAR_1}.$"

@ Unused
SlateportCity_BattleTentLobby_Text_RulesAreListed:
	.string "Les règles de l'Échange de Combat sont listées.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReadWhichHeading:
	.string "Quel titre voulez-vous lire ?$"

SlateportCity_BattleTentLobby_Text_ExplainBasicRules:
	.string "Dans un événement Échange de Combat, vous ne pouvez utiliser\n"
	.string "que trois POKéMON.\p"
	.string "Que vous louiez ou échangiez,\n"
	.string "votre équipe ne peut pas avoir deux ou plus\l"
	.string "du même POKéMON.$"

SlateportCity_BattleTentLobby_Text_ExplainSwapPartnerRules:
	.string "Vous ne pouvez échanger des POKéMON qu'avec\n"
	.string "le DRESSEUR que vous venez de battre.\p"
	.string "Vous ne pouvez échanger que contre les POKéMON\n"
	.string "utilisés par le DRESSEUR battu.$"

SlateportCity_BattleTentLobby_Text_ExplainSwapNumberRules:
	.string "Après chaque combat gagné, vous pouvez\n"
	.string "échanger contre un des POKéMON de votre adversaire\l"
	.string "vaincu.\p"
	.string "Vous ne pourrez pas échanger de POKéMON\n"
	.string "avec le troisième DRESSEUR de l'événement.$"

SlateportCity_BattleTentLobby_Text_ExplainSwapNotes:
	.string "Il y a deux points clés à connaître\n"
	.string "lors de l'échange de POKéMON.\p"
	.string "Premièrement, lors d'un échange, vous ne pouvez pas vérifier\n"
	.string "les stats du POKéMON que vous allez\l"
	.string "recevoir.\p"
	.string "Deuxièmement, les POKéMON de votre équipe\n"
	.string "sont alignés selon l'ordre dans lequel vous les avez loués.\p"
	.string "Cet ordre reste inchangé\n"
	.string "même après des échanges.$"

SlateportCity_BattleTentLobby_Text_ExplainMonRules:
	.string "Les POKéMON du BATTLE TENT de POIVRESSEL\n"
	.string "sont tous des locations.\p"
	.string "Tous les POKéMON de location sont au\n"
	.string "Niveau 30.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_RulesAreListed2:
	.string "Les règles du BATTLE TENT de VERDURANDE\n"
	.string "sont listées.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ReadWhichHeading:
	.string "Quel titre voulez-vous lire ?$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainBasicRules:
	.string "Ici, au BATTLE TENT de VERDURANDE,\n"
	.string "les POKéMON doivent réfléchir et\l"
	.string "combattre par eux-mêmes.\p"
	.string "Contrairement à la nature, les POKéMON qui vivent\n"
	.string "avec des humains se comportent différemment\l"
	.string "selon leur nature.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainNatureRules:
	.string "Selon sa nature, un POKéMON\n"
	.string "peut préférer attaquer quoi qu'il arrive.\p"
	.string "Un autre POKéMON peut préférer se protéger\n"
	.string "de tout danger.\p"
	.string "Un autre encore peut aimer embêter ou\n"
	.string "déconcerter ses adversaires.\p"
	.string "Selon sa nature, un POKéMON\n"
	.string "aura des attaques favorites qu'il maîtrise\l"
	.string "particulièrement.\p"
	.string "Il peut aussi ne pas aimer certaines attaques\n"
	.string "qu'il a du mal à utiliser.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainMoveRules:
	.string "Il y a des attaques offensives qui infligent\n"
	.string "des dégâts directs à l'adversaire.\p"
	.string "Il y a des attaques défensives qui servent\n"
	.string "à se préparer aux attaques ennemies ou\l"
	.string "à soigner les PV, etc.\p"
	.string "Il y a aussi d'autres attaques un peu étranges\n"
	.string "qui peuvent affaiblir les adversaires avec\l"
	.string "des problèmes de stats comme le poison et\l"
	.string "la paralysie.\p"
	.string "Les POKéMON envisageront d'utiliser des attaques dans\n"
	.string "ces trois catégories.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainUnderpoweredRules:
	.string "Lorsqu'il n'est pas sous le commandement de son DRESSEUR,\n"
	.string "un POKéMON peut ne pas réussir à utiliser\l"
	.string "certaines attaques efficacement.\p"
	.string "Un POKéMON n'est pas doué pour utiliser une attaque\n"
	.string "qu'il n'aime pas.\p"
	.string "Si un POKéMON ne connaît que des attaques qui\n"
	.string "ne correspondent pas à sa nature, il sera souvent\l"
	.string "incapable d'exprimer tout son potentiel.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainWhenInDangerRules:
	.string "Selon sa nature, un POKéMON peut\n"
	.string "commencer à utiliser des attaques qui ne correspondent pas à sa\l"
	.string "nature lorsqu'il est en difficulté.\p"
	.string "Si un POKéMON commence à agir étrangement\n"
	.string "dans une situation critique, surveillez-le attentivement.$"

BattleTentLobby_Text_ExplainLevelRules:
	.string "Dans ce BATTLE TENT, les niveaux de\n"
	.string "vos adversaires seront ajustés pour\l"
	.string "correspondre à ceux de vos POKéMON.\p"
	.string "Cependant, aucun DRESSEUR que vous affronterez n'aura\n"
	.string "de POKéMON en dessous du niveau 30.$"

VerdanturfTown_BattleTentLobby_Text_RulesAreListed:
	.string "Les règles du BATTLE TENT de VERDURANDE\n"
	.string "sont listées.$"
