BattleDome_Text_Potential1::
	.string "Le meilleur candidat pour devenir champion !$"

BattleDome_Text_Potential2::
	.string "Une équipe sûre d'aller en finale.$"

BattleDome_Text_Potential3::
	.string "Une équipe probablement dans le top 3.$"

BattleDome_Text_Potential4::
	.string "Une équipe candidate à la première place.$"

BattleDome_Text_Potential5::
	.string "Une équipe au potentiel de haut niveau.$"

BattleDome_Text_Potential6::
	.string "L'équipe outsider de ce tournoi.$"

BattleDome_Text_Potential7::
	.string "Une équipe au-dessus de la moyenne.$"

BattleDome_Text_Potential8::
	.string "L'équipe moyenne de ce tournoi.$"

BattleDome_Text_Potential9::
	.string "Une équipe au potentiel moyen.$"

BattleDome_Text_Potential10::
	.string "Une équipe en dessous de la moyenne.$"

BattleDome_Text_Potential11::
	.string "Une équipe en quête de sa première victoire.$"

BattleDome_Text_Potential12::
	.string "Une victoire rendra cette équipe fière.$"

BattleDome_Text_Potential13::
	.string "Dans l'ensemble, une équipe faible.$"

BattleDome_Text_Potential14::
	.string "Une équipe au potentiel très faible.$"

BattleDome_Text_Potential15::
	.string "Une équipe peu susceptible de gagner le tournoi.$"

BattleDome_Text_Potential16::
	.string "L'équipe la moins susceptible de gagner.$"

BattleDome_Text_PotentialDomeAceTucker::
	.string "La superstar parfaite et invincible !$"

BattleDome_Text_StyleRiskDisaster::
	.string "Prêt à risquer le désastre total parfois.$"

BattleDome_Text_StyleEndureLongBattles::
	.string "Doué pour endurer de longs combats.$"

BattleDome_Text_StyleVariesTactics::
	.string "Varie ses tactiques selon l'adversaire.$"

BattleDome_Text_StyleToughWinningPattern::
	.string "Possède une stratégie gagnante solide.$"

BattleDome_Text_StyleUsesVeryRareMove::
	.string "Utilise parfois une capacité très rare.$"

BattleDome_Text_StyleUsesStartlingMoves::
	.string "Utilise des attaques surprenantes et perturbatrices.$"

BattleDome_Text_StyleConstantlyWatchesHP::
	.string "Surveille constamment ses PV en combat.$"

BattleDome_Text_StyleStoresAndLoosesPower::
	.string "Bon pour accumuler puis libérer sa puissance.$"

BattleDome_Text_StyleEnfeeblesFoes::
	.string "Doué pour affaiblir ses adversaires.$"

BattleDome_Text_StylePrefersLuckTactics::
	.string "Préfère les tactiques basées sur la chance.$"

BattleDome_Text_StyleRegalAtmosphere::
	.string "Attaque avec une aura royale.$"

BattleDome_Text_StylePowerfulLowPPMoves::
	.string "Utilise des attaques puissantes à peu de PP.$"

BattleDome_Text_StyleEnfeebleThenAttack::
	.string "Affaiblit puis attaque avec talent.$"

BattleDome_Text_StyleBattlesWhileEnduring::
	.string "Se bat en encaissant toutes les attaques.$"

BattleDome_Text_StyleUpsetsFoesEmotionally::
	.string "Doué pour déstabiliser ses adversaires.$"

BattleDome_Text_StyleStrongAndStraightforward::
	.string "Utilise des attaques fortes et directes.$"

BattleDome_Text_StyleAggressivelyStrongMoves::
	.string "Utilise agressivement des attaques puissantes.$"

BattleDome_Text_StyleCleverlyDodgesAttacks::
	.string "Se bat en esquivant habilement les attaques.$"

BattleDome_Text_StyleUsesUpsettingMoves::
	.string "Maîtrise les attaques déstabilisantes.$"

BattleDome_Text_StyleUsesPopularMoves::
	.string "Utilise de nombreuses attaques populaires.$"

BattleDome_Text_StyleHasPowerfulComboMoves::
	.string "Possède des attaques pour de puissantes combinaisons.$"

BattleDome_Text_StyleUsesHighProbabilityMoves::
	.string "Utilise des attaques à forte probabilité de succès.$"

BattleDome_Text_StyleAggressivelySpectacularMoves::
	.string "Utilise agressivement des attaques spectaculaires.$"

BattleDome_Text_StyleEmphasizesOffenseOverDefense::
	.string "Privilégie l'attaque à la défense.$"

BattleDome_Text_StyleEmphasizesDefenseOverOffense::
	.string "Privilégie la défense à l'attaque.$"

BattleDome_Text_StyleAttacksQuicklyStrongMoves::
	.string "Attaque rapidement avec des coups puissants.$"

BattleDome_Text_StyleUsesAddedEffectMoves::
	.string "Utilise souvent des attaques à effets secondaires.$"

BattleDome_Text_StyleUsesBalancedMixOfMoves::
	.string "Utilise un mélange équilibré d'attaques.$"

BattleDome_Text_StyleSampleMessage1::
	.string "Ceci est le message d'exemple 1.$"

BattleDome_Text_StyleSampleMessage2::
	.string "Ceci est le message d'exemple 2.$"

BattleDome_Text_StyleSampleMessage3::
	.string "Ceci est le message d'exemple 3.$"

BattleDome_Text_StyleSampleMessage4::
	.string "Ceci est le message d'exemple 4.$"

BattleDome_Text_EmphasizesHPAndAtk::
	.string "Met l'accent sur les PV et l'ATTAQUE.$"

BattleDome_Text_EmphasizesHPAndDef::
	.string "Met l'accent sur les PV et la DÉFENSE.$"

BattleDome_Text_EmphasizesHPAndSpeed::
	.string "Met l'accent sur les PV et la VITESSE.$"

BattleDome_Text_EmphasizesHPAndSpAtk::
	.string "Met l'accent sur les PV et l'ATQ. SPÉ.$"

BattleDome_Text_EmphasizesHPAndSpDef::
	.string "Met l'accent sur les PV et la DÉF. SPÉ.$"

BattleDome_Text_EmphasizesAtkAndDef::
	.string "Met l'accent sur l'ATTAQUE et la DÉFENSE.$"

BattleDome_Text_EmphasizesAtkAndSpeed::
	.string "Met l'accent sur l'ATTAQUE et la VITESSE.$"

BattleDome_Text_EmphasizesAtkAndSpAtk::
	.string "Met l'accent sur l'ATTAQUE et l'ATQ. SPÉ.$"

BattleDome_Text_EmphasizesAtkAndSpDef::
	.string "Met l'accent sur l'ATTAQUE et la DÉF. SPÉ.$"

BattleDome_Text_EmphasizesDefAndSpeed::
	.string "Met l'accent sur la DÉFENSE et la VITESSE.$"

BattleDome_Text_EmphasizesDefAndSpAtk::
	.string "Met l'accent sur la DÉFENSE et l'ATQ. SPÉ.$"

BattleDome_Text_EmphasizesDefAndSpDef::
	.string "Met l'accent sur la DÉFENSE et la DÉF. SPÉ.$"

BattleDome_Text_EmphasizesSpeedAndSpAtk::
	.string "Met l'accent sur la VITESSE et l'ATQ. SPÉ.$"

BattleDome_Text_EmphasizesSpeedAndSpDef::
	.string "Met l'accent sur la VITESSE et la DÉF. SPÉ.$"

BattleDome_Text_EmphasizesSpAtkAndSpDef::
	.string "Met l'accent sur l'ATQ. SPÉ. et la DÉF. SPÉ.$"

BattleDome_Text_EmphasizesHP::
	.string "Met l'accent sur les PV.$"

BattleDome_Text_EmphasizesAtk::
	.string "Met l'accent sur l'ATTAQUE.$"

BattleDome_Text_EmphasizesDef::
	.string "Met l'accent sur la DÉFENSE.$"

BattleDome_Text_EmphasizesSpeed::
	.string "Met l'accent sur la VITESSE.$"

BattleDome_Text_EmphasizesSpAtk::
	.string "Met l'accent sur l'ATQ. SPÉ.$"

BattleDome_Text_EmphasizesSpDef::
	.string "Met l'accent sur la DÉF. SPÉ.$"

BattleDome_Text_NeglectsHPAndAtk::
	.string "Néglige les PV et l'ATTAQUE.$"

BattleDome_Text_NeglectsHPAndDef::
	.string "Néglige les PV et la DÉFENSE.$"

BattleDome_Text_NeglectsHPAndSpeed::
	.string "Néglige les PV et la VITESSE.$"

BattleDome_Text_NeglectsHPAndSpAtk::
	.string "Néglige les PV et l'ATQ. SPÉ.$"

BattleDome_Text_NeglectsHPAndSpDef::
	.string "Néglige les PV et la DÉF. SPÉ.$"

BattleDome_Text_NeglectsAtkAndDef::
	.string "Néglige l'ATTAQUE et la DÉFENSE.$"

BattleDome_Text_NeglectsAtkAndSpeed::
	.string "Néglige l'ATTAQUE et la VITESSE.$"

BattleDome_Text_NeglectsAtkAndSpAtk::
	.string "Néglige l'ATTAQUE et l'ATQ. SPÉ.$"

BattleDome_Text_NeglectsAtkAndSpDef::
	.string "Néglige l'ATTAQUE et la DÉF. SPÉ.$"

BattleDome_Text_NeglectsDefAndSpeed::
	.string "Néglige la DÉFENSE et la VITESSE.$"

BattleDome_Text_NeglectsDefAndSpAtk::
	.string "Néglige la DÉFENSE et l'ATQ. SPÉ.$"

BattleDome_Text_NeglectsDefAndSpDef::
	.string "Néglige la DÉFENSE et la DÉF. SPÉ.$"

BattleDome_Text_NeglectsSpeedAndSpAtk::
	.string "Néglige la VITESSE et l'ATQ. SPÉ.$"

BattleDome_Text_NeglectsSpeedAndSpDef::
	.string "Néglige la VITESSE et la DÉF. SPÉ.$"

BattleDome_Text_NeglectsSpAtkAndSpDef::
	.string "Néglige l'ATQ. SPÉ. et la DÉF. SPÉ.$"

BattleDome_Text_NeglectsHP::
	.string "Néglige les PV.$"

BattleDome_Text_NeglectsAtk::
	.string "Néglige l'ATTAQUE.$"

BattleDome_Text_NeglectsDef::
	.string "Néglige la DÉFENSE.$"

BattleDome_Text_NeglectsSpeed::
	.string "Néglige la VITESSE.$"

BattleDome_Text_NeglectsSpAtk::
	.string "Néglige l'ATQ. SPÉ.$"

BattleDome_Text_NeglectsSpDef::
	.string "Néglige la DÉF. SPÉ.$"

BattleDome_Text_RaisesMonsWellBalanced::
	.string "Élève ses POKéMON de façon équilibrée.$"

BattleDome_Text_LetTheBattleBegin::
	.string "Que le combat commence !$"

BattleDome_Text_TrainerWonUsingMove::
	.string "{STR_VAR_1} a gagné grâce à {STR_VAR_2} !$"

BattleDome_Text_TrainerBecameChamp::
	.string "{STR_VAR_1} est devenu champion !$"

BattleDome_Text_TrainerWonByDefault::
	.string "{STR_VAR_1} a gagné par forfait !$"

BattleDome_Text_TrainerWonOutrightByDefault::
	.string "{STR_VAR_1} a gagné d'office !$"

BattleDome_Text_TrainerWonNoMoves::
	.string "{STR_VAR_1} a gagné sans utiliser de capacité !$"

BattleDome_Text_TrainerWonOutrightNoMoves::
	.string "{STR_VAR_1} a gagné d'office sans attaque !$"

BattleDome_Text_Round1Match1::
	.string "1er tour, Match 1$"

BattleDome_Text_Round1Match2::
	.string "1er tour, Match 2$"

BattleDome_Text_Round1Match3::
	.string "1er tour, Match 3$"

BattleDome_Text_Round1Match4::
	.string "1er tour, Match 4$"

BattleDome_Text_Round1Match5::
	.string "1er tour, Match 5$"

BattleDome_Text_Round1Match6::
	.string "1er tour, Match 6$"

BattleDome_Text_Round1Match7::
	.string "1er tour, Match 7$"

BattleDome_Text_Round1Match8::
	.string "1er tour, Match 8$"

BattleDome_Text_Round2Match1::
	.string "2e tour, Match 1$"

BattleDome_Text_Round2Match2::
	.string "2e tour, Match 2$"

BattleDome_Text_Round2Match3::
	.string "2e tour, Match 3$"

BattleDome_Text_Round2Match4::
	.string "2e tour, Match 4$"

BattleDome_Text_SemifinalMatch1::
	.string "Demi-finale, Match 1$"

BattleDome_Text_SemifinalMatch2::
	.string "Demi-finale, Match 2$"

BattleDome_Text_FinalMatch::
	.string "Finale$"
