PetalburgCity_Gym_Text_GiveEnigmaBerry:
	.string "PAPA : Salut, {PLAYER} !\p"
	.string "Je viens de recevoir une BAIE très rare.\n"
	.string "J'aimerais que tu l'aies.$"

Route104_Text_PlantBerriesInSoilTakeThis:
	.string "Si tu vois des BAIES pousser dans un sol\n"
	.string "fertile, n'hésite pas à les cueillir.\p"
	.string "Mais pense à replanter une BAIE au même\n"
	.string "endroit. C'est la moindre des choses.\p"
	.string "Tiens, je partage ça avec toi.$"

Route104_Text_TrainersOftenMakeMonHoldBerries:
	.string "À te voir, tu dois être un DRESSEUR, non ?\p"
	.string "Les DRESSEURS font souvent tenir des BAIES\n"
	.string "à leurs POKéMON.\p"
	.string "C'est à toi de décider si tu veux cultiver\n"
	.string "des BAIES ou les utiliser.$"

Route111_Text_WateredPlantsEveryDayTakeBerry:
	.string "J'ai arrosé les plantes tous les jours.\n"
	.string "Elles ont donné plein de fleurs.\p"
	.string "Et elles m'ont aussi donné plein de BAIES.\p"
	.string "Tiens !\n"
	.string "C'est pour toi !$"

Route111_Text_GoingToTryToMakeDifferentColorBerries:
	.string "Je vais faire de mon mieux pour obtenir\n"
	.string "des BAIES de différentes couleurs.\p"
	.string "J'espère que tu feras de ton mieux aussi !$"

Route111_Text_WhatColorBerriesToLookForToday:
	.string "Je me demande de quelle couleur seront\n"
	.string "les BAIES que je vais chercher aujourd'hui.$"

Route114_Text_LoveUsingBerryCrushShareBerry:
	.string "J'adore utiliser la machine BAIE CRUSH,\n"
	.string "alors je collectionne les BAIES.\p"
	.string "Je peux t'en donner une, si tu veux.$"

Route114_Text_TryBerryCrushWithFriends:
	.string "Tu devrais essayer la machine BAIE CRUSH\n"
	.string "avec tes amis.$"

Route114_Text_FunToThinkAboutBerries:
	.string "Quelle BAIE faut-il planter ?\n"
	.string "Faut-il les utiliser ou les garder ?\p"
	.string "C'est amusant d'y réfléchir.$"

Route120_Text_BerriesExpressionOfLoveIsntIt:
	.string "Les BAIES poussent en absorbant la lumière du soleil.\p"
	.string "On aide les BAIES à pousser en les arrosant\n"
	.string "régulièrement.\p"
	.string "C'est une preuve d'amour, tu ne trouves pas ?$"

Route120_Text_YesYouUnderstand:
	.string "Oui, oui.\n"
	.string "Tu comprends ce que je veux dire.\p"
	.string "Tu devrais prendre ceci.$"

Route120_Text_MakeYourOwnImpressions:
	.string "Oh… Mais il est important de se faire\n"
	.string "sa propre opinion, je suppose…\p"
	.string "Tu peux prendre ceci.$"

Route120_Text_BerryIsRareRaiseItWithCare:
	.string "Je pense que cette BAIE est rare.\n"
	.string "J'espère que tu la feras pousser avec amour.$"

Route120_Text_IllGetMoreBerriesFromBerryMaster:
	.string "J'aurai d'autres BAIES grâce au\n"
	.string "MAÎTRE DES BAIES.$"

LilycoveCity_Text_BerrySuitsYou:
	.string "Au fond, tu sais…\p"
	.string "Comme un costume me va parfaitement,\n"
	.string "une brise fraîche va à la mer.\p"
	.string "Et toi, une BAIE te va à merveille…\p"
	.string "Pourquoi donc ?$"

LilycoveCity_Text_BecauseYoureTrainer:
	.string "Au fond, tu sais…\p"
	.string "C'est parce que tu es un DRESSEUR !$"

LilycoveCity_Text_PokeblocksSuitPokemon:
	.string "Au fond, tu sais…\p"
	.string "Comme la simplicité me va bien,\n"
	.string "les {POKEBLOCK}S vont parfaitement aux POKéMON.$"

Route123_BerryMastersHouse_Text_YoureDeservingOfBerry:
	.string "Tu peux m'appeler le MAÎTRE DES BAIES.\p"
	.string "Je rêve de remplir le monde de belles fleurs,\n"
	.string "alors je cultive des BAIES\l"
	.string "et j'en donne à tout le monde.\p"
	.string "Tu en mérites une !$"

Route123_BerryMastersHouse_Text_YoureDeservingOfMulch:
	.string "Le FERTILIBAIE permet de faire pousser\n"
	.string "instantanément n'importe quel arbre à BAIES.\l"
	.string "Essaie-le sur la BAIE du jour !$"

Route123_BerryMastersHouse_Text_WhyBeStingyTakeAnother:
	.string "Pourquoi être avare ?\n"
	.string "Prends-en une autre !$"

Route123_BerryMastersHouse_Text_VisitPrettyPetalFlowerShop:
	.string "N'oublie pas de visiter la boutique\n"
	.string "FLEURISSON près de MÉROUVILLE.\p"
	.string "Que les fleurs envahissent le monde !$"

Route123_BerryMastersHouse_Text_DoneForToday:
	.string "J'ai fini pour aujourd'hui.\n"
	.string "Reviens un autre jour.\p"
	.string "Que les fleurs envahissent le monde !$"

Route123_BerryMastersHouse_Text_HeardAGoodSayingLately:
	.string "La façon dont mon mari cultive les BAIES,\n"
	.string "oh, c'est le meilleur du monde.\p"
	.string "Je suis fière de lui, vraiment.\p"
	.string "Dis-moi, enfant, as-tu entendu\n"
	.string "une bonne expression récemment ?$"

Route123_BerryMastersHouse_Text_InspirationalTakeThis:
	.string "Ah ! Quelle expression remarquable !\n"
	.string "C'est inspirant, vraiment !\p"
	.string "Je veux que tu prennes ceci.$"

Route123_BerryMastersHouse_Text_GoodSayingTakeThis:
	.string "Oh ! C'est une bonne expression.\n"
	.string "Tu es vraiment remarquable.\p"
	.string "Je veux que tu prennes ceci.$"

Route123_BerryMastersHouse_Text_JoyNeverGoesOutOfMyLife:
	.string "Nos quatre petits-enfants devraient devenir\n"
	.string "plus accomplis que mon mari.\p"
	.string "La joie ne quitte jamais ma vie !$"

Route123_BerryMastersHouse_Text_Ah:
	.string "Ah…$"

Route104_PrettyPetalFlowerShop_Text_ThisIsPrettyPetalFlowerShop:
	.string "Bonjour !\p"
	.string "Bienvenue à la boutique FLEURISSON.\n"
	.string "Des fleurs partout dans le monde !$"

Route104_PrettyPetalFlowerShop_Text_LearnAboutBerries:
	.string "{PLAYER}{KUN}, veux-tu en savoir plus sur\n"
	.string "les BAIES ?$"

Route104_PrettyPetalFlowerShop_Text_IntroLearnAboutBerries:
	.string "Comment tu t'appelles ?\p"
	.string "{PLAYER}{KUN}.\n"
	.string "C'est un joli prénom.\p"
	.string "{PLAYER}{KUN}, veux-tu en savoir plus sur\n"
	.string "les BAIES ?$"

Route104_PrettyPetalFlowerShop_Text_BerriesExplanation:
	.string "Les BAIES poussent sur des arbres qui ne\n"
	.string "vivent que dans un sol fertile et meuble.\p"
	.string "Si tu cueilles des BAIES, pense à en\n"
	.string "replanter une dans le sol.\p"
	.string "Une BAIE plantée germera vite,\n"
	.string "deviendra une plante, fleurira joliment,\l"
	.string "puis donnera à nouveau des BAIES.\p"
	.string "J'aimerais voir le monde entier rempli\n"
	.string "de belles fleurs.\l"
	.string "C'est mon rêve.\p"
	.string "Aide-moi, {PLAYER}{KUN}. Plante des BAIES\n"
	.string "et apporte plus de fleurs dans le monde.$"

Route104_PrettyPetalFlowerShop_Text_FlowersBringHappiness:
	.string "Les fleurs apportent tant de bonheur\n"
	.string "aux gens, tu ne trouves pas ?$"

Route104_PrettyPetalFlowerShop_Text_YouCanHaveThis:
	.string "Bonjour !\p"
	.string "Plus tu prends soin des fleurs,\n"
	.string "plus elles s'épanouissent.\p"
	.string "Tu aimeras t'occuper des fleurs. J'en suis\n"
	.string "sûre. Tiens, ceci est pour toi.$"

Route104_PrettyPetalFlowerShop_Text_WailmerPailExplanation:
	.string "Pendant que les plants de BAIES poussent,\n"
	.string "arrose-les avec l'ARROSOIR WAILMER.\p"
	.string "Oh, encore une chose.\p"
	.string "Si tu ne cueilles pas les BAIES pendant un moment,\n"
	.string "elles tomberont au sol.\l"
	.string "Mais elles germeront à nouveau.\p"
	.string "N'est-ce pas génial ?\n"
	.string "C'est comme si elles avaient la volonté de vivre.$"

Route104_PrettyPetalFlowerShop_Text_ImGrowingFlowers:
	.string "J'essaie d'être comme mes grandes sœurs.\n"
	.string "Je fais pousser des fleurs aussi !\p"
	.string "Tiens !\n"
	.string "C'est pour toi !$"

Route104_PrettyPetalFlowerShop_Text_MachineMixesBerries:
	.string "Un POKéMON peut manger une BAIE pour guérir,\n"
	.string "ou tu peux lui en faire tenir une.\p"
	.string "Dans une région lointaine que j'ai visitée,\n"
	.string "il y avait une machine qui mélangeait\l"
	.string "différentes BAIES pour faire des bonbons\l"
	.string "pour les POKéMON.\p"
	.string "Moi aussi, je veux des bonbons.$"

SootopolisCity_Text_NameIsKiriHaveOneOfThese:
	.string "Salut, comment tu t'appelles ?\p"
	.string "… … …  … … …  … … …\n"
	.string "D'accord. C'est joli !\p"
	.string "Je m'appelle KIRI.\p"
	.string "Papa et maman m'ont donné ce prénom pour\n"
	.string "que je grandisse en bonne santé et avec un grand cœur.\l"
	.string "C'est ce qu'ils souhaitaient.\p"
	.string "Tu peux en avoir un.$"

SootopolisCity_Text_GiveYouThisBerryToo:
	.string "KIRI va aussi te donner cette BAIE !\n"
	.string "Je l'aime vraiment beaucoup !$"

SootopolisCity_Text_WhatKindOfWishInYourName:
	.string "Je me demande quel vœu se cache\n"
	.string "dans ton prénom.$"

SootopolisCity_Text_LikeSeasonBornIn:
	.string "Printemps, été, automne et hiver.\p"
	.string "Si tu es né(e) au printemps, tu aimes le\n"
	.string "printemps, et si tu es né(e) en été,\l"
	.string "tu aimes l'été ?$"

SootopolisCity_Text_ThenILoveAutumn:
	.string "Alors KIRI est née en automne,\n"
	.string "donc j'aime l'automne !\p"
	.string "Quelle saison préfères-tu ?$"

SootopolisCity_Text_OhDoesntMatter:
	.string "Oh…\n"
	.string "Ce n'est pas grave…\p"
	.string "Il y a tant de choses que je veux savoir…$"
