gText_Birch_Welcome::
	.string "Hi! Sorry to keep you waiting!\p"
	.string "Welcome to the world of POKéMON!\p"
	.string "My name is OAK.\p"
	.string "People call me the POKéMON\n"
	.string "PROFESSOR.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "This world is widely inhabited by\n"
	.string "creatures known as POKéMON.\p"
	.string "People and POKéMON live together,\n"
	.string "by supporting each other.\p"
	.string "Some people play with POKéMON,\n"
	.string "some battle with them. \p"
	.string "But we don't know everything about\n"
	.string "POKéMON yet. \p"
	.string "There are still many mysteries\n"
	.string "to solve. That's why I study\l"
	.string "POKéMON every day.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "And you are?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_Difficulty::
	.string "Aha…\p"
	.string "And… How do you think this\n"
	.string "adventure is going to be?$"

gText_Birch_LockDifficulty::
	.string "If you need to change the DIFFICULTY\n"
	.string "you can open the OPTIONS MENU and\l"
	.string "change it from there.\p"
	.string "You can also lock it, if you want.\n"
	.string "Do you want to lock the\l"
	.string "chosen DIFFICULTY?\p"
	.string "This cannot be changed later.$"

gText_Birch_Challenge::
	.string "Oh, is that so?\p"
	.string "All right, with that clear…\n"
	.string "Do you expect any CHALLENGE\l"
	.string "in your journey?\p"
	.string "And what's your name?$"

gText_Birch_WhatsYourName::
	.string "Now, what did you say your name.\n"
	.string "was?$"

gText_Birch_SoItsPlayer::
	.string "Oh! So you're {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "{PLAYER}{KUN}, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "You'll face fun times and tough\n"
	.string "challenges.\p"
	.string "A world of dreams and adventures\n"
	.string "with POKéMON awaits! Let's go!\p"
	.string "I'll be seeing you later!\p"
	.string "$"
