gText_Birch_Welcome::
	.string "Salut! Désolé de t'avoir fait attendre!\p"
	.string "Bienvenue dans le monde des POKéMON!\p"
	.string "Je m'appelle ORME.\p"
	.string "On m'appelle le PROFESSEUR\n"
	.string "POKéMON.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "Voici ce que l'on appelle un « POKéMON ».\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "Ce monde est largement peuplé de\n"
	.string "créatures appelées POKéMON.\p"
	.string "Les gens et les POKéMON vivent ensemble,\n"
	.string "en s'entraidant.\p"
	.string "Certaines personnes jouent avec les POKéMON,\n"
	.string "d'autres combattent avec eux.\p"
	.string "Mais nous ne savons pas encore tout\n"
	.string "sur les POKéMON.\p"
	.string "Il reste encore beaucoup de mystères\n"
	.string "à résoudre. C'est pourquoi j'étudie\l"
	.string "les POKéMON chaque jour.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Et toi, qui es-tu?$"

gText_Birch_BoyOrGirl::
	.string "Es-tu un garçon ?\n"
	.string "Ou es-tu une fille ?$"

gText_Birch_Difficulty::
	.string "Ah…\p"
	.string "Et… Comment penses-tu que cette\n"
	.string "aventure va se passer?$"

gText_Birch_LockDifficulty::
	.string "Si tu veux changer la DIFFICULTÉ\n"
	.string "tu peux ouvrir le MENU OPTIONS et\l"
	.string "la modifier depuis là.\p"
	.string "Tu peux aussi la verrouiller, si tu veux.\n"
	.string "Veux-tu verrouiller la\l"
	.string "DIFFICULTÉ choisie ?\p"
	.string "Cela ne pourra plus être changé plus tard.$"

gText_Birch_Challenge::
	.string "Oh, c'est ainsi ?\p"
	.string "Très bien, maintenant que c'est clair…\n"
	.string "Attends-tu un DÉFI\l"
	.string "dans ton aventure ?\p"
	.string "Et comment t'appelles-tu ?$"

gText_Birch_WhatsYourName::
	.string "Alors, comment as-tu dit que tu t'appelais ?\n"
	.string "$"

gText_Birch_SoItsPlayer::
	.string "Oh! Donc tu es {PLAYER}{KUN} ?$"

gText_Birch_YourePlayer::
	.string "{PLAYER}{KUN}, es-tu prêt ?\p"
	.string "Ta propre aventure est sur le point\n"
	.string "de commencer.\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Tu vivras des moments amusants et des\n"
	.string "défis difficiles.\p"
	.string "Un monde de rêves et d'aventures\n"
	.string "avec les POKéMON t'attend! Allons-y!\p"
	.string "On se revoit bientôt!\p"
	.string "$"
