@ NOTE: Le macro brailleformat dans ce fichier est un vestige de RS.
@       Les nombres sont simplement ignorés. Si vous souhaitez omettre
@       ce macro, vous devez également empêcher le saut de cette
@       section en modifiant ScrCmd_braillemessage.
Underwater_SealedChamber_Braille_GoUpHere:
	brailleformat 4, 6, 26, 13, 7, 9
	.braille "MONTEZ ICI.$"

SealedChamber_OuterRoom_Braille_ABC:
	brailleformat 7, 6, 21, 13, 10, 9
	.braille "ABC$"

SealedChamber_OuterRoom_Braille_GHI:
	brailleformat 7, 6, 21, 13, 10, 9
	.braille "GHI$"

SealedChamber_OuterRoom_Braille_MNO:
	brailleformat 7, 6, 21, 13, 10, 9
	.braille "MNO$"

SealedChamber_OuterRoom_Braille_TUV:
	brailleformat 7, 6, 21, 13, 10, 9
	.braille "TUV$"

SealedChamber_OuterRoom_Braille_DEF:
	brailleformat 7, 6, 21, 13, 10, 9
	.braille "DEF$"

SealedChamber_OuterRoom_Braille_JKL:
	brailleformat 7, 6, 21, 13, 10, 9
	.braille "JKL$"

SealedChamber_OuterRoom_Braille_PQRS:
	brailleformat 7, 6, 21, 13, 10, 9
	.braille "PQRS$"

SealedChamber_OuterRoom_Braille_Period:
	brailleformat 9, 6, 19, 13, 12, 9
	.braille ".$"

SealedChamber_OuterRoom_Braille_WXYZ:
	brailleformat 7, 6, 21, 13, 10, 9
	.braille "WXYZ$"

SealedChamber_OuterRoom_Braille_Comma:
	brailleformat 9, 6, 19, 13, 12, 9
	.braille ",$"

SealedChamber_OuterRoom_Braille_DigHere:
	brailleformat 7, 4, 23, 15, 10, 7
	.braille "DOUX PARFUM\n"
	.braille "ICI.$"

SealedChamber_InnerRoom_Braille_FirstWailordLastRelicanth:
	brailleformat 0, 0, 29, 19, 3, 3
	.braille "D'ABORD VIENT\n"
	.braille "MAGNEZONE.\n"
	.braille "EN DERNIER VIENT\n"
	.braille "VIBRAVA.$"

SealedChamber_InnerRoom_Braille_InThisCaveWeHaveLived:
	brailleformat 2, 0, 26, 19, 5, 3
	.braille "DANS CETTE\n"
	.braille "CAVERNE NOUS\n"
	.braille "AVONS\n"
	.braille "VÉCU.$"

SealedChamber_InnerRoom_Braille_WeOweAllToThePokemon:
	brailleformat 7, 2, 23, 17, 10, 5
	.braille "NOUS DEVONS TOUT\n"
	.braille "AUX\n"
	.braille "POKÉMON.$"

SealedChamber_InnerRoom_Braille_ButWeSealedThePokemonAway:
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "MAIS, NOUS\n"
	.braille "AVONS SCELLÉ LES\n"
	.braille "POKÉMON\n"
	.braille "AU LOIN.$"

SealedChamber_InnerRoom_Braille_WeFearedIt:
	brailleformat 5, 6, 25, 13, 8, 9
	.braille "NOUS EN AVIONS PEUR.$"

SealedChamber_InnerRoom_Braille_ThoseWithCourageHope:
	brailleformat 6, 0, 24, 19, 9, 3
	.braille "CEUX QUI ONT\n"
	.braille "DU COURAGE,\n"
	.braille "CEUX QUI ONT\n"
	.braille "DE L'ESPOIR.$"

SealedChamber_InnerRoom_Braille_OpenDoorEternalPokemonWaits:
	brailleformat 3, 2, 27, 17, 6, 5
	.braille "OUVREZ UNE PORTE.\n"
	.braille "UN POKÉMON\n"
	.braille "ÉTERNEL\n"
	.braille "ATTEND.$"

DesertRuins_Braille_UseRockSmash:
	brailleformat 1, 0, 27, 19, 4, 3
	.braille "GAUCHE, GAUCHE,\n"
	.braille "BAS, BAS.\n"
	.braille "PUIS, UTILISEZ\n"
	.braille "ÉCLATROC.$"

IslandCave_Braille_RunLapAroundWall:
	brailleformat 5, 0, 25, 19, 8, 3
	.braille "RESTEZ PRÈS\n"
	.braille "DU MUR.\n"
	.braille "FAITES LE TOUR\n"
	.braille "UNE FOIS.$"

AncientTomb_Braille_ShineInTheMiddle:
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "CEUX QUI\n"
	.braille "HÉRITENT DE NOTRE\n"
	.braille "VOLONTÉ, BRILLEZ\n"
	.braille "AU CENTRE.$"

Regieleki_Braille_Sapphire:
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "PRENEZ LA GEMME\n"
	.braille "BLEUE LÀ OÙ IL\n"
	.braille "PLEUT. PLACEZ-LA\n"
	.braille "AU CENTRE.$"

Regidrago_Braille_Text:
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "BAS, TROIS.\n"
	.braille "DROITE, CINQ.\n"
	.braille "APPUYEZ SUR\n"
	.braille "LE BOUTON.$"

Regigigas_Braille_Text:
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "CINQ TITANS\n"
	.braille "VAINCUS.\n"
	.braille "VOUS ÊTES\n"
	.braille "CHAMPION.$"
