CableClub_Text_WelcomeWhichCableClubService:
	.string "Bienvenue au CLUB CÂBLE POKéMON\n"
	.string ".\p"
	.string "Quel service souhaitez-vous utiliser\n"
	.string "?$"

CableClub_Text_WhichService:
	.string "Quel service souhaitez-vous utiliser\n"
	.string "?$"

CableClub_Text_TradeUsingLinkCable::
	.string "Échangez des POKéMON avec un autre joueur\n"
	.string "en utilisant un câble Game Link GBA.$"

CableClub_Text_BattleUsingLinkCable::
	.string "Vous pouvez combattre un autre DRESSEUR\n"
	.string "en utilisant un câble Game Link GBA.$"

CableClub_Text_RecordCornerUsingLinkCable::
	.string "Vous pouvez utiliser le COIN ENREGISTREMENT avec\n"
	.string "d'autres joueurs via un câble Game Link GBA.$"

@ Unused
CableClub_Text_CloseThisMenu:
	.string "Fermer ce menu.$"

CableClub_Text_NeedTwoMonsForDoubleBattle:
	.string "Pour un COMBAT DUO, vous devez\n"
	.string "avoir au moins deux POKéMON.$"

CableClub_Text_NeedTwoMonsToTrade:
	.string "Pour échanger, vous devez avoir au\n"
	.string "moins deux POKéMON avec vous.$"

CableClub_Text_CantTradeEnigmaBerry:
	.string "Un POKéMON tenant la BAIE {STR_VAR_1}\n"
	.string "ne peut pas être échangé.$"

gText_PleaseWaitForLink::
	.string "Veuillez patienter.\n"
	.string "… … Bouton B : Annuler$"

gText_ConfirmLinkWhenPlayersReady::
	.string "Quand tous les joueurs sont prêts…\n"
	.string "Bouton A : Confirmer\l"
	.string "Bouton B : Annuler$"

gText_ConfirmStartLinkWithXPlayers::
	.string "Commencer la connexion avec {STR_VAR_1} joueurs.\n"
	.string "Bouton A : Confirmer\l"
	.string "Bouton B : Annuler$"

gText_AwaitingLinkup::
	.string "En attente de connexion…\n"
	.string "… … Bouton B : Annuler$"

@ Unused
CableClub_Text_OkayToSaveProgress::
	.string "Votre progression doit être sauvegardée avant\n"
	.string "la connexion. Voulez-vous sauvegarder?$"

CableClub_Text_PleaseEnter:
	.string "Veuillez entrer.$"

CableClub_Text_DirectYouToYourRoom:
	.string "Je vais vous conduire à votre salle maintenant.$"

Text_SomeoneIsNotReadyToLink:
	.string "Quelqu'un n'est pas prêt à se connecter.\p"
	.string "Veuillez revenir après que tout le monde\n"
	.string "se soit préparé.$"

Text_LinkErrorPleaseReset:
	.string "Désolé, il y a une erreur de connexion…\n"
	.string "Veuillez réinitialiser et réessayer.$"

Text_PlayersMadeDifferentSelections:
	.string "Il semble que les partenaires aient fait\n"
	.string "des choix différents.$"

CableClub_Text_PleaseVisitAgain:
	.string "Veuillez revenir nous voir.$"

CableClub_Text_IncorrectNumberOfParticipants:
	.string "Le nombre de participants est\n"
	.string "incorrect.$"

CableClub_Text_CantSingleBattleWithXPlayers:
	.string "Le mode COMBAT SOLO ne peut pas être\n"
	.string "joué par {STR_VAR_1} joueurs.$"

CableClub_Text_CantDoubleBattleWithXPlayers:
	.string "Le mode COMBAT DUO ne peut pas être\n"
	.string "joué par {STR_VAR_1} joueurs.$"

CableClub_Text_NeedFourPlayers:
	.string "Il faut quatre joueurs pour jouer\n"
	.string "à ce mode de combat.$"

CableClub_Text_PleaseConfirmNumberAndRestart:
	.string "Veuillez confirmer le nombre de\n"
	.string "joueurs et recommencer.$"

Text_TerminateLinkConfirmation:
	.string "La connexion sera terminée si vous\n"
	.string "quittez la salle. Est-ce correct?$"

Text_TerminateLinkPleaseWait:
	.string "Fin de la connexion…\n"
	.string "Vous allez être escorté hors de\l"
	.string "la salle. Veuillez patienter.$"

CableClub_Text_TooBusyToNotice:
	.string "Ce DRESSEUR est trop occupé pour\n"
	.string "remarquer…$"

CableClub_Text_GotToLookAtTrainerCard:
	.string "Génial ! J'ai pu voir la CARTE DRESSEUR de {STR_VAR_1} !$"

CableClub_Text_GotToLookAtColoredTrainerCard:
	.string "Génial ! J'ai pu voir la CARTE DRESSEUR de {STR_VAR_1} !\p"
	.string "C'est une carte {STR_VAR_2} !$"

BattleColosseum_2P_Text_TakePlaceStartBattle:
	.string "Veuillez prendre place et commencer\n"
	.string "votre combat.$"

TradeCenter_Text_TakeSeatStartTrade:
	.string "Veuillez vous asseoir et commencer\n"
	.string "votre échange.$"

RecordCorner_Text_ThanksForComing:
	.string "Merci d'être venu.$"

CableClub_Text_TrainerCardDataOverwritten:
	.string "Les données de la CARTE DRESSEUR vont\n"
	.string "être écrasées.$"

CableClub_Text_HopeToSeeYouAgain:
	.string "J'espère vous revoir bientôt !$"

CableClub_Text_NotSetUpForFarAwayRegion:
	.string "Je suis vraiment désolé.\p"
	.string "Nous ne sommes pas encore prêts pour les échanges\n"
	.string "avec des DRESSEURS d'une autre région lointaine…$"

CableClub_Text_OtherTrainerNotReady:
	.string "L'autre DRESSEUR n'est pas prêt.$"

CableClub_Text_YouHaveAMonThatCantBeTaken:
	.string "Vous avez au moins un POKéMON\n"
	.string "qui ne peut pas être emmené.$"

RecordCorner_Text_TakeSeatAndWait:
	.string "Veuillez vous asseoir et attendre.$"

RecordCorner_Text_PlayerSentOverOneX:
	.string "{STR_VAR_1} a envoyé un\n"
	.string "{STR_VAR_2}.$"

CableClub_Text_CantMixWithJapaneseGame:
	.string "Désolé, il y a une erreur de transmission.\p"
	.string "Vous ne pouvez pas mélanger les données avec\n"
	.string "les jeux Rubis ou Saphir japonais.\p"
	.string "De plus, vous ne pouvez pas mélanger les données avec\n"
	.string "Émeraude japonaise et Rubis ou Saphir étrangers en même temps.$"

CableClub_Text_AdapterNotConnected:
	.string "L'Adaptateur Sans Fil n'est pas\n"
	.string "connecté correctement.$"

CableClub_Text_ParticipantsStepUpToCounter:
	.string "Les participants sont priés de s'avancer\n"
	.string "au comptoir de réception.$"

@ Unused
CableClub_Text_Hello:
	.string "Bonjour !$"

@ Unused
CableClub_Text_PleaseWait:
	.string "Veuillez patienter.$"

CableClub_Text_YouMayTradeHere::
	.string "Vous pouvez échanger vos POKéMON ici\n"
	.string "avec un autre DRESSEUR.$"

CableClub_Text_YouMayBattleHere::
	.string "Vous pouvez combattre avec vos amis\n"
	.string "ici.$"

CableClub_Text_CanMakeBerryPowder::
	.string "Deux à cinq DRESSEURS peuvent fabriquer\n"
	.string "de la POUDRE BAIE ensemble.$"

CableClub_Text_CanMixRecords::
	.string "Les données de deux à quatre joueurs\n"
	.string "peuvent être mélangées.$"

@ Unused
CableClub_Text_GuideToVariousServices:
	.string "Un guide des différents services du\n"
	.string "CLUB SANS FIL.$"

CableClub_Text_CancelSelectedItem::
	.string "Annule l'élément du MENU sélectionné.$"

@ Unused
CableClub_Text_WhichBattleMode:
	.string "Quel mode de combat souhaitez-vous?$"

@ Unused
CableClub_Text_ReturnsToPreviousStep:
	.string "Retourne à l'étape précédente.$"

CableClub_Text_NeedBerryForBerryCrush:
	.string "Pour utiliser le service BERRY CRUSH,\n"
	.string "vous devez avoir au moins une BAIE.$"

CableClub_Text_NeedTwoMonsForUnionRoom:
	.string "Pour entrer dans la SALLE UNION, vous devez\n"
	.string "avoir au moins deux POKéMON.$"

CableClub_Text_NoEnigmaBerryInUnionRoom:
	.string "Aucun POKéMON tenant la BAIE {STR_VAR_1}\n"
	.string "ne peut entrer dans la SALLE UNION.$"

CableClub_Text_UnionRoomAdapterNotConnected:
	.string "Ceci est la SALLE UNION du CLUB SANS FIL POKéMON\n"
	.string ".\p"
	.string "Malheureusement, votre Adaptateur Sans Fil\n"
	.string "n'est pas connecté correctement.\p"
	.string "Veuillez revenir nous voir.$"

@ Unused
CableClub_Text_OhExcuseMe:
	.string "Oh…\n"
	.string "Excusez-moi !$"

CableClub_Text_PlayerIsWaiting:
	.string "Il semble que {STR_VAR_1} joue\n"
	.string "en ce moment.\l"
	.string "Allez-y !$"

MossdeepCity_GameCorner_1F_Text_DescribeWhichGame:
	.string "Je peux vous expliquer les règles du jeu,\n"
	.string "si vous le souhaitez.\p"
	.string "Quel jeu dois-je décrire?$"

MossdeepCity_GameCorner_1F_Text_PokemonJumpInfo:
	.string "« POKéMON JUMP »\p"
	.string "Faites sauter votre POKéMON par-dessus la corde\n"
	.string "FOUET LIANES avec le bouton A.\p"
	.string "Seuls les mini-POKéMON d'environ 70 cm\n"
	.string "ou moins peuvent participer.\p"
	.string "Les POKéMON qui ne font que nager, creuser,\n"
	.string "ou voler ne sont pas doués pour sauter.\p"
	.string "En conséquence, ces POKéMON ne peuvent pas\n"
	.string "participer.\p"
	.string "De bonnes choses arrivent si tout le monde\n"
	.string "saute en même temps.$"

MossdeepCity_GameCorner_1F_Text_DodrioBerryPickingInfo:
	.string "« DODRIO RAMASSE-BAIES »\p"
	.string "Contrôlez les trois têtes de DODRIO pour\n"
	.string "attraper les BAIES qui tombent.\p"
	.string "Appuyez à droite, en haut ou à gauche sur la\n"
	.string "croix directionnelle {PLUS} pour bouger les têtes.\p"
	.string "Pour jouer à ce jeu, vous devez avoir\n"
	.string "un DODRIO.$"

MossdeepCity_GameCorner_1F_Text_TalkToOldManToPlay:
	.string "Si vous voulez jouer à un jeu,\n"
	.string "veuillez le dire au vieil homme à côté de moi.$"

MossdeepCity_GameCorner_1F_Text_WelcomeCanYouWait:
	.string "Bonjour, bienvenue !\n"
	.string "Êtes-vous ici pour jouer à des jeux via\l"
	.string "la Communication Sans Fil ?\p"
	.string "Pouvez-vous patienter un petit instant ?$"

MossdeepCity_GameCorner_1F_Text_ComeAgain:
	.string "Très bien, revenez nous voir !$"

MossdeepCity_GameCorner_1F_Text_AdapterNotConnected:
	.string "L'Adaptateur Sans Fil n'est pas connecté.\n"
	.string "Revenez quand il sera branché !$"

MossdeepCity_GameCorner_1F_Text_PlayWhichGame:
	.string "Très bien, à quel jeu voulez-vous\n"
	.string "jouer?$"

MossdeepCity_GameCorner_1F_Text_EnterWhichPokemon:
	.string "Quel POKéMON souhaitez-vous\n"
	.string "inscrire?$"

MossdeepCity_GameCorner_1F_Text_AllGoodToGo:
	.string "C'est bon, vous êtes prêt.\n"
	.string "Ne vous laissez pas battre par les autres !$"

@ Unused
MossdeepCity_GameCorner_1F_Text_LeavingDoComeAgain:
	.string "Vous partez déjà ?\n"
	.string "Revenez nous voir !$"

MossdeepCity_GameCorner_1F_Text_ExplainRequiredMon:
	.string "On dirait que vous n'avez aucun\n"
	.string "POKéMON que vous pouvez inscrire…\p"
	.string "Voulez-vous que je vous explique quels\n"
	.string "POKéMON peuvent participer?$"

MossdeepCity_GameCorner_1F_Text_ShortJumpingPokemonAllowed:
	.string "« POKéMON JUMP » est ouvert aux POKéMON\n"
	.string "d'environ 70 cm ou moins.\p"
	.string "Ceux que vous ne pouvez pas inscrire sont les\n"
	.string "POKéMON qui ne peuvent pas sauter.\p"
	.string "Vous savez, comme les POKéMON qui ne font que\n"
	.string "nager, creuser ou voler.\p"
	.string "C'est tout ce que vous devez savoir.$"

MossdeepCity_GameCorner_1F_Text_OnlyDodrioAllowed:
	.string "DODRIO RAMASSE-BAIES est un jeu auquel\n"
	.string "seul DODRIO peut participer.$"

@ Unused
MossdeepCity_GameCorner_1F_Text_RetryPlease:
	.string "Pourriez-vous recommencer depuis le début\n"
	.string "s'il vous plaît ?$"

CableClub_Text_WelcomeWhichDirectCornerRoom:
	.string "Bienvenue au CLUB SANS FIL POKéMON\n"
	.string "COIN DIRECT.\p"
	.string "Vous pouvez interagir directement avec\n"
	.string "vos amis ici.\p"
	.string "Dans quelle salle souhaitez-vous\n"
	.string "entrer ?$"

CableClub_Text_TradePokemon:
	.string "Voulez-vous échanger des POKéMON ?$"

CableClub_Text_PlayWhichBattleMode:
	.string "Quel mode de combat souhaitez-vous\n"
	.string "jouer ?$"

CableClub_Text_AccessRecordCorner:
	.string "Voulez-vous accéder au\n"
	.string "COIN ENREGISTREMENT ?$"

CableClub_Text_UseBerryCrush:
	.string "Voulez-vous utiliser le système\n"
	.string "BERRY CRUSH ?$"

CableClub_Text_ExplainBattleModes:
	.string "Il y a trois modes de combat.\p"
	.string "LE COMBAT SOLO est pour deux DRESSEURS\n"
	.string "ayant chacun un ou plusieurs POKéMON.\p"
	.string "Chaque DRESSEUR peut avoir un POKéMON\n"
	.string "en combat à la fois.\p"
	.string "LE COMBAT DUO est pour deux DRESSEURS\n"
	.string "ayant chacun deux POKéMON ou plus.\p"
	.string "Chaque DRESSEUR envoie deux POKéMON\n"
	.string "en combat à la fois.\p"
	.string "LE COMBAT MULTI est pour quatre DRESSEURS\n"
	.string "ayant chacun un ou plusieurs POKéMON.\p"
	.string "Chaque DRESSEUR peut avoir un POKéMON\n"
	.string "en combat à la fois.$"

CableClub_Text_ChooseGroupLeaderOfTwo:
	.string "Veuillez décider lequel de vous deux\n"
	.string "sera le LEADER.\p"
	.string "L'autre joueur doit alors choisir\n"
	.string "« REJOINDRE LE GROUPE ».$"

CableClub_Text_ChooseGroupLeaderOfFour:
	.string "Veuillez décider lequel de vous quatre\n"
	.string "sera le LEADER DU GROUPE.\p"
	.string "Les autres joueurs doivent alors choisir\n"
	.string "« REJOINDRE LE GROUPE ».$"

CableClub_Text_ChooseGroupLeader:
	.string "Veuillez décider lequel d'entre vous\n"
	.string "sera le LEADER DU GROUPE.\p"
	.string "Les autres joueurs doivent alors choisir\n"
	.string "« REJOINDRE LE GROUPE ».$"

CableClub_Text_WelcomeUnionRoomEnter:
	.string "Bienvenue dans la SALLE UNION du CLUB SANS FIL\n"
	.string "POKéMON.\p"
	.string "Vous pouvez interagir directement avec\n"
	.string "d'autres DRESSEURS ici, certains que\l"
	.string "vous ne connaissez peut-être même pas.\p"
	.string "Voulez-vous entrer dans la SALLE ?$"

CableClub_Text_UnionRoomInfo:
	.string "Les DRESSEURS dans la SALLE UNION\n"
	.string "seront les joueurs autour de vous\l"
	.string "qui sont aussi entrés dans la SALLE.\p"
	.string "Vous pouvez faire toutes sortes de choses\n"
	.string "ici, comme échanger des salutations.\p"
	.string "Vous pouvez inscrire deux POKéMON jusqu'au\n"
	.string "Niv. 30 pour un combat en un contre un.\p"
	.string "Vous pouvez participer à une discussion avec\n"
	.string "deux à cinq personnes.\p"
	.string "Ou, vous pouvez enregistrer un POKéMON pour\n"
	.string "l'échange.\p"
	.string "Voulez-vous entrer dans la SALLE ?$"

CableClub_Text_EnjoyUnionRoom:
	.string "J'espère que vous apprécierez votre temps dans\n"
	.string "la SALLE UNION.$"

CableClub_Text_FirstTimeRightThisWay:
	.string "Bonjour !\n"
	.string "Je m'appelle TEALA.\p"
	.string "C'est sûrement votre première fois\n"
	.string "ici.\p"
	.string "Je vais vous montrer comment fonctionne le\n"
	.string "Système de Communication Sans Fil.\p"
	.string "D'abord, je dois vous montrer cet étage\n"
	.string "de notre CENTRE POKéMON.\p"
	.string "Par ici, s'il vous plaît.$"

CableClub_Text_ExplainWirelessClubFirstTime:
	.string "Au dernier étage, il y a deux salles\n"
	.string "et le WONDERTRADE.\p"
	.string "D'abord, le système WONDERTRADE.\p"
	.string "L'homme au comptoir peut vous l'expliquer\n"
	.string "en détail, il en sait plus que moi !\p"
	.string "Allez lui parler.\p"
	.string "Ensuite, la salle au centre.\n"
	.string "C'est la SALLE UNION.\p"
	.string "There are three Battle Modes.\p"
	.string "SINGLE BATTLE is for two TRAINERS\n"
	.string "with one or more POKéMON each.\p"
	.string "Each TRAINER can have one POKéMON\n"
	.string "in battle at a time.\p"
	.string "DOUBLE BATTLE is for two TRAINERS\n"
	.string "with two or more POKéMON each.\p"
	.string "Each TRAINER will send out two\n"
	.string "POKéMON in battle at a time.\p"
	.string "MULTI BATTLE is for four TRAINERS\n"
	.string "with one or more POKéMON each.\p"
	.string "Each TRAINER can have one POKéMON\n"
	.string "in battle at a time.$"

CableClub_Text_ChooseGroupLeaderOfTwo:
	.string "Please decide which of you two\n"
	.string "will become the LEADER.\p"
	.string "The other player must then choose\n"
	.string "“JOIN GROUP.”$"

CableClub_Text_ChooseGroupLeaderOfFour:
	.string "Please decide which of you four\n"
	.string "will become the GROUP LEADER.\p"
	.string "The other players must then choose\n"
	.string "“JOIN GROUP.”$"

CableClub_Text_ChooseGroupLeader:
	.string "Please decide which of you will\n"
	.string "become the GROUP LEADER.\p"
	.string "The other players must then choose\n"
	.string "“JOIN GROUP.”$"

CableClub_Text_WelcomeUnionRoomEnter:
	.string "Welcome to the POKéMON WIRELESS\n"
	.string "CLUB UNION ROOM.\p"
	.string "You may interact directly with\n"
	.string "other TRAINERS here, some of\l"
	.string "whom you may not even know.\p"
	.string "Would you like to enter the ROOM?$"

CableClub_Text_UnionRoomInfo:
	.string "The TRAINERS in the UNION ROOM\n"
	.string "will be those players around you\l"
	.string "who have also entered the ROOM.\p"
	.string "You may do all sorts of things\n"
	.string "here, such as exchanging greetings.\p"
	.string "You may enter two POKéMON up to\n"
	.string "Lv. 30 for a one-on-one battle.\p"
	.string "You may take part in a chat with\n"
	.string "two to five people.\p"
	.string "Or, you may register a POKéMON for\n"
	.string "trade.\p"
	.string "Would you like to enter the ROOM?$"

CableClub_Text_EnjoyUnionRoom:
	.string "I hope you enjoy your time in\n"
	.string "the UNION ROOM.$"

CableClub_Text_FirstTimeRightThisWay:
	.string "Hello!\n"
	.string "My name is TEALA.\p"
	.string "This must be your first time\n"
	.string "up here.\p"
	.string "I'll show you how the Wireless\n"
	.string "Communication System works.\p"
	.string "First, I need to show you this\n"
	.string "floor of our POKéMON CENTER.\p"
	.string "Right this way, please.$"

CableClub_Text_ExplainWirelessClubFirstTime:
	.string "On the top floor, there are two\n"
	.string "rooms and the WONDERTRADE.\p"
	.string "First, the WONDERTRADE system.\p"
	.string "The man on the counter can explain\n"
	.string "it in better detail, as he knows\l"
	.string "more about it than me!\p"
	.string "Please go ahead and talk to him.\p"
	.string "Second, the room on the center.\n"
	.string "It's the UNION ROOM.\p"
	.string "You may link up with TRAINERS\n"
	.string "around you who have also entered\l"
	.string "the UNION ROOM.\p"
	.string "With them, you may do things like\n"
	.string "chat, battle, and trade.\p"
	.string "Lastly, the room on the far right\n"
	.string "it the DIRECT CORNER.\p"
	.string "You may trade or battle POKéMON\n"
	.string "with your friends in this room.\p"
	.string "If the Wireless Adapter isn't\n"
	.string "connected, you may still link up\l"
	.string "using a GBA Game Link cable.\p"
	.string "If that is the case, you must go\n"
	.string "to the DIRECT CORNER.\p"
	.string "I hope you enjoy the Wireless \n"
	.string "Communication System.$"

CableClub_Text_AskAboutLinking:
	.string "Hello, {PLAYER}!\p"
	.string "It's me, TEALA, the POKéMON\n"
	.string "CENTER 2F attendant.\p"
	.string "Is there something you needed to\n"
	.string "ask me about linking?$"

CableClub_Text_ExplainWirelessClub:
	.string "Let me explain how the POKéMON\n"
	.string "WIRELESS CLUB works.\p"
	.string "On this, the top floor, there are\n"
	.string "two rooms.\p"
	.string "First, the room on the left.\n"
	.string "It's the UNION ROOM.\p"
	.string "You may link up with TRAINERS\n"
	.string "around you who have also entered\l"
	.string "the UNION ROOM.\p"
	.string "With them, you may do things like\n"
	.string "chat, battle, and trade.\p"
	.string "Second, the room on the right is\n"
	.string "the DIRECT CORNER.\p"
	.string "You may trade or battle POKéMON\n"
	.string "with your friends in this room.\p"
	.string "Sometimes, you may not be able to\n"
	.string "find your friends in the UNION ROOM\l"
	.string "or the DIRECT CORNER.\p"
	.string "In that case, please move closer\n"
	.string "to your friends.\p"
	.string "If the Wireless Adapter isn't\n"
	.string "connected, you may still link up\l"
	.string "using a GBA Game Link cable.\p"
	.string "If that is the case, you must go\n"
	.string "to the DIRECT CORNER.\p"
	.string "I hope you enjoy the Wireless \n"
	.string "Communication System.$"

CableClub_Text_HopeYouEnjoyWirelessSystem:
	.string "I hope you enjoy the Wireless\n"
	.string "Communication System.$"
