Text_PictureBookShelf:
	.string "Il y a une collection de livres illustrés POKéMON.$"

Text_BookShelf:
	.string "Elle est remplie de toutes sortes de livres.$"

Text_PokemonCenterBookShelf:
	.string "Magazines POKéMON !\n"
	.string "POKéMON PAL…\p"
	.string "POKéMON HANDBOOK…\n"
	.string "ADORABLE POKéMON…$"

Text_Vase:
	.string "Ce vase a l'air cher…\n"
	.string "Tu regardes à l'intérieur…\p"
	.string "Mais il est vide.$"

Text_EmptyTrashCan:
	.string "C'est vide.$"

Text_ShopShelf:
	.string "Les étagères débordent de toutes sortes\n"
	.string "d'articles POKéMON.$"

Text_Blueprint:
	.string "Un genre de plan ?\n"
	.string "C'est trop compliqué !$"
