gContestHallPaintingCaption::
	.string "{STR_VAR_1}\n"
	.string "{STR_VAR_3} de {STR_VAR_2}$"

@ Unused
gContestPaintingContest::
	.string "CONCOURS$"

gContestRankNormal::
	.string "NIVEAU NORMAL$"

gContestRankSuper::
	.string "NIVEAU SUPER$"

gContestRankHyper::
	.string "NIVEAU HYPER$"

gContestRankMaster::
	.string "NIVEAU MASTER$"

gContestLink::
	.string "LIEN$"

gContestCoolness::
	.string "SANG-FROID$"

gContestBeauty::
	.string "BEAUTÉ$"

gContestCuteness::
	.string "GRÂCE$"

gContestSmartness::
	.string "INTELLIGENCE$"

gContestToughness::
	.string "ROBUSTESSE$"

gContestPaintingCool1::
	.string "Super cool sans arrêt--\n"
	.string "l'inestimable {STR_VAR_1}$"

gContestPaintingCool2::
	.string "Hé, toi !\n"
	.string "Le POKéMON stylé {STR_VAR_1}$"

gContestPaintingCool3::
	.string "Le merveilleux, formidable et\n"
	.string "très grand {STR_VAR_1}$"

gContestPaintingBeauty1::
	.string "La dernière Vénus du siècle--\n"
	.string "la belle {STR_VAR_1}$"

gContestPaintingBeauty2::
	.string "Le sourire éblouissant et\n"
	.string "étincelant de {STR_VAR_1}$"

gContestPaintingBeauty3::
	.string "L'idole du CENTRE POKéMON--\n"
	.string "l'incomparable {STR_VAR_1}$"

gContestPaintingCute1::
	.string "L'adorable et douce {STR_VAR_1}$"

gContestPaintingCute2::
	.string "Le portrait gagnant de\n"
	.string "la jolie {STR_VAR_1}$"

gContestPaintingCute3::
	.string "Fais-nous un clin d'œil !\n"
	.string "Le POKéMON mignon {STR_VAR_1}$"

gContestPaintingSmart1::
	.string "Le maestro de l'intelligence--\n"
	.string "le POKéMON sage {STR_VAR_1}$"

gContestPaintingSmart2::
	.string "{STR_VAR_1}--l'élu\n"
	.string "parmi tous les POKéMON$"

gContestPaintingSmart3::
	.string "Le moment d'élégance de\n"
	.string "l'excellent {STR_VAR_1}$"

gContestPaintingTough1::
	.string "Le sprinteur puissamment musclé\n"
	.string "{STR_VAR_1}$"

gContestPaintingTough2::
	.string "Le fort, plus fort, et\n"
	.string "le plus fort {STR_VAR_1}$"

gContestPaintingTough3::
	.string "Le super robuste\n"
	.string "POKéMON hyper {STR_VAR_1}$"
