@ À l'exception de "Link standby", aucun des textes ci-dessous n'est utilisé

gTest_MissedTurn::
	.string "Tour manqué$"

gText_LinkStandby4::
	.string "En attente de connexion !$"

gText_WinnerIsPlayersMonCongrats::
	.string "Le gagnant est {STR_VAR_2} de {STR_VAR_1} !\n"
	.string "Félicitations !$"

gText_WinnerIsPlayersMon::
	.string "Le gagnant est {STR_VAR_2} de {STR_VAR_1} !{PAUSE_UNTIL_PRESS}$"

gText_PrimaryJudgingNumX::
	.string "Évaluation principale : N° {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_SecondaryJudgingNumX::
	.string "Évaluation secondaire : N° {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_SetEventNumX::
	.string "Événement défini : N° {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_MoveUsedMostOften::
	.string "Capacité la plus utilisée :\n"
	.string "{STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_MostImpressiveMon::
	.string "Le POKéMON le plus impressionnant :\n"
	.string "{STR_VAR_2} de {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_SetEventNumX2::
	.string "Événement défini : N° {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_LinkTVProgramWillNotBeMadeTrainerLost::
	.string "Une émission TV par lien ne sera pas créée\n"
	.string "car le DRESSEUR a perdu.{PAUSE_UNTIL_PRESS}$"
