EventTicket_Text_ShowOldSeaMap:
	.string "Le ferry pour POIVRESSEL est…\p"
	.string "Pardon ?\n"
	.string "Peut-on naviguer vers cet endroit sur la carte ?\p"
	.string "Je connais quelqu'un qui pourra mieux vous aider.\n"
	.string "Veuillez patienter.$"

EventTicket_Text_ThatPass:
	.string "Le ferry pour POIVRESSEL est…\p"
	.string "Oh ?\n"
	.string "Ce PASS…$"

EventTicket_Text_ShowEonTicket:
	.string "Hé, matelot, c'est toi qui as apporté\n"
	.string "ce PASS drôlement étrange ?\p"
	.string "Je vais te dire, tu veux aller sur un\n"
	.string "minuscule bout d'île loin au sud.\p"
	.string "Impossible de savoir ce qu'on trouvera\n"
	.string "une fois là-bas, hein.\l"
	.string "Ça me donne la chair de poule !\p"
	.string "Tout le monde à bord !$"

EventTicket_Text_SouthernIslandSailBack:
	.string "Hé, matelot, il n'y a rien à voir ni à faire\n"
	.string "sur cette île oubliable.\p"
	.string "Que dirais-tu de rentrer à OLIVILLE ?$"

EventTicket_Text_SailHome:
	.string "D'accord, alors !\n"
	.string "On rentre à la maison !$"

EventTicket_Text_AsYouLike:
	.string "D'accord, comme tu veux, alors.$"

SouthernIsland_Interior_Text_Sign:
	.string "« Tous les rêves ne sont qu'une autre réalité.\n"
	.string "N'oublie jamais… »$"

SouthernIsland_Exterior_Text_Sign:
	.string "« Ceux dont les souvenirs s'effacent cherchent à\n"
	.string "les graver dans leur cœur… »$"
