EventTicket_Text_OldSeaMapTooFar:
	.string "Qu'y a-t-il, jeune homme ?\p"
	.string "Quoi, c'est toi qui es censé avoir\n"
	.string "une vieille carte toute abîmée ?\p"
	.string "Voyons un peu ça.\n"
	.string "… … … … … …\p"
	.string "Eh bien, c'est vraiment très loin.\n"
	.string "Je crains de ne pas pouvoir t'aider…$"

EventTicket_Text_BrineyHoldOnASecond:
	.string "PEPOU: Attendez une seconde !\p"
	.string "Comment osez-vous refuser quelqu'un\n"
	.string "à qui je dois tant ?$"

EventTicket_Text_BrineyLetsSail:
	.string "{PLAYER}{KUN}, je suis vraiment désolé.\p"
	.string "Tu es venu me demander de l'aide,\n"
	.string "et on a failli te refuser.\p"
	.string "Laisse-moi arranger ça.\p"
	.string "On va partir tout de suite, bien sûr !\p"
	.string "Trouvons cette île sur\n"
	.string "cette VIEILLE CARTE MARINE !$"

EventTicket_Text_OddTicketGetOnBoard:
	.string "C'est toi qui as apporté ce\n"
	.string "drôle de ticket ?\p"
	.string "L'endroit où tu veux aller est une île\n"
	.string "très, très éloignée.\p"
	.string "Personne ne sait ce qui t'attend là-bas…\p"
	.string "Rien que d'y penser, ça fait bouillonner\n"
	.string "le sang d'un marin !\p"
	.string "Monte à bord, jeune homme !$"

FarawayIsland_Entrance_Text_SailorReturn:
	.string "Veux-tu retourner à OLIVILLE ?$"

BirthIsland_Harbor_Text_SailorReturn:
	.string "Quelle île de forme étrange, hein ?\n"
	.string "Veux-tu retourner à OLIVILLE ?$"

EventTicket_Text_OddTicketsWhereTo:
	.string "C'est toi qui as apporté ces\n"
	.string "drôles de tickets ?\p"
	.string "… … …Hm.\p"
	.string "Ces tickets te mèneront vers des îles\n"
	.string "très, très éloignées.\p"
	.string "Personne ne sait ce qui t'attend là-bas,\n"
	.string "ni ce qui peut s'y passer.\p"
	.string "Rien que d'y penser, ça fait bouillonner\n"
	.string "le sang d'un marin !\p"
	.string "Monte à bord, jeune homme !\n"
	.string "Où allons-nous en premier ?$"

NavelRock_Harbor_Text_SailorReturn:
	.string "Tu… Tu as entendu ça ?\n"
	.string "Ce grondement sourd qui vient du fond.\p"
	.string "Tu es sûr que c'est sans danger ?\n"
	.string "Tu penses qu'on devrait partir ?$"

FarawayIsland_Entrance_Text_Sign:
	.string "L'écriture s'efface comme si elle avait\n"
	.string "été tracée il y a très longtemps…\p"
	.string "« …bre, 6e jour\n"
	.string "Si un humain… pose le pied ici…\l"
	.string "à nouveau… que ce soit une âme bienveill…\l"
	.string "…vec cet espoir, je m'en vais… »$"

FarawayIsland_Interior_Text_Mew:
	.string "Myuu…$"
