@ Tour Battle
gText_AnabelWonSilver::
	.string "C'est très décevant…$"

gText_AnabelDefeatSilver::
	.string "D'accord, je comprends…$"

gText_AnabelWonGold::
	.string "Je suis vraiment désolée…$"

gText_AnabelDefeatGold::
	.string "Merci…$"

@ Dôme de Combat
gText_TuckerWonSilver::
	.string "Ahahaha ! Tu n'as pas honte ?\n"
	.string "Tout le monde regarde !$"

gText_TuckerDefeatSilver::
	.string "Grr…\n"
	.string "Quoi…?$"

gText_TuckerWonGold::
	.string "Mon titre d'AS DU DÔME n'est pas pour faire joli !$"

gText_TuckerDefeatGold::
	.string "Ahahaha !\n"
	.string "Tu es inspirant !$"

@ Usine de Combat
gText_NolandWonSilver::
	.string "Bien joué !\n"
	.string "C'était une bonne leçon, hein ?$"

gText_NolandDefeatSilver::
	.string "Bravo !\n"
	.string "Tu sais ce que tu fais !$"

gText_NolandWonGold::
	.string "Hé, hé, hé !\n"
	.string "Tu as déjà fini ?$"

gText_NolandDefeatGold::
	.string "Que s'est-il passé ici ?$"

@ Pic de Combat
gText_LucyWonSilver::
	.string "Humph…$"

gText_LucyDefeatSilver::
	.string "Urk…$"

gText_LucyWonGold::
	.string "Ha !$"

gText_LucyDefeatGold::
	.string "Zut !$"

@ Arène de Combat
gText_GretaWonSilver::
	.string "Allez, voyons !\n"
	.string "Il faut faire mieux que ça !$"

gText_GretaDefeatSilver::
	.string "Pas possible !\n"
	.string "Bravo !$"

gText_GretaWonGold::
	.string "Héhé !\n"
	.string "À quoi t'attendais-tu ?$"

gText_GretaDefeatGold::
	.string "Hein ?\n"
	.string "Tu es sérieux ?!$"

@ Palais de Combat
gText_SpenserWonSilver::
	.string "Tes POKéMON sont faibles parce que\n"
	.string "tu es faible comme DRESSEUR !$"

gText_SpenserDefeatSilver::
	.string "Ah…\n"
	.string "Là, c'est autre chose…$"

gText_SpenserWonGold::
	.string "Gwahahaha !\n"
	.string "Mes frères, nous n'avons rien à craindre !$"

gText_SpenserDefeatGold::
	.string "Gwah !\n"
	.string "Hahahaha !$"

@ Pyramide de Combat
gText_BrandonWonSilver::
	.string "Hé ! Qu'est-ce qui ne va pas ?\n"
	.string "Montre un peu d'effort ! Lève-toi !$"

gText_BrandonDefeatSilver::
	.string "C'est ça ! Tu as été super !\n"
	.string "Tu as travaillé dur pour ça !$"

gText_BrandonWonGold::
	.string "Hé ! N'abandonne pas maintenant !\n"
	.string "Lève-toi ! Garde confiance en toi !$"

gText_BrandonDefeatGold::
	.string "C'est ça ! Tu l'as fait !\n"
	.string "Tu as continué à travailler pour ça !$"
