MatchCall_WildBattleText1::
	.string "Salut ! {PLAYER}{KUN}, bonjour !\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "J'ai vu un {STR_VAR_2} il y a quelque temps\n"
	.string "mais je n'ai pas pu l'attraper.\p"
	.string "J'étais si près, en plus !\n"
	.string "Bon, à la prochaine !$"

MatchCall_WildBattleText2::
	.string "Bonjour, {PLAYER}{KUN}.\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "J'ai essayé d'attraper un joli {STR_VAR_2}\n"
	.string "il n'y a pas longtemps.\p"
	.string "Mais il s'est échappé.\n"
	.string "J'étais vraiment déçu !\p"
	.string "Bon, à plus !$"

MatchCall_WildBattleText3::
	.string "Hé, {PLAYER} !\n"
	.string "C'est moi, {STR_VAR_1}.\p"
	.string "J'ai tenté d'attraper ce {STR_VAR_2},\n"
	.string "mais il s'est enfui.\p"
	.string "J'étais vraiment tout près !\p"
	.string "Ça m'a gâché la journée…\n"
	.string "Bon, à bientôt !$"

MatchCall_WildBattleText4::
	.string "Salut, {PLAYER}{KUN}.\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "Tu connais le POKéMON {STR_VAR_2} ?\n"
	.string "J'ai failli en attraper un.\p"
	.string "C'était il n'y a pas longtemps.\n"
	.string "Je croyais l'avoir, mais il s'est échappé.\p"
	.string "Si je le revois, cette fois je l'aurai\n"
	.string "c'est sûr.\p"
	.string "Bon, à la prochaine.$"

MatchCall_WildBattleText5::
	.string "Coucou, {PLAYER}{KUN} !\n"
	.string "C'est {STR_VAR_1}.\l"
	.string "Tu attrapes des POKéMON en ce moment ?\p"
	.string "Il y a peu, j'ai failli en attraper un,\n"
	.string "mais il s'est échappé.\p"
	.string "Allez, prends soin de toi !$"

MatchCall_WildBattleText6::
	.string "Salut, {PLAYER}{KUN}.\n"
	.string "C'est {STR_VAR_1}.\l"
	.string "Tu as attrapé des POKéMON récemment ?\p"
	.string "J'ai failli en avoir un l'autre jour.\n"
	.string "Mais il m'a échappé, je ne sais comment.\p"
	.string "Prends soin de toi.$"

MatchCall_WildBattleText7::
	.string "…Euh, {PLAYER}{KUN} ?\n"
	.string "C'est moi, {STR_VAR_1}.\p"
	.string "Oh, attends ! Attends !\n"
	.string "Je peux attraper ce {STR_VAR_2}…\p"
	.string "Aaarrrgh ! Il s'est enfui !\n"
	.string "C'était vraiment très juste !$"

MatchCall_WildBattleText8::
	.string "Oh, {PLAYER}{KUN}, comment vas-tu ?\n"
	.string "Ici {STR_VAR_1}.\p"
	.string "As-tu réussi à attraper des POKéMON\n"
	.string "récemment ?\p"
	.string "J'ai failli y arriver il y a peu,\n"
	.string "mais ma cible s'est libérée.\p"
	.string "Je dois m'entraîner encore !\n"
	.string "À la prochaine !$"

MatchCall_WildBattleText9::
	.string "Oh, {PLAYER}{KUN}, salut !\n"
	.string "C'est {STR_VAR_1} !\p"
	.string "Alors ? Tu attrapes plus de POKéMON ?\n"
	.string "Tu en as plein ?\p"
	.string "Moi, j'ai vraiment du mal !\n"
	.string "Ils s'échappent tous !\p"
	.string "À bientôt !$"

MatchCall_WildBattleText10::
	.string "Oh, {PLAYER}{KUN}, bonjour…\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "Écoute, j'ai failli attraper ce {STR_VAR_2}…\n"
	.string "Mais il m'a échappé…\p"
	.string "Je dois m'améliorer.\n"
	.string "À la prochaine.$"

MatchCall_WildBattleText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "C'est {STR_VAR_1}.\l"
	.string "Comment ça va ?\p"
	.string "J'ai essayé d'attraper un {STR_VAR_2} sauvage\n"
	.string "plus tôt, mais il s'est enfui.\p"
	.string "Je me sens vaincu…$"

MatchCall_WildBattleText12::
	.string "Bonjour, {PLAYER}{KUN}.\n"
	.string "C'est moi, {STR_VAR_1}.\l"
	.string "Tu attrapes toujours des POKéMON ?\p"
	.string "J'essaie aussi, mais ce n'est pas facile.\p"
	.string "La voie des POKéMON est profonde !$"

MatchCall_WildBattleText13::
	.string "Ah, bonjour, {PLAYER}{KUN} !\n"
	.string "C'est {STR_VAR_1} !\l"
	.string "Tu attrapes des POKéMON ?\p"
	.string "J'essaie aussi, mais sans grand succès.\p"
	.string "La voie des POKéMON est profonde !$"

MatchCall_WildBattleText14::
	.string "Oh, salut, {PLAYER}{KUN}, comment vas-tu ?\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "Je viens d'essayer d'attraper un joli\n"
	.string "{STR_VAR_2}.\p"
	.string "Mais il s'est échappé !\n"
	.string "Oh, j'étais vraiment déçu !\p"
	.string "À bientôt !$"

MatchCall_WildBattleText15::
	.string "Hé, {PLAYER} !\n"
	.string "C'est {STR_VAR_1} !\p"
	.string "Je pensais essayer d'attraper\n"
	.string "des POKéMON.\p"
	.string "Mais je n'en trouve pas.\n"
	.string "C'est un vrai casse-tête !\p"
	.string "Je ne sais plus quoi faire !\n"
	.string "À la prochaine !$"

MatchCall_NegativeBattleText1::
	.string "Salut ! {PLAYER}{KUN}, bonjour !\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "J'ai affronté un autre DRESSEUR,\n"
	.string "mais j'ai perdu.\p"
	.string "C'était vraiment décevant.\n"
	.string "Bon, à la prochaine !$"

MatchCall_NegativeBattleText2::
	.string "Bonjour, {PLAYER}{KUN}.\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "J'ai défié quelqu'un après notre combat.\p"
	.string "J'étais près de gagner, mais j'ai fini\n"
	.string "par perdre. Tant pis !$"

MatchCall_NegativeBattleText3::
	.string "Hé, {PLAYER} !\n"
	.string "C'est moi, {STR_VAR_1}.\p"
	.string "Je me suis fait battre en combat.\p"
	.string "Je crois que je dois encore entraîner\n"
	.string "mon équipe !$"

MatchCall_NegativeBattleText4::
	.string "Salut, {PLAYER}.\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "J'ai refait un combat hier,\n"
	.string "mais je n'ai pas pu gagner.\p"
	.string "Mon équipe a besoin d'entraînement.\n"
	.string "Bon, à la prochaine.$"

MatchCall_NegativeBattleText5::
	.string "Coucou, {PLAYER} !\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "Comment ça va ?\p"
	.string "Je continue à combattre,\n"
	.string "mais je ne gagne pas souvent.\p"
	.string "Je n'y arrive pas.\n"
	.string "Allez, prends soin de toi !$"

MatchCall_NegativeBattleText6::
	.string "Salut, {PLAYER}.\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "Et toi, ça va ?\p"
	.string "Je combats beaucoup ces temps-ci,\n"
	.string "mais sans grand succès.\p"
	.string "Je n'arrive pas à trouver le rythme.\n"
	.string "Prends soin de toi.$"

MatchCall_NegativeBattleText7::
	.string "C'est {STR_VAR_1}.\n"
	.string "Comment ça va ces temps-ci ?\p"
	.string "J'ai perdu un combat hier,\n"
	.string "et j'y pense encore.\p"
	.string "Je dois trouver une stratégie…\n"
	.string "À bientôt.$"

MatchCall_NegativeBattleText8::
	.string "Oh, {PLAYER}{KUN}, comment vas-tu ?\n"
	.string "Ici {STR_VAR_1}.\p"
	.string "Comment vont tes POKéMON ?\n"
	.string "J'ai perdu un match l'autre jour.\p"
	.string "Je dois m'améliorer !\n"
	.string "À la prochaine !$"

MatchCall_NegativeBattleText9::
	.string "Oh, {PLAYER}{KUN}, salut !\n"
	.string "C'est {STR_VAR_1} !\p"
	.string "Écoute, écoute, il faut que je te raconte !\p"
	.string "J'ai fait un combat de POKéMON plus tôt,\n"
	.string "mais j'ai perdu à la dernière seconde.\p"
	.string "Oh, ça m'énerve !$"

MatchCall_NegativeBattleText10::
	.string "Oh, {PLAYER}{KUN}, bonjour…\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "J'ai fait un combat il y a peu.\n"
	.string "Mais j'ai perdu.\p"
	.string "Je dois entraîner mes POKéMON davantage.\n"
	.string "À la prochaine.$"

MatchCall_NegativeBattleText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "C'est {STR_VAR_1}.\l"
	.string "Comment vont tes POKéMON ?\p"
	.string "Je viens encore de perdre un combat.\p"
	.string "Bon, à bientôt !$"

MatchCall_NegativeBattleText12::
	.string "Bonjour, {PLAYER}{KUN}.\n"
	.string "C'est moi, {STR_VAR_1}.\l"
	.string "Tu combats toujours autant ?\p"
	.string "Moi, j'ai perdu récemment, alors\n"
	.string "j'entraîne mon équipe partout.\p"
	.string "On se revoit !$"

MatchCall_NegativeBattleText13::
	.string "Ah, bonjour, {PLAYER}{KUN} !\n"
	.string "C'est {STR_VAR_1} !\p"
	.string "J'espère que tu vas bien.\p"
	.string "J'ai fait un combat il y a peu.\p"
	.string "{PLAYER}{KUN}, essaie d'être actif comme moi.\n"
	.string "À la prochaine !$"

MatchCall_NegativeBattleText14::
	.string "Oh, salut, {PLAYER}{KUN}.\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "Tu vas bien ?\p"
	.string "Tu devrais rentrer chez toi de temps en temps,\n"
	.string "tu sais.\p"
	.string "À bientôt !$"

MatchCall_PositiveBattleText1::
	.string "Salut ! {PLAYER}{KUN}, bonjour !\n"
	.string "C'est {STR_VAR_1} !\p"
	.string "J'ai affronté un autre DRESSEUR tout à l'heure.\n"
	.string "J'ai gagné ! J'ai gagné !\p"
	.string "Mon {STR_VAR_2} s'est vraiment donné à fond\n"
	.string "pour moi. C'est génial !$"

MatchCall_PositiveBattleText2::
	.string "Bonjour, {PLAYER}{KUN} !\n"
	.string "C'est {STR_VAR_1} !\p"
	.string "J'ai fait un combat hier et\n"
	.string "j'ai gagné ! C'est fantastique !$"

MatchCall_PositiveBattleText3::
	.string "Hé, {PLAYER} !\n"
	.string "C'est moi, {STR_VAR_1} !\l"
	.string "Comment vont tes combats ?\p"
	.string "Moi, j'ai combattu l'autre jour,\n"
	.string "et mon {STR_VAR_2} a été incroyable !\p"
	.string "La prochaine fois qu'on se battra,\n"
	.string "{PLAYER}, ce n'est pas moi qui perdrai !$"

MatchCall_PositiveBattleText4::
	.string "Salut, {PLAYER}.\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "J'ai fait un match tout à l'heure.\n"
	.string "J'ai réussi à gagner, mais c'était serré.\p"
	.string "Mon {STR_VAR_2} a vraiment assuré.$"

MatchCall_PositiveBattleText5::
	.string "Coucou, {PLAYER}{KUN} !\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "Comment ça va ?\n"
	.string "Tu combats beaucoup ?\p"
	.string "Je viens de gagner il y a peu !\n"
	.string "Mon {STR_VAR_2} était brillant !\p"
	.string "Attends-toi à ce que je te batte\n"
	.string "la prochaine fois ! Allez, prends soin de toi !$"

MatchCall_PositiveBattleText6::
	.string "Salut, {PLAYER}{KUN}.\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "Et toi, ça va ?\p"
	.string "Je suis sur une bonne lancée.\n"
	.string "Je viens de gagner un combat.\p"
	.string "La prochaine fois qu'on se battra,\n"
	.string "je ne perdrai pas !$"

MatchCall_PositiveBattleText7::
	.string "{PLAYER}{KUN} ?\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "Mon {STR_VAR_2} est une vraie force !\n"
	.string "Il m'a encore fait gagner un combat !\p"
	.string "J'ai hâte de faire une revanche\n"
	.string "avec toi.$"

MatchCall_PositiveBattleText8::
	.string "Oh, {PLAYER}{KUN}, comment vas-tu ?\n"
	.string "Ici {STR_VAR_1}.\p"
	.string "J'espère que tu vas bien.\n"
	.string "Je voulais te dire que je viens de gagner.\p"
	.string "Mon {STR_VAR_2} s'est donné à fond\n"
	.string "pour la victoire.\p"
	.string "À la prochaine !$"

MatchCall_PositiveBattleText9::
	.string "Oh, {PLAYER}{KUN}, salut !\n"
	.string "C'est {STR_VAR_1} !\p"
	.string "Tes POKéMON vont bien ?\n"
	.string "Les miens viennent de gagner un combat !\p"
	.string "Mon {STR_VAR_2} était spectaculaire,\n"
	.string "je dois le dire !\p"
	.string "J'aurais aimé te le montrer !\n"
	.string "À la prochaine !$"

MatchCall_PositiveBattleText10::
	.string "Oh, {PLAYER}{KUN}, bonjour…\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "Comment va la vie ?\p"
	.string "Mes POKéMON débordent d'énergie.\p"
	.string "Je viens de gagner un combat avec eux.\n"
	.string "À la prochaine.$"

MatchCall_PositiveBattleText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "Tu as fait des combats récemment ?\n"
	.string "Je viens d'en gagner un autre aujourd'hui !\p"
	.string "Je suis en pleine forme ! Gahahaha !\n"
	.string "Bon, à bientôt !$"

MatchCall_PositiveBattleText12::
	.string "Bonjour, {PLAYER}{KUN}.\n"
	.string "C'est moi, {STR_VAR_1}.\p"
	.string "J'espère que tu vas bien ?\n"
	.string "J'ai toujours la forme !\p"
	.string "Je viens tout juste de gagner un autre match.\n"
	.string "Je ne vais pas laisser la place aux\l"
	.string "jeunes tout de suite !$"

MatchCall_PositiveBattleText13::
	.string "Ah, bonjour, {PLAYER}{KUN} !\n"
	.string "C'est {STR_VAR_1} !\p"
	.string "J'espère que tu vas bien.\n"
	.string "J'ai encore la pêche !\p"
	.string "Je viens encore de gagner un combat.\n"
	.string "Oh, je ne vais pas perdre contre les jeunes\l"
	.string "tout de suite !\p"
	.string "À la prochaine !$"

MatchCall_PositiveBattleText14::
	.string "Oh, salut, {PLAYER}{KUN}.\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "J'ai fait un combat récemment, et mon\n"
	.string "{STR_VAR_2} a été exceptionnel !\p"
	.string "J'aurais aimé que tu le voies,\n"
	.string "{PLAYER}{KUN}. À bientôt !$"

MatchCall_SameRouteBattleRequestText1::
	.string "Salut ! {PLAYER}, bonjour !\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "Hein ? Attends, tu es près de\n"
	.string "{STR_VAR_2} ?\p"
	.string "Oh, génial, il faut qu'on se batte alors !\n"
	.string "Je t'attends ! À bientôt !$"

MatchCall_SameRouteBattleRequestText2::
	.string "Bonjour, {PLAYER} !\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "Oh ? Tu es près de\n"
	.string "{STR_VAR_2} en ce moment ?\p"
	.string "Tu veux te battre maintenant ?\n"
	.string "Je t'attends ! À bientôt !$"

MatchCall_SameRouteBattleRequestText3::
	.string "Hé, {PLAYER} !\n"
	.string "C'est moi, {STR_VAR_1}.\p"
	.string "Oh, tu es près de\n"
	.string "{STR_VAR_2} en ce moment ?\p"
	.string "Ça te dirait de te battre avec moi\n"
	.string "tout de suite ?\p"
	.string "Je ne vais pas perdre cette fois !\n"
	.string "Je t'attends ! À très vite !$"

MatchCall_SameRouteBattleRequestText4::
	.string "Salut, {PLAYER}{KUN}.\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "Tu es où en ce moment ?\n"
	.string "Hein ? {STR_VAR_2} ?\p"
	.string "Tu veux te battre maintenant ?\n"
	.string "Je t'attends. À bientôt !$"

MatchCall_SameRouteBattleRequestText5::
	.string "Coucou, {PLAYER}{KUN} !\n"
	.string "C'est {STR_VAR_1}.\l"
	.string "Comment ça va ?\p"
	.string "Tu es où là ?\n"
	.string "{STR_VAR_2} ?\p"
	.string "Et si on faisait un petit match\n"
	.string "tout de suite ?\p"
	.string "Je vais te guetter.\n"
	.string "À très vite !$"

MatchCall_SameRouteBattleRequestText6::
	.string "Salut, {PLAYER}{KUN}.\n"
	.string "C'est {STR_VAR_1}.\l"
	.string "Tes POKéMON vont bien ?\p"
	.string "Ah bon ? Tu es près de\n"
	.string "{STR_VAR_2} ?\p"
	.string "Alors, on ferait bien un match.\n"
	.string "Je peux attendre, pas de souci.\n"
	.string "À bientôt !$"

MatchCall_SameRouteBattleRequestText7::
	.string "…Euh, {PLAYER}{KUN} ?\n"
	.string "C'est {STR_VAR_1}…\p"
	.string "Oh, tu es près de\n"
	.string "{STR_VAR_2} ?\p"
	.string "Alors, battons-nous.\n"
	.string "Tout de suite, je veux dire.\p"
	.string "Je vais te montrer mes POKéMON.\n"
	.string "Je t'attends.$"

MatchCall_SameRouteBattleRequestText8::
	.string "Oh, {PLAYER}{KUN}, comment vas-tu ?\n"
	.string "Ici {STR_VAR_1}.\p"
	.string "J'espère que tu vas bien.\n"
	.string "Oh, tu es près de {STR_VAR_2}.\p"
	.string "Tu veux faire un combat avec moi ?\p"
	.string "Je t'attends.\n"
	.string "À très vite !$"

MatchCall_SameRouteBattleRequestText9::
	.string "Oh, {PLAYER}{KUN}, salut !\n"
	.string "C'est {STR_VAR_1} !\p"
	.string "Tu tiens le coup ?\n"
	.string "Oh, tu es près de {STR_VAR_2} ?\p"
	.string "Alors, tu ne crois pas qu'on devrait\n"
	.string "se battre ?\p"
	.string "Ne me fais pas trop attendre !$"

MatchCall_SameRouteBattleRequestText10::
	.string "Oh, {PLAYER}{KUN}, bonjour…\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "Comment ça va ?\n"
	.string "Oh, tu es près de {STR_VAR_2}.\p"
	.string "On devrait se battre maintenant.\p"
	.string "Je suis prêt et j'attends.\n"
	.string "Dépêche-toi !$"

MatchCall_SameRouteBattleRequestText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "Ah, donc tu es à\n"
	.string "{STR_VAR_2} ?\p"
	.string "Alors, il faut qu'on fasse un combat,\n"
	.string "tu ne crois pas ?\p"
	.string "Je vais t'attendre !\n"
	.string "À tout de suite !$"

MatchCall_SameRouteBattleRequestText12::
	.string "Bonjour, {PLAYER}{KUN}.\n"
	.string "C'est moi, {STR_VAR_1}.\l"
	.string "Tu es où en ce moment ?\p"
	.string "{STR_VAR_2} ?\n"
	.string "C'est tout près !\p"
	.string "On fait un combat maintenant ?\n"
	.string "Je peux attendre.\n"
	.string "À bientôt !$"

MatchCall_SameRouteBattleRequestText13::
	.string "Ah, bonjour, {PLAYER}{KUN} !\n"
	.string "C'est {STR_VAR_1} !\p"
	.string "J'espère que tu vas bien.\n"
	.string "Oh, tu es près de {STR_VAR_2} ?\p"
	.string "Comme ce n'est pas loin,\n"
	.string "viens me voir pour un combat.\p"
	.string "Je t'attends.\n"
	.string "À plus !$"

MatchCall_SameRouteBattleRequestText14::
	.string "Oh, salut, {PLAYER}{KUN}.\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "Tu es où ? …{STR_VAR_2} ?\n"
	.string "C'est tout près.\p"
	.string "Tu ne crois pas qu'on devrait faire\n"
	.string "un combat ?\p"
	.string "Je vais te chercher !\n"
	.string "À bientôt !$"

MatchCall_DifferentRouteBattleRequestText1::
	.string "Salut ! {PLAYER}, bonjour !\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "Tu veux faire un combat avec moi ?\p"
	.string "Je t'attendrai vers\n"
	.string "{STR_VAR_2} !$"

MatchCall_DifferentRouteBattleRequestText2::
	.string "Bonjour, {PLAYER} !\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "Tu voudrais refaire un combat\n"
	.string "avec moi ?\p"
	.string "Tu peux me trouver vers\n"
	.string "{STR_VAR_2}. Je t'attends !$"

MatchCall_DifferentRouteBattleRequestText3::
	.string "Hé, {PLAYER} !\n"
	.string "C'est moi, {STR_VAR_1}.\p"
	.string "Mes POKéMON sont devenus bien\n"
	.string "plus forts depuis la dernière fois.\p"
	.string "Je veux voir à quel point ils sont\n"
	.string "devenus puissants face à tes POKéMON, {PLAYER}.\p"
	.string "Alors, faisons un combat !\p"
	.string "Je t'attendrai vers\n"
	.string "{STR_VAR_2}.$"

MatchCall_DifferentRouteBattleRequestText4::
	.string "Hé, {PLAYER}{KUN}.\n"
	.string "C'est {STR_VAR_1}.\l"
	.string "Comment ça va ?\p"
	.string "Mes POKéMON sont devenus assez\n"
	.string "costauds ces derniers temps.\p"
	.string "Dis, ça te dirait de refaire\n"
	.string "un combat avec moi ?\p"
	.string "Retrouvons-nous vers\n"
	.string "{STR_VAR_2}, d'accord ?$"

MatchCall_DifferentRouteBattleRequestText5::
	.string "Coucou, {PLAYER}{KUN} !\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "Mes POKéMON grandissent\n"
	.string "plutôt bien.\p"
	.string "J'aimerais vraiment refaire un\n"
	.string "combat avec toi.\p"
	.string "Je guetterai ta venue vers\n"
	.string "{STR_VAR_2}. À bientôt !$"

MatchCall_DifferentRouteBattleRequestText6::
	.string "Hé, {PLAYER}{KUN}.\n"
	.string "C'est {STR_VAR_1}.\l"
	.string "J'espère que tout va bien pour toi.\p"
	.string "Je pensais qu'un autre combat\n"
	.string "avec toi serait sympa. Qu'en dis-tu ?\p"
	.string "Si tu veux te battre,\n"
	.string "viens à {STR_VAR_2}.\p"
	.string "À bientôt !$"

MatchCall_DifferentRouteBattleRequestText7::
	.string "…Euh, {PLAYER}{KUN} ?\n"
	.string "C'est {STR_VAR_1}…\l"
	.string "Alors ? Tes POKéMON grandissent ?\p"
	.string "Les miens sont devenus plus forts.\n"
	.string "J'aimerais te montrer ça.\p"
	.string "Je serai vers {STR_VAR_2}.\n"
	.string "Viens me voir pour un match.\p"
	.string "À bientôt.$"

MatchCall_DifferentRouteBattleRequestText8::
	.string "Oh, {PLAYER}{KUN}, comment vas-tu ?\n"
	.string "Ici {STR_VAR_1} à l'appareil.\p"
	.string "J'espère que tu vas bien.\n"
	.string "Mes POKéMON sont très en forme.\p"
	.string "Si tu es dans le coin, viens me\n"
	.string "défier à nouveau.\p"
	.string "Je serai vers {STR_VAR_2}.\n"
	.string "À bientôt, au revoir !$"

MatchCall_DifferentRouteBattleRequestText9::
	.string "Oh, {PLAYER}{KUN}, salut !\n"
	.string "C'est {STR_VAR_1} !\l"
	.string "Comment vont tes POKéMON ?\p"
	.string "Les miens deviennent de plus en plus forts.\n"
	.string "J'aimerais te montrer ça, {PLAYER}{KUN}.\p"
	.string "Je suis vers {STR_VAR_2} maintenant,\n"
	.string "alors viens te battre si tu es dans le coin.\p"
	.string "J'espère te voir bientôt !$"

MatchCall_DifferentRouteBattleRequestText10::
	.string "Oh, {PLAYER}{KUN}, bonjour…\n"
	.string "C'est {STR_VAR_1}.\l"
	.string "Alors, comment ça va ?\p"
	.string "Mes POKéMON sont devenus bien\n"
	.string "plus forts qu'avant.\p"
	.string "J'aimerais refaire un combat avec toi,\n"
	.string "{PLAYER}{KUN}.\p"
	.string "Je serai vers {STR_VAR_2}.\n"
	.string "Viens me voir si tu es dans le coin.$"

MatchCall_DifferentRouteBattleRequestText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "C'est {STR_VAR_1}.\l"
	.string "Où es-tu en ce moment ?\p"
	.string "Mes POKéMON débordent d'énergie.\n"
	.string "Ils ont hâte de voir tes POKéMON, {PLAYER}{KUN}.\p"
	.string "Je suis vers {STR_VAR_2} maintenant.\n"
	.string "J'espère que tu viendras nous voir.$"

MatchCall_DifferentRouteBattleRequestText12::
	.string "Bonjour, {PLAYER}{KUN}.\n"
	.string "C'est moi, {STR_VAR_1}.\p"
	.string "Je dois te dire, mes POKéMON sont\n"
	.string "devenus assez robustes ces temps-ci.\p"
	.string "J'aimerais les voir en combat\n"
	.string "contre toi, {PLAYER}{KUN}.\p"
	.string "Nous serons vers {STR_VAR_2}.\n"
	.string "Viens nous voir quand tu veux !$"

MatchCall_DifferentRouteBattleRequestText13::
	.string "Ah, bonjour, {PLAYER}{KUN} !\n"
	.string "C'est {STR_VAR_1} !\l"
	.string "Tes POKéMON vont bien ?\p"
	.string "Les miens sont tellement en forme,\n"
	.string "qu'ils semblent imbattables !\p"
	.string "J'aimerais vraiment refaire un\n"
	.string "combat avec toi.\p"
	.string "Si tu es près de {STR_VAR_2},\n"
	.string "viens nous voir.$"

MatchCall_DifferentRouteBattleRequestText14::
	.string "Oh, salut, {PLAYER}{KUN}.\n"
	.string "C'est {STR_VAR_1}.\l"
	.string "J'espère que tu vas bien.\p"
	.string "Oh, oui ! Mes POKéMON sont\n"
	.string "bien plus forts qu'avant.\p"
	.string "Tu ne crois pas qu'on devrait faire\n"
	.string "un combat, {PLAYER}{KUN} ?\p"
	.string "Nous t'attendrons vers\n"
	.string "{STR_VAR_2}.\p"
	.string "Viens nous voir quand tu veux, d'accord ?$"

MatchCall_PersonalizedText1::
	.string "C'est moi, {STR_VAR_1}, l'ami des montagnes !\n"
	.string "\p"
	.string "Alors, depuis qu'on s'est rencontrés, tu as appris\n"
	.string "à aimer davantage les montagnes ?\p"
	.string "Je te vois rarement en montagne…\p"
	.string "La prochaine fois, retrouvons-nous quelque part\n"
	.string "vers {STR_VAR_2}.$"

MatchCall_PersonalizedText2::
	.string "C'est {STR_VAR_1}.\n"
	.string "Bonjour.\p"
	.string "Je parlais justement de toi à une nouvelle\n"
	.string "dresseuse.\p"
	.string "Je lui ai parlé d'un dresseur fort\n"
	.string "qui élève ses POKéMON avec soin.\p"
	.string "J'espère que tu deviendras un dresseur\n"
	.string "que tout le monde admirera.\p"
	.string "J'espère qu'on se reverra !$"

MatchCall_PersonalizedText3::
	.string "Bonjour ! C'est {STR_VAR_1}.\p"
	.string "J'adore l'endroit où je suis.\n"
	.string "C'est agréable et ça sent bon !\p"
	.string "Je pense que quelqu'un a planté des BAIES,\n"
	.string "et elles sont toutes en fleurs.\p"
	.string "À bientôt j'espère !$"

MatchCall_PersonalizedText4::
	.string "Bonjour ! Trente ans d'exploration,\n"
	.string "{STR_VAR_1} à votre service !\p"
	.string "On dirait que tu voyages avec énergie\n"
	.string "un peu partout.\p"
	.string "As-tu découvert de nouvelles ruines ?\n"
	.string "Dis-le-moi si c'est le cas !\p"
	.string "Bon, excuse-moi,\n"
	.string "j'ai des ruines à explorer.$"

MatchCall_PersonalizedText5::
	.string "C'est {STR_VAR_1} !\p"
	.string "Tu sais ce que je fais aujourd'hui ?\n"
	.string "Je regarde les vagues depuis la plage !\p"
	.string "Soupir… Les vagues brillent de mille feux.\n"
	.string "La mer est la plus belle vue d'ici.\l"
	.string "J'ai faim, alors à bientôt !$"

MatchCall_PersonalizedText6::
	.string "Miam-miam…\n"
	.string "Oh, salut, c'est {STR_VAR_1}.\l"
	.string "J'adore manger sur la plage.\p"
	.string "Mes POKéMON et moi, on va super bien.\n"
	.string "On est plein d'énergie !\l"
	.string "Je vais nager. À plus !$"

MatchCall_PersonalizedText7::
	.string "Bonjour, ici {STR_VAR_1}…\p"
	.string "Je commence à être un peu lassé de ce\n"
	.string "truc de TOPDRESSEUR…\p"
	.string "Tout le monde pense que je suis un dresseur\n"
	.string "parfait, alors j'essaie d'être à la hauteur.\p"
	.string "Mais je suppose que ça fait partie du rôle\n"
	.string "de TOPDRESSEUR.\p"
	.string "Je vais devoir m'accrocher…\n"
	.string "et faire bonne figure.\p"
	.string "Tu es la seule personne à qui je peux\n"
	.string "me confier comme ça.\p"
	.string "Mais la prochaine fois qu'on se verra,\n"
	.string "ne t'inquiète pas, je ne me plaindrai pas !$"

MatchCall_PersonalizedText8::
	.string "Youhou, c'est {STR_VAR_1} !\n"
	.string "Comment vas-tu ?\p"
	.string "J'ai entraîné mes POKéMON en pensant\n"
	.string "à toi comme objectif.\p"
	.string "Je n'ai pas l'intention de perdre la\n"
	.string "prochaine fois qu'on se battra.\p"
	.string "C'est super d'avoir des amis dresseurs !\n"
	.string "On se revoit bientôt !$"

MatchCall_PersonalizedText9::
	.string "C'est {STR_VAR_1}…\n"
	.string "Juste derrière toi, en ce moment…\l"
	.string "Il n'y avait pas quelque chose… ?\p"
	.string "Le pouvoir des POKéMON qui dorment\n"
	.string "ici au MT. PYRE…\p"
	.string "Il me parle de toi…\p"
	.string "Tu devrais partir vite et ne jamais\n"
	.string "te retourner…\p"
	.string "Hihihi…\n"
	.string "Adieu…$"

MatchCall_PersonalizedText10::
	.string "C'est {STR_VAR_1}.\n"
	.string "Comment vas-tu ?\p"
	.string "N'est-ce pas pratique de pouvoir\n"
	.string "discuter comme ça à distance ?\p"
	.string "Avant, si je voulais parler à quelqu'un,\n"
	.string "je devais demander à mon père de me conduire…\p"
	.string "Je dois y aller maintenant.\n"
	.string "Je suis content d'avoir pu discuter !$"

MatchCall_PersonalizedText11::
	.string "C'est {STR_VAR_1} !\n"
	.string "Tu veux écouter ça ?\p"
	.string "J'adore la ZONE SAFARI,\n"
	.string "mais à chaque fois, je me perds !\p"
	.string "Toute cette herbe haute !\n"
	.string "Et c'est tellement grand !\p"
	.string "Ça fait du bien d'en parler !\p"
	.string "Je retourne à la ZONE SAFARI !\n"
	.string "À plus !$"

MatchCall_PersonalizedText12::
	.string "Bonjour, ici {STR_VAR_1}.\n"
	.string "Oui, c'est vrai, je suis riche, oui.\p"
	.string "Je dois te dire, ma fortune a\n"
	.string "augmenté depuis notre dernière rencontre.\p"
	.string "En plus, mes POKéMON sont aussi\n"
	.string "devenus plus forts.\p"
	.string "J'ai l'impression que ce monde existe\n"
	.string "pour moi !\p"
	.string "Oh, inutile de dire un mot !\n"
	.string "Tout le monde le sait !\p"
	.string "Oh, excuse-moi, je dois aller à un\n"
	.string "dîner officiel.$"

MatchCall_PersonalizedText13::
	.string "Ufufufufu…\n"
	.string "C'est moi, {STR_VAR_1}…\p"
	.string "Devine ce que je vois ?\n"
	.string "Un duo de {STR_VAR_2} en combat.\p"
	.string "Peut-être que j'essaierai d'attraper le gagnant…\n"
	.string "Ufufufufufu…\p"
	.string "Je… Je suis un peu occupée maintenant.\n"
	.string "Je dois y aller.$"

MatchCall_PersonalizedText14::
	.string "Oh, c'est {STR_VAR_1} !\p"
	.string "Je pensais justement que je commençais\n"
	.string "à me lasser du BATEAU ABANDONNÉ.\p"
	.string "Mais puisque je suis déjà là,\n"
	.string "et que je veux te battre au moins une fois,\l"
	.string "je vais rester encore un peu.\p"
	.string "Si tu en as envie, viens me voir !\p"
	.string "Je pense qu'aujourd'hui sera le jour où\n"
	.string "je défierai enfin l'homme d'à côté.\p"
	.string "À bientôt !$"

MatchCall_PersonalizedText15::
	.string "Je suis {STR_VAR_1} !\n"
	.string "L'homme de la mer !\p"
	.string "Tu sais ce que je pense ?\p"
	.string "Les dresseurs en mer sont\n"
	.string "les plus forts des plus forts !\p"
	.string "Tu devrais t'inspirer de moi et t'entraîner\n"
	.string "en mer…\p"
	.string "Oups, une grosse vague arrive !\p"
	.string "C'est une super occasion d'entraînement !\n"
	.string "Désolé, je dois y aller !$"

MatchCall_PersonalizedText16::
	.string "C'est {STR_VAR_1} ! Écoute, j'ai appris\n"
	.string "le karaté à mes POKéMON.\p"
	.string "Mais maintenant ils sont meilleurs que moi !\n"
	.string "Je ne fais que perdre contre eux !\p"
	.string "Mais même si je perds contre mes POKéMON,\n"
	.string "je ne perdrai pas contre un autre dresseur !\p"
	.string "Il faut qu'on se batte à nouveau !\n"
	.string "Ugwaah !$"

MatchCall_PersonalizedText17::
	.string "C'est moi, {STR_VAR_1}.\n"
	.string "Comment se passent tes voyages ?\p"
	.string "…Ouah, c'est vrai ?\n"
	.string "Ça a l'air super palpitant !\p"
	.string "Je pense que je pourrais écrire une chanson\n"
	.string "sur une de tes aventures.\p"
	.string "…Oh, attends, je la sens venir.\n"
	.string "J'entends déjà la mélodie dans ma tête.\p"
	.string "Je dois vite écrire ce morceau,\n"
	.string "alors je file ! À plus !$"

MatchCall_PersonalizedText18::
	.string "C'est {STR_VAR_1}…\n"
	.string "Écoute ma nouvelle chanson.\p"
	.string "Lalala, {STR_VAR_2}, {STR_VAR_2} !\n"
	.string "Pourquoi es-tu ce {STR_VAR_2} ?\l"
	.string "Pourquoi je ne peux pas être toi, {STR_VAR_2} ?\l"
	.string "Lala, {STR_VAR_2} et {STR_VAR_1},\l"
	.string "{STR_VAR_1} et {STR_VAR_2}…\p"
	.string "On répète le refrain, fondu…$"

MatchCall_PersonalizedText19::
	.string "Je suis {STR_VAR_1}, tu sais,\n"
	.string "l'expert du camping !\p"
	.string "Quand on s'est battus, je n'ai pas pu\n"
	.string "m'empêcher de perdre contre toi.\p"
	.string "Après tout, mon domaine, c'est le camping.\p"
	.string "Mais gagner ou perdre, j'aime me battre\n"
	.string "quand je campe.\p"
	.string "Viens te battre avec nous encore, d'accord ?\n"
	.string "Oh, et allons camper aussi !$"

MatchCall_PersonalizedText20::
	.string "C'est moi, moi, {STR_VAR_1} !\p"
	.string "J'aimerais grimper d'autres montagnes\n"
	.string "que celle-ci, pour être honnête.\p"
	.string "Mais je ne sais pas s'il y aurait des dames\n"
	.string "comme au MT. CHIMNÉE.\p"
	.string "Si tu connais une autre montagne\n"
	.string "avec des dames, dis-le-moi !\p"
	.string "Ehehehe, à bientôt !$"

MatchCall_PersonalizedText21::
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "C'est {STR_VAR_1}…\p"
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "C'est tout pour aujourd'hui…$"

MatchCall_PersonalizedText22::
	.string "C'est {STR_VAR_1}. Aujourd'hui, j'ai eu\n"
	.string "le pressentiment qu'on allait discuter.\p"
	.string "Mon envie de te battre grandit\n"
	.string "jour et nuit.\p"
	.string "Toi aussi tu as un rival comme ça, non ?\n"
	.string "J'aimerais que ce soit moi…\p"
	.string "Merci de m'avoir écouté.\n"
	.string "À bientôt !$"

MatchCall_PersonalizedText23::
	.string "C'est {STR_VAR_1}.\p"
	.string "Quand il y a un dresseur fort\n"
	.string "dans les environs, je le sens parfois\l"
	.string "d'une façon ou d'une autre.\p"
	.string "Tu es passé près d'ici, {PLAYER}{KUN} ?\n"
	.string "C'était peut-être toi.\p"
	.string "Je t'attendrai pour une visite.\n"
	.string "À bientôt !$"

MatchCall_PersonalizedText24::
	.string "Bonjour, ici {STR_VAR_1}.\n"
	.string "Tu as l'air en forme, {PLAYER}{KUN}.\p"
	.string "J'ai voyagé autour du monde,\n"
	.string "mais je dois dire que j'aime beaucoup cette région.\p"
	.string "Je compte rester ici un moment.\n"
	.string "Peut-être qu'on pourra se revoir ?\p"
	.string "Je n'ai pas oublié tes techniques brillantes.\p"
	.string "J'espère vraiment un nouveau combat !$"

MatchCall_PersonalizedText25::
	.string "Snif… C'est… {STR_VAR_1}…\n"
	.string "…Snif…\p"
	.string "ROXANNE m'a grondé en classe\n"
	.string "aujourd'hui.\p"
	.string "Mais je ne la déteste pas ou quoi.\p"
	.string "ROXANNE me dit exactement ce que\n"
	.string "j'ai mal fait pour que je progresse.\p"
	.string "Tu peux être sûr que j'irai à\n"
	.string "l'ÉCOLE DES DRESSEURS demain !\p"
	.string "À plus tard !$"

MatchCall_PersonalizedText26::
	.string "C'est {STR_VAR_1} !\p"
	.string "ROXANNE m'a laissé me battre contre elle\n"
	.string "hier.\p"
	.string "Le résultat…\n"
	.string "Affreux, comme si tu ne t'en doutais pas.\p"
	.string "Mais j'étais ravi que ROXANNE\n"
	.string "accepte même de me défier !\p"
	.string "Tu ne peux pas savoir à quel point\n"
	.string "je l'admire encore plus !\p"
	.string "Je vais vraiment me concentrer et bosser !\n"
	.string "Je dois y aller !$"

MatchCall_PersonalizedText27::
	.string "Salut, c'est ANNA ! Je suis encore avec ma\n"
	.string "partenaire MEG aujourd'hui.\p"
	.string "J'adore m'occuper de MEG et des POKéMON.\n"
	.string "Ils sont trop mignons !\p"
	.string "J'aimerais pouvoir m'occuper d'eux\n"
	.string "comme s'ils étaient mes frères et sœurs !\p"
	.string "Oh, salut, MEG !\n"
	.string "Tu as pris les petits pains ?\p"
	.string "Hein ? Non, non, je ne te traite pas\n"
	.string "comme mon esclave !\p"
	.string "Tu as perdu le match, alors tu dois\n"
	.string "aller acheter le pain comme punition !\p"
	.string "Je ne te traiterais jamais comme une esclave,\n"
	.string "MEG ! Tu es trop spéciale pour moi !\p"
	.string "Je dois y aller maintenant.\n"
	.string "C'est l'heure du goûter !$"

MatchCall_PersonalizedText28::
	.string "J'adore les POKéMON !\n"
	.string "C'est {STR_VAR_1} du FAN CLUB !\p"
	.string "Tu dois entendre ça !\n"
	.string "Mon adorable POKéMON…\p"
	.string "Snif ! Wahaha !\n"
	.string "Je ne peux pas en dire plus ! C'est un secret !\l"
	.string "C'est trop mignon pour être décrit !\p"
	.string "Oh, mon cher {STR_VAR_2} réclame\n"
	.string "un {POKEBLOCK} !\p"
	.string "C'est la perfection de la mignonnerie !\p"
	.string "Désolé, je ne peux pas parler maintenant !\n"
	.string "Tu devras entendre ça la prochaine fois !$"

MatchCall_PersonalizedText29::
	.string "Ohoho !\p"
	.string "C'est {STR_VAR_1} ! Je meurs d'envie de\n"
	.string "te parler de mon cher POKéMON !\p"
	.string "S'il te plaît, écoute-moi.\n"
	.string "C'est à propos de mon cher {STR_VAR_2}.\p"
	.string "Dès que quelqu'un le prend,\n"
	.string "il saute dans mes bras !\p"
	.string "Oh… Oh… Y a-t-il quelque chose\n"
	.string "de plus merveilleux ?\p"
	.string "Oh, c'est si divin !\p"
	.string "Je suis si heureux d'avoir pu partager\n"
	.string "un peu de mon bonheur avec toi.\p"
	.string "Bon, je dois y aller.\n"
	.string "Au revoir !$"

MatchCall_PersonalizedText30::
	.string "Je suis… {STR_VAR_1}.\n"
	.string "On m'appelle un EXPERT.\p"
	.string "Mais il y a une chose que je sais.\n"
	.string "Je ne pourrais pas être EXPERT par ma seule force.\p"
	.string "C'est seulement avec l'aide des POKéMON\n"
	.string "qu'un dresseur devient EXPERT.\p"
	.string "Humph ! Je crois que je viens de dire\n"
	.string "quelque chose de profond !\p"
	.string "Je te laisse de bonne humeur !$"

MatchCall_PersonalizedText31::
	.string "C'est {STR_VAR_1}.\n"
	.string "Je suis content de discuter avec toi !\p"
	.string "Je me sens vivant et rafraîchi\n"
	.string "en me baignant dans cette source chaude.\p"
	.string "J'ai affronté de jeunes dresseurs\n"
	.string "depuis qu'on s'est rencontrés, mais tu restes\l"
	.string "le meilleur de tous.\p"
	.string "Je pense que tu deviendras un EXPERT\n"
	.string "en vieillissant ! Ohohoho…$"

MatchCall_PersonalizedText32::
	.string "Youpi ! C'est {STR_VAR_1} !\n"
	.string "Quoi de neuf ?\p"
	.string "Je me fais peut-être des idées, mais quand\n"
	.string "je gagne des combats, mon short semble\l"
	.string "plus agréable à porter. Vraiment !\p"
	.string "Qu'est-ce que je veux dire par là ?\n"
	.string "C'est difficile à expliquer, mais…\l"
	.string "Comment dire…\l"
	.string "Mon short est plus soyeux !\p"
	.string "Et quand je me suis battu contre toi, {PLAYER}{KUN},\n"
	.string "mon short était rêche et désagréable.\p"
	.string "… … … … … …\n"
	.string "Tu n'as pas vraiment cru ça ?\l"
	.string "Ehehehe, c'est tout ! À plus !$"

MatchCall_PersonalizedText33::
	.string "Ohé !\n"
	.string "C'est {STR_VAR_1} !\p"
	.string "Comme toujours, je pêche avec une\n"
	.string "énergie folle !\p"
	.string "Y a-t-il d'autres endroits où je peux\n"
	.string "pêcher que la mer et les rivières ?\p"
	.string "J'ai parfois de puissantes envies de\n"
	.string "pêcher n'importe où !\p"
	.string "Oh, mince alors !\n"
	.string "Ma ligne est toute emmêlée !\p"
	.string "Je dois y aller !\n"
	.string "Trouve-moi de nouveaux coins de pêche !$"

MatchCall_PersonalizedText34::
	.string "Salut ! C'est {STR_VAR_1}.\n"
	.string "Tu prends la vie cool ?\p"
	.string "Depuis que je suis petit, tu sais,\n"
	.string "j'ai toujours été calme, hein ?\p"
	.string "Je n'ai jamais été du genre à me\n"
	.string "stresser ou à me presser.\p"
	.string "Mais tu vois, maintenant je suis\n"
	.string "TRIATHLÈTE.\p"
	.string "On ne sait jamais où la vie peut\n"
	.string "nous mener, tu vois ?\p"
	.string "Tu es DRESSEUR maintenant, mais qui\n"
	.string "sait ce que l'avenir te réserve, hein ?\p"
	.string "Imagine-toi professeur,\n"
	.string "ou peut-être artiste. Sympa, non ?\p"
	.string "Mais, hé, reste cool. Prends la vie cool.\n"
	.string "À la prochaine !$"

MatchCall_PersonalizedText35::
	.string "C'est {STR_VAR_1} !\n"
	.string "Je fais du vélo en ce moment.\p"
	.string "J'adore nager et courir,\n"
	.string "mais le vélo, c'est mon premier amour !\p"
	.string "J'ai l'impression que tout mon corps\n"
	.string "ne fait qu'un avec le vent.\p"
	.string "C'est grisant, comme si je volais !\p"
	.string "Bon ! Aujourd'hui, je vais battre un\n"
	.string "nouveau record sur la PISTE CYCLABLE !\p"
	.string "Tu devrais essayer aussi !\n"
	.string "À bientôt !$"

MatchCall_PersonalizedText36::
	.string "Yo, c'est {STR_VAR_1} ! Je suis en plein\n"
	.string "milieu d'un triathlon !\p"
	.string "Mais j'ai toujours le temps de\n"
	.string "bavarder un peu !\p"
	.string "Faire du sport avec des POKéMON,\n"
	.string "c'est vraiment génial !\p"
	.string "Sans même parler, on se synchronise\n"
	.string "comme si on partageait un cœur.\p"
	.string "C'est inspirant !\p"
	.string "Hah… Parler en courant…\n"
	.string "Je commence à fatiguer…\l"
	.string "Hah… Je… dois… y aller…$"

MatchCall_PersonalizedText37::
	.string "Salut, c'est {STR_VAR_1}.\n"
	.string "Si tu veux améliorer ton endurance,\l"
	.string "l'entraînement en altitude, c'est le top !\p"
	.string "Essaie de courir au sommet d'une montagne.\n"
	.string "Tu seras vite à bout de souffle !\p"
	.string "Je manque d'oxygène moi aussi !\n"
	.string "À plus !$"

MatchCall_PersonalizedText38::
	.string "Oh, c'est {STR_VAR_1}, bonjour.\p"
	.string "J'ai beaucoup nagé mais je n'arrive\n"
	.string "toujours pas à atteindre ÉVERGRANDE.\p"
	.string "Peut-être que je tourne en rond.\p"
	.string "Non, non, ce n'est pas possible.\n"
	.string "Wahahaha.\l"
	.string "Prends soin de toi !$"

MatchCall_PersonalizedText39::
	.string "Hé, c'est {STR_VAR_1}…\n"
	.string "Oups !\p"
	.string "Plouf !\p"
	.string "Blou-blou-blou-blou…\p"
	.string "Splaf !\p"
	.string "Snif-snif ! Snif-snif !\p"
	.string "Oh ! Désolé pour ça !\n"
	.string "Je viens de mettre de la crème solaire.\p"
	.string "Du coup, mon POKéNAV a glissé\n"
	.string "de ma main dans l'eau !\p"
	.string "Mais, dis donc, le POKéNAV de DEVON\n"
	.string "est solide. Il a survécu à la baignade !\p"
	.string "Bref, je bronze, alors on discutera\n"
	.string "une autre fois.$"

MatchCall_PersonalizedText40::
	.string "Bonjour, c'est {STR_VAR_1}.\p"
	.string "Parmi les trois épreuves du triathlon,\n"
	.string "je préfère la natation.\p"
	.string "Mais si je reste trop longtemps dans la mer,\n"
	.string "je vais finir tout fripé, non ?\p"
	.string "Ouh, le triathlon est une telle épreuve\n"
	.string "pour l'endurance humaine ! À bientôt !$"

MatchCall_PersonalizedText41::
	.string "Bonjour, {PLAYER}{KUN}.\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "Comment vont tes POKéMON ?\p"
	.string "Mes POKéMON DRAGON semblent être\n"
	.string "en pleine forme. À bientôt !$"

MatchCall_PersonalizedText42::
	.string "C'est {STR_VAR_1}.\p"
	.string "Mon {STR_VAR_2} est devenu encore plus\n"
	.string "fort que la dernière fois.\p"
	.string "Je ne perdrai plus contre toi.\n"
	.string "Attends-toi à la prochaine fois !\p"
	.string "À la prochaine !$"

MatchCall_PersonalizedText43::
	.string "C'est {STR_VAR_1}.\p"
	.string "J'ai poursuivi mes études dans\n"
	.string "l'art de la dissimulation.\p"
	.string "Mais j'ai trop bien réussi.\n"
	.string "Personne n'a pu me trouver.\l"
	.string "Ma réussite me rend solitaire…\p"
	.string "Comme la fumée, je disparais !\n"
	.string "Adieu !$"

MatchCall_PersonalizedText44::
	.string "C'est {STR_VAR_1}.\n"
	.string "Je me suis entraîné depuis qu'on s'est vus.\p"
	.string "Mon {STR_VAR_2} devient vraiment\n"
	.string "costaud.\p"
	.string "S'entraîner sur la plage, c'est efficace,\n"
	.string "comme je le pensais. À bientôt !$"

MatchCall_PersonalizedText45::
	.string "Comment ça va ?\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "Je me demande quand cette vilaine\n"
	.string "cendre volcanique va arrêter de tomber ?\p"
	.string "Si elle devient trop épaisse, elle va\n"
	.string "couvrir le motif de mon parasol…\p"
	.string "Promettons-nous de nous revoir !$"

MatchCall_PersonalizedText46::
	.string "Salut, c'est {STR_VAR_1}.\p"
	.string "Tu savais qu'il est plus facile de\n"
	.string "flotter dans la mer que dans une piscine ?\p"
	.string "En restant immobile, ton corps flotte\n"
	.string "tout seul.\p"
	.string "Mais si tu flottes trop longtemps,\n"
	.string "fais attention à ne pas te laisser\l"
	.string "emporter trop loin.\p"
	.string "…Où suis-je, d'ailleurs ?\n"
	.string "Je ferais mieux d'y aller !$"

MatchCall_PersonalizedText47::
	.string "Oh, {PLAYER}{KUN}, bonjour !\n"
	.string "C'est {STR_VAR_1}.\l"
	.string "Je suis dans les montagnes maintenant.\p"
	.string "Mais le sol est trop bosselé.\n"
	.string "Je ne peux pas planter ma tente ici…\p"
	.string "Oh, j'ai une idée géniale !\p"
	.string "Peut-être que mes POKéMON peuvent\n"
	.string "aplatir le sol ici !\p"
	.string "Je vais essayer ça !\n"
	.string "À bientôt !$"

MatchCall_PersonalizedText48::
	.string "Oh, salut, salut, c'est {STR_VAR_1} !\p"
	.string "J'élève des POKéMON avec LIV !\n"
	.string "On fait de notre mieux !\p"
	.string "Si on s'applique encore plus, on peut\n"
	.string "devenir numéro un ? À bientôt !$"

MatchCall_PersonalizedText49::
	.string "C'est {STR_VAR_1} !\p"
	.string "Je suis MARIN, mais je ne suis pas sur un bateau\n"
	.string "en ce moment.\p"
	.string "Je me demande—comment appelle-t-on\n"
	.string "un MARIN sur la terre ferme ?\p"
	.string "C'est à ça que je pense en regardant\n"
	.string "l'horizon sur les vagues.\p"
	.string "Bon, à la prochaine !$"

MatchCall_PersonalizedText50::
	.string "C'est {STR_VAR_1}.\n"
	.string "Alors ? Tu as attrapé d'autres POKéMON ?\p"
	.string "Si tu attrapes un nouveau POKéMON,\n"
	.string "tu dois venir me le montrer.\p"
	.string "Je ne vais pas pleurnicher, promis.\n"
	.string "Je t'attendrai. À bientôt.$"

MatchCall_PersonalizedText51::
	.string "C'est {STR_VAR_1}.\p"
	.string "Tu élèves tes POKéMON de la meilleure\n"
	.string "façon possible ?\p"
	.string "L'air est pur là où je suis.\n"
	.string "C'est l'environnement parfait pour\l"
	.string "élever des POKéMON.\p"
	.string "Si tu veux te concentrer sur l'élevage\n"
	.string "de POKéMON, tu devrais venir à\l"
	.string "{STR_VAR_2}. Prends soin de toi !$"

MatchCall_PersonalizedText52::
	.string "Salut, c'est {STR_VAR_1}.\p"
	.string "J'ai donné un {POKEBLOCK} à mon {STR_VAR_2}.\n"
	.string "Il avait l'air d'adorer ça.\p"
	.string "On dirait que les POKéMON ont leurs\n"
	.string "préférences pour les {POKEBLOCK}S.\p"
	.string "Je trouve ça fascinant.\n"
	.string "Prends soin de toi !$"

MatchCall_PersonalizedText53::
	.string "C'est {STR_VAR_1}.\p"
	.string "Si tu coopères avec les POKéMON,\n"
	.string "on peut être à l'aise dans la nature.\p"
	.string "Tout le monde devrait s'en rendre compte\n"
	.string "et coopérer davantage avec les POKéMON.\p"
	.string "Ce serait l'idéal.\n"
	.string "J'en suis convaincu.\p"
	.string "Je pense que tu es sur la bonne voie !\n"
	.string "À plus tard !$"

MatchCall_PersonalizedText54::
	.string "Salut, c'est {STR_VAR_1}. Tu sais,\n"
	.string "le DRESSEUR toujours prêt !\p"
	.string "{PLAYER}{KUN}, tu as assez d'objets ?\n"
	.string "Tes POKéMON sont prêts à agir ?\p"
	.string "Garder tout parfait autour de toi\n"
	.string "tout le temps, c'est le secret pour\l"
	.string "continuer ton aventure.\p"
	.string "Je vais vérifier mes propres\n"
	.string "provisions ! Sois vigilant !$"

MatchCall_PersonalizedText55::
	.string "C'est {STR_VAR_1} !\n"
	.string "C'est {STR_VAR_1} !\p"
	.string "{STR_VAR_2} est une route très fréquentée,\n"
	.string "alors je me fais défier par plein de\l"
	.string "DRESSEURS chaque jour.\p"
	.string "Aujourd'hui, j'ai gagné cinq combats et\n"
	.string "je n'en ai perdu que trois !\p"
	.string "Et toi, comment ça s'est passé ?\n"
	.string "Raconte-moi la prochaine fois, d'accord ?$"

MatchCall_PersonalizedText56::
	.string "C'est moi, {STR_VAR_1}.\p"
	.string "Je suis populaire parce que j'ai plein\n"
	.string "de POKéMON INSECTE, non ?\p"
	.string "J'ai emmené plein de mes insectes\n"
	.string "préférés à l'école aujourd'hui.\p"
	.string "La fille que j'aime s'est mise à pleurer !\n"
	.string "Tu peux te moquer si tu veux.\p"
	.string "Je dois lui apprendre ce qui rend\n"
	.string "les POKéMON INSECTE si géniaux.\p"
	.string "Snif…\n"
	.string "À plus !$"

MatchCall_PersonalizedText57::
	.string "Hah ! Hah ! Hah ! Hah !\p"
	.string "Salut ! C'est {STR_VAR_1} ! Hah ! Hah !\p"
	.string "Essayer de parler…\n"
	.string "En grimpant…\l"
	.string "C'est du sport… Hah ! Hah !\p"
	.string "Ouf ! Aïe…\n"
	.string "Ça devient plus raide…\l"
	.string "On parlera… une autre fois…\l"
	.string "Hah ! Hah ! Hah !$"

MatchCall_PersonalizedText58::
	.string "Oh, salut !\p"
	.string "Je cherche encore des trésors\n"
	.string "avec KIRA !\p"
	.string "Peut-être qu'il n'y a pas de trésor\n"
	.string "ici du tout…\p"
	.string "Mais l'important, c'est de chercher\n"
	.string "avec KIRA.\p"
	.string "Oh, hé, KIRA !\n"
	.string "P-pourquoi tu es fâchée ?\p"
	.string "Je ne t'ignore pas, chérie !\n"
	.string "Tu es mon unique et seule !\p"
	.string "…{PLAYER}, je dois y aller, salut !$"

MatchCall_PersonalizedText59::
	.string "C'est {STR_VAR_1} !\p"
	.string "Je suis retourné à l'ARÈNE de MYOKARA\n"
	.string "pour m'entraîner.\p"
	.string "BRAWLY, le CHAMPION d'ARÈNE, a l'air\n"
	.string "encore plus fort maintenant.\p"
	.string "Il paraît qu'il s'est endurci avec\n"
	.string "les vagues sauvages…\p"
	.string "Mais il est toujours aussi cool.\n"
	.string "Les filles l'adorent !\l"
	.string "J'en suis jaloux, franchement.\p"
	.string "Je me demande… Est-ce que son ami BRUNO\n"
	.string "est comme BRAWLY ?\p"
	.string "Tu sais, tout en sueur ou qui sent fort,\n"
	.string "et qui appelle les gens “grosse vague”, ce genre de truc.\p"
	.string "Mais bon, la jalousie, c'est pas très joli, hein ?\p"
	.string "Oublie cette discussion, d'accord ?\n"
	.string "Allez, salut !$"

MatchCall_PersonalizedText60::
	.string "C'est un plaisir de discuter avec\n"
	.string "un jeune DRESSEUR comme toi.\p"
	.string "J'imagine que tu continueras à aimer\n"
	.string "les POKéMON quel que soit ton âge.\p"
	.string "Ce serait bien d'avoir un partenariat\n"
	.string "comme le nôtre, non ?\p"
	.string "Bien sûr, {PLAYER}{KUN}, tu profites déjà\n"
	.string "de la confiance et de la compagnie\l"
	.string "de tes POKéMON.\p"
	.string "Tu as déjà tout pour des relations\n"
	.string "longues et durables !\p"
	.string "Hahaha !\n"
	.string "Ne te décourage jamais !$"

MatchCall_PersonalizedText61::
	.string "Salut, c'est {STR_VAR_1} !\n"
	.string "On vient de gagner un combat !\p"
	.string "On ne gagne pas souvent, mais c'était\n"
	.string "contre un super NAGEUR.\p"
	.string "Ma sœur était furieuse !\p"
	.string "Elle voulait faire semblant d'être faible\n"
	.string "pour impressionner !\p"
	.string "Elle me gronde toujours, qu'on gagne\n"
	.string "ou qu'on perde !\p"
	.string "{PLAYER}{KUN}, tu pourrais lui dire un mot\n"
	.string "la prochaine fois ?\p"
	.string "Bon, à plus !$"

MatchCall_PersonalizedText62::
	.string "C'est {STR_VAR_1}, oui.\n"
	.string "Je suis parti en mer hier.\p"
	.string "J'espérais trouver une nouvelle\n"
	.string "ruine à explorer.\p"
	.string "Mais les marées m'ont ramené\n"
	.string "là où j'ai commencé.\p"
	.string "Je suis encore faible en combat…\n"
	.string "Moque-toi si tu veux…\l"
	.string "Mais je n'abandonnerai pas.\p"
	.string "Mon jour viendra quand je découvrirai\n"
	.string "une nouvelle ruine !\p"
	.string "C'est tout ce que j'avais à dire !\n"
	.string "Adieu pour l'instant !$"

MatchCall_PersonalizedText63::
	.string "Ohé !\n"
	.string "C'est moi, {STR_VAR_1} !\l"
	.string "Je suis sur la ROUTE 108 maintenant !\l"
	.string "Comme d'habitude, quoi !\p"
	.string "Aujourd'hui, une superbe NAGEUSE\n"
	.string "est passée à côté de moi !\p"
	.string "Alors je l'ai surprise en criant !\p"
	.string "Et elle m'a lancé un regard noir !\p"
	.string "C'était tout pour la ROUTE 108 !\n"
	.string "À bientôt, signé {STR_VAR_1} !$"

MatchCall_PersonalizedText64::
	.string "C'est {STR_VAR_1} !\p"
	.string "Je suis un peu occupé, mais je voulais\n"
	.string "te dire que j'ai encore battu cinq\l"
	.string "DRESSEURS aujourd'hui.\p"
	.string "Si je continue comme ça, je pourrai\n"
	.string "sûrement te battre la prochaine fois.\p"
	.string "Je pense qu'on sera de bons rivaux,\n"
	.string "toi et moi. À bientôt !$"

MatchCall_BattleFrontierStreakText1::
	.string "Salut ! C'est {STR_VAR_1}.\n"
	.string "J'ai entendu la nouvelle !\p"
	.string "On dit que tu as excellé à\n"
	.string "la {STR_VAR_2}.\p"
	.string "C'est génial, {STR_VAR_3} victoires d'affilée ?\n"
	.string "À bientôt !$"

MatchCall_BattleFrontierStreakText2::
	.string "Bonjour, c'est {STR_VAR_1} !\n"
	.string "J'ai entendu parler de toi !\p"
	.string "On dit que tu as gagné {STR_VAR_3} combats\n"
	.string "d'affilée à la {STR_VAR_2}.\p"
	.string "C'est spécial ! Je devrais essayer\n"
	.string "plus fort aussi ! À bientôt !$"

MatchCall_BattleFrontierStreakText3::
	.string "Salut, {PLAYER} !\n"
	.string "C'est moi, {STR_VAR_1}.\p"
	.string "J'ai entendu que tu as tout déchiré à\n"
	.string "la {STR_VAR_2} !\p"
	.string "Une série de {STR_VAR_3} victoires…\n"
	.string "C'est un sacré record, non ?\p"
	.string "Je ferais mieux de m'y mettre aussi !\n"
	.string "À bientôt !$"

MatchCall_BattleFrontierStreakText4::
	.string "Salut, {PLAYER}{KUN}.\n"
	.string "C'est {STR_VAR_1}. Quoi de neuf ?\p"
	.string "Il paraît que tu as enchaîné {STR_VAR_3}\n"
	.string "victoires à la {STR_VAR_2}.\p"
	.string "Je dois m'améliorer aussi.\n"
	.string "À bientôt !$"

MatchCall_BattleFrontierStreakText5::
	.string "Salut, {PLAYER}{KUN} !\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "Tu étais à la {STR_VAR_2}\n"
	.string "et tu as gagné {STR_VAR_3} combats d'affilée ?\l"
	.string "C'est quelque chose !\p"
	.string "Je dois mieux entraîner mes POKéMON.\n"
	.string "À bientôt !$"

MatchCall_BattleFrontierStreakText6::
	.string "Salut, {PLAYER}{KUN}.\n"
	.string "C'est {STR_VAR_1}. Comment ça va ?\p"
	.string "Au fait, j'ai entendu que tu as réussi\n"
	.string "l'exploit de {STR_VAR_3} victoires d'affilée à\l"
	.string "la {STR_VAR_2}.\p"
	.string "Ça m'inspire à me concentrer sur\n"
	.string "l'entraînement de mon équipe.$"

MatchCall_BattleFrontierStreakText7::
	.string "…Euh, {PLAYER}{KUN} ?\n"
	.string "C'est {STR_VAR_1}…\p"
	.string "Ah oui, tu étais à la\n"
	.string "{STR_VAR_2}, non ?\p"
	.string "Et tu as gagné {STR_VAR_3} combats d'affilée.\p"
	.string "Oh, voilà un POKéMON rare !\n"
	.string "Je dois y aller !$"

MatchCall_BattleFrontierStreakText8::
	.string "Oh, {PLAYER}{KUN}, comment vas-tu ?\n"
	.string "C'est {STR_VAR_1} qui parle.\l"
	.string "J'espère que tu vas bien.\p"
	.string "Oh, mais tu vas bien. J'ai entendu que\n"
	.string "tu as gagné {STR_VAR_3} matchs d'affilée à\l"
	.string "la {STR_VAR_2}.\p"
	.string "C'est très impressionnant !\n"
	.string "Je te souhaite de continuer ainsi.$"

MatchCall_BattleFrontierStreakText9::
	.string "Oh, {PLAYER}{KUN}, salut !\n"
	.string "C'est {STR_VAR_1} !\p"
	.string "J'ai entendu ! Ta série de {STR_VAR_3}\n"
	.string "victoires à la {STR_VAR_2} !\p"
	.string "C'est trop cool !\n"
	.string "Je dois essayer plus fort aussi !$"

MatchCall_BattleFrontierStreakText10::
	.string "Oh, {PLAYER}{KUN}, bonjour…\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "Tu as gagné {STR_VAR_3} combats d'affilée à\n"
	.string "la {STR_VAR_2} ?\p"
	.string "C'est un bel exploit.\n"
	.string "Je dois m'améliorer.$"

MatchCall_BattleFrontierStreakText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "On dit que tu fais peur à la\n"
	.string "{STR_VAR_2} ?\p"
	.string "Tu as gagné, quoi, {STR_VAR_3} matchs\n"
	.string "d'affilée ?\p"
	.string "Tu es fort, toi.\n"
	.string "Je me demande combien je peux en gagner !$"

MatchCall_BattleFrontierStreakText12::
	.string "Bonjour, {PLAYER}{KUN}.\n"
	.string "C'est moi, {STR_VAR_1}.\l"
	.string "Tu vas bien ?\p"
	.string "Quelqu'un m'a parlé de toi.\n"
	.string "Comment tu as gagné {STR_VAR_3} combats\l"
	.string "d'affilée à un endroit appelé {STR_VAR_2} ?\p"
	.string "C'est une sacrée histoire.\n"
	.string "À bientôt !$"

MatchCall_BattleFrontierStreakText13::
	.string "Ah, salut, {PLAYER}{KUN} !\n"
	.string "C'est {STR_VAR_1} !\l"
	.string "J'espère que tu vas bien.\p"
	.string "On dit que tu as gagné {STR_VAR_3} combats\n"
	.string "d'affilée à la {STR_VAR_2}.\p"
	.string "J'admire ton énergie !\n"
	.string "À bientôt !$"

MatchCall_BattleFrontierStreakText14::
	.string "Oh, salut, {PLAYER}{KUN}.\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "J'ai entendu parler de toi !\n"
	.string "Tu n'as pas gagné {STR_VAR_3} combats\l"
	.string "d'affilée à la {STR_VAR_2} ?\p"
	.string "Tu es une inspiration !\n"
	.string "À bientôt !$"

MatchCall_BattleFrontierRecordStreakText1::
	.string "Salut ! C'est {STR_VAR_1}.\n"
	.string "J'ai entendu la nouvelle !\p"
	.string "On dit que tu as excellé à\n"
	.string "la {STR_VAR_2}.\p"
	.string "C'est génial—{STR_VAR_3} victoires d'affilée ?\n"
	.string "À bientôt !$"

MatchCall_BattleFrontierRecordStreakText2::
	.string "Bonjour, c'est {STR_VAR_1} !\n"
	.string "J'ai entendu parler de toi !\p"
	.string "On dit que tu as gagné {STR_VAR_3} combats\n"
	.string "d'affilée à la {STR_VAR_2}.\p"
	.string "C'est spécial ! Je devrais essayer\n"
	.string "plus fort aussi ! À bientôt !$"

MatchCall_BattleFrontierRecordStreakText3::
	.string "Salut, {PLAYER} !\n"
	.string "C'est moi, {STR_VAR_1}.\p"
	.string "J'ai entendu que tu as tout déchiré à\n"
	.string "la {STR_VAR_2} !\p"
	.string "Une série de {STR_VAR_3} victoires…\n"
	.string "C'est un sacré record, non ?\p"
	.string "Je ferais mieux de m'y mettre aussi !\n"
	.string "À bientôt !$"

MatchCall_BattleFrontierRecordStreakText4::
	.string "Salut, {PLAYER}{KUN}.\n"
	.string "C'est {STR_VAR_1}. Quoi de neuf ?\p"
	.string "Il paraît que tu as enchaîné {STR_VAR_3}\n"
	.string "victoires à la {STR_VAR_2}.\p"
	.string "Je dois m'améliorer aussi.\n"
	.string "À bientôt !$"

MatchCall_BattleFrontierRecordStreakText5::
	.string "Salut, {PLAYER}{KUN} !\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "Tu étais à la {STR_VAR_2}\n"
	.string "et tu as gagné {STR_VAR_3} combats d'affilée ?\l"
	.string "C'est quelque chose !\p"
	.string "Moi ? Je progresse, je dirais.\n"
	.string "À bientôt !$"

MatchCall_BattleFrontierRecordStreakText6::
	.string "Salut, {PLAYER}{KUN}.\n"
	.string "C'est {STR_VAR_1}. Comment ça va ?\p"
	.string "Au fait, j'ai entendu que tu as réussi\n"
	.string "l'exploit de {STR_VAR_3} victoires d'affilée à\l"
	.string "la {STR_VAR_2}.\p"
	.string "Je dois essayer plus fort moi-même !\n"
	.string "À bientôt !$"

MatchCall_BattleFrontierRecordStreakText7::
	.string "…Euh, {PLAYER}{KUN} ?\n"
	.string "C'est {STR_VAR_1}…\p"
	.string "Ah oui, tu étais à la\n"
	.string "{STR_VAR_2}, non ?\p"
	.string "Et tu as gagné {STR_VAR_3} combats d'affilée.\p"
	.string "Oh, voilà un POKéMON rare !\n"
	.string "Je dois y aller !$"

MatchCall_BattleFrontierRecordStreakText8::
	.string "Oh, {PLAYER}{KUN}, comment vas-tu ?\n"
	.string "C'est {STR_VAR_1} qui parle.\l"
	.string "J'espère que tu vas bien.\p"
	.string "Oh, mais tu vas bien. J'ai entendu que\n"
	.string "tu as gagné {STR_VAR_3} matchs d'affilée à\l"
	.string "la {STR_VAR_2}.\p"
	.string "C'est très impressionnant !\n"
	.string "Je dois aussi entraîner mes POKéMON !$"

MatchCall_BattleFrontierRecordStreakText9::
	.string "Oh, {PLAYER}{KUN}, salut !\n"
	.string "C'est {STR_VAR_1} !\p"
	.string "J'ai entendu ! Ta série de {STR_VAR_3}\n"
	.string "victoires à la {STR_VAR_2} !\p"
	.string "C'est trop cool !\n"
	.string "Je dois essayer plus fort aussi !$"

MatchCall_BattleFrontierRecordStreakText10::
	.string "Oh, {PLAYER}{KUN}, bonjour…\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "Tu as gagné {STR_VAR_3} combats d'affilée à\n"
	.string "la {STR_VAR_2} ?\p"
	.string "C'est un bel exploit.\n"
	.string "Je dois m'améliorer.$"

MatchCall_BattleFrontierRecordStreakText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "On dit que tu fais peur à la\n"
	.string "{STR_VAR_2} ?\p"
	.string "Tu as gagné, quoi, {STR_VAR_3} matchs\n"
	.string "d'affilée ?\p"
	.string "Tu es fort, toi.\n"
	.string "Je me demande combien je peux en gagner !$"

MatchCall_BattleFrontierRecordStreakText12::
	.string "Bonjour, {PLAYER}{KUN}.\n"
	.string "C'est moi, {STR_VAR_1}.\l"
	.string "Tu vas bien ?\p"
	.string "Quelqu'un m'a parlé de toi.\n"
	.string "Comment tu as gagné {STR_VAR_3} combats\l"
	.string "d'affilée à un endroit appelé {STR_VAR_2} ?\p"
	.string "C'est une sacrée histoire.\n"
	.string "À bientôt !$"

MatchCall_BattleFrontierRecordStreakText13::
	.string "Ah, salut, {PLAYER}{KUN} !\n"
	.string "C'est {STR_VAR_1} !\l"
	.string "J'espère que tu vas bien.\p"
	.string "On dit que tu as gagné {STR_VAR_3} combats\n"
	.string "d'affilée à la {STR_VAR_2}.\p"
	.string "J'admire ton énergie !\n"
	.string "À bientôt !$"

MatchCall_BattleFrontierRecordStreakText14::
	.string "Oh, salut, {PLAYER}{KUN}.\n"
	.string "C'est {STR_VAR_1}.\l"
	.string "J'ai entendu parler de toi !\p"
	.string "Tu n'as pas gagné {STR_VAR_3} combats\n"
	.string "d'affilée à la {STR_VAR_2} ?\p"
	.string "Tu es une inspiration !\n"
	.string "À bientôt !$"

MatchCall_BattleDomeText1::
	.string "Salut ! {PLAYER} ?\n"
	.string "Bonjour, c'est {STR_VAR_1} !\l"
	.string "J'ai entendu la nouvelle !\p"
	.string "Tu es devenu champion à\n"
	.string "la {STR_VAR_2} {STR_VAR_3} fois ?\p"
	.string "C'est génial ! Je dois faire mieux !\n"
	.string "À bientôt !$"

MatchCall_BattleDomeText2::
	.string "Bonjour, c'est {STR_VAR_1} !\n"
	.string "J'ai entendu parler de toi !\p"
	.string "On dit que tu as remporté {STR_VAR_3} titres\n"
	.string "à la {STR_VAR_2}.\p"
	.string "C'est super ! Je me demande si je peux\n"
	.string "devenir champion ?$"

MatchCall_BattleDomeText3::
	.string "Salut, {PLAYER} !\n"
	.string "C'est moi, {STR_VAR_1}.\l"
	.string "Comment ça va ?\p"
	.string "J'ai entendu que tu as gagné {STR_VAR_3} fois\n"
	.string "des épreuves à la {STR_VAR_2} !\p"
	.string "Fais-en une de plus la prochaine fois !\n"
	.string "À bientôt !$"

MatchCall_BattleDomeText4::
	.string "Salut, {PLAYER}{KUN}.\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "J'ai entendu que tu es devenu champion\n"
	.string "à la {STR_VAR_2} {STR_VAR_3} fois.\p"
	.string "On dirait que tu travailles dur.\n"
	.string "Je vais essayer de suivre !$"

MatchCall_BattleDomeText5::
	.string "Salut, {PLAYER}{KUN} !\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "J'ai entendu que tu as gagné {STR_VAR_3} fois\n"
	.string "d'affilée à la {STR_VAR_2}.\p"
	.string "Je dois m'y mettre aussi !\n"
	.string "À bientôt !$"

MatchCall_BattleDomeText6::
	.string "Salut, {PLAYER}{KUN} ?\n"
	.string "C'est {STR_VAR_1}. Comment ça va ?\p"
	.string "Au fait, j'ai entendu que tu es devenu\n"
	.string "champion {STR_VAR_3} fois à\l"
	.string "la {STR_VAR_2}.\p"
	.string "Je dois entraîner mes POKéMON avant\n"
	.string "que tu ne prennes trop d'avance.$"

MatchCall_BattleDomeText7::
	.string "{PLAYER}{KUN} ?\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "Tu étais à la {STR_VAR_2}\n"
	.string "et tu es devenu champion {STR_VAR_3} fois ?\p"
	.string "C'est chouette. Au fait, tu as attrapé\n"
	.string "des POKéMON rares récemment ?\p"
	.string "Ah, d'accord.\n"
	.string "Bon, salut.$"

MatchCall_BattleDomeText8::
	.string "Oh, {PLAYER}{KUN}, comment vas-tu ?\n"
	.string "C'est {STR_VAR_1} qui parle.\l"
	.string "J'espère que tu vas bien.\l"
	.string "Oh, mais tu vas bien.\p"
	.string "J'ai entendu que tu as remporté {STR_VAR_3} titres\n"
	.string "à la {STR_VAR_2}.\p"
	.string "Je dois élever mes POKéMON comme toi.\n"
	.string "À la prochaine !$"

MatchCall_BattleDomeText9::
	.string "Oh, {PLAYER}{KUN}, salut !\n"
	.string "C'est {STR_VAR_1} !\p"
	.string "J'ai entendu ! Tu as remporté le titre\n"
	.string "{STR_VAR_3} fois à la {STR_VAR_2} !\p"
	.string "C'est trop cool !\n"
	.string "Je dois essayer plus fort aussi !$"

MatchCall_BattleDomeText10::
	.string "Oh, {PLAYER}{KUN}, bonjour.\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "Tu as gagné {STR_VAR_3} fois d'affilée à\n"
	.string "la {STR_VAR_2} ?\p"
	.string "C'est un bel exploit.\n"
	.string "Je dois m'améliorer.$"

MatchCall_BattleDomeText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "On dit que tu fais peur à la\n"
	.string "{STR_VAR_2} ?\p"
	.string "Tu as gagné, quoi, {STR_VAR_3} fois d'affilée\n"
	.string "maintenant ?\p"
	.string "Je me demande si je pourrai un jour\n"
	.string "devenir champion ?\p"
	.string "…Plutôt impossible ?\n"
	.string "Bon, à bientôt !$"

MatchCall_BattleDomeText12::
	.string "Bonjour, {PLAYER}{KUN}.\n"
	.string "C'est moi, {STR_VAR_1}.\l"
	.string "Tu vas bien ?\p"
	.string "Tu as gagné {STR_VAR_3} épreuves à un endroit\n"
	.string "appelé {STR_VAR_2} ?\p"
	.string "C'est une sacrée histoire.\n"
	.string "À bientôt !$"

MatchCall_BattleDomeText13::
	.string "Ah, salut, {PLAYER}{KUN} !\n"
	.string "C'est {STR_VAR_1} !\l"
	.string "J'espère que tu vas bien.\p"
	.string "On dit que tu as gagné {STR_VAR_3} épreuves\n"
	.string "à la {STR_VAR_2} ?\p"
	.string "J'admire ton énergie !\n"
	.string "À bientôt !$"

MatchCall_BattleDomeText14::
	.string "Oh, salut, {PLAYER}{KUN}.\n"
	.string "C'est {STR_VAR_1}.\l"
	.string "J'ai entendu parler de toi !\p"
	.string "Tu n'as pas gagné {STR_VAR_3} titres\n"
	.string "à la {STR_VAR_2} ?\p"
	.string "Tu es une inspiration !\n"
	.string "À la prochaine !$"

MatchCall_BattlePikeText1::
	.string "Salut ! {PLAYER} ?\n"
	.string "Bonjour, c'est {STR_VAR_1} !\l"
	.string "J'ai entendu la nouvelle !\p"
	.string "Tu as traversé {STR_VAR_3} salles\n"
	.string "à la {STR_VAR_2} !\p"
	.string "C'est génial !\n"
	.string "À bientôt !$"

MatchCall_BattlePikeText2::
	.string "Bonjour, c'est {STR_VAR_1} !\n"
	.string "J'ai entendu parler de toi !\p"
	.string "On dit que tu as franchi {STR_VAR_3} salles\n"
	.string "à la {STR_VAR_2}.\p"
	.string "Je dois m'entraîner beaucoup plus !\n"
	.string "Salut !$"

MatchCall_BattlePikeText3::
	.string "Salut, {PLAYER} !\n"
	.string "C'est moi, {STR_VAR_1}.\l"
	.string "Comment ça va ?\p"
	.string "J'ai entendu que tu as franchi {STR_VAR_3} salles\n"
	.string "à la {STR_VAR_2} !\p"
	.string "Essaie de faire encore mieux la prochaine fois !\n"
	.string "À bientôt !$"

MatchCall_BattlePikeText4::
	.string "Salut, {PLAYER}{KUN}.\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "J'ai entendu que tu as traversé {STR_VAR_3} salles\n"
	.string "à la {STR_VAR_2}.\p"
	.string "Je dois entraîner mes POKéMON et\n"
	.string "essayer de suivre !$"

MatchCall_BattlePikeText5::
	.string "Salut, {PLAYER}{KUN} !\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "J'ai entendu que tu as passé {STR_VAR_3} salles\n"
	.string "à la {STR_VAR_2}.\p"
	.string "Je dois m'y mettre aussi !\n"
	.string "À bientôt !$"

MatchCall_BattlePikeText6::
	.string "Salut, {PLAYER}{KUN} ?\n"
	.string "C'est {STR_VAR_1}. Comment ça va ?\p"
	.string "Au fait, j'ai entendu que tu as traversé\n"
	.string "{STR_VAR_3} salles à la {STR_VAR_2}.\p"
	.string "Je dois entraîner mes POKéMON avant\n"
	.string "que tu ne prennes trop d'avance.$"

MatchCall_BattlePikeText7::
	.string "{PLAYER}{KUN} ?\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "Tu étais à la {STR_VAR_2}\n"
	.string "et tu as franchi {STR_VAR_3} salles ?\p"
	.string "C'est génial.\p"
	.string "Oh, voilà un POKéMON rare !\n"
	.string "Bon, salut.$"

MatchCall_BattlePikeText8::
	.string "Oh, {PLAYER}{KUN}, comment vas-tu ?\n"
	.string "C'est {STR_VAR_1} qui parle.\l"
	.string "J'espère que tu vas bien.\l"
	.string "Oh, mais tu vas bien.\p"
	.string "J'ai entendu que tu as traversé\n"
	.string "{STR_VAR_3} salles à la {STR_VAR_2}.\p"
	.string "C'est très impressionnant !\n"
	.string "Je dois élever mes POKéMON comme toi.\l"
	.string "À la prochaine !$"

MatchCall_BattlePikeText9::
	.string "Oh, {PLAYER}{KUN}, salut !\n"
	.string "C'est {STR_VAR_1} !\p"
	.string "J'ai entendu ! Tu as franchi\n"
	.string "{STR_VAR_3} salles à la {STR_VAR_2} !\p"
	.string "C'est trop cool !\n"
	.string "Je dois essayer plus fort aussi !$"

MatchCall_BattlePikeText10::
	.string "Oh, {PLAYER}{KUN}, bonjour.\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "Tu as franchi {STR_VAR_3} salles à\n"
	.string "la {STR_VAR_2} ?\p"
	.string "C'est un bel exploit.\n"
	.string "Je dois m'améliorer.$"

MatchCall_BattlePikeText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "On dit que tu fais peur à la\n"
	.string "{STR_VAR_2} ?\p"
	.string "Tu as traversé, quoi, {STR_VAR_3} salles ?\n"
	.string "Ça doit compter pour quelque chose.\p"
	.string "Je me demande si je pourrai un jour\n"
	.string "devenir champion ?\p"
	.string "…Plutôt impossible ?\n"
	.string "Bon, à bientôt !$"

MatchCall_BattlePikeText12::
	.string "Bonjour, {PLAYER}{KUN}.\n"
	.string "C'est moi, {STR_VAR_1}.\l"
	.string "Tu vas bien ?\p"
	.string "Tu as traversé {STR_VAR_3} salles à un endroit\n"
	.string "appelé {STR_VAR_2} ?\p"
	.string "C'est une sacrée histoire.\n"
	.string "À bientôt !$"

MatchCall_BattlePikeText13::
	.string "Ah, salut, {PLAYER}{KUN} !\n"
	.string "C'est {STR_VAR_1} !\l"
	.string "J'espère que tu vas bien.\p"
	.string "On dit que tu as gagné dans {STR_VAR_3} salles\n"
	.string "à la {STR_VAR_2} ?\p"
	.string "J'admire ton énergie !\n"
	.string "À bientôt !$"

MatchCall_BattlePikeText14::
	.string "Oh, salut, {PLAYER}{KUN}.\n"
	.string "C'est {STR_VAR_1}.\l"
	.string "J'ai entendu parler de toi !\p"
	.string "Tu n'as pas traversé {STR_VAR_3} salles\n"
	.string "à la {STR_VAR_2} ?\p"
	.string "Tu es une inspiration !\n"
	.string "À la prochaine !$"

MatchCall_BattlePyramidText1::
	.string "Salut ! {PLAYER} ?\n"
	.string "Bonjour, c'est {STR_VAR_1} !\l"
	.string "J'ai entendu la nouvelle !\p"
	.string "Tu as gravi {STR_VAR_3} étages dans\n"
	.string "la {STR_VAR_2}, c'est bien ça ?\p"
	.string "C'est génial !\n"
	.string "Je devrais essayer ce défi.$"

MatchCall_BattlePyramidText2::
	.string "Bonjour, c'est {STR_VAR_1} !\n"
	.string "J'ai entendu parler de toi !\p"
	.string "On dit que tu as franchi {STR_VAR_3} étages\n"
	.string "dans la {STR_VAR_2}.\p"
	.string "Waouh, c'est fantastique !\n"
	.string "Je dois aussi entraîner mes POKéMON !$"

MatchCall_BattlePyramidText3::
	.string "Salut, {PLAYER} !\n"
	.string "C'est moi, {STR_VAR_1}.\l"
	.string "Comment ça va ?\p"
	.string "J'ai entendu que tu as gravi {STR_VAR_3} étages\n"
	.string "dans la {STR_VAR_2} !\p"
	.string "Essaie de faire encore mieux la prochaine fois !\n"
	.string "À bientôt !$"

MatchCall_BattlePyramidText4::
	.string "Salut, {PLAYER}{KUN}.\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "J'ai entendu que tu as gravi {STR_VAR_3} étages\n"
	.string "dans la {STR_VAR_2}.\p"
	.string "Je dois travailler dur et essayer\n"
	.string "de suivre !$"

MatchCall_BattlePyramidText5::
	.string "Salut, {PLAYER}{KUN} !\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "J'ai entendu que tu as gravi {STR_VAR_3} étages\n"
	.string "dans la {STR_VAR_2}.\p"
	.string "Je dois m'y mettre aussi !\n"
	.string "À bientôt !$"

MatchCall_BattlePyramidText6::
	.string "Salut, {PLAYER}{KUN} ?\n"
	.string "C'est {STR_VAR_1}. Comment ça va ?\p"
	.string "Au fait, j'ai entendu que tu as traversé\n"
	.string "{STR_VAR_3} étages dans la {STR_VAR_2}.\p"
	.string "Je dois entraîner mes POKéMON avant\n"
	.string "que tu ne prennes trop d'avance.$"

MatchCall_BattlePyramidText7::
	.string "{PLAYER}{KUN} ?\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "Tu étais à la {STR_VAR_2}\n"
	.string "et tu as gravi {STR_VAR_3} étages ?\p"
	.string "Sympa. Il y avait des POKéMON rares\n"
	.string "là-bas ?\p"
	.string "Non, hein ?\n"
	.string "Bon, salut.$"

MatchCall_BattlePyramidText8::
	.string "Oh, {PLAYER}{KUN}, comment vas-tu ?\n"
	.string "C'est {STR_VAR_1} qui parle.\l"
	.string "J'espère que tu vas bien.\l"
	.string "Oh, mais tu vas bien.\p"
	.string "J'ai entendu que tu as traversé\n"
	.string "{STR_VAR_3} étages dans la {STR_VAR_2}.\p"
	.string "C'est très impressionnant !\n"
	.string "Je dois élever mes POKéMON comme toi.\l"
	.string "À la prochaine !$"

MatchCall_BattlePyramidText9::
	.string "Oh, {PLAYER}{KUN}, salut !\n"
	.string "C'est {STR_VAR_1} !\p"
	.string "J'ai entendu ! Tu as franchi\n"
	.string "{STR_VAR_3} étages dans la {STR_VAR_2} !\p"
	.string "C'est trop cool !\n"
	.string "Je dois essayer plus fort aussi !$"

MatchCall_BattlePyramidText10::
	.string "Oh, {PLAYER}{KUN}, bonjour.\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "Tu as gravi {STR_VAR_3} étages dans\n"
	.string "la {STR_VAR_2} ?\p"
	.string "C'est un bel exploit.\n"
	.string "Je dois m'améliorer.$"

MatchCall_BattlePyramidText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "On dit que tu fais peur à la\n"
	.string "{STR_VAR_2} ?\p"
	.string "Tu as gravi, quoi, {STR_VAR_3} étages ?\n"
	.string "Ça doit compter pour quelque chose.\p"
	.string "Je me demande si je pourrai un jour\n"
	.string "devenir champion ?\p"
	.string "…Plutôt impossible ?\n"
	.string "Bon, à bientôt !$"

MatchCall_BattlePyramidText12::
	.string "Bonjour, {PLAYER}{KUN}.\n"
	.string "C'est moi, {STR_VAR_1}.\l"
	.string "Tu vas bien ?\p"
	.string "Tu as traversé {STR_VAR_3} étages dans un endroit\n"
	.string "appelé {STR_VAR_2} ?\p"
	.string "C'est une sacrée histoire.\n"
	.string "À bientôt !$"

MatchCall_BattlePyramidText13::
	.string "Ah, salut, {PLAYER}{KUN} !\n"
	.string "C'est {STR_VAR_1} !\l"
	.string "J'espère que tu vas bien.\p"
	.string "On dit que tu as gravi {STR_VAR_3} étages\n"
	.string "dans la {STR_VAR_2} ?\p"
	.string "J'admire ton énergie !\n"
	.string "À bientôt !$"

MatchCall_BattlePyramidText14::
	.string "Oh, salut, {PLAYER}{KUN}.\n"
	.string "C'est {STR_VAR_1}.\l"
	.string "J'ai entendu parler de toi !\p"
	.string "Tu n'as pas traversé {STR_VAR_3} étages\n"
	.string "dans la {STR_VAR_2} ?\p"
	.string "Tu es une inspiration !\n"
	.string "À la prochaine !$"

MatchCall_Text_Mom1::
	.string "MAMAN : Ton père et toi…\n"
	.string "Tout le monde est captivé par les POKéMON.\p"
	.string "Quel est le charme des POKéMON ?\p"
	.string "Moi ?\n"
	.string "J'adore les POKéMON qui m'aident dans\l"
	.string "mes tâches quotidiennes.$"

MatchCall_Text_Mom2::
	.string "MAMAN : Salut, {PLAYER} !\n"
	.string "Ton père reste enfermé dans\l"
	.string "l'ARÈNE de CLÉMENTI-VILLE.\p"
	.string "Il rentre à la maison de temps en temps.\n"
	.string "Mais il retourne à l'ARÈNE dès qu'il\l"
	.string "a tout mangé ce qu'il peut.\p"
	.string "Je parie que perdre contre toi a été\n"
	.string "un sacré coup pour son orgueil !$"

MatchCall_Text_Mom3::
	.string "MAMAN : {PLAYER}…\n"
	.string "Ne t'inquiète pas pour moi ou la maison.\p"
	.string "Porte ces CHAUSSURES DE SPORT jusqu'à\n"
	.string "ce qu'elles tombent en morceaux, chéri(e) !$"

MatchCall_Text_Baoba1::
	.string "BAOBA : {PLAYER} !\n"
	.string "La ZONE SAFARI est presque prête !\p"
	.string "Je t'appellerai dès qu'elle sera\n"
	.string "ouverte !$"

MatchCall_Text_Baoba2::
	.string "BAOBA : {PLAYER} !\n"
	.string "La ZONE SAFARI est ouverte ! Viens\p"
	.string "quand tu veux !$"

MatchCall_Text_Roxanne1::
	.string "ROXANNE : Oh, bonjour, {PLAYER} !\p"
	.string "Je m'entraîne dur depuis notre\n"
	.string "rencontre.\p"
	.string "J'aurai encore besoin d'un peu de temps\n"
	.string "avant de pouvoir rouvrir l'ARÈNE.\p"
	.string "Mais quand ce sera fait, viens me voir\n"
	.string "pour une revanche !$"

MatchCall_Text_Roxanne2::
	.string "ROXANNE : C'est bien {PLAYER} ?\n"
	.string "Félicitations !\l"
	.string "J'entends beaucoup parler de toi !\p"
	.string "Pour ma part, il me faut encore un peu\n"
	.string "de temps avant de rouvrir l'ARÈNE.\p"
	.string "Mais quand ce sera fait, viens me voir\n"
	.string "pour une revanche !$"

MatchCall_Text_Roxanne3::
	.string "ROXANNE : {PLAYER} !\n"
	.string "Mon ARÈNE est prête !\p"
	.string "Viens à MÉROUVILLE quand tu veux !$"

MatchCall_Text_Roxanne4::
	.string "ROXANNE : À l'ARÈNE de MÉROUVILLE,\n"
	.string "le fait que nous nous soyons battus, {PLAYER},\l"
	.string "est une grande fierté.$"

MatchCall_Text_Brawly1::
	.string "BASTIEN : Salut, {PLAYER}{KUN} !\p"
	.string "J'ai beaucoup appris de notre combat.\n"
	.string "Je compte reprendre mon entraînement,\n"
	.string "puis rouvrir l'ARÈNE.\p"
	.string "Il me faudra encore un peu de temps\n"
	.string "avant d'être prêt à la diriger à nouveau.\p"
	.string "Mais si je peux rouvrir l'ARÈNE,\n"
	.string "je veux que tu viennes nous défier encore !$"

MatchCall_Text_Brawly2::
	.string "BASTIEN : Salut, {PLAYER}{KUN} !\n"
	.string "Félicitations !\p"
	.string "On parle de tes exploits jusque sur\n"
	.string "les vagues !\p"
	.string "On dirait que je dois encore m'entraîner\n"
	.string "un peu plus.\p"
	.string "Il me faudra encore un peu de temps\n"
	.string "avant d'être prêt à la diriger à nouveau.\p"
	.string "Mais si je peux rouvrir l'ARÈNE,\n"
	.string "je veux que tu viennes nous défier encore !$"

MatchCall_Text_Brawly3::
	.string "BASTIEN : Salut, {PLAYER}{KUN} !\n"
	.string "Mon ARÈNE est prête à l'action !\p"
	.string "Reviens à MYOKARA quand tu veux\n"
	.string "pour un nouveau défi !$"

MatchCall_Text_Brawly4::
	.string "BASTIEN : {PLAYER}{KUN}, je crois que\n"
	.string "je ne me lasserai jamais de t'affronter !$"

MatchCall_Text_Wattson1::
	.string "VOLTERR : Oh, c'est toi !\p"
	.string "Depuis ton départ, j'ai repris\n"
	.string "mon entraînement depuis le début.\p"
	.string "Je dirais qu'il me faudrait encore\n"
	.string "un peu de temps pour rouvrir mon ARÈNE.\p"
	.string "Il faudra patienter jusque-là !\n"
	.string "Wahahahaha !$"

MatchCall_Text_Wattson2::
	.string "VOLTERR : Wahahahaha !\p"
	.string "Tu l'as vraiment fait, n'est-ce pas ?\n"
	.string "On parle beaucoup de toi !\p"
	.string "Il semble que je doive encore\n"
	.string "m'entraîner davantage.\p"
	.string "Je dirais qu'il me faudrait encore\n"
	.string "un peu de temps pour rouvrir mon ARÈNE.\p"
	.string "Il faudra patienter jusque-là !\n"
	.string "Wahahahaha !$"

MatchCall_Text_Wattson3::
	.string "VOLTERR : Oh, c'est toi !\n"
	.string "Mon ARÈNE est prête !\p"
	.string "Viens à LAVANDIA quand tu veux !\n"
	.string "Wahahahaha !$"

MatchCall_Text_Wattson4::
	.string "VOLTERR : Wahahaha !\p"
	.string "Un combat contre toi est toujours\n"
	.string "électrisant !$"

MatchCall_Text_Flannery1::
	.string "ADRIANE : {PLAYER}…\p"
	.string "Notre combat m'a appris à quel point\n"
	.string "j'étais encore immature.\p"
	.string "Mais je n'ai pas dit mon dernier mot !\p"
	.string "Je vais reprendre mon entraînement et\n"
	.string "rouvrir l'ARÈNE.\p"
	.string "Quand ce sera le moment, {PLAYER},\n"
	.string "viens nous défier à nouveau !$"

MatchCall_Text_Flannery2::
	.string "ADRIANE : Allô, {PLAYER} ?\n"
	.string "Félicitations !\p"
	.string "La nouvelle de ton succès nous est\n"
	.string "parvenue comme la chaleur d'un volcan !\p"
	.string "Notre entraînement avance très bien\n"
	.string "ici.\p"
	.string "Quand l'ARÈNE sera prête, une marque\n"
	.string "apparaîtra à côté de mon nom dans la\l"
	.string "liste MATCH CALL.$"

MatchCall_Text_Flannery3::
	.string "ADRIANE : Oh, {PLAYER} ?\n"
	.string "Notre ARÈNE est prête !\p"
	.string "Viens à VERFEUILLE pour un bain\n"
	.string "thermal et un défi !$"

MatchCall_Text_Flannery4::
	.string "ADRIANE : {PLAYER}…\n"
	.string "Je suis sûre que tu deviens meilleur\l"
	.string "à chaque entraînement.$"

MatchCall_Text_Winona1::
	.string "ALIZÉE : Bonjour, {PLAYER} !\p"
	.string "Grâce à notre combat, j'ai compris\n"
	.string "mes points faibles !\p"
	.string "Quand je rouvrirai l'ARÈNE, je ne\n"
	.string "perdrai plus comme ça !$"

MatchCall_Text_Winona2::
	.string "ALIZÉE : Tu l'as fait, {PLAYER} !\p"
	.string "La nouvelle du nouveau CHAMPION\n"
	.string "est arrivée jusqu'à CLEMENTI-VILLE !\p"
	.string "Mais… La prochaine fois que nous\n"
	.string "combattrons, ce ne sera pas pareil !$"

MatchCall_Text_Winona3::
	.string "ALIZÉE : C'est bien {PLAYER} ?\n"
	.string "Notre ARÈNE est de nouveau ouverte !\p"
	.string "Nous t'attendons à CLEMENTI-VILLE !$"

MatchCall_Text_Winona4::
	.string "ALIZÉE : {PLAYER}…\n"
	.string "Même si j'ai perdu, mes ailes ne\l"
	.string "se briseront jamais.\p"
	.string "Oui, tout comme tu n'as jamais perdu\n"
	.string "de vue ton rêve.$"

MatchCall_Text_TateLiza1::
	.string "LÉO : Oh ! Tu es…\n"
	.string "LÉA : {PLAYER} !\p"
	.string "LÉO : On s'entraîne à nouveau…\n"
	.string "LÉA : Pour pouvoir rouvrir notre ARÈNE !\p"
	.string "LÉO : Quand notre ARÈNE sera prête…\n"
	.string "LÉA : Quand notre ARÈNE sera prête…\p"
	.string "LÉO : Une marque apparaîtra à côté de notre nom…\n"
	.string "LÉA : Dans la liste MATCH CALL.$"

MatchCall_Text_TateLiza2::
	.string "LÉO : {PLAYER}, félicitations !\n"
	.string "LÉA : {PLAYER}, félicitations !\p"
	.string "LÉO : Nous deux, on est…\n"
	.string "LÉA : Toujours en entraînement !\p"
	.string "LÉO : Il nous faut encore un peu de temps, mais…\n"
	.string "LÉA : Quand notre ARÈNE sera prête…\p"
	.string "LÉO : Une marque apparaîtra à côté de notre nom…\n"
	.string "LÉA : Dans la liste MATCH CALL.$"

MatchCall_Text_TateLiza3::
	.string "LÉO : {PLAYER} !\n"
	.string "LÉA : {PLAYER} !\p"
	.string "LÉO : Notre ARÈNE est prête !\n"
	.string "LÉA : Notre ARÈNE est prête !\p"
	.string "LÉO : Viens nous rendre visite…\n"
	.string "LÉA : À ALGATIA quand tu veux !$"

MatchCall_Text_TateLiza4::
	.string "LÉO : {PLAYER}, le combat qu'on a eu…\n"
	.string "LÉA : Est une expérience inestimable.\p"
	.string "LÉO : Ce serait bien si…\n"
	.string "LÉA : On pouvait tous se battre à nouveau !$"

MatchCall_Text_Juan1::
	.string "JUAN : Hmm…\n"
	.string "{PLAYER}{KUN}… C'est bien ça ?\p"
	.string "Notre combat m'a rappelé le moment\n"
	.string "où j'ai rencontré WALLACE pour la première fois.\l"
	.string "Peut-être es-tu un génie qui pourra\n"
	.string "dépasser WALLACE !$"

MatchCall_Text_Juan2::
	.string "JUAN : Fufu… {PLAYER}{KUN}…\n"
	.string "Tu as enfin atteint ton objectif.\p"
	.string "Mon œil pour repérer le talent ne\n"
	.string "s'est pas trompé…\p"
	.string "J'espère avoir une autre chance de\n"
	.string "te rencontrer, car tu as atteint le sommet\l"
	.string "du pouvoir et du prestige.$"

MatchCall_Text_Juan3::
	.string "JUAN : Hoho… {PLAYER}{KUN}…\p"
	.string "Notre ARÈNE de SOOTOPOLIS a enfin\n"
	.string "rouvert.\p"
	.string "Si tu veux me voir, tu es le bienvenu\n"
	.string "quand tu veux !$"

MatchCall_Text_Juan4::
	.string "JUAN : {PLAYER}{KUN}…\p"
	.string "Comme la plus belle des musiques, les combats\n"
	.string "que nous menons ensemble font vibrer\l"
	.string "mon cœur d'inspiration…\p"
	.string "Quand je ferme les yeux, je te vois\n"
	.string "t'envoler avec la mélodie…$"

MatchCall_Text_Sidney::
	.string "SIDNEY : Yo, {PLAYER} !\p"
	.string "Si tu veux te battre à nouveau contre moi,\n"
	.string "reviens à la LIGUE POKéMON quand tu veux.\l"
	.string "Je serai toujours là !\n"
	.string "Je t'attendrai !$"

MatchCall_Text_Phoebe::
	.string "SPECTRA : Salut, {PLAYER} !\p"
	.string "Et si tu revenais ici un de ces jours ?\p"
	.string "J'aimerais voir à quel point ton lien\n"
	.string "avec tes POKéMON s'est renforcé.$"

MatchCall_Text_Glacia::
	.string "GLACIA : Bonjour, {PLAYER}.\p"
	.string "J'espère que tu n'es pas devenu\n"
	.string "trop sûr de ta force ?\p"
	.string "Si tu ressens le besoin de refroidir\n"
	.string "un peu tes ardeurs, viens donc\l"
	.string "à la LIGUE POKéMON…$"

MatchCall_Text_Drake::
	.string "ARAGON : Cette voix… {PLAYER}, c'est toi ?\n"
	.string "Tu as l'air en forme…\p"
	.string "Je crois comprendre qu'il existe\n"
	.string "un endroit appelé la FRONTIÈRE\l"
	.string "DE COMBAT qui teste les talents des\l"
	.string "DRESSEURS.\p"
	.string "Mais si tu veux de vrais combats,\n"
	.string "rien ne vaut la LIGUE POKéMON !\p"
	.string "Tu n'es pas d'accord, {PLAYER} ?$"

MatchCall_Text_Wallace::
	.string "PIERRE : Bonjour, {PLAYER}{KUN}.\n"
	.string "As-tu rencontré STEVEN ?\p"
	.string "Il est…\n"
	.string "En fait, incroyablement doué.\p"
	.string "Mais c'est un drôle de type qui\n"
	.string "combat rarement.\p"
	.string "Il préfère chercher des pierres rares.\p"
	.string "Je suis sûr qu'il creuse dans une grotte ou\n"
	.string "sur une montagne quelque part.\p"
	.string "Mais qu'est-ce qu'une pierre rare exactement ?\n"
	.string "Tout ce qui me vient à l'esprit, c'est une MÉTÉORITE…$"

MatchCall_Text_MayRayquazaCall:
	.string "… … … … … …\n"
	.string "… … … … … Bip !\p"
	.string "FLORA : Salut, {PLAYER}{KUN} !\p"
	.string "J'étais à PACIFIVILLE il y a peu.\n"
	.string "J'ai vu un énorme POKéMON vert\n"
	.string "voler haut dans le ciel.\p"
	.string "Je…\n"
	.string "Je n'ai jamais rien vu de tel.\p"
	.string "Je me demande ce que c'était.\n"
	.string "Est-ce une grande découverte ?\p"
	.string "… … … … … …\n"
	.string "… … … … … Clic !$"

MatchCall_Text_BrendanRayquazaCall:
	.string "… … … … … …\n"
	.string "… … … … … Bip !\p"
	.string "BRICE : Hé, {PLAYER} !\n"
	.string "J'étais à PACIFIVILLE à l'instant.\p"
	.string "J'ai vu un énorme POKéMON vert\n"
	.string "voler dans le ciel.\p"
	.string "Je n'ai jamais vu quelque chose\n"
	.string "d'aussi incroyable.\p"
	.string "J'aurais aimé que tu le voies,\n"
	.string "{PLAYER}.\p"
	.string "… … … … … …\n"
	.string "… … … … … Clic !$"

MatchCall_Text_May1::
	.string "FLORA : Salut, {PLAYER}{KUN} !\p"
	.string "M. MARCO a pris sa retraite de MARIN,\n"
	.string "mais je le vois encore parfois en mer\l"
	.string "avec son PICO.\p"
	.string "Il doit vraiment aimer la mer !$"

MatchCall_Text_May2::
	.string "FLORA : Salut, {PLAYER}{KUN} !\p"
	.string "Tu sais que des petites villes comme\n"
	.string "CLÉMENTI-VILLE et MYOKARA ont des ARÈNES ?\p"
	.string "Mais pour une raison étrange, le grand port\n"
	.string "de POIVRESSEL n'a pas d'ARÈNE.\p"
	.string "Quand ils en construiront une, je devrais\n"
	.string "postuler pour être CHAMPIONNE !$"

MatchCall_Text_May3::
	.string "FLORA : Salut, {PLAYER}{KUN} !\p"
	.string "Tu te souviens d'un homme appelé\n"
	.string "le COUPEUR à MÉROUVILLE ?\l"
	.string "Il avait une maison là-bas, tu te rappelles ?\p"
	.string "Eh bien, j'ai appris que son petit frère\n"
	.string "vit à LAVANDIA.\p"
	.string "Tu devines son nom ?\p"
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "Le MAÎTRE ÉCLAT'ROC !$"

MatchCall_Text_May4::
	.string "FLORA : {PLAYER}{KUN} ?\p"
	.string "TUNNEL MEROUFLE…\n"
	.string "Ils l'ont appelé ainsi car il relie\l"
	.string "MÉROUVILLE et VERDANVILLE.$"

MatchCall_Text_May5::
	.string "FLORA : {PLAYER}{KUN}, comment vas-tu ?\p"
	.string "Je suis sur la ROUTE 111 en ce moment.\p"
	.string "Je vais me reposer chez une vieille dame.\p"
	.string "Elle habite juste au nord du désert.$"

MatchCall_Text_May6::
	.string "FLORA : Salut, {PLAYER}{KUN} !\p"
	.string "Tu connais la TOUR MIRAGE dans le désert ?\p"
	.string "On dit qu'elle apparaît et disparaît\n"
	.string "comme un mirage.\p"
	.string "J'aimerais tant la voir !$"

MatchCall_Text_May7::
	.string "FLORA : {PLAYER}{KUN}, youhou !\n"
	.string "Je suis sur la ROUTE 119 maintenant.\p"
	.string "Il y a une grande rivière ici, et\n"
	.string "il pleut souvent.\p"
	.string "Je suis toute trempée !$"

MatchCall_Text_May8::
	.string "FLORA : {PLAYER}{KUN}, salut.\p"
	.string "LE MONT MÉMOIRE est un mémorial pour les POKéMON\n"
	.string "qui nous ont quittés.\p"
	.string "Peut-être pour ça qu'il y a tant de\n"
	.string "POKéMON SPECTRE là-bas !$"

MatchCall_Text_May9::
	.string "FLORA : Salut, {PLAYER}{KUN} !\p"
	.string "Je pensais aller aux sources chaudes\n"
	.string "de VERFEUILLE.\p"
	.string "Mais en chemin, vers la CHEMINÉE,\n"
	.string "j'ai croisé des gens louches. Ambiance bizarre !$"

MatchCall_Text_May10::
	.string "FLORA : Salut, {PLAYER}{KUN} !\n"
	.string "Tu as vu les infos ?\p"
	.string "On dit que le CAPT. PORTO a découvert\n"
	.string "la CAVERNE FOND-MARIN lors de son\l"
	.string "expédition en sous-marin.$"

MatchCall_Text_May11::
	.string "FLORA : Salut, {PLAYER}{KUN} !\n"
	.string "Tu ne trouves pas ça génial ?\p"
	.string "Même sans bateau, tu peux traverser la mer\n"
	.string "grâce à une capacité de POKéMON.\p"
	.string "Tu savais qu'il y a encore mieux ?\p"
	.string "Il existe une capacité qui permet d'aller\n"
	.string "au fond de la mer !$"

MatchCall_Text_May12::
	.string "FLORA : Salut, {PLAYER}{KUN} !\n"
	.string "J'espère que tout va bien !\p"
	.string "Tu as déjà été bloqué en mer,\n"
	.string "impossible d'aller plus loin ?\p"
	.string "Essaie de plonger et de suivre\n"
	.string "les tranchées sous-marines.\p"
	.string "Quand tu arrives de l'autre côté,\n"
	.string "remonte à la surface. Facile !$"

MatchCall_Text_May13::
	.string "FLORA : Salut, {PLAYER}{KUN} !\p"
	.string "Comment ça va ?\n"
	.string "Tu remplis ton POKéDEX ?\p"
	.string "J'ai entendu une rumeur sur des POKéMON\n"
	.string "super-anciens. Il y en aurait trois !\p"
	.string "J'aimerais tant en voir un…$"

MatchCall_Text_May14::
	.string "FLORA : {PLAYER}{KUN} !\n"
	.string "J'ai entendu les rumeurs !\p"
	.string "Tu as battu le CHAMPION de l'ARÈNE\n"
	.string "de SOOTOPOLIS ?\p"
	.string "Ça veut dire que tu es presque au bout,\n"
	.string "non ?$"

MatchCall_Text_May15::
	.string "FLORA : Il n'y a plus un seul DRESSEUR\n"
	.string "à HOENN qui ne connaisse pas\l"
	.string "ton nom, {PLAYER}{KUN} !\p"
	.string "Quand je dis que je suis ton amie,\n"
	.string "tout le monde est surpris !$"

MatchCall_Text_Brendan1::
	.string "BRICE : Salut, {PLAYER} !\p"
	.string "M. MARCO a pris sa retraite de MARIN,\n"
	.string "mais je le vois encore parfois en mer\l"
	.string "avec son PICO.\p"
	.string "Il doit vraiment aimer la mer !$"

MatchCall_Text_Brendan2::
	.string "BRICE : Salut, {PLAYER} !\p"
	.string "Je ne comprends pas comment des petites villes\n"
	.string "comme CLÉMENTI-VILLE et MYOKARA ont des ARÈNES.\p"
	.string "Alors que le grand port de POIVRESSEL\n"
	.string "n'en a pas.\p"
	.string "Quand ils en construiront une, je devrais\n"
	.string "postuler pour être CHAMPION !$"

MatchCall_Text_Brendan3::
	.string "BRICE : Yo, {PLAYER} !\p"
	.string "Tu te souviens d'un gars appelé\n"
	.string "le COUPEUR à MÉROUVILLE ?\l"
	.string "Il avait une maison là-bas, non ?\p"
	.string "Eh bien, il paraît que son petit frère\n"
	.string "vit à LAVANDIA.\p"
	.string "Tu devines son nom ?\p"
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "Le MAÎTRE ÉCLAT'ROC !$"

MatchCall_Text_Brendan4::
	.string "BRICE : Cette voix… {PLAYER} ?\p"
	.string "Ils ont appelé le TUNNEL MEROUFLE ainsi\n"
	.string "car il relie MÉROUVILLE et VERDANVILLE.\p"
	.string "Tu savais ça ?$"

MatchCall_Text_Brendan5::
	.string "BRICE : {PLAYER}, quoi de neuf ?\p"
	.string "Je suis sur la ROUTE 111 en ce moment.\p"
	.string "Je vais me reposer chez une vieille dame\n"
	.string "au nord du désert.\p"
	.string "Si tu es dans le coin, tu devrais\n"
	.string "lui rendre visite aussi !$"

MatchCall_Text_Brendan6::
	.string "BRICE : Salut, {PLAYER} !\p"
	.string "Tu connais la TOUR MIRAGE dans le désert ?\p"
	.string "On dit qu'elle n'apparaît que parfois,\n"
	.string "comme un mirage.\p"
	.string "J'aimerais bien la voir !$"

MatchCall_Text_Brendan7::
	.string "BRICE : Qui est-ce ? Oh, {PLAYER} ?\n"
	.string "Devine quoi ? Je suis sur la ROUTE 119.\p"
	.string "Il y a une grande rivière ici, et\n"
	.string "il pleut tout le temps.\p"
	.string "Je suis trempé jusqu'aux os !$"

MatchCall_Text_Brendan8::
	.string "BRICE : {PLAYER} !\p"
	.string "LE MONT MÉMOIRE est un mémorial pour les POKéMON\n"
	.string "qui nous ont quittés.\p"
	.string "C'est sûrement pour ça qu'il y a tant de\n"
	.string "POKéMON SPECTRE là-bas !$"

MatchCall_Text_Brendan9::
	.string "BRICE : Salut, {PLAYER}.\p"
	.string "Je rentrais des sources chaudes de VERFEUILLE.\p"
	.string "Mais vers la CHEMINÉE, j'ai croisé\n"
	.string "des types louches.\p"
	.string "Ces types…\n"
	.string "Je crois que c'était la TEAM MAGMA !$"

MatchCall_Text_Brendan10::
	.string "BRICE : Salut, {PLAYER} !\n"
	.string "Tu as vu les infos ?\p"
	.string "On dit que le CAPT. PORTO a découvert\n"
	.string "la CAVERNE FOND-MARIN lors de son\l"
	.string "expédition en sous-marin.$"

MatchCall_Text_Brendan11::
	.string "BRICE : Salut, {PLAYER} !\n"
	.string "Tu ne trouves pas ça génial ?\p"
	.string "Même sans bateau, tu peux traverser la mer\n"
	.string "grâce à une capacité de POKéMON.\p"
	.string "Et il y a même une capacité qui permet\n"
	.string "d'aller au fond de la mer.\p"
	.string "Les POKéMON peuvent tout faire !$"

MatchCall_Text_Brendan12::
	.string "BRICE : Salut, {PLAYER} !\n"
	.string "Comment tu vas ?\p"
	.string "Tu as déjà été bloqué en mer ?\p"
	.string "Essaie de plonger et de suivre\n"
	.string "les tranchées au fond.\p"
	.string "Quand tu arrives de l'autre côté,\n"
	.string "remonte à la surface. Simple !$"

MatchCall_Text_Brendan13::
	.string "BRICE : Salut, {PLAYER} !\p"
	.string "Comment ça va ? Tu remplis bien\n"
	.string "ton POKéDEX ?\p"
	.string "J'ai entendu une rumeur sur des POKéMON\n"
	.string "super-anciens. Il n'y en aurait pas qu'un,\l"
	.string "mais trois !\p"
	.string "J'aimerais tant en attraper un…$"

MatchCall_Text_Brendan14::
	.string "BRICE : {PLAYER} !\n"
	.string "J'ai entendu les rumeurs !\p"
	.string "Tu as battu le CHAMPION de l'ARÈNE\n"
	.string "de SOOTOPOLIS ? Génial !\p"
	.string "Tu es tout près du but !$"

MatchCall_Text_Brendan15::
	.string "BRICE : Il n'y a pas un DRESSEUR à\n"
	.string "HOENN qui ne connaisse pas\l"
	.string "ton nom, {PLAYER} !\p"
	.string "Quand je dis que je suis ton ami,\n"
	.string "tout le monde est jaloux !$"

MatchCall_Text_Wally1::
	.string "TIMMY : Oh, {PLAYER} !\p"
	.string "Je deviens de plus en plus en forme\n"
	.string "et en meilleure santé.\p"
	.string "J'espère devenir un DRESSEUR comme\n"
	.string "toi bientôt, {PLAYER} !$"

MatchCall_Text_Wally2::
	.string "TIMMY : {PLAYER}, bonjour !\p"
	.string "Depuis que le TUNNEL MEROUFLE est ouvert,\n"
	.string "WANDA est très heureuse !$"

MatchCall_Text_Wally3::
	.string "TIMMY : Oh, {PLAYER} !\p"
	.string "J'ai… J'ai quitté la maison de mon oncle à\n"
	.string "VERDANVILLE sans prévenir personne.\p"
	.string "Je me demande s'il est furieux contre moi…\p"
	.string "{PLAYER}, tu comprends ce que\n"
	.string "je ressens, n'est-ce pas ?$"

MatchCall_Text_Wally4::
	.string "TIMMY : {PLAYER} ?\n"
	.string "C'est moi, TIMMY !\p"
	.string "Le monde des DRESSEURS est incroyable !\p"
	.string "Quand j'ai mes POKéMON avec moi,\n"
	.string "tout le monde me salue !\p"
	.string "C'est comme si tout le monde était\n"
	.string "connecté grâce aux POKéMON !$"

MatchCall_Text_Wally5::
	.string "TIMMY : {PLAYER} ? C'est génial !\n"
	.string "Le TARSAL qu'on a attrapé ensemble ?\l"
	.string "Il a évolué, {PLAYER} !\p"
	.string "Peut-être que j'ai du talent…\p"
	.string "Oh, mais je ne devrais pas prendre\n"
	.string "la grosse tête !\p"
	.string "Après tout, c'est le POKéMON qui\n"
	.string "doit être félicité !$"

MatchCall_Text_Wally6::
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "TIMMY semble être hors de portée\n"
	.string "du service du POKéNAV…$"

MatchCall_Text_Wally7::
	.string "TIMMY : Oh, {PLAYER} !\p"
	.string "Avant de te rencontrer, je ne sortais\n"
	.string "presque jamais de chez moi…\p"
	.string "Mais maintenant, je vis une aventure\n"
	.string "avec mes propres POKéMON…\p"
	.string "{PLAYER}…\n"
	.string "Merci…$"

MatchCall_Text_Scott1::
	.string "SCOTT : Salut, {PLAYER}{KUN} !\p"
	.string "Tu sais que les POKéMON se trouvent\n"
	.string "partout ?\p"
	.string "Dans les montagnes, la mer, les hautes herbes…\n"
	.string "Partout !\p"
	.string "Comme les POKéMON, tu peux trouver\n"
	.string "des DRESSEURS partout aussi.\p"
	.string "Du coup, je dois me dépêcher partout.\n"
	.string "Occupé, occupé !$"

MatchCall_Text_Scott2::
	.string "SCOTT : Je suis sur la ROUTE 119 en ce moment.\n"
	.string "Il y a plein de DRESSEURS !\p"
	.string "Il y a aussi de l'herbe haute partout,\n"
	.string "on dirait.\p"
	.string "Marcher en short ici, ça me chatouille !$"

MatchCall_Text_Scott3::
	.string "SCOTT : Salut, salut, {PLAYER}{KUN} !\p"
	.string "As-tu déjà eu l'occasion de gravir\n"
	.string "le MONT MÉMOIRE ?\p"
	.string "C'est un mémorial pour les POKéMON\n"
	.string "disparus.\p"
	.string "Tout DRESSEUR devrait le gravir au moins une fois !$"

MatchCall_Text_Scott4::
	.string "SCOTT : Salut, {PLAYER}{KUN} !\p"
	.string "J'entends parler de drôles de gangs\n"
	.string "qui posent problème.\p"
	.string "TEAM MAGMA et TEAM AQUA,\n"
	.string "je crois.\p"
	.string "Je pense qu'il doit y avoir des DRESSEURS\n"
	.string "talentueux parmi eux.\p"
	.string "…Mais si ce sont des voyous…$"

MatchCall_Text_Scott5::
	.string "SCOTT : Oh, salut, {PLAYER}{KUN}.\p"
	.string "Y aurait-il des DRESSEURS coriaces\n"
	.string "au fond de la mer ?\p"
	.string "Je ne peux pas aller vérifier moi-même.\n"
	.string "Je ne sais pas nager, déjà.\l"
	.string "Et je n'élève pas de POKéMON…$"

MatchCall_Text_Scott6::
	.string "SCOTT : Salut, salut, {PLAYER}{KUN} !\p"
	.string "Tu sais que tu peux défier la LIGUE POKéMON\n"
	.string "quand tu as tous les BADGES d'ARÈNE ?\p"
	.string "Avec ton talent, devenir CHAMPION\n"
	.string "n'est pas un rêve impossible.\p"
	.string "Mais savais-tu qu'il y a encore mieux ?\n"
	.string "Mais c'est tout ce que je peux dire\n"
	.string "pour l'instant.\p"
	.string "C'est quelque chose que tu peux attendre\n"
	.string "avec impatience.\p"
	.string "Quand tu auras franchi la LIGUE POKéMON\n"
	.string "et que tu entreras au PANTHÉON !$"

MatchCall_Text_Scott7::
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "SCOTT semble être hors de portée\n"
	.string "du service du POKéNAV…$"

MatchCall_Text_Norman1::
	.string "PAPA : À MÉROUVILLE, il y a un homme\n"
	.string "qu'on appelle le COUPEUR.\l"
	.string "Si tu es dans le coin, tu devrais\n"
	.string "lui rendre visite.$"

MatchCall_Text_Norman2::
	.string "PAPA : Hm… Petit à petit, mais sûrement,\n"
	.string "tu deviens plus fort, {PLAYER}.\l"
	.string "Plus tu deviens fort, plus tu t'éloignes\n"
	.string "de ta mère et de moi…\p"
	.string "C'est un sentiment difficile à expliquer.$"

MatchCall_Text_Norman3::
	.string "PAPA : Je vois…\n"
	.string "Tu as déjà quatre BADGES d'ARÈNE…\p"
	.string "On ne peut plus reculer maintenant.\n"
	.string "Nous nous battrons comme promis.\p"
	.string "Viens quand tu veux.\n"
	.string "Nous t'attendrons tous !$"

MatchCall_Text_Norman4::
	.string "PAPA : {PLAYER} ! Tu devrais aller voir\n"
	.string "ta mère de temps en temps.\p"
	.string "Je vais rester ici et redoubler\n"
	.string "d'entraînement.\p"
	.string "La voie du combat est profonde\n"
	.string "et impitoyable !$"

MatchCall_Text_Norman5::
	.string "PAPA : Oh, salut, {PLAYER} !\p"
	.string "Quoi ? L'EMBLÈME MAGMA ?\n"
	.string "Je ne sais pas ce que c'est.\p"
	.string "Mais avec un nom pareil, ça doit avoir\n"
	.string "un lien avec un volcan !$"

MatchCall_Text_Norman6::
	.string "PAPA : Hiyah ! Haah ! Dwah !\p"
	.string "…Oh ? {PLAYER} !\p"
	.string "Tu m'as surpris en plein entraînement\n"
	.string "POKéMON !$"

MatchCall_Text_Norman7::
	.string "PAPA : {PLAYER} !\p"
	.string "Qui aurait cru que tu deviendrais\n"
	.string "CHAMPION de la LIGUE POKéMON…\p"
	.string "D'accord !\n"
	.string "Je ne vais pas me laisser distancer !$"

MatchCall_Text_Norman8::
	.string "PAPA : Hm ? {PLAYER} ?\n"
	.string "Ça tombe bien !\p"
	.string "Cette fois, c'est moi qui vais te défier\n"
	.string "en combat.\p"
	.string "Je t'attends à l'ARÈNE de CLÉMENTI-VILLE.\n"
	.string "Relève mon défi quand tu veux !$"

MatchCall_Text_Norman9::
	.string "PAPA : …Tu m'épates, {PLAYER}.\n"
	.string "Jusqu'où iras-tu ?$"

MatchCall_Text_Steven1::
	.string "PIERRE : Salut, {PLAYER}{KUN} !\p"
	.string "Tu es déjà allé à LAVANDIA ?\p"
	.string "Tu devrais visiter le MAGASIN DE VÉLOS\n"
	.string "et obtenir un VÉLO MACH.\p"
	.string "Ensuite, essaie d'explorer à fond\n"
	.string "la GROTTE GRANITE.\p"
	.string "Tu pourrais y faire une découverte !$"

MatchCall_Text_Steven2::
	.string "PIERRE : Salut, {PLAYER}{KUN} !\p"
	.string "J'ai rencontré beaucoup de DRESSEURS\n"
	.string "différents jusqu'ici.\p"
	.string "Mais tu es unique.\n"
	.string "Tu n'es comme personne d'autre.$"

MatchCall_Text_Steven3::
	.string "PIERRE : Salut, {PLAYER}{KUN} !\p"
	.string "Quand tu pars à l'aventure avec tes POKéMON,\n"
	.string "qu'en penses-tu ?\p"
	.string "Les considères-tu comme de puissants\n"
	.string "partenaires ?\p"
	.string "Ou comme des compagnons amusants ?\p"
	.string "Selon ta façon de voir, ton aventure\n"
	.string "prend un sens différent.$"

MatchCall_Text_Steven4::
	.string "PIERRE : Allô ?\n"
	.string "{PLAYER}{KUN} ?\p"
	.string "J'ai quelques soucis au CENTRE SPATIAL.\p"
	.string "Désolé, je ne peux pas parler maintenant.\n"
	.string "À bientôt !$"

MatchCall_Text_Steven5::
	.string "PIERRE : Oh !\n"
	.string "{PLAYER}{KUN} !\p"
	.string "Pas besoin de parler.\n"
	.string "Il n'est plus temps de discuter.\p"
	.string "Tu dois croire en toi et faire\n"
	.string "ce qui est juste.$"

MatchCall_Text_Steven6::
	.string "… … … … … …\p"
	.string "PIERRE ne semble pas recevoir\n"
	.string "l'appel…$"

MatchCall_Text_Steven7::
	.string "PIERRE : {PLAYER}{KUN}… Félicitations\n"
	.string "pour ton entrée au PANTHÉON.\p"
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "J'espère qu'on se reverra\n"
	.string "quelque part !$"

MatchCall_Text_BirchRegisterCall:
	.string "PROF. SEKO : Oh, {PLAYER}{KUN} !\n"
	.string "J'ai déjà entendu parler de toi !\p"
	.string "Il paraît que ton POKéNAV a été\n"
	.string "mis à jour avec MATCH CALL.\p"
	.string "Eh bien, je devrais m'enregistrer aussi !\p"
	.string "Comme ça, je pourrai examiner ton POKéDEX\n"
	.string "même quand tu es sur le terrain.\l"
	.string "… … … … … …$"

MatchCall_Text_RegisteredBirch:
	.string "PROF. SEKO enregistré\n"
	.string "dans le POKéNAV.$"

MatchCall_Text_UnusedProfBirch:
	.string "PROF. SEKO : Quand on a à la fois\n"
	.string "le POKéDEX et le POKéNAV, étudier\l"
	.string "les POKéMON devient plus amusant, non ?$"

MatchCall_Text_MrStone1::
	.string "MR. ROCHE : Oh ? {PLAYER}{KUN} !\p"
	.string "Puisque tu m'appelles, le POKéNAV\n"
	.string "doit bien fonctionner !\p"
	.string "D'autres personnes seront enregistrées,\n"
	.string "essaie de les appeler aussi !\p"
	.string "Bien ! Bien !\n"
	.string "Tu as l'air heureux !\p"
	.string "Hm…\n"
	.string "Comment je le sais ?\p"
	.string "Parce que je te regarde depuis la fenêtre\n"
	.string "de mon bureau !\p"
	.string "Wahahaha !\n"
	.string "À bientôt !$"

MatchCall_Text_MrStone2::
	.string "MR. ROCHE : Oh ? {PLAYER}{KUN} !\p"
	.string "Qu'y a-t-il ? Tu as oublié ma petite\n"
	.string "commission ?\p"
	.string "J'ai besoin que tu remettes ma lettre\n"
	.string "à STEVEN à MYOKARA.\p"
	.string "Ensuite, livre notre colis au CAPT. PORTO\n"
	.string "à POIVRESSEL.\p"
	.string "Tu t'en souviens, n'est-ce pas ?\p"
	.string "Bon, comme je suis un PRÉSIDENT occupé,\n"
	.string "je dois y aller ! Au revoir !$"

MatchCall_Text_MrStone3::
	.string "MR. ROCHE : Oh ! {PLAYER}{KUN} !\p"
	.string "Ah, tu as rencontré STEVEN !\n"
	.string "Je dois te récompenser alors !\p"
	.string "Quand tu reviendras à MÉROUVILLE,\n"
	.string "viens me voir à mon bureau.\p"
	.string "Je t'attendrai !$"

MatchCall_Text_MrStone4::
	.string "MR. ROCHE : Oh ! {PLAYER}{KUN} !\p"
	.string "Savais-tu que DEVON creusait\n"
	.string "le TUNNEL MEROUFLE ?\p"
	.string "Mais nous avons arrêté les travaux pour\n"
	.string "protéger les POKéMON de la région.\p"
	.string "C'est évident, non ?\p"
	.string "Il est plus important de laisser les POKéMON\n"
	.string "vivre en paix que de penser à notre\l"
	.string "propre confort.$"

MatchCall_Text_MrStone5::
	.string "MR. ROCHE : Bonjour, bonjour, {PLAYER}{KUN} !\p"
	.string "J'ai entendu à CLÉMENTI-VILLE que tu es\n"
	.string "l'enfant de NORMAN !\p"
	.string "Pas étonnant que tu sois si doué !$"

MatchCall_Text_MrStone6::
	.string "MR. ROCHE : Quoi ?\p"
	.string "Tu as affronté ton propre père et\n"
	.string "tu l'as battu ?\p"
	.string "C'est incroyable !\p"
	.string "Je ne savais pas que j'avais un ami\n"
	.string "aussi spécial ! Wahaha !$"

MatchCall_Text_MrStone7::
	.string "Bonjour !\n"
	.string "Ici la société DEVON…\l"
	.string "Oh, bonjour, {PLAYER} !\p"
	.string "Notre PRÉSIDENT était là il y a peu,\n"
	.string "mais il est sorti.\p"
	.string "Notre PRÉSIDENT est occupé, mais tu\n"
	.string "as l'air tout aussi occupé, {PLAYER}.$"

MatchCall_Text_MrStone8::
	.string "…Hein ? …Quoi ?\p"
	.string "GROU… Oui ? …DON ?\p"
	.string "La communication coupe…\n"
	.string "…je n'entends plus…\p"
	.string "BZZZZ…$"

MatchCall_Text_MrStone9::
	.string "…Hein ? …Quoi ?\p"
	.string "Fonds… Oui ? …Caver… ?\p"
	.string "La communication coupe…\n"
	.string "…je n'entends plus…\p"
	.string "BZZZZ…$"

MatchCall_Text_MrStone10::
	.string "MR. ROCHE : {PLAYER}{KUN} ! C'est moi !\p"
	.string "Tu as été impliqué dans plein de choses,\n"
	.string "mais moi, avec mon emploi du temps chargé,\l"
	.string "je n'ai aucune idée de quoi exactement !\p"
	.string "Mais je t'encourage à suivre la voie\n"
	.string "que tu crois juste.\p"
	.string "Je serai toujours de ton côté !\n"
	.string "Prends soin de toi !$"

MatchCall_Text_MrStone11::
	.string "MR. ROCHE : … … … … … …\n"
	.string "C'est peut-être {PLAYER}{KUN} ?\p"
	.string "Ta voix est si pleine de confiance,\n"
	.string "que je ne t'ai pas reconnu tout de suite !\p"
	.string "Hm ! Tu dois venir nous voir chez DEVON\n"
	.string "un de ces jours !$"
