@ Contient uniquement les textes pour l'homme de Lavandia nommé Giddy. Le reste est dans scripts/mauville_man.inc
GiddyText_SoPretty::
	.string " si joli !$"

GiddyText_SoDarling::
	.string " si adorable !$"

GiddyText_SoRelaxed::
	.string " si relaxant !$"

GiddyText_SoSunny::
	.string " si ensoleillé !$"

GiddyText_SoDesirable::
	.string " si désirable !$"

GiddyText_SoExciting::
	.string " si excitant !$"

GiddyText_SoAmusing::
	.string " si amusant !$"

GiddyText_SoMagical::
	.string " si magique !$"

GiddyText_Is::
	.string " est$"

GiddyText_DontYouAgree::
	.string "\n"
	.string "Tu n'es pas d'accord ?$"

GiddyText_ISoWantToGoOnAVacation::
	.string "J'ai tellement envie de partir en vacances.\n"
	.string "Tu connaîtrais un endroit sympa ?$"

GiddyText_IBoughtCrayonsWith120Colors::
	.string "J'ai acheté des crayons avec 120 couleurs !\n"
	.string "Tu trouves pas ça génial ?$"

GiddyText_WouldntItBeNiceIfWeCouldFloat::
	.string "Ce serait chouette si on pouvait flotter\n"
	.string "loin sur un nuage de bulles, non ?$"

GiddyText_WhenYouWriteOnASandyBeach::
	.string "Quand tu écris sur une plage de sable,\n"
	.string "ça s'efface. Ça me rend triste.$"

GiddyText_WhatsTheBottomOfTheSeaLike::
	.string "À quoi ressemble le fond de la mer ?\n"
	.string "Juste une fois, j'aimerais tant y aller !$"

GiddyText_WhenYouSeeTheSettingSunDoesIt::
	.string "Quand tu vois le soleil se coucher, est-ce que\n"
	.string "ça te donne envie de rentrer chez toi ?$"

GiddyText_LyingBackInTheGreenGrass::
	.string "Allongé dans l'herbe verte…\n"
	.string "Oh, c'est tellement agréable !$"

GiddyText_SecretBasesAreSoWonderful::
	.string "LES BASES SECRÈTES sont tellement géniales !\n"
	.string "Tu ne sens pas l'excitation ?$"
