MoveTutor_Text_ThisMoveCanOnlyBeLearnedOnce:
	.string "Es-tu prêt à apprendre cette capacité ?$"
	.string "Cela te coûtera 5 000¥.$"

MoveTutor_Text_ThisMoveCanOnlyBeLearnedOnceFinite:
	.string "Cette capacité ne peut être apprise\n"
	.string "qu'une seule fois. Ça te va ?$"

MoveTutor_Text_SwaggerTeach:
	.string "Héhé ! Mon POKéMON est trop classe !\n"
	.string "Il est plus cool que n'importe quel POKéMON !\p"
	.string "Je me la racontais avec une démarche\n"
	.string "pleine d'assurance, mais le PRÉSIDENT\l"
	.string "m'a remis à ma place.\p"
	.string "Ça m'a calmé direct.\p"
	.string "Si tu veux, je peux apprendre la capacité\n"
	.string "VANTARDISE à l'un de tes POKéMON.$"

MoveTutor_Text_SwaggerDeclined:
	.string "Quoi, non ? Tu n'es pas dans\n"
	.string "l'ambiance ?$"

MoveTutor_Text_SwaggerWhichMon:
	.string "Très bien, quel POKéMON veut\n"
	.string "apprendre VANTARDISE ?$"

MoveTutor_Text_SwaggerTaught:
	.string "Dorénavant, je féliciterai mon POKéMON\n"
	.string "sans me vanter.$"

MoveTutor_Text_RolloutTeach:
	.string "Savais-tu qu'on peut aller très loin\n"
	.string "dans cette direction sans changer de cap ?\l"
	.string "\p"
	.string "Je pourrais même rouler comme ça.\p"
	.string "Tu crois que ton POKéMON voudrait\n"
	.string "rouler aussi ?\p"
	.string "Je peux lui apprendre la capacité ROULEBOULE\n"
	.string "si tu veux.$"

MoveTutor_Text_RolloutDeclined:
	.string "Pas besoin d'être timide.\n"
	.string "Allez, on roule !$"

MoveTutor_Text_RolloutWhichMon:
	.string "Ehehe, bien sûr ! Ce serait génial si\n"
	.string "le POKéMON me ressemblait.$"

MoveTutor_Text_RolloutTaught:
	.string "Rouler dans l'herbe me rend heureux.\n"
	.string "Allez, on roule !$"

MoveTutor_Text_FuryCutterTeach:
	.string "Il existe une capacité qui devient plus forte\n"
	.string "quand on l'utilise plusieurs fois d'affilée.\p"
	.string "C'est une attaque de type INSECTE, et elle est\n"
	.string "vraiment géniale.\p"
	.string "Elle s'appelle COUP D'BOUTE.\n"
	.string "Tu veux que je l'apprenne à un POKéMON ?$"

MoveTutor_Text_FuryCutterDeclined:
	.string "On n'est pas sur la même longueur d'onde.$"

MoveTutor_Text_FuryCutterWhichMon:
	.string "Youpi !\n"
	.string "Montre-moi à quel POKéMON je dois l'apprendre.$"

MoveTutor_Text_FuryCutterTaught:
	.string "J'adore voir si la capacité touche\n"
	.string "plusieurs fois de suite !$"

MoveTutor_MimicTeach:
	.string "Ah, jeune dresseur !\p"
	.string "Je suis jeune aussi, mais j'imite\n"
	.string "le style et la façon de parler des anciens\l"
	.string "de cette ville.\p"
	.string "Qu'en dis-tu, jeune dresseur ?\n"
	.string "Accepterais-tu que je propose d'apprendre\l"
	.string "la capacité MIMIQUIQUE ?$"

MoveTutor_MimicDeclined:
	.string "Oh, zut ! Je voulais apprendre MIMIQUIQUE\n"
	.string "à ton POKéMON !$"

MoveTutor_Text_MimicWhichMon:
	.string "Fwofwo ! Ainsi soit-il !\n"
	.string "Montre-moi le POKéMON\l"
	.string "que tu veux que j'enseigne.$"

MoveTutor_Text_MimicTaught:
	.string "MIMIQUIQUE est une capacité très profonde.\p"
	.string "Pourrais-tu l'exécuter à la perfection\n"
	.string "aussi bien que moi…?$"

MoveTutor_Text_MetronomeTeach:
	.string "Je veux plein de choses !\n"
	.string "Mais j'ai déjà dépensé mon argent de poche…\p"
	.string "Ce serait bien s'il existait un sort\n"
	.string "qui faisait apparaître de l'argent quand\l"
	.string "on remue un doigt ?\p"
	.string "Si tu veux, je peux apprendre à ton POKéMON\n"
	.string "la capacité MÉTAMORPHOSE.\p"
	.string "L'argent n'apparaîtra pas, mais ton POKéMON\n"
	.string "remuera un doigt. D'accord ?$"

MoveTutor_Text_MetronomeDeclined:
	.string "D'accord. Je serai là si tu changes\n"
	.string "d'avis.$"

MoveTutor_Text_MetronomeWhichMon:
	.string "D'accord ! Je vais l'enseigner !\n"
	.string "À quel POKéMON dois-je l'apprendre ?$"

MoveTutor_Text_MetronomeTaught:
	.string "Quand un POKéMON remue son doigt\n"
	.string "comme un MÉTAMORPHOSE, plein de choses\l"
	.string "sympas arrivent.\p"
	.string "Ce serait bien si on pouvait\n"
	.string "l'utiliser aussi !$"

MoveTutor_Text_SleepTalkTeach:
	.string "Humph ! Ma femme compte sur PUISSANCE CACHÉE\n"
	.string "pour rester éveillée.\p"
	.string "Elle devrait juste faire une sieste comme moi,\n"
	.string "et utiliser BAVARDAGE.\p"
	.string "Je peux apprendre à ton POKéMON\n"
	.string "à utiliser BAVARDAGE à la place. Intéressé ?$"

MoveTutor_Text_SleepTalkDeclined:
	.string "Bon, bon. Tu veux rester éveillé\n"
	.string "avec PUISSANCE CACHÉE, toi aussi…$"

MoveTutor_Text_SleepTalkWhichMon:
	.string "Ah, un enfant reconnaissant !\n"
	.string "À quel POKéMON dois-je l'apprendre ?$"

MoveTutor_Text_SleepTalkTaught:
	.string "Je n'ai jamais réussi le tour de pièce\n"
	.string "de ma femme.\p"
	.string "Je serais heureux d'y arriver\n"
	.string "même en BAVARDANT…$"

MoveTutor_Text_SubstituteTeach:
	.string "Quand je voyage autour du monde...\p"
	.string "Je me dis que ce serait bien\n"
	.string "s'il y avait plus d'un moi\l"
	.string "pour profiter de toutes les vies possibles.\p"
	.string "Bien sûr, ce n'est pas possible.\n"
	.string "Hihi…\p"
	.string "Je sais ! Ça t'intéresserait qu'un POKéMON\n"
	.string "apprenne la capacité CLONAGE ?$"

MoveTutor_Text_SubstituteDeclined:
	.string "Oh, non ?\p"
	.string "Un POKéMON peut se copier lui-même\n"
	.string "grâce à cette capacité, tu sais.$"

MoveTutor_Text_SubstituteWhichMon:
	.string "Hihi…\n"
	.string "Quel POKéMON veux-tu que j'enseigne\l"
	.string "CLONAGE ?$"

MoveTutor_Text_SubstituteTaught:
	.string "Nous, humains, devrions profiter de\n"
	.string "notre vie au maximum !\p"
	.string "J'espère que tu y arriveras aussi !$"

MoveTutor_Text_DynamicPunchTeach:
	.string "Je n'en peux plus !\p"
	.string "C'est complètement désespéré !\p"
	.string "Je suis un DRESSEUR de type COMBAT,\n"
	.string "mais je n'arrive pas à gagner à l'ARENE de SAFRANIA\l"
	.string "peu importe mes efforts !\p"
	.string "Argh ! Coup de poing ! Coup de poing ! Coup de poing !\n"
	.string "Coup de poing ! Coup de poing ! Coup de poing !\p"
	.string "Quoi, ne me regarde pas comme ça !\n"
	.string "Je frappe juste le sol !\p"
	.string "Ou tu veux que j'apprenne à ton POKéMON\n"
	.string "DYNAMO-POING ?$"

MoveTutor_Text_DynamicPunchDeclined:
	.string "Zut ! Tu te moques de moi aussi ?\n"
	.string "Coup de poing ! Coup de poing ! Coup de poing !$"

MoveTutor_Text_DynamicPunchWhichMon:
	.string "Quoi ? Tu veux ? Tu es quelqu'un de bien !\n"
	.string "À quel POKéMON dois-je l'apprendre ?$"

MoveTutor_Text_DynamicPunchTaught:
	.string "Je veux que tu gagnes à l'ARÈNE de SAFRANIA\n"
	.string "avec ce DYNAMO-POING !$"

MoveTutor_Text_DoubleEdgeTeach:
	.string "Soupir…\p"
	.string "Le CHAMPION de l'ARÈNE de JADIELLE est\n"
	.string "vraiment admirable et attachant.\p"
	.string "Mais ça veut dire que j'ai beaucoup\n"
	.string "de rivaux pour attirer son attention.\p"
	.string "Il a du charme avec son DAMOCLES.\n"
	.string "Je n'ai même pas réussi à attirer son regard.\p"
	.string "S'il te plaît, laisse-moi apprendre à ton POKéMON\n"
	.string "la capacité DAMOCLES !$"

MoveTutor_Text_DoubleEdgeDeclined:
	.string "Oh…\n"
	.string "Même toi tu me rejettes…$"

MoveTutor_Text_DoubleEdgeWhichMon:
	.string "D'accord, à quel POKéMON dois-je apprendre\n"
	.string "DAMOCLES ?$"

MoveTutor_Text_DoubleEdgeTaught:
	.string "Je ne vivrai plus pour l'amour !\n"
	.string "Je vais devenir forte !$"

MoveTutor_Text_ExplosionTeach:
	.string "Je n'ai pas l'intention de rester coincé\n"
	.string "dans ce trou perdu toute ma vie.\p"
	.string "Tu verras, j'irai en ville et je deviendrai\n"
	.string "une vraie star.\p"
	.string "Sérieusement, je vais provoquer\n"
	.string "une EXPLOSION de popularité !\p"
	.string "Si tu as entendu ça, je peux apprendre\n"
	.string "EXPLOSION à ton POKéMON avec plaisir !$"

MoveTutor_Text_ExplosionDeclined:
	.string "Grrr ! Tu me refuses parce que\n"
	.string "je vis à la campagne ?$"

MoveTutor_Text_ExplosionWhichMon:
	.string "Très bien ! Ce sera une EXPLOSION !\n"
	.string "Quel POKéMON veut exploser ?$"

MoveTutor_Text_ExplosionTaught:
	.string "Depuis longtemps, j'apprends à des POKéMON\n"
	.string "à utiliser EXPLOSION, mais je n'ai jamais\l"
	.string "provoqué ma propre EXPLOSION…\p"
	.string "Peut-être qu'au fond,\n"
	.string "je préfère rester ici…$"
