gText_PkmnTransferredSomeonesPC::
	.string "{STR_VAR_2} a été transféré\n"
	.string "sur le PC de QUELQU'UN.\p"
	.string "Il a été placé dans\n"
	.string "la BOÎTE « {STR_VAR_1} ».$"

gText_PkmnTransferredBillsPC::
	.string "{STR_VAR_2} a été transféré\n"
	.string "sur le PC de LEO.\p"
	.string "Il a été placé dans\n"
	.string "la BOÎTE « {STR_VAR_1} ».$"

gText_PkmnTransferredSomeonesPCBoxFull::
	.string "La BOÎTE « {STR_VAR_3} » sur\n"
	.string "le PC de QUELQU'UN était pleine.\p"
	.string "{STR_VAR_2} a été transféré dans\n"
	.string "la BOÎTE « {STR_VAR_1} ».$"

gText_PkmnTransferredBillsPCBoxFull::
	.string "La BOÎTE « {STR_VAR_3} » sur\n"
	.string "le PC de LEO était pleine.\p"
	.string "{STR_VAR_2} a été transféré dans\n"
	.string "la BOÎTE « {STR_VAR_1} ».$"

gText_NoMoreRoomForPokemon::
	.string "Il n'y a plus de place pour les POKéMON !\p"
	.string "Les BOÎTES PC sont pleines et\n"
	.string "ne peuvent plus en accepter !$"

gText_NicknameThisPokemon::
	.string "Veux-tu donner un surnom à\n"
	.string "ce {STR_VAR_1} ?$"
