gText_WouldYouLikeToRestYourPkmn::
	.string "Bonjour et bienvenue au\n"
	.string "CENTRE POKéMON.\p"
	.string "Nous soignons tes POKéMON fatigués\n"
	.string "pour qu'ils retrouvent la pleine forme.\p"
	.string "Veux-tu faire soigner tes POKéMON ?$"

gText_IllTakeYourPkmn::
	.string "Très bien, je vais prendre tes POKéMON\n"
	.string "quelques secondes.$"

gText_RestoredPkmnToFullHealth::
	.string "Merci d'avoir patienté.\p"
	.string "Tes POKéMON sont en pleine forme !$"

gText_WeHopeToSeeYouAgain::
	.string "À bientôt, nous espérons te revoir !$"

gText_WelcomeCutShort::
	.string "Bonjour et bienvenue au\n"
	.string "CENTRE POKéMON.\p"
	.string "Nous soignons tes POKéMON fatigués\n"
	.string "pour qu'ils retrouvent la pleine forme.\p"
	.string "Veux-tu…$"

gText_NoticesGoldCard::
	.string "C-cette carte…\n"
	.string "Serait-ce… la CARTE OR ?!\p"
	.string "Oh, cette couleur dorée est splendide !\n"
	.string "Les quatre étoiles semblent scintiller !\p"
	.string "J'ai déjà vu plusieurs DRESSEURS avec\n"
	.string "une CARTE ARGENT, mais, {PLAYER},\l"
	.string "tu es le premier DRESSEUR que je vois\l"
	.string "avec une CARTE OR !\p"
	.string "Très bien, {PLAYER}, permets-moi\n"
	.string "l'honneur de soigner tes POKéMON !$"

gText_YouWantTheUsual::
	.string "Je suis ravie de te voir, {PLAYER} !\n"
	.string "Tu veux comme d'habitude, n'est-ce pas ?$"

gText_IllTakeYourPkmn2::
	.string "Très bien, je vais prendre tes POKéMON\n"
	.string "quelques secondes.$"

gText_ThankYouForWaiting::
	.string "Merci d'avoir patienté.$"

gText_WeHopeToSeeYouAgain2::
	.string "À bientôt, nous espérons te revoir !$"

gText_PkmnCenterChallenge_NoVisitsLeft:: @ tx_difficulty_challenge
    .string "Désolé, mais tu joues avec\n"
    .string "le défi POKéCENTER !\p"
    .string "Bonne chance !{PAUSE_UNTIL_PRESS}$"
