gBirchDexRatingText_GoFindMrPokemon::
	.string "PROF. ORME : Ah, {PLAYER}{KUN} !\p"
	.string "As-tu déjà trouvé la maison de\n"
	.string "M. POKéMON ? Elle est sur la ROUTE 30,\p"
	.string "tu ne peux pas la manquer !$"

gBirchDexRatingText_Robbery::
	.string "PROF. ORME : {PLAYER}{KUN} !\p"
	.string "Viens vite ! Il s'est passé\n"
	.string "quelque chose de terrible !$"

gBirchDexRatingText_AreYouCurious::
	.string "PROF. ORME : Ah, {PLAYER}{KUN} !\p"
	.string "Tu es curieux(se) de savoir comment\n"
	.string "avance ton POKéDEX ?$"

gBirchDexRatingText_Cancel::
	.string "Hm ? Oh, tu n'as pas attrapé assez\n"
	.string "de POKéMON pour que ça vaille le coup.$"

gBirchDexRatingText_SoYouveSeenAndCaught::
	.string "Hmhm…\p"
	.string "Alors, tu as vu {STR_VAR_1} POKéMON,\n"
	.string "et tu en as attrapé {STR_VAR_2}…$"

gBirchDexRatingText_LessThan10::
	.string "Va plus souvent dans les hautes herbes\n"
	.string "et cherche les POKéMON attentivement.$"

gBirchDexRatingText_LessThan20::
	.string "Je vois que tu commences à comprendre.\n"
	.string "Mais ça va devenir plus difficile !$"

gBirchDexRatingText_LessThan30::
	.string "Certains POKéMON n'apparaissent que\n"
	.string "dans certaines zones.\l"
	.string "Il faut être persévérant.$"

gBirchDexRatingText_LessThan40::
	.string "Bon, il en faudrait un peu plus,\n"
	.string "mais ça commence à ressembler\l"
	.string "à un vrai POKéDEX.$"

gBirchDexRatingText_LessThan50::
	.string "Ça avance plutôt bien.\n"
	.string "Continue tes efforts !$"

gBirchDexRatingText_LessThan60::
	.string "Utilises-tu des CANNES ?\n"
	.string "Il y a beaucoup de POKéMON dans la mer.$"

gBirchDexRatingText_LessThan70::
	.string "Au lieu de seulement attraper des POKéMON,\n"
	.string "pourquoi ne pas les faire évoluer aussi ?$"

gBirchDexRatingText_LessThan80::
	.string "Ton POKéDEX va devenir fantastique.\l"
	.string "C'est le sentiment que j'ai !$"

gBirchDexRatingText_LessThan90::
	.string "Tu en as déjà rassemblé autant…\n"
	.string "Ton talent est remarquable !$"

gBirchDexRatingText_LessThan100::
	.string "As-tu visité le PARC SAFARI ?\p"
	.string "J'ai entendu dire que certains POKéMON\n"
	.string "ne peuvent être attrapés que là-bas.$"

gBirchDexRatingText_LessThan110::
	.string "Tu as enfin atteint la barre des 100.\p"
	.string "C'est un POKéDEX impressionnant !$"

gBirchDexRatingText_LessThan120::
	.string "Il y a peut-être des POKéMON que tu peux\n"
	.string "trouver en utilisant ÉCLATE-ROC.$"

gBirchDexRatingText_LessThan130::
	.string "J'ai entendu parler de POKéMON qui évoluent\n"
	.string "lorsqu'ils aiment vraiment leur\l"
	.string "DRESSEUR.$"

gBirchDexRatingText_LessThan140::
	.string "J'ai entendu parler de POKéMON qui évoluent\n"
	.string "lorsqu'ils aiment vraiment leur\l"
	.string "DRESSEUR.$"

gBirchDexRatingText_LessThan150::
	.string "Je ne savais pas qu'il y avait autant\n"
	.string "d'espèces de POKéMON dans la région\l"
	.string "de JOHTO.$"

gBirchDexRatingText_LessThan160::
	.string "Parfois, certains POKéMON apparaissent\n"
	.string "en grand nombre, comme lors d'épidémies.\p"
	.string "Ne rate pas ces occasions !$"

gBirchDexRatingText_LessThan170::
	.string "On peut se faire une très bonne idée des\n"
	.string "POKéMON de JOHTO en regardant\l"
	.string "ton POKéDEX.$"

gBirchDexRatingText_LessThan180::
	.string "Je dirais que tu es déjà digne d'être\n"
	.string "un PROFESSEUR POKéMON, et un bon\l"
	.string "en plus !$"

gBirchDexRatingText_LessThan190::
	.string "Avec un POKéDEX aussi complet,\n"
	.string "tu es un vrai professionnel !$"

gBirchDexRatingText_LessThan200::
	.string "Tu es très proche de compléter\n"
	.string "ce POKéDEX.\l"
	.string "Je le sens au fond de moi !$"

gBirchDexRatingText_DexCompleted::
	.string "Félicitations !\n"
	.string "Ton POKéDEX est complet !$"

gBirchDexRatingText_OnANationwideBasis::
	.string "Hmhm…\n"
	.string "À l'échelle nationale…\p"
	.string "Tu as vu {STR_VAR_1} POKéMON,\n"
	.string "et tu en as attrapé {STR_VAR_2}…$"

gBirchDexRatingText_CaughtAllNational::
	.string "Hmhm…\n"
	.string "À l'échelle nationale…\p"
	.string "Tu as vu {STR_VAR_1} POKéMON,\n"
	.string "et tu en as attrapé {STR_VAR_2}…\p"
	.string "C'est incroyable, {PLAYER} !\p"
	.string "Tu as complété le POKéDEX NATIONAL !\n"
	.string "Félicitations !$"
