	.align 2
gText_ConfirmSave::
	.string "Veux-tu sauvegarder la partie ?$"

gText_AlreadySavedFile::
	.string "Il y a déjà une sauvegarde.\n"
	.string "Écraser la sauvegarde existante ?$"

gText_SavingDontTurnOff::
	.string "SAUVEGARDE…\n"
	.string "NE PAS ÉTEINDRE LA CONSOLE.$"

gText_PlayerSavedGame::
	.string "{PLAYER} a sauvegardé la partie.$"

gText_DifferentSaveFile::
	.string "ATTENTION !\p"
	.string "Une autre sauvegarde de jeu existe déjà.\p"
	.string "Si tu sauvegardes maintenant, l'aventure\n"
	.string "de l'autre fichier, y compris les objets et\l"
	.string "les POKéMON, sera entièrement perdue.\p"
	.string "Es-tu sûr(e) de vouloir sauvegarder\n"
	.string "et écraser l'autre fichier ?$"

gText_SaveError::
	.string "Erreur de sauvegarde.\p"
	.string "Merci de remplacer la\n"
	.string "mémoire de sauvegarde.$"

gText_SavingDontTurnOffPower::
	.string "SAUVEGARDE…\n"
	.string "NE PAS ÉTEINDRE LA CONSOLE.$"
