SecretBase_Text_Trainer0Intro:
	.string "As-tu déjà créé une BASE SECRÈTE ?\p"
	.string "J'ai cherché partout avant de choisir\n"
	.string "cet endroit.\p"
	.string "Puisque tu es là, ça te dirait un combat ?$"

SecretBase_Text_Trainer0AcceptBattle:
	.string "D'accord !\n"
	.string "On arrive !$"

SecretBase_Text_Trainer0DeclineBattle:
	.string "Hein ?\n"
	.string "Oh, tu ne peux pas maintenant…$"

SecretBase_Text_Trainer0Defeated::
	.string "Waaargh ! Tu es trop fort(e) !\n"
	.string "Pour ma défaite… Garde ça secret !$"

SecretBase_Text_Trainer0PostBattle:
	.string "Que penses-tu de ma BASE SECRÈTE ?\n"
	.string "Reviens me voir demain !$"

SecretBase_Text_Trainer0PreChampion:
	.string "As-tu déjà créé une BASE SECRÈTE ?\p"
	.string "J'ai cherché partout avant de choisir\n"
	.string "cet endroit.\p"
	.string "Tu peux rester autant que tu veux !$"

SecretBase_Text_Trainer5Intro:
	.string "Il y a plein d'endroits où tu peux faire\n"
	.string "une BASE SECRÈTE.\p"
	.string "Mais j'aime cet endroit plus que tout.\n"
	.string "Tu ne trouves pas qu'il est sympa ?\p"
	.string "Oh, tu veux faire un combat ?$"

SecretBase_Text_Trainer5AcceptBattle:
	.string "D'accord, c'est parti !$"

SecretBase_Text_Trainer5DeclineBattle:
	.string "Oh…\n"
	.string "Tu ne peux pas maintenant, d'accord.$"

SecretBase_Text_Trainer5Defeated::
	.string "Hmm… On a perdu…\n"
	.string "Mais ne le dis à personne !\l"
	.string "C'est un secret confidentiel !$"

SecretBase_Text_Trainer5PostBattle:
	.string "Si tu repasses dans le coin,\n"
	.string "j'espère que tu viendras me voir !$"

SecretBase_Text_Trainer5PreChampion:
	.string "Il y a plein d'endroits où tu peux faire\n"
	.string "une BASE SECRÈTE.\p"
	.string "Mais j'aime cet endroit plus que tout.\n"
	.string "Tu ne trouves pas qu'il est sympa ?$"

SecretBase_Text_Trainer1Intro:
	.string "C'est un endroit très prisé.\n"
	.string "Il est toujours occupé.\p"
	.string "Oh ! Tu pensais aussi à prendre\n"
	.string "cet endroit ?\p"
	.string "Je te propose un truc : tu peux l'avoir\n"
	.string "si tu arrives à me battre !$"

SecretBase_Text_Trainer1AcceptBattle:
	.string "D'accord !\n"
	.string "Je vais défendre ma BASE SECRÈTE !$"

SecretBase_Text_Trainer1DeclineBattle:
	.string "Hein ? C'est vrai ?\n"
	.string "Tu n'es pas intéressé(e) par cet endroit ?$"

SecretBase_Text_Trainer1Defeated::
	.string "Je ne peux plus continuer !\n"
	.string "Je me rends !$"

SecretBase_Text_Trainer1PostBattle:
	.string "D'accord, quand je partirai un jour,\n"
	.string "cet endroit sera à toi !$"

SecretBase_Text_Trainer1PreChampion:
	.string "C'est un endroit très prisé.\n"
	.string "Il est toujours occupé.\p"
	.string "J'ai attendu longtemps qu'il se libère.\n"
	.string "J'ai enfin pu l'utiliser !$"

SecretBase_Text_Trainer6Intro:
	.string "Bienvenue dans mon LABO POKéMON.\p"
	.string "J'étudie les combats en toute discrétion.\p"
	.string "Veux-tu voir à quel point je suis fort(e) ?$"

SecretBase_Text_Trainer6AcceptBattle:
	.string "Je vais tout donner !$"

SecretBase_Text_Trainer6DeclineBattle:
	.string "Oh.\n"
	.string "Une autre fois, alors !$"

SecretBase_Text_Trainer6Defeated::
	.string "Hmm… J'ai encore beaucoup à apprendre.\n"
	.string "Je dois étudier davantage !$"

SecretBase_Text_Trainer6PostBattle:
	.string "Merci d'avoir combattu avec moi.\n"
	.string "Reviens me voir demain !$"

SecretBase_Text_Trainer6PreChampion:
	.string "Bienvenue dans mon LABO POKéMON.\p"
	.string "J'étudie les combats en toute discrétion.$"

SecretBase_Text_Trainer2Intro:
	.string "Un grand manoir, c'est bien, mais je\n"
	.string "préfère ce genre d'endroit.\p"
	.string "J'aime ici car plein de gens\n"
	.string "viennent me rendre visite.\p"
	.string "Alors, ça te dit un combat ?$"

SecretBase_Text_Trainer2AcceptBattle:
	.string "C'est parti !$"

SecretBase_Text_Trainer2DeclineBattle:
	.string "Quand tu seras prêt(e), fais-moi signe !$"

SecretBase_Text_Trainer2Defeated::
	.string "Oh non ! C'est fini pour moi !\n"
	.string "Mais c'est toujours amusant de combattre !$"

SecretBase_Text_Trainer2PostBattle:
	.string "Bon, je devrais aller acheter des\n"
	.string "décorations et des meubles.\p"
	.string "Je veux que ma BASE SECRÈTE soit un lieu\n"
	.string "où les autres peuvent s'amuser !$"

SecretBase_Text_Trainer2PreChampion:
	.string "Un grand manoir, c'est bien, mais je\n"
	.string "préfère ce genre d'endroit.\p"
	.string "J'aime ici car plein de gens\n"
	.string "viennent me rendre visite.$"

SecretBase_Text_Trainer7Intro:
	.string "J'adore faire du shopping pour des\n"
	.string "décorations et des meubles.\p"
	.string "J'aime aussi élever des POKéMON\n"
	.string "tout autant.\p"
	.string "Si tu veux bien, veux-tu combattre\n"
	.string "avec mes POKéMON ?$"

SecretBase_Text_Trainer7AcceptBattle:
	.string "Merci.\n"
	.string "On commence ?$"

SecretBase_Text_Trainer7DeclineBattle:
	.string "Oh.\n"
	.string "Comme c'est décevant…$"

SecretBase_Text_Trainer7Defeated::
	.string "J'abandonne…$"

SecretBase_Text_Trainer7PostBattle:
	.string "C'était pour le fun !\n"
	.string "Je vais aller faire du shopping maintenant !$"

SecretBase_Text_Trainer7PreChampion:
	.string "J'adore faire du shopping pour des\n"
	.string "décorations et des meubles.\p"
	.string "J'aime aussi élever des POKéMON\n"
	.string "tout autant.$"

SecretBase_Text_Trainer3Intro:
	.string "Certaines personnes font leur BASE SECRÈTE\n"
	.string "dans des endroits difficiles à trouver.\l"
	.string "Ils veulent se cacher ?\p"
	.string "Mais puisque tu m'as trouvé(e), que dirais-tu\n"
	.string "d'un combat ?$"

SecretBase_Text_Trainer3AcceptBattle:
	.string "Je ne vais pas me laisser faire !$"

SecretBase_Text_Trainer3DeclineBattle:
	.string "Oh… Tu es peut-être fatigué(e) d'avoir\n"
	.string "cherché cet endroit ?$"

SecretBase_Text_Trainer3Defeated::
	.string "Je suis tombé(e)…$"

SecretBase_Text_Trainer3PostBattle:
	.string "Où est ta BASE SECRÈTE ?\n"
	.string "Je devrais venir te rendre visite !$"

SecretBase_Text_Trainer3PreChampion:
	.string "Certaines personnes font leur BASE SECRÈTE\n"
	.string "dans des endroits difficiles à trouver.\l"
	.string "Ils veulent se cacher ?$"

SecretBase_Text_Trainer8Intro:
	.string "On m'a dit qu'on pouvait obtenir des\n"
	.string "décorations de plusieurs façons.\p"
	.string "On devrait faire la course pour voir qui\n"
	.string "aura les plus belles décorations et meubles !\p"
	.string "En attendant, tu veux combattre ?$"

SecretBase_Text_Trainer8AcceptBattle:
	.string "C'est ma BASE SECRÈTE.\n"
	.string "Je ne peux pas perdre !$"

SecretBase_Text_Trainer8DeclineBattle:
	.string "Je combattrai avec toi quand tu veux !$"

SecretBase_Text_Trainer8Defeated::
	.string "Hein ?\n"
	.string "J'ai perdu ?$"

SecretBase_Text_Trainer8PostBattle:
	.string "Je ne perdrai pas à la collecte de décorations.\n"
	.string "Reviens me voir !$"

SecretBase_Text_Trainer8PreChampion:
	.string "On m'a dit qu'on pouvait obtenir des\n"
	.string "décorations de plusieurs façons.\p"
	.string "On devrait faire la course pour voir qui\n"
	.string "aura les plus belles décorations et meubles !$"

SecretBase_Text_Trainer4Intro:
	.string "J'ai trouvé un endroit que j'aime et je l'ai\n"
	.string "décoré avec mes objets préférés.\p"
	.string "J'élève mon POKéMON préféré et je deviens\n"
	.string "plus fort(e) avec lui.\p"
	.string "C'est ce que je fais.\n"
	.string "Tu veux te battre avec moi ?$"

SecretBase_Text_Trainer4AcceptBattle:
	.string "Montre-moi de quoi tu es capable !$"

SecretBase_Text_Trainer4DeclineBattle:
	.string "Il y a des fois où on n'a pas envie,\n"
	.string "je suppose.$"

SecretBase_Text_Trainer4Defeated::
	.string "Je sais maintenant exactement de quoi tu es capable !$"

SecretBase_Text_Trainer4PostBattle:
	.string "On peut tous les deux devenir plus forts.\n"
	.string "Continuons comme ça !$"

SecretBase_Text_Trainer4PreChampion:
	.string "J'ai trouvé un endroit que j'aime et je l'ai\n"
	.string "décoré avec mes objets préférés.\p"
	.string "J'élève mon POKéMON préféré et je deviens\n"
	.string "plus fort(e) avec lui.\p"
	.string "Chaque jour est un jour génial !$"

SecretBase_Text_Trainer9Intro:
	.string "On peut en apprendre beaucoup sur le goût\n"
	.string "et le sens des gens par le type de\l"
	.string "décorations qu'ils ont et comment ils\l"
	.string "les exposent.\p"
	.string "Que penses-tu de mon goût ?\n"
	.string "Tu es sans voix ?\p"
	.string "Veux-tu voir mon style en combat ?$"

SecretBase_Text_Trainer9AcceptBattle:
	.string "Je ne vais pas me retenir !$"

SecretBase_Text_Trainer9DeclineBattle:
	.string "Je serai ravi(e) de te montrer mon style\n"
	.string "quand tu veux !$"

SecretBase_Text_Trainer9Defeated::
	.string "Tu es vraiment talentueux(se) !\n"
	.string "Ta puissance semble sans limite…$"

SecretBase_Text_Trainer9PostBattle:
	.string "Qu'as-tu pensé de mon style ?\n"
	.string "Je vais continuer à le perfectionner !$"

SecretBase_Text_Trainer9PreChampion:
	.string "On peut en apprendre beaucoup sur le goût\n"
	.string "et le sens des gens par le type de\l"
	.string "décorations qu'ils ont et comment ils\l"
	.string "les exposent.\p"
	.string "Que penses-tu de mon goût ?\n"
	.string "Tu es sans voix ?$"
