ShoalCave_LowTideEntranceRoom_Text_AreYouPlanningOnGoingInThere:
	.string "Tu comptes aller au fond\n"
	.string "de la GROTTE ?\p"
	.string "Et si tu me rapportais un peu de\n"
	.string "SEL MARIN et des COQUILLES MARINES ?\p"
	.string "Je peux te fabriquer quelque chose de bien\n"
	.string "si tu m'apportes les ingrédients.$"

ShoalCave_LowTideEntranceRoom_Text_BringMe4ShoalSaltAndShells:
	.string "Si tu m'apportes quatre SELS MARINS\n"
	.string "et quatre COQUILLES MARINES,\l"
	.string "je peux te fabriquer une GRELLOT COQUE…\p"
	.string "Tu peux trouver ces ingrédients\n"
	.string "tous les jours.$"

ShoalCave_LowTideEntranceRoom_Text_WouldYouLikeShellBell:
	.string "Oh, tiens ! SEL MARIN et COQUILLES MARINES !\n"
	.string "Et en quantité suffisante, en plus !\p"
	.string "Veux-tu que je te fabrique\n"
	.string "une GRELLOT COQUE avec ça ?$"

ShoalCave_LowTideEntranceRoom_Text_MakeShellBellRightAway:
	.string "Très bien ! Je vais te fabriquer\n"
	.string "une GRELLOT COQUE tout de suite.\p"
	.string "… … … … … … … …\n"
	.string "… … … … … … … …\p"
	.string "Voilà ! C'est prêt !$"

ShoalCave_LowTideEntranceRoom_Text_ExplainShellBell:
	.string "Fais tenir ça à un POKéMON.\n"
	.string "Il va adorer, c'est certain.\p"
	.string "Le tintement de la GRELLOT COQUE…\n"
	.string "C'est tout simplement sublime !\p"
	.string "Tu peux avoir les ingrédients chaque jour,\n"
	.string "donc je peux t'en fabriquer d'autres.$"

ShoalCave_LowTideEntranceRoom_Text_WantedToMakeShellBell:
	.string "Oh… C'est comme ça…\n"
	.string "Je voulais fabriquer une GRELLOT COQUE…$"

ShoalCave_LowTideEntranceRoom_Text_NoSpaceInYourBag:
	.string "Tu n'as pas de place dans ton SAC\n"
	.string "si je te la fabrique maintenant.\p"
	.string "Fais de la place et reviens\n"
	.string "pour une GRELLOT COQUE.$"

ShoalCave_Text_WasShoalSaltNowNothing:
	.string "Il y avait du SEL MARIN ici.\n"
	.string "Mais il n'y en a plus maintenant.$"

ShoalCave_Text_WasShoallShellNowNothing:
	.string "Il y avait une COQUILLE MARINE ici.\n"
	.string "Mais il n'y en a plus maintenant.$"
