Route102_Text_CalvinIntro:
	.string "Si tu as des POKéMON avec toi, alors\n"
	.string "tu es un DRESSEUR POKéMON officiel !\l"
	.string "Tu ne peux pas refuser mon défi !$"

Route102_Text_CalvinDefeated:
	.string "Argh, j'ai perdu…\n"
	.string "J'aurais dû mieux entraîner les miens…$"

Route102_Text_CalvinPostBattle:
	.string "Écoute, toi. Si tu es fort,\n"
	.string "tu aurais dû me le dire avant !$"

Route102_Text_CalvinRegister:
	.string "Je me suis beaucoup entraîné depuis\n"
	.string "la dernière fois qu'on s'est vus.\p"
	.string "J'aimerais me battre à nouveau, alors\n"
	.string "tu peux m'enregistrer dans ton POKéNAV ?$"

Route102_Text_CalvinRegisterShort:
	.string "J'aimerais me battre à nouveau, alors\n"
	.string "tu peux m'enregistrer dans ton POKéNAV ?$"

Route102_Text_CalvinRematchIntro:
	.string "Depuis que j'ai perdu contre toi, j'ai\n"
	.string "entraîné mes POKéMON sans relâche.\l"
	.string "Tu ne peux pas refuser mon défi !$"

Route102_Text_CalvinRematchDefeated:
	.string "Argh, j'ai encore perdu…\n"
	.string "Ma méthode d'entraînement n'est pas bonne ?$"

Route102_Text_CalvinRematchPostBattle:
	.string "Si tu deviens plus fort,\n"
	.string "je deviendrai plus fort aussi.$"

Route102_Text_AllenIntro:
	.string "Tu viens de devenir DRESSEUR ?\n"
	.string "On est tous les deux débutants !$"

Route102_Text_AllenDefeated:
	.string "Je t'ai appelé parce que je pensais\n"
	.string "pouvoir te battre…$"

Route102_Text_AllenPostBattle:
	.string "Je n'ai encore jamais gagné…\n"
	.string "J'aimerais bien gagner bientôt…$"

Route102_Text_RickIntro:
	.string "Hahaha ! Nos regards se sont croisés !\n"
	.string "Je vais t'affronter avec mes POKéMON INSECTE !$"

Route102_Text_RickDefeated:
	.string "Aïe ! K.O. !$"

Route102_Text_RickPostBattle:
	.string "Si tu croises le regard d'un DRESSEUR,\n"
	.string "tu dois le défier ! C'est la règle !$"

Route102_Text_TianaIntro:
	.string "Je vais continuer à gagner et viser\n"
	.string "le titre de meilleur DRESSEUR.\p"
	.string "Aide-moi à faire avancer ma carrière !$"

Route102_Text_TianaDefeated:
	.string "C'est ta carrière que j'ai fait avancer…$"

Route102_Text_TianaPostBattle:
	.string "Pour continuer à gagner, je vois que\n"
	.string "je dois attraper plus de POKéMON.$"

Route103_Text_DaisyIntro:
	.string "As-tu ressenti l'appel de notre\n"
	.string "parfum apaisant pour l'âme ?$"

Route103_Text_DaisyDefeated:
	.string "Tu n'as pas été troublé par notre arôme…$"

Route103_Text_DaisyPostBattle:
	.string "L'aromathérapie est une forme de soin\n"
	.string "mental qui agit avec les parfums.$"

Route103_Text_AmyIntro:
	.string "AMY : Je suis AMY.\n"
	.string "Et voici ma petite sœur LIV.\l"
	.string "On se bat ensemble !$"

Route103_Text_AmyDefeated:
	.string "AMY : Oh non, on a perdu.$"

Route103_Text_AmyPostBattle:
	.string "AMY : Il faut penser à plein de choses\n"
	.string "quand on affronte deux DRESSEURS.$"

Route103_Text_AmyNotEnoughPokemon:
	.string "AMY : Oh non, tu n'as qu'un seul\n"
	.string "POKéMON avec toi.\l"
	.string "Tu ne peux pas nous affronter comme ça.$"

Route103_Text_LivIntro:
	.string "LIV : On se bat ensemble comme une\n"
	.string "équipe.$"

Route103_Text_LivDefeated:
	.string "LIV : Oh, on a perdu, grande sœur…$"

Route103_Text_LivPostBattle:
	.string "LIV : On travaille parfaitement ensemble,\n"
	.string "moi et ma grande sœur…\p"
	.string "Mais on a quand même perdu…$"

Route103_Text_AmyLivRegister:
	.string "LIV : Vraiment, on est bien meilleures…\n"
	.string "C'est vrai ! On te le montrera la prochaine fois !$"

Route103_Text_LivNotEnoughPokemon:
	.string "LIV : Si tu veux nous affronter,\n"
	.string "il te faut deux POKéMON !\l"
	.string "C'est pas juste sinon !$"

Route103_Text_AmyRematchIntro:
	.string "AMY : Je suis AMY.\n"
	.string "Et voici ma petite sœur LIV.\l"
	.string "On se bat ensemble !$"

Route103_Text_AmyRematchDefeated:
	.string "AMY : Oh non !\n"
	.string "On n'a encore pas pu gagner…$"

Route103_Text_AmyRematchPostBattle:
	.string "AMY : Il faut penser à plein de choses\n"
	.string "quand on affronte deux DRESSEURS.$"

Route103_Text_AmyRematchNotEnoughPokemon:
	.string "AMY : Oh non, tu n'as qu'un seul\n"
	.string "POKéMON avec toi.\l"
	.string "Tu ne peux pas nous affronter comme ça.$"

Route103_Text_LivRematchIntro:
	.string "LIV : On se bat ensemble comme une\n"
	.string "équipe.$"

Route103_Text_LivRematchDefeated:
	.string "LIV : Oh non, on a encore perdu…\n"
	.string "Grande sœur…$"

Route103_Text_LivRematchPostBattle:
	.string "LIV : On travaille parfaitement ensemble,\n"
	.string "moi et ma grande sœur…\p"
	.string "Mais pourquoi on a encore perdu ?$"

Route103_Text_LivRematchNotEnoughPokemon:
	.string "LIV : Si tu veux nous affronter, tu\n"
	.string "dois avoir deux POKéMON !\l"
	.string "C'est pas juste sinon !$"

Route103_Text_AndrewIntro:
	.string "Grrr ! Ma ligne de pêche est toute emmêlée !\n"
	.string "Je deviens frustré et grognon !\l"
	.string "Ça suffit ! Combat !$"

Route103_Text_AndrewDefeated:
	.string "Grrr ! J'ai perdu !\n"
	.string "Je suis encore plus énervé maintenant !$"

Route103_Text_AndrewPostBattle:
	.string "Grrr, je suis toujours bouillant de colère…\n"
	.string "Grrrrr…$"

Route103_Text_MiguelIntro:
	.string "Mon POKéMON est adorable à croquer !\n"
	.string "Ne sois pas timide--je vais te le montrer !$"

Route103_Text_MiguelDefeated:
	.string "Oh, mon dieu !\n"
	.string "Mon précieux POKéMON !$"

Route103_Text_MiguelPostBattle:
	.string "Mon adorable POKéMON est mignon\n"
	.string "même quand il est K.O. !$"

Route103_Text_MiguelRegister:
	.string "Je veux que tu reviennes voir mon\n"
	.string "adorable POKéMON encore !$"

Route103_Text_MiguelRematchIntro:
	.string "Salut, toi ! Mon POKéMON adorable\n"
	.string "est encore plus mignon !$"

Route103_Text_MiguelRematchDefeated:
	.string "Oh !\n"
	.string "Mon précieux POKéMON !$"

Route103_Text_MiguelRematchPostBattle:
	.string "Plus je passe de temps avec lui,\n"
	.string "plus mon POKéMON devient adorable.$"

Route103_Text_PeteIntro:
	.string "Pour une distance comme ça…\n"
	.string "Tu devrais juste nager !$"

Route103_Text_PeteDefeated:
	.string "Oh, bien joué !$"

Route103_Text_PetePostBattle:
	.string "Oh, je comprends mieux ton point de vue.\p"
	.string "Si j'avais un POKéMON aussi fiable,\n"
	.string "je voudrais aussi SURFER dessus !$"

Route103_Text_IsabelleIntro:
	.string "Fais attention où tu vas !\n"
	.string "On va se rentrer dedans !$"

Route103_Text_IsabelleDefeated:
	.string "Gémissement…$"

Route103_Text_IsabellePostBattle:
	.string "Je nage mal alors je m'entraînais…\n"
	.string "Désolée d'avoir failli te rentrer dedans.$"

Route103_Text_RhettIntro:
	.string "Ouah !\n"
	.string "Comment t'es-tu retrouvé dans un espace si petit ?$"

Route103_Text_RhettDefeated:
	.string "Ouah !\n"
	.string "Ce gamin assure !$"

Route103_Text_RhettPostBattle:
	.string "Tu aimes les endroits exigus\n"
	.string "comme celui-ci ?$"

Route103_Text_MarcosIntro:
	.string "C'est le cri de ma guitare qui t'a attiré ?$"

Route103_Text_MarcosDefeated:
	.string "Mon concert solo est ruiné…$"

Route103_Text_MarcosPostBattle:
	.string "Je jouais de la guitare là où il y avait\n"
	.string "peu de monde, mais plein de fans sont venus.\p"
	.string "Héhé, je devrais peut-être devenir pro.$"

Route104_Text_GinaIntro:
	.string "GINA : Allez, battons-nous avec nos\n"
	.string "POKéMON !$"

Route104_Text_GinaDefeat:
	.string "GINA : Perdre me contrarie !$"

Route104_Text_GinaPostBattle:
	.string "GINA : Tu es fort !\n"
	.string "On doit encore beaucoup s'entraîner !$"

Route104_Text_GinaNotEnoughMons:
	.string "GINA : Oh ? Un seul POKéMON ?\n"
	.string "Alors, on ne se bat pas avec toi.\p"
	.string "S'il n'y a qu'un POKéMON, il sera\n"
	.string "tout seul. C'est pas sympa !$"

Route104_Text_MiaIntro:
	.string "MIA : On est jumelles, alors on se bat\n"
	.string "ensemble avec nos POKéMON.$"

Route104_Text_MiaDefeat:
	.string "MIA : On s'est battues ensemble, mais\n"
	.string "on a toutes les deux perdu…$"

Route104_Text_MiaPostBattle:
	.string "MIA : On va entraîner nos POKéMON encore\n"
	.string "et devenir fortes comme toi.$"

Route104_Text_MiaNotEnoughMons:
	.string "MIA : Tu veux te battre contre nous ?\p"
	.string "C'est interdit si tu n'as pas deux\n"
	.string "POKéMON avec toi.\l"
	.string "On est trop fortes pour toi !$"

Route104_Text_IvanIntro:
	.string "Pourquoi garder ça secret ?\n"
	.string "Je suis l'expert des POKéMON EAU !\p"
	.string "Hein ?\n"
	.string "Tu ne me connais pas ?$"

Route104_Text_IvanDefeat:
	.string "Je pensais ne pas être trop mauvais,\n"
	.string "mais finalement non… Beurk…$"

Route104_Text_IvanPostBattle:
	.string "Je me suis trop concentré sur la pêche.\n"
	.string "J'ai oublié d'entraîner mes POKéMON…$"

Route104_Text_BillyIntro:
	.string "Laisser des traces de pas dans le sable,\n"
	.string "c'est trop amusant !$"

Route104_Text_BillyDefeat:
	.string "Ouah ! J'ai du sable dans mes chaussures !\n"
	.string "Elles sont toutes pleines de grains !$"

Route104_Text_BillyPostBattle:
	.string "Je veux laisser mes traces de pas partout\n"
	.string "dans le sable, mais elles\l"
	.string "disparaissent vite…$"

Route104_Text_HaleyIntro:
	.string "Je devrais…\n"
	.string "Ou je ne devrais pas ?\p"
	.string "Bon, d'accord, je vais me battre !$"

Route104_Text_HaleyDefeat:
	.string "J'aurais pas dû me battre…$"

Route104_Text_HaleyPostBattle:
	.string "Si tu dois prendre une décision et que\n"
	.string "tu laisses quelqu'un d'autre choisir,\l"
	.string "tu le regretteras, peu importe le résultat.$"

Route104_Text_HaleyRegister1:
	.string "Tu es fort, mais est-ce que je devrais\n"
	.string "t'enregistrer dans mon POKéNAV ?\l"
	.string "Peut-être que non…\p"
	.string "Bon, d'accord, je vais t'enregistrer !$"

Route104_Text_HaleyRegister2:
	.string "Tu es fort, mais est-ce que je devrais\n"
	.string "t'enregistrer dans mon POKéNAV ?\l"
	.string "Peut-être que non…\p"
	.string "Bon, d'accord, je vais t'enregistrer !$"

Route104_Text_HaleyRematchIntro:
	.string "Allez, bats-toi avec moi !$"

Route104_Text_HaleyRematchDefeat:
	.string "Ohh…\n"
	.string "Je pensais pouvoir gagner…$"

Route104_Text_HaleyPostRematch:
	.string "J'ai pris la décision de me battre, alors\n"
	.string "je peux accepter cette défaite avec grâce.\p"
	.string "Mais je suis quand même déçue !$"

Route104_Text_WinstonIntro:
	.string "Oh, bien sûr, j'accepte ton défi.\n"
	.string "J'ai beaucoup d'argent.$"

Route104_Text_WinstonDefeat:
	.string "Pourquoi je n'ai pas pu gagner ?$"

Route104_Text_WinstonPostBattle:
	.string "Il y a des choses que l'argent ne peut pas acheter.\n"
	.string "Comme les POKéMON…$"

Route104_Text_WinstonRegister1:
	.string "Hein ?\n"
	.string "Ah, tu as obtenu un POKéNAV.\p"
	.string "Je vais t'enregistrer avec plaisir.\n"
	.string "Après tout, j'ai plein d'argent !$"

Route104_Text_WinstonRegister2:
	.string "Hein ?\n"
	.string "Ah, tu as obtenu un POKéNAV.\p"
	.string "Je vais t'enregistrer avec plaisir.\n"
	.string "Après tout, j'ai plein d'argent !$"

Route104_Text_WinstonRematchIntro:
	.string "Après avoir perdu contre toi, j'ai appris\n"
	.string "plein de choses sur les POKéMON.$"

Route104_Text_WinstonRematchDefeat:
	.string "J'ai encore perdu ?\n"
	.string "Pourquoi je n'ai pas pu gagner ?$"

Route104_Text_WinstonPostRematch:
	.string "Je suis fabuleusement riche, mais je n'arrive\n"
	.string "pas à gagner aux POKéMON…\p"
	.string "C'est profond, le monde des POKéMON…$"

Route104_Text_CindyIntro:
	.string "On devait être destinés à nous rencontrer.\n"
	.string "Puis-je te demander un combat ?$"

Route104_Text_CindyDefeat:
	.string "Oh, mince !$"

Route104_Text_CindyPostBattle:
	.string "« Bonjour » est le début de « au revoir ».\n"
	.string "J'espère qu'on se reverra.$"

Route104_Text_CindyRegister1:
	.string "Bonjour, on se revoit.\p"
	.string "On dirait qu'on est attirés l'un vers l'autre.\n"
	.string "Enregistrons-nous dans nos POKéNAVS.$"

Route104_Text_CindyRegister2:
	.string "On devrait célébrer le fait qu'on semble\n"
	.string "attirés l'un vers l'autre.\p"
	.string "Enregistrons-nous dans nos\n"
	.string "POKéNAVS.$"

Route104_Text_CindyRematchIntro:
	.string "Bonjour, on se revoit.\n"
	.string "Puis-je te demander un combat ?$"

Route104_Text_CindyRematchDefeat:
	.string "Oh, mince…\n"
	.string "J'ai fait de mon mieux…$"

Route104_Text_CindyPostRematch:
	.string "« Bonjour » est le début de « au revoir ».\n"
	.string "J'espère qu'on se reverra.$"

Route104_Text_DarianIntro:
	.string "J'ai pêché un POKéMON qui a l'air costaud !\p"
	.string "Il a une qualité magique !\n"
	.string "Il a vraiment l'air fort, oui !$"

Route104_Text_DarianDefeat:
	.string "Quoi…?$"

Route104_Text_DarianPostBattle:
	.string "Hé, MAGIKARP, tu ne fais pas honneur\n"
	.string "à ton nom, hein ?$"

Route105_Text_FosterIntro:
	.string "Il paraît qu'il y a un rocher mystique\n"
	.string "dans le coin.\l"
	.string "Tu en sais quelque chose ?$"

Route105_Text_FosterDefeated:
	.string "Je pensais trop à ce rocher alors que\n"
	.string "mes POKéMON restaient faibles…$"

Route105_Text_FosterPostBattle:
	.string "Je peux passer des heures à contempler\n"
	.string "un beau rocher sans m'ennuyer.$"

Route105_Text_LuisIntro:
	.string "Ouf ! J'ai cru qu'un enfant se noyait\n"
	.string "quand je t'ai vu.\p"
	.string "Tu as l'air d'aller bien, alors que\n"
	.string "dirais-tu d'un combat ?$"

Route105_Text_LuisDefeated:
	.string "Glou… Glou…$"

Route105_Text_LuisPostBattle:
	.string "Si tu te noies, le signal c'est de\n"
	.string "faire signe d'un bras vers la plage.$"

Route105_Text_DominikIntro:
	.string "Nager dans la mer bleue profonde…\n"
	.string "C'est le top !$"

Route105_Text_DominikDefeated:
	.string "J'ai perdu…\n"
	.string "Maintenant je broie du noir…$"

Route105_Text_DominikPostBattle:
	.string "Pourquoi la mer est-elle bleue ?\p"
	.string "Je l'ai appris au MUSÉE de POIVRESSEL,\n"
	.string "mais j'ai oublié.$"

Route105_Text_BeverlyIntro:
	.string "Je me sens plus légère dans l'eau.\n"
	.string "C'est comme si j'avais minci !$"

Route105_Text_BeverlyDefeated:
	.string "Je flotte…$"

Route105_Text_PostBattle:
	.string "Ton poids est réduit à un dixième dans l'eau.\p"
	.string "Ça ferait de moi…\n"
	.string "Oups ! Je ne te dirai pas mon poids !$"

Route105_Text_ImaniIntro:
	.string "Le ciel bleu, bleu…\n"
	.string "La mer immense…\l"
	.string "C'est si paisible…$"

Route105_Text_ImaniDefeated:
	.string "J'ai perdu en me prélassant !$"

Route105_Text_ImaniPostBattle:
	.string "J'aimerais qu'on me dise que je suis\n"
	.string "agréable à côtoyer. Hihi.$"

Route105_Text_AndresIntro:
	.string "Je suis convaincu que la mer garde\n"
	.string "des secrets pour nous.$"

Route105_Text_AndresDefeated:
	.string "Oui…\n"
	.string "Je ne suis pas doué pour les combats…$"

Route105_Text_AndresPostBattle:
	.string "Je suis sûr qu'il y a plein de secrets\n"
	.string "à découvrir dans les mers du monde.\p"
	.string "Je compte tous les trouver !$"

Route105_Text_AndresRegister:
	.string "Hein ? Je suis si faible, mais tu veux\n"
	.string "m'enregistrer dans ton POKéNAV ?$"

Route105_Text_AndresRematchIntro:
	.string "Je t'ai dit que je suis faible…\n"
	.string "Tu es sûr de vouloir faire ça ?$"

Route105_Text_AndresRematchDefeated:
	.string "Oui…\n"
	.string "Je ne pensais pas pouvoir gagner.$"

Route105_Text_AndresRematchPostBattle:
	.string "Je suis peut-être nul en combat, mais\n"
	.string "ma soif d'exploration est imbattable.\p"
	.string "Je parcourrai les mers du monde !$"

Route105_Text_JosueIntro:
	.string "Je suis épuisé par la nage.\n"
	.string "Je n'ai pas l'habitude.\p"
	.string "Il me faut un combat pour changer d'air !$"

Route105_Text_JosueDefeated:
	.string "J'ai perdu parce que j'ai combattu en mer.$"

Route105_Text_JosuePostBattle:
	.string "Oui, pour moi, le ciel me convient\n"
	.string "bien mieux que la mer.$"

Route106_Text_ElliotIntro:
	.string "Tu préfères pêcher en mer ou en rivière ?$"

Route106_Text_ElliotDefeated:
	.string "Comme à la pêche en haute mer, j'ai perdu\n"
	.string "spectaculairement !$"

Route106_Text_ElliotPostBattle:
	.string "La pêche, c'est génial, que ce soit en\n"
	.string "mer ou en rivière.\l"
	.string "Tu es d'accord, non ?$"

Route106_Text_ElliotRegister:
	.string "La pêche, c'est super, mais les combats aussi.\n"
	.string "Si ça te dit, on se revoit ?$"

Route106_Text_ElliotRematchIntro:
	.string "J'ai attrapé plein de POKéMON à la pêche.\n"
	.string "Je vais te montrer un combat impressionnant !$"

Route106_Text_ElliotRematchDefeated:
	.string "J'ai encore perdu spectaculairement !$"

Route106_Text_ElliotRematchPostBattle:
	.string "Gagner ou perdre, les POKéMON c'est le top !\n"
	.string "Tu es d'accord, non ?$"

Route106_Text_NedIntro:
	.string "Que font les gens s'ils doivent aller\n"
	.string "aux toilettes ?\p"
	.string "Et si ma CANNE attrape un gros poisson\n"
	.string "pendant que j'y suis ? Je peux pas y aller…$"

Route106_Text_NedDefeated:
	.string "J'ai perdu parce que j'essaie de ne pas\n"
	.string "aller aux toilettes…$"

Route106_Text_NedPostBattle:
	.string "Oh non ! Je sens que je vais attraper\n"
	.string "un gros poisson !$"

Route106_Text_DouglasIntro:
	.string "Hahaha ! Je cours mal, mais dans l'eau\n"
	.string "tu ne peux pas m'attraper !$"

Route106_Text_DouglasDefeated:
	.string "J'abandonne !$"

Route106_Text_DouglasPostBattle:
	.string "Je ne perdrais pas à une course de natation…$"

Route106_Text_KylaIntro:
	.string "La mer, c'est mon jardin. Je ne vais pas\n"
	.string "te ménager parce que tu es un enfant !$"

Route106_Text_KylaDefeated:
	.string "Tu m'as ménagée, par hasard ?$"

Route106_Text_KylaPostBattle:
	.string "Se laisser porter par les vagues…\n"
	.string "J'adore ça ! Tu devrais essayer !$"

Route107_Text_DarrinIntro:
	.string "Bâillement…\p"
	.string "J'ai dû m'endormir en me laissant\n"
	.string "bercer par les vagues.$"

Route107_Text_DarrinDefeated:
	.string "Ahaha, j'ai perdu…\n"
	.string "Je vais faire une sieste, je crois…$"

Route107_Text_DarrinPostBattle:
	.string "Flotter et se laisser bercer par les\n"
	.string "vagues--c'est comme dormir dans\l"
	.string "un lit moelleux et douillet.$"

Route107_Text_TonyIntro:
	.string "La mer, c'est comme mon jardin.\n"
	.string "Allons nous battre !$"

Route107_Text_TonyDefeated:
	.string "J'ai perdu sur mon terrain…\n"
	.string "Je suis sous le choc !$"

Route107_Text_TonyPostBattle:
	.string "Je nage en mer avec un cœur plein de\n"
	.string "rêves…\p"
	.string "C'est une chanson !\n"
	.string "Bon, je vais encore nager !$"

Route107_Text_TonyRegister:
	.string "Tu m'as choqué jusqu'à l'os !\n"
	.string "Comme ça tu ne m'oublieras pas…$"

Route107_Text_TonyRematchIntro:
	.string "En nageant dans la grande mer,\n"
	.string "mon POKéMON est devenu plus fort !$"

Route107_Text_TonyRematchDefeated:
	.string "Quel choc !\p"
	.string "Mon POKéMON est devenu plus fort, mais\n"
	.string "je reste faible comme DRESSEUR !$"

Route107_Text_TonyRematchPostBattle:
	.string "Ce qu'on apprend en combat fait de toi\n"
	.string "un meilleur DRESSEUR.\l"
	.string "Les vagues m'ont appris ça.$"

Route107_Text_DeniseIntro:
	.string "Tu connais une petite ville appelée\n"
	.string "MYOKARA ?$"

Route107_Text_DeniseDefeated:
	.string "J'aime pas ça !$"

Route107_Text_DenisePostBattle:
	.string "Une expression bizarre devient très\n"
	.string "tendance à la SALLE de MYOKARA.$"

Route107_Text_BethIntro:
	.string "Tu voulais te battre contre moi ?\n"
	.string "D'accord, je viens !$"

Route107_Text_BethDefeated:
	.string "Je n'étais pas assez forte pour toi.$"

Route107_Text_BethPostBattle:
	.string "Je pense que tu vas devenir encore meilleur.\n"
	.string "Moi aussi, je vais m'accrocher !$"

Route107_Text_LisaIntro:
	.string "LISA : On te défie en tant que sœur\n"
	.string "et frère !$"

Route107_Text_LisaDefeated:
	.string "LISA : Génial.\n"
	.string "Tu es d'une autre catégorie !$"

Route107_Text_LisaPostBattle:
	.string "LISA : Tu as des amis qui iraient\n"
	.string "à la plage avec toi ?$"

Route107_Text_LisaNotEnoughPokemon:
	.string "LISA : Si tu veux te battre contre nous,\n"
	.string "ramène plus de POKéMON.$"

Route107_Text_RayIntro:
	.string "RAY : On se bat toujours avec des POKéMON,\n"
	.string "ma sœur et moi.\p"
	.string "Je perds toujours, mais à deux contre deux,\n"
	.string "on peut te battre !$"

Route107_Text_RayDefeated:
	.string "RAY : Waouh, tu es à un niveau supérieur\n"
	.string "à nous !$"

Route107_Text_RayPostBattle:
	.string "RAY : Ma sœur m'a donné mon POKéMON.\n"
	.string "Je l'ai élevé, et maintenant c'est mon\l"
	.string "partenaire précieux !$"

Route107_Text_RayNotEnoughPokemon:
	.string "RAY : Si tu veux nous affronter,\n"
	.string "ramène plus de POKéMON !$"

Route107_Text_CamronIntro:
	.string "Je suis en plein triathlon,\n"
	.string "mais je ne suis pas du tout fatigué !$"

Route107_Text_CamronDefeated:
	.string "Ça m'a épuisé…$"

Route107_Text_CamronPostBattle:
	.string "Il me reste encore la natation et la course\n"
	.string "après ça.\p"
	.string "Est-ce que je vais tenir le coup ?$"

Route108_Text_JeromeIntro:
	.string "Mon rêve, c'est de nager sur les sept mers\n"
	.string "du monde !$"

Route108_Text_JeromeDefeated:
	.string "Je ne pourrai pas nager sur les sept mers\n"
	.string "comme ça…$"

Route108_Text_JeromePostBattle:
	.string "Jouer avec les POKéMON marins, c'est un des\n"
	.string "plaisirs de la natation !$"

Route108_Text_MatthewIntro:
	.string "Ohé, toi ! Tu vas aussi sur le\n"
	.string "BATEAU ABANDONNÉ ?$"

Route108_Text_MatthewDefeated:
	.string "Je coule !\n"
	.string "Glou… Glou…$"

Route108_Text_MatthewPostBattle:
	.string "Certains vont même à l'intérieur de ce\n"
	.string "BATEAU ABANDONNÉ.$"

Route108_Text_TaraIntro:
	.string "Mon copain menteur m'a dit que\n"
	.string "je suis superbe en bikini…$"

Route108_Text_TaraDefeated:
	.string "Oh, zut !$"

Route108_Text_TaraPostBattle:
	.string "Même si c'est un mensonge, j'adore\n"
	.string "qu'on me dise que je suis belle…\l"
	.string "Nous, les filles, sommes si compliquées…$"

Route108_Text_MissyIntro:
	.string "J'adore la mer !\n"
	.string "J'oublie tous mes soucis en nageant !$"

Route108_Text_MissyDefeated:
	.string "Quand je perds un combat, je deviens\n"
	.string "toute stressée !$"

Route108_Text_MissyPostBattle:
	.string "Évacue ton stress en nageant !\n"
	.string "C'est tellement sain !$"

Route108_Text_CoryIntro:
	.string "J'adore les POKéMON de type EAU.\n"
	.string "J'aime aussi les autres POKéMON !$"

Route108_Text_CoryDefeated:
	.string "Ouin ! J'ai perdu !\n"
	.string "Ouin ! Ouin !$"

Route108_Text_CoryPostBattle:
	.string "Crier me fait du bien !\n"
	.string "Ça me remonte le moral !$"

Route108_Text_CoryRegister:
	.string "J'aime aussi les DRESSEURS forts !\n"
	.string "Enregistre-moi dans ton POKéNAV !$"

Route108_Text_CoryRematchIntro:
	.string "Gagner ou perdre, j'adore combattre en mer !$"

Route108_Text_CoryRematchDefeated:
	.string "Ouin ! J'ai encore perdu !\n"
	.string "Ouin ! Ouin !$"

Route108_Text_CoryRematchPostBattle:
	.string "Si tu fais face à un défi,\n"
	.string "essaie de crier à la mer !$"

Route108_Text_CarolinaIntro:
	.string "Je suis très fière de mes POKéMON.\n"
	.string "On va te montrer un combat rapide !$"

Route108_Text_CarolinaDefeated:
	.string "Ce n'était pas mignon du tout.$"

Route108_Text_CarolinaPostBattle:
	.string "Puisque je suis en mer comme ça, ça ne me\n"
	.string "dérangerait pas de mettre un maillot rose à volants…$"

Route109_Text_DavidIntro:
	.string "Hiya ! Regarde mes abdos sculptés !\n"
	.string "C'est ça, être « cut » !$"

Route109_Text_DavidDefeated:
	.string "Aïe !\n"
	.string "Raté !$"

Route109_Text_DavidPostBattle:
	.string "Hiya !\p"
	.string "Mes abdos n'ont rien à voir avec les\n"
	.string "combats POKéMON !$"

Route109_Text_AliceIntro:
	.string "Es-tu bien protégé contre\n"
	.string "le soleil ?$"

Route109_Text_AliceDefeated:
	.string "Aïe, aïe, aïe !$"

Route109_Text_AlicePostBattle:
	.string "Les joues sont les plus exposées aux coups de soleil !$"

Route109_Text_HueyIntro:
	.string "J'ai jeté l'ancre dans des ports du monde entier,\n"
	.string "mais POIVRESSEL est le meilleur.$"

Route109_Text_HueyDefeated:
	.string "Tu es le meilleur !$"

Route109_Text_HueyPostBattle:
	.string "Dans le meilleur port, il y avait le meilleur\n"
	.string "DRESSEUR…$"

Route109_Text_EdmondIntro:
	.string "Buuuurp…\n"
	.string "Un combat ? Avec moi ?$"

Route109_Text_EdmondDefeated:
	.string "Burp… Ooooooohhhhhh…\n"
	.string "Buuuurp…$"

Route109_Text_EdmondPostBattle:
	.string "Je suis d'habitude plus fort que ça !\n"
	.string "Je suis juste malade comme un chien !\p"
	.string "Je suis MARIN, mais…$"

Route109_Text_RickyIntro:
	.string "J'ai soif… J'irais bien boire un SODA COOL\n"
	.string "à la MAISON DU BORD DE MER…$"

Route109_Text_RickyDefeated:
	.string "Gémissement…$"

Route109_Text_RickyPostBattle:
	.string "Je meurs de faim… Ma bouée ressemble\n"
	.string "à un énorme donut…$"

Route109_Text_RickyRegister:
	.string "Tu veux refaire un combat avec moi\n"
	.string "quand je n'aurai plus soif ?$"

Route109_Text_RickyRematchIntro:
	.string "J'ai faim, mais j'ai assez d'énergie\n"
	.string "pour un combat !$"

Route109_Text_RickyRematchDefeated:
	.string "J'ai perdu…\n"
	.string "C'est parce que j'ai faim…$"

Route109_Text_RickyRematchPostBattle:
	.string "Quand tu manges à la plage, tout\n"
	.string "semble meilleur !$"

Route109_Text_LolaIntro:
	.string "Un parasol de plage, ça ne ressemble pas\n"
	.string "à une énorme fleur ?$"

Route109_Text_LolaDefeated:
	.string "Maman !$"

Route109_Text_LolaPostBattle:
	.string "Si tu regardes la plage du ciel,\n"
	.string "ça ressemble à un grand jardin de fleurs !$"

Route109_Text_LolaRegister:
	.string "Moi ?\n"
	.string "Je suis là tous les jours !$"

Route109_Text_LolaRematchIntro:
	.string "Je ne vais pas encore perdre contre toi !\n"
	.string "C'est pour ça que j'ai ma bouée !$"

Route109_Text_LolaRematchDefeated:
	.string "Maman !$"

Route109_Text_LolaRematchPostBattle:
	.string "Si j'ai une bouée, la mignonnerie de moi\n"
	.string "et de mon POKéMON monte en flèche !$"

Route109_Text_AustinaIntro:
	.string "Je ne peux pas nager sans ma bouée,\n"
	.string "mais je ne perdrai pas en POKéMON !$"

Route109_Text_AustinaDefeated:
	.string "J'ai perdu à cause de ma bouée ?$"

Route109_Text_AustinaPostBattle:
	.string "Ma bouée est un accessoire de mode.\n"
	.string "Je ne peux pas me montrer sans !$"

Route109_Text_GwenIntro:
	.string "Salut, grand DRESSEUR.\n"
	.string "Tu veux te battre avec moi ?$"

Route109_Text_GwenDefeated:
	.string "Oh, tu es fort.$"

Route109_Text_GwenPostBattle:
	.string "Comment tu es devenu si fort ?$"

Route109_Text_CarterIntro:
	.string "Wahahah ! Ce gars va attraper\n"
	.string "un gros poisson !$"

Route109_Text_CarterDefeated:
	.string "Ce gars vient d'en perdre un…$"

Route109_Text_CarterPostBattle:
	.string "Ce gars pense que tu es un gros poisson.\n"
	.string "Non, tu es un futur gros poisson !$"

Route109_Text_PaulIntro:
	.string "PAUL : Eh bien, ça casse l'ambiance.\p"
	.string "J'aimerais que tu ne déranges pas\n"
	.string "notre moment précieux à deux.$"

Route109_Text_PaulDefeated:
	.string "PAUL : Bon, j'abandonne.$"

Route109_Text_PaulPostBattle:
	.string "PAUL : Surtout, ne dis à personne qu'on\n"
	.string "est ici.\l"
	.string "C'est notre petit monde à deux !$"

Route109_Text_PaulNotEnoughPokemon:
	.string "PAUL : On est totalement, profondément amoureux.\n"
	.string "C'est pour ça qu'on fait combattre nos POKéMON\l"
	.string "ensemble.$"

Route109_Text_MelIntro:
	.string "MEL : On est, genre, trop amoureux.\n"
	.string "Notre romance enflamme tout HOENN !$"

Route109_Text_MelDefeated:
	.string "MEL : On a perdu, et c'est ma faute !\n"
	.string "PAUL va me détester !$"

Route109_Text_MelPostBattle:
	.string "MEL : Euh, PAUL, tu es fâché contre moi ?\n"
	.string "S'il te plaît, ne sois pas fâché.$"

Route109_Text_MelNotEnoughPokemon:
	.string "MEL : On est, genre, vraiment et profondément amoureux.\n"
	.string "C'est pour ça qu'on fait combattre nos POKéMON\l"
	.string "ensemble.$"

Route109_Text_ChandlerIntro:
	.string "Tadaaa ! Tu vois ?\n"
	.string "Ma bouée est ronde !$"

Route109_Text_ChandlerDefeated:
	.string "Oh, oh !\n"
	.string "Dommage !$"

Route109_Text_ChandlerPostBattle:
	.string "Après t'avoir montré ma bouée ronde, en plus…$"

Route109_Text_HaileyIntro:
	.string "Je ne sais pas nager, alors je fais\n"
	.string "semblant de nager.$"

Route109_Text_HaileyDefeated:
	.string "Je m'en doutais !\n"
	.string "Je ne pensais pas qu'on pouvait gagner.$"

Route109_Text_HaileyPostBattle:
	.string "Quand j'apprendrai à nager, je pense\n"
	.string "que mon POKéMON deviendra plus fort.$"

Route109_Text_ElijahIntro:
	.string "Pour un gars aussi macho que moi, ce genre\n"
	.string "de POKéMON est le partenaire idéal !$"

Route109_Text_ElijahDefeated:
	.string "Je reste cool même en perdant, hein ?$"

Route109_Text_ElijahPostBattle:
	.string "Pour un gars aussi macho que moi, un port\n"
	.string "est l'endroit parfait !\p"
	.string "Je pense que je vais aller à POIVRESSEL.$"

Route110_Text_JacobIntro:
	.string "Ouh là ! Fais attention !\n"
	.string "Tu n'as pas l'habitude des courses à vélo, hein ?$"

Route110_Text_JacobDefeated:
	.string "Ouh là !\n"
	.string "Mes freins ont lâché !$"

Route110_Text_JacobPostBattle:
	.string "Un pneu crevé ou des freins défectueux\n"
	.string "peuvent causer de graves blessures !\l"
	.string "Vérifie bien ton VÉLO !$"

Route110_Text_AnthonyIntro:
	.string "Hé, toi !\n"
	.string "Tu peux suivre ma vitesse ?$"

Route110_Text_AnthonyDefeated:
	.string "Accident et défaite !$"

Route110_Text_AnthonyPostBattle:
	.string "La vitesse seule ne suffit pas pour gagner aux POKéMON.\n"
	.string "Je dois revoir ma stratégie…$"

Route110_Text_BenjaminIntro:
	.string "Ne panique pas si ton VÉLO va vite !$"

Route110_Text_BenjaminDefeated:
	.string "Je ne devrais pas paniquer pendant les\n"
	.string "combats de POKéMON…$"

Route110_Text_BenjaminPostBattle:
	.string "Il ne faut pas paniquer ou stresser.\n"
	.string "Reste cool. On a tout le temps.$"

Route110_Text_BenjaminRegister:
	.string "Je continue sans stresser.\n"
	.string "Fais-moi signe si tu veux !$"

Route110_Text_BenjaminRematchIntro:
	.string "Tu ne vas pas un peu trop vite ?\n"
	.string "Ralentis et combattons.$"

Route110_Text_BenjaminRematchDefeated:
	.string "Je n'ai pas paniqué, mais j'ai quand même perdu…$"

Route110_Text_BenjaminRematchPostBattle:
	.string "Il ne faut pas paniquer ou stresser.\n"
	.string "Reste cool. On a tout le temps.$"

Route110_Text_AbigailIntro:
	.string "Le triathlon, c'est super dur !\p"
	.string "Il faut finir les trois épreuves :\n"
	.string "natation, cyclisme et course à pied.$"

Route110_Text_AbigailDefeated:
	.string "Les combats de POKéMON sont durs aussi !$"

Route110_Text_AbigailPostBattle:
	.string "Je suis épuisée, il me faut une pause.\n"
	.string "C'est important de bien se reposer.$"

Route110_Text_AbigailRegister:
	.string "Tu sais, je t'aime bien !\n"
	.string "On fait une revanche sur la ROUTE CYCLABLE ?$"

Route110_Text_AbigailRematchIntro:
	.string "C'est pas génial de combattre tout en\n"
	.string "faisant du vélo ?$"

Route110_Text_AbigailRematchDefeated:
	.string "Ouah…\n"
	.string "Comment tu peux être aussi fort(e) ?$"

Route110_Text_AbigailRematchPostBattle:
	.string "Tu visais un record ?\p"
	.string "Désolée si je t'ai ralenti(e) !$"

Route110_Text_JasmineIntro:
	.string "Je roule sans m'arrêter.\n"
	.string "Mes cuisses sont en béton !$"

Route110_Text_JasmineDefeated:
	.string "J'ai peur d'avoir des crampes…$"

Route110_Text_JasminePostBattle:
	.string "Oh, tu as des BADGES d'ARÈNE ?\n"
	.string "Pas étonnant que tu sois si fort(e) !$"

Route110_Text_EdwardIntro:
	.string "J'ai prévu tes intentions !\n"
	.string "Je ne peux pas perdre !$"

Route110_Text_EdwardDefeated:
	.string "Je n'ai pas su prédire ma propre défaite !$"

Route110_Text_EdwardPostBattle:
	.string "Je vois ton avenir…\p"
	.string "Hmm…\n"
	.string "Je vois une lumière éclatante…$"

Route110_Text_JaclynIntro:
	.string "Ahahahaha !\n"
	.string "Je vais t'éblouir avec mes merveilles !$"

Route110_Text_JaclynDefeated:
	.string "J'ai perdu de façon merveilleuse !$"

Route110_Text_JaclynPostBattle:
	.string "Tu n'as gagné que par miracle ! Oui, un miracle !\l"
	.string "Ne crois pas que tu gagneras à chaque fois !$"

Route110_Text_EdwinIntro:
	.string "Je peux voir tes POKéMON ?\n"
	.string "Juste un coup d'œil, s'il te plaît !$"

Route110_Text_EdwinDefeated:
	.string "Je voulais compléter\n"
	.string "ma collection…$"

Route110_Text_EdwinPostBattle:
	.string "Quand je vois un POKéMON que je ne connais pas,\n"
	.string "ma passion de collectionneur s'enflamme !$"

Route110_Text_EdwinRegister:
	.string "J'aime aussi collectionner les enregistrements\n"
	.string "dans le MATCH CALL…$"

Route110_Text_EdwinRematchIntro:
	.string "Salut, tu as attrapé de nouveaux POKéMON ?\p"
	.string "Je peux voir tes POKéMON ?\n"
	.string "Juste un coup d'œil, s'il te plaît !$"

Route110_Text_EdwinRematchDefeated:
	.string "Tes POKéMON…\n"
	.string "Je t'envie.$"

Route110_Text_EdwinRematchPostBattle:
	.string "Oh, j'aimerais tant que tous les POKéMON rares\n"
	.string "soient à moi !$"

Route110_Text_DaleIntro:
	.string "Hé !\n"
	.string "Ne m'approche pas par derrière comme ça !$"

Route110_Text_DaleDefeated:
	.string "J'ai perdu !\n"
	.string "Zut !$"

Route110_Text_DalePostBattle:
	.string "La pêche, c'est une question de concentration.\n"
	.string "Il faut bien surveiller le flotteur.$"

Route110_Text_IsabelIntro:
	.string "Ahahaha ! J'irais n'importe où pour montrer\n"
	.string "mes adorables POKéMON !$"

Route110_Text_IsabelDefeated:
	.string "Oh, mince, ça ne va pas du tout.$"

Route110_Text_IsabelPostBattle:
	.string "Plutôt que de combattre, je devrais peut-être\n"
	.string "montrer mes POKéMON au FAN CLUB.$"

Route110_Text_IsabelRegister:
	.string "Ce n'était pas suffisant pour montrer\n"
	.string "mes POKéMON.\p"
	.string "Je te veux comme public captif\n"
	.string "aussi souvent que possible !$"

Route110_Text_IsabelRematchIntro:
	.string "Ahahaha ! Je serais ravie de montrer\n"
	.string "mes POKéMON aussi souvent que tu veux !$"

Route110_Text_IsabelRematchDefeated:
	.string "Oh, mince, ça ne va pas du tout.$"

Route110_Text_IsabelRematchPostBattle:
	.string "Je ne pense pas pouvoir m'arrêter\n"
	.string "de montrer mes POKéMON.\p"
	.string "Mais j'aime aussi combattre !$"

Route110_Text_TimmyIntro:
	.string "J'ai trouvé des POKéMON trop cool dans l'herbe\n"
	.string "par ici !$"

Route110_Text_TimmyDefeated:
	.string "Être cool ne suffit pas pour gagner…$"

Route110_Text_TimmyPostBattle:
	.string "C'est dur de combattre avec des POKéMON\n"
	.string "qu'on vient d'attraper.$"

Route110_Text_AlyssaIntro:
	.string "Je suis tombée de la ROUTE CYCLABLE…\p"
	.string "Je vais oublier ma honte en\n"
	.string "combattant contre toi !$"

Route110_Text_AlyssaDefeated:
	.string "Oups !\n"
	.string "J'ai fini par perdre !$"

Route110_Text_AlyssaPostBattle:
	.string "Tomber… Perdre…\n"
	.string "C'est tellement humiliant !$"

Route110_Text_JosephIntro:
	.string "OK ! À fond la caisse ! Si tu ne suis pas\n"
	.string "le rythme, tu restes derrière !$"

Route110_Text_JosephDefeated:
	.string "Tu as bien trouvé le rythme…$"

Route110_Text_JosephPostBattle:
	.string "Ça ne va pas me décourager !\n"
	.string "Perdre m'a rendu meilleur !$"

Route110_Text_KalebIntro:
	.string "Quand des POKéMON mignons s'entraident…\n"
	.string "On ne voit rien de plus adorable !$"

Route110_Text_KalebDefeated:
	.string "Tu n'as donc aucune compassion ?$"

Route110_Text_KalebPostBattle:
	.string "Bon, bon, tu as fait de ton mieux,\n"
	.string "mes petits chéris.$"

Route111_Text_DrewIntro:
	.string "Oh, hé ! Ces LUNETTES SABLE te vont bien.\n"
	.string "Mais je pense qu'elles me vont mieux.\p"
	.string "Décidons à qui elles vont le mieux\n"
	.string "avec un combat !$"

Route111_Text_DrewDefeat:
	.string "Je ne voyais pas ce qui se passait sur les côtés\n"
	.string "à cause des LUNETTES SABLE.$"

Route111_Text_DrewPostBattle:
	.string "Les LUNETTES SABLE permettent de traverser\n"
	.string "les tempêtes de sable.\l"
	.string "Ça me rend heureux !$"

Route111_Text_HeidiIntro:
	.string "Je pique-nique dans le désert.\p"
	.string "On trouve toujours un DRESSEUR,\n"
	.string "alors je peux aussi profiter d'un combat !$"

Route111_Text_HeidiDefeat:
	.string "Ohhh ! Tu es méchant(e) !$"

Route111_Text_HeidiPostBattle:
	.string "Quand tu combats dans une tempête de sable,\n"
	.string "fais attention aux PV de tes POKéMON.\p"
	.string "Ils peuvent s'évanouir si tu ne fais\n"
	.string "pas attention !$"

Route111_Text_BeauIntro:
	.string "Avec ces LUNETTES SABLE, je me sens\n"
	.string "comme un super-héros.\l"
	.string "Personne ne peut me battre maintenant !$"

Route111_Text_BeauDefeat:
	.string "L'esprit ne suffit pas pour gagner…$"

Route111_Text_BeauPostBattle:
	.string "Je deviendrai un vrai héros un jour.\n"
	.string "Je vais travailler dur pour devenir plus fort\l"
	.string "avec mes POKéMON.$"

Route111_Text_BeckyIntro:
	.string "J'ai entendu dire qu'il y a des fossiles\n"
	.string "dans le désert. Où sont-ils ?$"

Route111_Text_BeckyDefeat:
	.string "J'ai échoué…$"

Route111_Text_BeckyPostBattle:
	.string "S'ils trouvent des fossiles dans le désert,\n"
	.string "c'était sûrement une mer avant.$"

Route111_Text_DustyIntro:
	.string "Depuis trente ans, je cherche des\n"
	.string "ruines anciennes !\l"
	.string "Tu veux me défier ?$"

Route111_Text_DustyDefeat:
	.string "J'ai cherché des ruines, mais pas\n"
	.string "de POKéMON puissants.$"

Route111_Text_DustyPostBattle:
	.string "Depuis trente ans, je cherche des ruines !\p"
	.string "Non, attends, c'était quarante ans ?\n"
	.string "Je ne sais plus…$"

Route111_Text_DustyRegister:
	.string "Je ne cherche pas de POKéMON puissants.\p"
	.string "Mais, pour une raison inconnue, j'adore\n"
	.string "les POKéNAV.$"

Route111_Text_DustyRematchIntro:
	.string "Depuis trente ans, je cherche des ruines !\p"
	.string "Non, attends, c'était quarante ans ?\n"
	.string "Enfin, tu veux me défier ?$"

Route111_Text_DustyRematchDefeat:
	.string "Je n'ai trouvé ni ruines, ni POKéMON puissants…$"

Route111_Text_DustyPostRematch:
	.string "Depuis trente ans, je cherche des ruines !\p"
	.string "Non, attends, c'était quarante ans\n"
	.string "que je cherche ?\p"
	.string "Hmm… Peut-être même cinquante…\n"
	.string "Depuis combien de temps je fais ça ?$"

Route111_Text_TravisIntro:
	.string "Je suis plein d'énergie !\n"
	.string "Et mon POKéMON aussi !$"

Route111_Text_TravisDefeat:
	.string "Mon POKéMON a perdu son énergie…$"

Route111_Text_TravisPostBattle:
	.string "Quand je vois un DRESSEUR plein d'énergie,\n"
	.string "je ne peux pas m'empêcher de regarder.$"

Route111_Text_IreneIntro:
	.string "Je ne sais pas où tu vas,\n"
	.string "mais tu veux te battre ?$"

Route111_Text_IreneDefeat:
	.string "Oh, tu es incroyablement fort(e) !$"

Route111_Text_IrenePostBattle:
	.string "Je pense aller au MONT CHIMNÉE, mais la vue\n"
	.string "ici est très belle aussi.$"

Route111_Text_DaisukeIntro:
	.string "Pour m'entraîner, je défie tous ceux\n"
	.string "que je croise !$"

Route111_Text_DaisukeDefeat:
	.string "Pitié ! J'abandonne !$"

Route111_Text_DaisukePostBattle:
	.string "Tout ce que je peux faire, c'est m'entraîner\n"
	.string "jusqu'à pouvoir battre des DRESSEURS forts\l"
	.string "comme toi.$"

Route111_Text_WiltonIntro:
	.string "Montre-moi à quel point tu as renforcé\n"
	.string "tes POKéMON.$"

Route111_Text_WiltonDefeat:
	.string "Je vois, tu les as bien renforcés.$"

Route111_Text_WiltonPostBattle:
	.string "Les POKéMON et les DRESSEURS apprennent beaucoup\n"
	.string "en combattant.\p"
	.string "Le plus important, c'est de ne jamais abandonner\n"
	.string "même en cas de défaite.$"

Route111_Text_WiltonRegister:
	.string "On peut apprendre beaucoup de ta façon\n"
	.string "de t'entraîner.\p"
	.string "Je demande une revanche si tu\n"
	.string "es d'accord.$"

Route111_Text_WiltonRematchIntro:
	.string "On s'entraîne ici pour passer au niveau\n"
	.string "supérieur.\l"
	.string "Reste et entraîne-toi avec nous !$"

Route111_Text_WiltonRematchDefeat:
	.string "Ooh, tu es doué(e) !$"

Route111_Text_WiltonPostRematch:
	.string "Vu ta force, tu devrais viser la LIGUE POKéMON !$"

Route111_Text_BrookeIntro:
	.string "Oh, tes POKéMON ont l'air d'acteurs sérieux.\l"
	.string "Je dois te demander un combat !$"

Route111_Text_BrookeDefeat:
	.string "Ils n'avaient pas seulement l'air forts,\n"
	.string "ils le sont vraiment !$"

Route111_Text_BrookePostBattle:
	.string "Je croyais bien élever mes POKéMON,\n"
	.string "mais il me reste encore du travail.$"

Route111_Text_BrookeRegister:
	.string "J'aimerais devenir amie avec plus de\n"
	.string "gens forts comme toi !$"

Route111_Text_BrookeRematchIntro:
	.string "On peut rendre les POKéMON plus forts ou\n"
	.string "plus faibles selon les capacités qu'on leur\l"
	.string "apprend.\p"
	.string "Quelles capacités connaissent tes POKéMON ?$"

Route111_Text_BrookeRematchDefeat:
	.string "Tu leur as appris de bonnes capacités !$"

Route111_Text_BrookePostRematch:
	.string "J'aurais peut-être dû empêcher mes POKéMON\n"
	.string "d'évoluer jusqu'à ce qu'ils apprennent\l"
	.string "de meilleures capacités…$"

Route111_Text_CeliaIntro:
	.string "Je n'aurais pas dû venir ici pour un pique-nique !$"

Route111_Text_CeliaDefeat:
	.string "Oh non !\n"
	.string "Je n'aurais vraiment pas dû venir !$"

Route111_Text_CeliaPostBattle:
	.string "Dans une tempête de sable comme ça, je ne peux\n"
	.string "même pas installer mon pique-nique avec mes\l"
	.string "LUNETTES SABLE…$"

Route111_Text_BryanIntro:
	.string "À quel point es-tu fort ?\n"
	.string "Nous allons le découvrir !$"

Route111_Text_BryanDefeat:
	.string "Oh ! Ta force !\n"
	.string "Elle est pleine de mystère !$"

Route111_Text_BryanPostBattle:
	.string "Ce désert cache des mystères dans\n"
	.string "ses sables mouvants !$"

Route111_Text_BrandenIntro:
	.string "Je te donne un bout de mon sandwich\n"
	.string "si tu perds.$"

Route111_Text_BrandenDefeat:
	.string "Tch ! Je croyais qu'un sandwich suffirait\n"
	.string "comme pot-de-vin…$"

Route111_Text_BrandenPostBattle:
	.string "Mon SABLETTE adore manger\n"
	.string "mes sandwichs.$"

Route111_Text_TyronIntro:
	.string "C'est mon type de POKéMON préféré !$"

Route111_Text_TyronDefeat:
	.string "Attends !\n"
	.string "Tu as bien regardé mon POKéMON ?$"

Route111_Text_TyronPostBattle:
	.string "En combat, j'adore montrer mon POKéMON.\p"
	.string "Je parie que tout le monde ressent ça\n"
	.string "en entrant dans un combat !$"

Route111_Text_CelinaIntro:
	.string "Montre-moi comment mettre un peu d'excitation\n"
	.string "dans ma vie.$"

Route111_Text_CelinaDefeat:
	.string "Oh… Mon…\n"
	.string "C'était trop d'émotions !$"

Route111_Text_CelinaPostBattle:
	.string "Mon cœur bat encore la chamade.\n"
	.string "Tu es un(e) DRESSEUR fabuleux(se).$"

Route111_Text_HaydenIntro:
	.string "Quand on a aussi faim que moi,\n"
	.string "il n'y a pas de place pour la pitié !$"

Route111_Text_HaydenDefeat:
	.string "Grrr…$"

Route111_Text_HaydenPostBattle:
	.string "Mon ventre gargouille !\n"
	.string "Je vais peut-être griller des BAIES…$"

Route111_Text_BiancaIntro:
	.string "Tu viens de LAVANDIA ?\n"
	.string "Alors tu dois être plein(e) d'énergie !$"

Route111_Text_BiancaDefeat:
	.string "Ouh là là !\n"
	.string "C'est beaucoup à encaisser !$"

Route111_Text_BiancaPostBattle:
	.string "Cette route…\n"
	.string "Il te reste encore du chemin à faire.$"

Route112_Text_BriceIntro:
	.string "Hahahaha !\n"
	.string "On fait un combat ?\l"
	.string "Toi et moi !\l"
	.string "Hahahaha !$"

Route112_Text_BriceDefeat:
	.string "J'ai perdu !\n"
	.string "Hahahaha !$"

Route112_Text_BricePostBattle:
	.string "Hahahahaha ! Quelque chose m'est monté au nez !\n"
	.string "Hahahaha-atchoum !$"

Route112_Text_TrentIntro:
	.string "Mes jambes sont solides à force de monter\n"
	.string "et descendre la montagne.\p"
	.string "Elles ne vont pas flancher facilement,\n"
	.string "mon ami !$"

Route112_Text_TrentDefeat:
	.string "Aïe ! J'ai une crampe à la jambe !$"

Route112_Text_TrentPostBattle:
	.string "Essaie la randonnée, et je parle de la vraie,\n"
	.string "sur ces sentiers de montagne\l"
	.string "avec un sac lourd de plusieurs kilos.\p"
	.string "Ça, mon ami, ça forge le corps !$"

Route112_Text_TrentRegister:
	.string "Aïe, mes jambes sont en crampe.\n"
	.string "Tu peux me passer des bandages dans\l"
	.string "mon sac à dos ?\p"
	.string "Non, ça c'est mon POKéNAV !\n"
	.string "Bon, je t'enregistre alors.$"

Route112_Text_TrentRematchIntro:
	.string "Je reste en forme grâce à la randonnée.\n"
	.string "La force, j'en ai à revendre !$"

Route112_Text_TrentRematchDefeat:
	.string "On m'a battu sur la force ?$"

Route112_Text_TrentRematchPostBattle:
	.string "J'ai entendu dire qu'il y a des DRESSEURS\n"
	.string "très forts au sommet du MONT CHIMNÉE.\p"
	.string "Je compte bien y aller pour les défier !$"

Route112_Text_LarryIntro:
	.string "Je suis fort.\n"
	.string "Je ne pleurerai pas si je perds.$"

Route112_Text_LarryDefeat:
	.string "Ouin ! $"

Route112_Text_LarryPostBattle:
	.string "Je ne pleure pas parce que ma maman me manque !\n"
	.string "Snif…$"

Route112_Text_CarolIntro:
	.string "Quand on pique-nique, il faut chanter !\l"
	.string "Allez, chante avec moi !$"

Route112_Text_CarolDefeat:
	.string "Oh, tu es trop fort(e) !$"

Route112_Text_CarolPostBattle:
	.string "Peu importe si tu chantes ou combats bien ou mal.\p"
	.string "Si tu t'amuses le plus, tu as gagné !$"

Route112_Text_BryantIntro:
	.string "J'ai attrapé des POKéMON brûlants dans la VOIE ARDENTE !\n"
	.string "Regarde !$"

Route112_Text_BryantDefeat:
	.string "Quel parcours mouvementé !$"

Route112_Text_BryantPostBattle:
	.string "J'aime ta façon de combattre.\n"
	.string "Il y a un certain style !$"

Route112_Text_ShaylaIntro:
	.string "Oh, tu es un(e) DRESSEUR adorable !\n"
	.string "S'il te plaît, je veux un combat romantique !\l"
	.string "Je suis plutôt douée !$"

Route112_Text_ShaylaDefeat:
	.string "Oh, comme tu es fort(e) !\n"
	.string "Tu m'as vraiment surprise !$"

Route112_Text_ShaylaPostBattle:
	.string "Tu es occupé(e) ?\n"
	.string "Je pensais qu'on pourrait refaire un combat\l"
	.string "tout de suite…\l"
	.string "Mais ce n'est pas grave si tu es pris(e).$"

Route113_Text_JaylenIntro:
	.string "Tu devines pourquoi il fait si frais\n"
	.string "par ici ?$"

Route113_Text_JaylenDefeat:
	.string "Pouah !\n"
	.string "Ça pue !$"

Route113_Text_JaylenPostBattle:
	.string "La cendre volcanique bloque le soleil,\n"
	.string "alors il ne fait pas très chaud.\p"
	.string "Tant mieux, je ne supporte pas la chaleur !$"

Route113_Text_DillonIntro:
	.string "L'éruption du volcan prouve que\n"
	.string "la terre est vivante.$"

Route113_Text_DillonDefeat:
	.string "Tu es vraiment fort(e) !$"

Route113_Text_DillonPostBattle:
	.string "Aïe ! Ouille ! Je ne vois plus rien !\n"
	.string "J'ai de la cendre dans les cils !\p"
	.string "Tu saisis ? Cendre et cils ?\p"
	.string "OK, c'était nul, désolé(e)…$"

Route113_Text_MadelineIntro:
	.string "J'utilise ce parasol pour protéger mon\n"
	.string "cher CHAMALOT de cette vilaine cendre volcanique.$"

Route113_Text_MadelineDefeat:
	.string "Ouf, ouf…\n"
	.string "Je suis épuisée…$"

Route113_Text_MadelinePostBattle:
	.string "Tu es très doué(e) pour ça.\n"
	.string "Je dois dire que je suis impressionnée !$"

Route113_Text_MadelineRegister:
	.string "Viens sous mon parasol.\n"
	.string "Je t'enregistre dans mon POKéNAV.$"

Route113_Text_MadelineRematchIntro:
	.string "Oh, bonjour, ça fait longtemps !\n"
	.string "Puis-je t'inviter à un combat ?$"

Route113_Text_MadelineRematchDefeat:
	.string "Oh, super !$"

Route113_Text_MadelinePostRematch:
	.string "Tu es toujours aussi doué(e) pour ça.\n"
	.string "Je dois dire que je suis impressionnée !$"

Route113_Text_LaoIntro:
	.string "Je surgis des cendres ! Hiyah !\n"
	.string "Je te défie !$"

Route113_Text_LaoDefeat:
	.string "J'admets ma défaite avec honneur !$"

Route113_Text_LaoPostBattle:
	.string "Je dois perfectionner l'art du camouflage.\n"
	.string "Je te dis adieu.$"

Route113_Text_LaoRegister:
	.string "Yiiyaah ! Observe l'ancienne technique ninja\n"
	.string "d'enregistrement sur le POKéNAV !$"

Route113_Text_LaoRematchIntro:
	.string "Je surgis des cendres ! Hiyah !\n"
	.string "Je te défie !$"

Route113_Text_LaoRematchDefeat:
	.string "J'admets ma défaite avec honneur !$"

Route113_Text_LaoPostRematch:
	.string "Mon camouflage parfait a été trahi par\n"
	.string "mon manque de talent en combat…\p"
	.string "Je te dis adieu.$"

Route113_Text_LungIntro:
	.string "Merci de m'avoir trouvé !\n"
	.string "Mais il faut quand même combattre !$"

Route113_Text_LungDefeat:
	.string "Je vais utiliser mon ninjutsu…\n"
	.string "« MANTEAU DE CENDRES VOLCANIQUES » !\p"
	.string "…Quoi ?\n"
	.string "C'est déjà fini ?$"

Route113_Text_LungPostBattle:
	.string "Tu sais ce qui est nul dans la cachette ?\n"
	.string "C'est que c'est triste si personne ne vient.$"

Route113_Text_ToriIntro:
	.string "TORI : Nous, on ramasse de la cendre.\n"
	.string "On combat aussi les POKéMON.$"

Route113_Text_ToriDefeat:
	.string "TORI : On a perdu… C'est nul, je vais\n"
	.string "ramasser plus de cendre.$"

Route113_Text_ToriPostBattle:
	.string "TORI : On a combien de cendre ?\n"
	.string "Assez pour une FLÛTE BLANCHE, j'espère.$"

Route113_Text_ToriNotEnoughMons:
	.string "TORI : On veut faire un combat à deux.\n"
	.string "Sinon, on perdrait !$"

Route113_Text_TiaIntro:
	.string "TIA : Nous, on ramasse de la cendre.\n"
	.string "On combat aussi les POKéMON.$"

Route113_Text_TiaDefeat:
	.string "TIA : On n'a pas pu gagner… C'est nul,\n"
	.string "je vais ramasser plus de cendre.$"

Route113_Text_TiaPostBattle:
	.string "TIA : On a plein de cendre !\n"
	.string "Je crois qu'on en a assez pour une FLÛTE BLANCHE !$"

Route113_Text_TiaNotEnoughMons:
	.string "TIA : On veut faire un combat à deux.\n"
	.string "Sinon, on ne gagnera pas !$"

Route113_Text_CobyIntro:
	.string "Pff, avec ces ailes je peux\n"
	.string "t'envoyer valser !$"

Route113_Text_CobyDefeat:
	.string "Hein… Quoi ?$"

Route113_Text_CobyPostBattle:
	.string "Je ne sais pas quoi dire quand je me fais\n"
	.string "battre aussi facilement…$"

Route113_Text_SophieIntro:
	.string "La chaleur ici me donne envie de dormir.\n"
	.string "Combats-moi pour que je reste éveillée !$"

Route113_Text_SophieDefeat:
	.string "C'est un rêve.\n"
	.string "J'en suis sûre…$"

Route113_Text_SophiePostBattle:
	.string "Perdre me donne chaud…\n"
	.string "Je vais dormir ici !\l"
	.string "Zzz !$"

Route113_Text_LawrenceIntro:
	.string "Tu étais en train de ramasser\n"
	.string "de la cendre volcanique ?$"

Route113_Text_LawrenceDefeat:
	.string "Ehehe.\n"
	.string "On s'est fait battre facilement.$"

Route113_Text_LawrencePostBattle:
	.string "Je devrais me cacher sous la cendre, moi aussi.$"

Route113_Text_WyattIntro:
	.string "T-tu veux te battre avec moi ?\n"
	.string "Alors que je viens juste d'attraper mon POKéMON ?$"

Route113_Text_WyattDefeat:
	.string "T-tu es content(e) de gagner ?\n"
	.string "Alors que c'est juste moi ?$"

Route113_Text_WyattPostBattle:
	.string "Ah, maintenant tu veux dire un mot au\n"
	.string "perdant ?\p"
	.string "Tu te crois trop cool, hein ?\n"
	.string "Pff !$"

Route114_Text_LennyIntro:
	.string "Yodelayhihoo !\p"
	.string "… …\p"
	.string "Tu dois crier « yodelayhihoo » car ici,\n"
	.string "ça ne résonne pas ! $"

Route114_Text_LennyDefeat:
	.string "Yodelayhihoo !$"

Route114_Text_LennyPostBattle:
	.string "Quand j'étais petit, je croyais qu'il y avait\n"
	.string "quelqu'un qui me répondait « Yodelayhihoo ».$"

Route114_Text_LucasIntro:
	.string "Si tu n'es pas prêt(e), tu ne devrais pas\n"
	.string "être en montagne !$"

Route114_Text_LucasDefeat:
	.string "La montagne ne pardonne pas…$"

Route114_Text_LucasPostBattle:
	.string "En hiver, la montagne devient mortelle\n"
	.string "avec les tempêtes de neige et les avalanches.$"

Route114_Text_ShaneIntro:
	.string "Le camping, c'est génial ! On peut pêcher,\n"
	.string "griller des marshmallows et raconter des histoires !\p"
	.string "Mais le mieux, ce sont les combats de POKéMON !$"

Route114_Text_ShaneDefeat:
	.string "Bien trop fort(e) !$"

Route114_Text_ShanePostBattle:
	.string "J'adore pouvoir camper avec mes POKéMON.$"

Route114_Text_NancyIntro:
	.string "Il faut faire de l'exercice après manger.\n"
	.string "On fait un combat !$"

Route114_Text_NancyDefeat:
	.string "Oh, non !$"

Route114_Text_NancyPostBattle:
	.string "Je viens de bien manger.\n"
	.string "Je commence à avoir sommeil…$"

Route114_Text_SteveIntro:
	.string "Ufufufufufu…\n"
	.string "Tu veux affronter mes POKéMON ?$"

Route114_Text_SteveDefeat:
	.string "M-Mes POKéMON…$"

Route114_Text_StevePostBattle:
	.string "Un grand corps tout bosselé et dur,\n"
	.string "d'énormes cornes, des crocs féroces…\p"
	.string "Ufufufufu…\n"
	.string "J'aimerais avoir un POKéMON comme ça…$"

Route114_Text_SteveRegister:
	.string "N'oublie pas ce que tu m'as fait !\n"
	.string "Je ferai en sorte que tu ne l'oublies pas !$"

Route114_Text_SteveRematchIntro:
	.string "Ufufufufufu…\n"
	.string "Allez, combats mes POKéMON…$"

Route114_Text_SteveRematchDefeat:
	.string "Je me sens chanceux(se) de voir tes\n"
	.string "POKéMON…$"

Route114_Text_StevePostRematch:
	.string "Ufufufufufu…\p"
	.string "Quand je vois des POKéMON combattre, j'en ai\n"
	.string "des frissons…$"

Route114_Text_BernieIntro:
	.string "Si tu fais un feu de camp,\n"
	.string "assure-toi d'avoir de l'eau à portée de main.$"

Route114_Text_BernieDefeat:
	.string "Merci d'avoir éteint mon feu !$"

Route114_Text_BerniePostBattle:
	.string "Il faut vraiment faire attention avec\n"
	.string "le feu en forêt.\p"
	.string "Ne sous-estime jamais la puissance\n"
	.string "du feu.$"

Route114_Text_BernieRegister:
	.string "Tu as enflammé mon esprit.\n"
	.string "On s'enregistre mutuellement !$"

Route114_Text_BernieRematchIntro:
	.string "Tu as appris à garder de l'eau à portée\n"
	.string "pour les feux de camp ?$"

Route114_Text_BernieRematchDefeat:
	.string "On m'a éteint avant que je puisse\n"
	.string "m'enflammer, je suppose.$"

Route114_Text_BerniePostRematch:
	.string "Il faut vraiment faire attention avec\n"
	.string "le feu en forêt.\p"
	.string "Ne sous-estime jamais la puissance\n"
	.string "du feu.$"

Route114_Text_ClaudeIntro:
	.string "Si on pêchait, tu n'aurais aucune chance\n"
	.string "contre moi.\l"
	.string "Alors, montre tes POKéMON !$"

Route114_Text_ClaudeDefeat:
	.string "Si on pêchait, j'aurais gagné…$"

Route114_Text_ClaudePostBattle:
	.string "Je vais tenter ma chance pour attraper\n"
	.string "un gros poisson à la CHUTE-MÉTÉORE.\p"
	.string "Il doit y avoir quelque chose là-bas.\n"
	.string "J'en suis sûr(e).$"

Route114_Text_NolanIntro:
	.string "J'aime pêcher. Mais j'aime aussi\n"
	.string "combattre !\p"
	.string "Si on me défie, je réponds présent,\n"
	.string "même en pêchant.$"

Route114_Text_NolanDefeat:
	.string "J'aime combattre, mais ça ne veut pas dire\n"
	.string "que je suis doué(e)…$"

Route114_Text_NolanPostBattle:
	.string "Cette fois, je vais y arriver !\p"
	.string "Je me dis toujours ça, alors je ne peux pas\n"
	.string "abandonner la pêche ou les POKéMON.$"

Route114_Text_TyraIntro:
	.string "TYRA : Bien sûr.\n"
	.string "J'en ai envie.\l"
	.string "Je vais t'apprendre un peu sur les POKéMON !$"

Route114_Text_TyraDefeat:
	.string "TYRA : Quel style de combat incroyable !$"

Route114_Text_TyraPostBattle:
	.string "TYRA : J'apprenais à ma cadette IVY\n"
	.string "des choses sur les POKéMON.$"

Route114_Text_TyraNotEnoughMons:
	.string "TYRA : Hihi…\n"
	.string "Si tu veux combattre avec nous, un seul\l"
	.string "POKéMON ne suffit pas !$"

Route114_Text_IvyIntro:
	.string "IVY : Qui t'a appris les POKéMON ?$"

Route114_Text_IvyDefeat:
	.string "IVY : Quel style de combat incroyable !$"

Route114_Text_IvyPostBattle:
	.string "IVY : J'ai commencé à entraîner des POKéMON\n"
	.string "parce que TYRA, ma mentor, m'a tout appris !$"

Route114_Text_IvyNotEnoughMons:
	.string "IVY : Tu n'as qu'un seul POKéMON ?\n"
	.string "Ça doit être triste, non ?$"

Route114_Text_KaiIntro:
	.string "J'ai ferré un gros !\n"
	.string "Un énorme, je te dis !$"

Route114_Text_KaiDefeat:
	.string "Qu'est-ce que c'était ?\n"
	.string "Le mien était plus petit ?$"

Route114_Text_KaiPostBattle:
	.string "OK !\n"
	.string "Je vais pêcher un encore plus gros !$"

Route114_Text_CharlotteIntro:
	.string "Moi !\n"
	.string "Je ne suis pas qu'un joli visage !$"

Route114_Text_CharlotteDefeat:
	.string "Ce n'était pas mignon du tout !$"

Route114_Text_CharlottePostBattle:
	.string "Je ne veux pas d'un POKéMON juste mignon.\p"
	.string "J'adore ceux qui ont un petit truc en plus !$"

Route114_Text_AngelinaIntro:
	.string "Tu as fait beaucoup évoluer tes POKéMON ?$"

Route114_Text_AngelinaDefeat:
	.string "Oh, je vois.\n"
	.string "C'est bon à savoir.$"

Route114_Text_AngelinaPostBattle:
	.string "Certains POKéMON changent tellement en évoluant,\n"
	.string "c'est surprenant !$"

Route115_Text_TimothyIntro:
	.string "Hmm…\n"
	.string "Tu as l'air plutôt doué(e)…\l"
	.string "Laisse-moi te tenir compagnie !$"

Route115_Text_TimothyDefeat:
	.string "Tu es bien plus fort(e) que\n"
	.string "je ne l'imaginais !$"

Route115_Text_TimothyPostBattle:
	.string "Il n'existe pas de génie inné.\n"
	.string "Tout dépend de l'effort !\l"
	.string "C'est ce que je crois…$"

Route115_Text_TimothyRegister:
	.string "Hmm… Une défaite aussi nette, ça faisait\n"
	.string "longtemps.\p"
	.string "Si tu veux bien, j'aimerais avoir\n"
	.string "une autre chance de combattre.$"

Route115_Text_TimothyRematchIntro:
	.string "Hmm… Comme toujours, ton agilité parle\n"
	.string "d'elle-même.\l"
	.string "Viens, tiens-moi compagnie !$"

Route115_Text_TimothyRematchDefeat:
	.string "Toujours aussi fort(e) !$"

Route115_Text_TimothyPostRematch:
	.string "Il suffit de faire des efforts !\p"
	.string "J'ai perdu parce que je n'en ai pas fait assez !$"

Route115_Text_KoichiIntro:
	.string "Toi !\p"
	.string "Mon MACHOC !\p"
	.string "Veut un combat !$"

Route115_Text_KoichiDefeat:
	.string "Aïe, aïe, aïe !$"

Route115_Text_KoichiPostBattle:
	.string "Mon équipe de MACHOC !\p"
	.string "Tant qu'ils cherchent la force, je\n"
	.string "deviendrai fort avec eux !$"

Route115_Text_NobIntro:
	.string "Mon plus grand talent, c'est de casser des briques\n"
	.string "avec mon front !$"

Route115_Text_NobDefeat:
	.string "Ugwaaaah !\n"
	.string "Ma tête est cassée !$"

Route115_Text_NobPostBattle:
	.string "J'apprends le karaté à mes POKéMON.\p"
	.string "On dirait qu'ils vont devenir bien meilleurs\n"
	.string "que moi. Ça m'excite !$"

Route115_Text_NobRegister:
	.string "Tu m'impressionnes ! Donne-moi une revanche\n"
	.string "après que je me sois réentraîné !$"

Route115_Text_NobRematchIntro:
	.string "Après ta victoire, on s'est entraînés dur\n"
	.string "pour progresser.\l"
	.string "Allez, donne-nous une revanche !$"

Route115_Text_NobRematchDefeat:
	.string "Ugwaaah !\n"
	.string "On a encore perdu !$"

Route115_Text_NobPostRematch:
	.string "Mes POKéMON deviendront plus forts !\n"
	.string "Je vais doubler d'efforts !$"

Route115_Text_CyndyIntro:
	.string "Cette plage est mon coin secret d'entraînement !\n"
	.string "Ne viens pas m'embêter !$"

Route115_Text_CyndyDefeat:
	.string "Je ne me suis pas assez entraînée !$"

Route115_Text_CyndyPostBattle:
	.string "Le sable amortit les chocs et évite les blessures.\l"
	.string "C'est l'endroit parfait pour s'entraîner.$"

Route115_Text_CyndyRegister:
	.string "Bon, d'accord, tu peux venir ici.\n"
	.string "En échange, je veux te combattre à nouveau !$"

Route115_Text_CyndyRematchIntro:
	.string "Allez, c'est parti pour le combat !$"

Route115_Text_CyndyRematchDefeat:
	.string "Je peux combattre mais mes POKéMON…$"

Route115_Text_CyndyPostRematch:
	.string "Même quand je perds, j'y prends du plaisir.\l"
	.string "C'est sûrement parce que j'aime les POKéMON.$"

Route115_Text_HectorIntro:
	.string "J'ai un POKéMON rare !\n"
	.string "Tu veux que je te le montre ?$"

Route115_Text_HectorDefeat:
	.string "Toi…\n"
	.string "Tu veux mon POKéMON, hein ?$"

Route115_Text_HectorPostBattle:
	.string "J'ai ce POKéMON rare.\n"
	.string "Ça me suffit pour être heureux.$"

Route115_Text_KyraIntro:
	.string "Je vais combattre en courant !\n"
	.string "Essaie de me suivre !$"

Route115_Text_KyraDefeat:
	.string "Hah… hah…$"

Route115_Text_KyraPostBattle:
	.string "J'ai eu tort d'essayer de combattre\n"
	.string "en courant !\p"
	.string "Je devrais aller courir pour me calmer…$"

Route115_Text_JaidenIntro:
	.string "Prends ça !\n"
	.string "Attaque ninja ultra-POKéMON !$"

Route115_Text_JaidenDefeat:
	.string "Ouin !\n"
	.string "Notre stratégie a échoué !$"

Route115_Text_JaidenPostBattle:
	.string "Mais mes POKéMON étaient ultra,\n"
	.string "non ?$"

Route115_Text_HeleneIntro:
	.string "Mes POKéMON ont la force d'une ceinture noire !$"

Route115_Text_HeleneDefeat:
	.string "C'est trop humiliant !$"

Route115_Text_HelenePostBattle:
	.string "Je rencontre rarement quelqu'un de meilleur\n"
	.string "que moi…\p"
	.string "Je comprends !\n"
	.string "Tu es un(e) CHAMPION(NE) d'ARÈNE, non ?$"

Route115_Text_AlixIntro:
	.string "Nos regards se sont croisés !\n"
	.string "Impossible de fuir maintenant !$"

Route115_Text_AlixDefeat:
	.string "Gah !\n"
	.string "Pas mal !$"

Route115_Text_AlixPostBattle:
	.string "Bon, tant pis.\n"
	.string "Je vais me TÉLÉPORTER chez moi.$"

Route115_Text_MarleneIntro:
	.string "Tu as troublé ma méditation…\n"
	.string "Tu vas être puni(e) !$"

Route115_Text_MarleneDefeat:
	.string "Tu as brisé ma concentration !$"

Route115_Text_MarlenePostBattle:
	.string "Je méditais avec mes POKéMON.\n"
	.string "Mais cet endroit n'est pas très paisible…$"

Route116_Text_ClarkIntro:
	.string "Si le tunnel ne passe pas, alors\n"
	.string "je passerai par-dessus !$"

Route116_Text_ClarkDefeat:
	.string "Hah… hah…\n"
	.string "Perdre m'a fatigué…$"

Route116_Text_ClarkPostBattle:
	.string "Ce n'est pas grave s'il n'y a pas de tunnel.\n"
	.string "Pour un MONTAGNARD, la montagne est une route !$"

Route116_Text_JoeyIntro:
	.string "Mes POKéMON sont trop forts !\n"
	.string "Regarde !$"

Route116_Text_JoeyDefeat:
	.string "Aïe ! Une égratignure !\n"
	.string "Je dois mettre un pansement !$"

Route116_Text_JoeyPostBattle:
	.string "Les pansements sont des signes de robustesse !\n"
	.string "J'en ai un autre !$"

Route116_Text_JoseIntro:
	.string "Mes POKéMON INSECTE sont costauds !\n"
	.string "Combattons !$"

Route116_Text_JoseDefeat:
	.string "J'ai perdu !\n"
	.string "Je croyais t'avoir !$"

Route116_Text_JosePostBattle:
	.string "Les POKéMON INSECTE évoluent vite.\n"
	.string "Donc ils deviennent vite forts aussi.$"

Route116_Text_JaniceIntro:
	.string "Laisse-moi te montrer la force de mon\n"
	.string "adorable POKéMON !$"

Route116_Text_JaniceDefeat:
	.string "Tu es un cran au-dessus…$"

Route116_Text_JanicePostBattle:
	.string "Un POKéMON mignon et fort, c'est l'idéal,\n"
	.string "je trouve.$"

Route116_Text_JerryIntro:
	.string "On apprend plein de choses à l'ÉCOLE DE DRESSEUR.\p"
	.string "Je veux tester tout ça en vrai !$"

Route116_Text_JerryDefeat:
	.string "J'ai glandé à l'école…\n"
	.string "C'est pour ça que j'ai perdu.$"

Route116_Text_JerryPostBattle:
	.string "Je vais devoir refaire des cours à\n"
	.string "l'ÉCOLE DE DRESSEUR.\l"
	.string "Sinon, ROXANNE va être furieuse.$"

Route116_Text_JerryRegister1:
	.string "J'ai appris à l'ÉCOLE DE DRESSEUR\n"
	.string "qu'on peut enregistrer des DRESSEURS sur le POKéNAV.\p"
	.string "Je ne comprends pas trop, alors je peux essayer ?$"

Route116_Text_JerryRegister2:
	.string "J'ai appris à l'ÉCOLE DE DRESSEUR\n"
	.string "qu'on peut enregistrer des DRESSEURS sur le POKéNAV.\p"
	.string "Je ne comprends pas trop, alors je peux essayer ?$"

Route116_Text_JerryRematchIntro:
	.string "J'ai étudié sérieusement à l'ÉCOLE DE DRESSEUR.\l"
	.string "Je ne perdrai pas comme la dernière fois !$"

Route116_Text_JerryRematchDefeat:
	.string "Hein ?\n"
	.string "J'ai étudié sérieusement.$"

Route116_Text_JerryPostRematch:
	.string "Je vais devoir refaire des cours à\n"
	.string "l'ÉCOLE DE DRESSEUR.\l"
	.string "Sinon, ROXANNE va être furieuse.$"

Route116_Text_KarenIntro:
	.string "J'étudie à l'école et aussi sur le chemin du retour !$"

Route116_Text_KarenDefeat:
	.string "Je suis choquée… J'ai perdu ?$"

Route116_Text_KarenPostBattle:
	.string "Oh non, je ne deviendrai jamais une DRESSEUSE\n"
	.string "élégante comme ROXANNE comme ça !$"

Route116_Text_KarenRegister1:
	.string "Oh, waouh ! C'est un POKéNAV ?\n"
	.string "J'en ai un aussi ! Enregistre-moi !$"

Route116_Text_KarenRegister2:
	.string "Oh, waouh ! C'est un POKéNAV ?\n"
	.string "J'en ai un aussi ! Enregistre-moi !$"

Route116_Text_KarenRematchIntro:
	.string "J'ai beaucoup étudié depuis qu'on s'est vus.\n"
	.string "Tu dois voir mes progrès !$"

Route116_Text_KarenRematchDefeat:
	.string "Je suis choquée.\n"
	.string "J'ai encore perdu ?$"

Route116_Text_KarenPostRematch:
	.string "Tu as battu ROXANNE ?\n"
	.string "Je ne peux pas te battre alors. Pas encore.$"

Route116_Text_SarahIntro:
	.string "Sache que je n'ai jamais été battue\n"
	.string "par qui que ce soit, en rien !$"

Route116_Text_SarahDefeat:
	.string "Oh, mon dieu.\n"
	.string "C'est une nouvelle expérience pour moi.$"

Route116_Text_SarahPostBattle:
	.string "Ma vie de luxe m'offre tout ce que je peux désirer.\p"
	.string "Mais pour les POKéMON, ma richesse ne sert à rien.$"

Route116_Text_DawsonIntro:
	.string "Quand tu verras la fourrure magnifique de mon POKéMON,\n"
	.string "sa beauté te rendra impuissant(e) !$"

Route116_Text_DawsonDefeat:
	.string "Oh non, dis-moi que c'est pas vrai !$"

Route116_Text_DawsonPostBattle:
	.string "Oh non, non, non !\n"
	.string "Tu as ébouriffé la fourrure de mon POKéMON !\l"
	.string "Tu as ruiné ma coiffure aussi !\l"
	.string "Je dois appeler mon coiffeur !$"

Route116_Text_DevanIntro:
	.string "On va te secouer fort !$"

Route116_Text_DevanDefeat:
	.string "Aïe aïe aïe !\n"
	.string "Aucune chance !$"

Route116_Text_DevanPostBattle:
	.string "Je devrais essayer d'autres types de POKéMON,\n"
	.string "c'est ce que je devrais faire.$"

Route116_Text_JohnsonIntro:
	.string "C'est une impasse ici.\n"
	.string "Je m'ennuie, on se bat ?$"

Route116_Text_JohnsonDefeat:
	.string "C'était amusant même si j'ai perdu.$"

Route116_Text_JohnsonPostBattle:
	.string "Tu veux rester ici et me tenir compagnie ?$"

Route117_Text_IsaacIntro:
	.string "Dis, tu veux bien combattre\n"
	.string "les POKéMON que j'élève ?$"

Route117_Text_IsaacDefeat:
	.string "Tu élèves les tiens à merveille…$"

Route117_Text_IsaacPostBattle:
	.string "Les POKéMON, ce n'est pas que la force.\p"
	.string "Développer un aspect unique de leur\n"
	.string "personnalité, c'est aussi une façon de profiter\l"
	.string "des POKéMON.$"

Route117_Text_IsaacRegister:
	.string "Je vais redoubler d'entraînement.\n"
	.string "Tu viendras nous voir ?$"

Route117_Text_IsaacRematchIntro:
	.string "Les POKéMON que j'élève sont en forme,\n"
	.string "comme toujours !$"

Route117_Text_IsaacRematchDefeat:
	.string "Tu sais bien les élever.\n"
	.string "Tu as peut-être l'âme d'un GARDIEN…$"

Route117_Text_IsaacPostRematch:
	.string "Tes POKéMON grandissent bien !\n"
	.string "Tu devrais les inscrire aux CONCOURS !$"

Route117_Text_LydiaIntro:
	.string "Permets-moi d'évaluer si tu as bien\n"
	.string "élevé tes POKéMON.$"

Route117_Text_LydiaDefeat:
	.string "Oui, ils grandissent bien.$"

Route117_Text_LydiaPostBattle:
	.string "Essaie d'élever tes POKéMON en faisant\n"
	.string "plus attention à leur caractère.$"

Route117_Text_LydiaRegister:
	.string "Je suis ravie d'avoir rencontré un(e) DRESSEUR\n"
	.string "aussi doué(e) que toi.\n"
	.string "J'espère te revoir.$"

Route117_Text_LydiaRematchIntro:
	.string "Permets-moi de réévaluer si tu as bien\n"
	.string "élevé tes POKéMON.$"

Route117_Text_LydiaRematchDefeat:
	.string "Ils grandissent admirablement.$"

Route117_Text_LydiaPostRematch:
	.string "Les POKéMON semblent aimer différents types\n"
	.string "de {POKEBLOCK}S selon leur nature.$"

Route117_Text_DylanIntro:
	.string "Je suis en plein triathlon, mais bon,\n"
	.string "on fait un combat !$"

Route117_Text_DylanDefeat:
	.string "Je n'ai plus d'énergie !$"

Route117_Text_DylanPostBattle:
	.string "J'ai peut-être tout gâché…\p"
	.string "J'ai peut-être fini dernier pendant\n"
	.string "ce combat…$"

Route117_Text_DylanRegister:
	.string "Les POKéMON doivent être forts aussi ?\n"
	.string "J'aimerais que tu m'entraînes !$"

Route117_Text_DylanRematchIntro:
	.string "Je suis en plein triathlon,\n"
	.string "mais je suis bien devant.\l"
	.string "On fait un combat rapide !$"

Route117_Text_DylanRematchDefeat:
	.string "Je n'ai encore plus d'énergie !$"

Route117_Text_DylanPostRematch:
	.string "J'étais le meilleur en natation et en vélo,\n"
	.string "mais je ne suis pas encore très confiant\l"
	.string "avec les POKéMON.$"

Route117_Text_MariaIntro:
	.string "Je m'entraîne au triathlon avec mes POKéMON,\n"
	.string "donc je suis assez confiante sur ma vitesse !$"

Route117_Text_MariaDefeat:
	.string "Je dois encore m'entraîner, je crois.$"

Route117_Text_MariaPostBattle:
	.string "L'entraînement n'a de sens que si on\n"
	.string "le fait régulièrement.\p"
	.string "OK ! Je reprends l'entraînement !\n"
	.string "Demain !$"

Route117_Text_MariaRegister:
	.string "Tu sembles bien t'entraîner…\n"
	.string "Si tu veux, on combattra plus tard !$"

Route117_Text_MariaRematchIntro:
	.string "Tu continues ton entraînement ?\n"
	.string "Moi oui !\l"
	.string "Je vais te le prouver !$"

Route117_Text_MariaRematchDefeat:
	.string "Je dois encore m'entraîner, je crois.$"

Route117_Text_MariaPostRematch:
	.string "Je reprendrai l'entraînement demain.\n"
	.string "On combattra encore une autre fois !$"

Route117_Text_DerekIntro:
	.string "Avant, j'étais CHASSEUR D'INSECTES !\n"
	.string "Maintenant, je suis MANIAQUE D'INSECTES !\p"
	.string "Mais mon amour pour les POKéMON n'a pas changé !$"

Route117_Text_DerekDefeat:
	.string "Mon incompétence non plus n'a pas changé…$"

Route117_Text_DerekPostBattle:
	.string "J'ai juste suivi mon cœur, et maintenant\n"
	.string "on m'appelle MANIAQUE D'INSECTES…\p"
	.string "Mais je suis un expert en POKéMON INSECTE,\n"
	.string "donc c'est normal qu'on m'appelle comme ça !$"

Route117_Text_AnnaIntro:
	.string "ANNA : Je suis avec ma jolie partenaire\n"
	.string "junior. Je dois bien faire !$"

Route117_Text_AnnaDefeat:
	.string "ANNA : Je suis avec ma jolie partenaire\n"
	.string "junior ! Laisse-moi gagner !$"

Route117_Text_AnnaPostBattle:
	.string "ANNA : Tes POKéMON font de bonnes\n"
	.string "combinaisons.\p"
	.string "Je dirais que tu es juste derrière nous !$"

Route117_Text_AnnaAndMegRegister:
	.string "ANNA : On ne va pas en rester là !\n"
	.string "Tu reviendras, hein ?$"

Route117_Text_AnnaNotEnoughMons:
	.string "ANNA : Si tu veux nous combattre,\n"
	.string "amène deux POKéMON !$"

Route117_Text_MegIntro:
	.string "MEG : Je vais faire équipe avec ma super\n"
	.string "partenaire senior et te battre !$"

Route117_Text_MegDefeat:
	.string "MEG : Oh, non !\n"
	.string "Pardon, ANNA ! Je t'ai déçue…$"

Route117_Text_MegPostBattle:
	.string "MEG : J'ai ralenti ANNA…\n"
	.string "Sinon, elle aurait gagné !$"

Route117_Text_MegNotEnoughMons:
	.string "MEG : Tu n'as qu'un seul POKéMON ?\n"
	.string "On ne peut pas combattre alors.\p"
	.string "On veut faire un combat à deux !$"

Route117_Text_AnnaRematchIntro:
	.string "ANNA : Je ne peux pas continuer à perdre\n"
	.string "devant ma partenaire junior, pas vrai ?$"

Route117_Text_AnnaRematchDefeat:
	.string "ANNA : Je n'ai pas réussi à me mettre dans le rythme.$"

Route117_Text_AnnaPostRematch:
	.string "ANNA : Tes POKéMON font de bonnes\n"
	.string "combinaisons.\p"
	.string "Je dirais que tu es juste derrière nous !$"

Route117_Text_AnnaRematchNotEnoughMons:
	.string "ANNA : Si tu veux nous combattre,\n"
	.string "amène deux POKéMON !$"

Route117_Text_MegRematchIntro:
	.string "MEG : Je vais faire équipe avec ma\n"
	.string "partenaire senior et gagner cette fois !$"

Route117_Text_MegRematchDefeat:
	.string "MEG : Trop fort !$"

Route117_Text_MegPostRematch:
	.string "MEG : J'ai combattu avec ma partenaire\n"
	.string "senior, mais on a perdu…\p"
	.string "C'est tellement décourageant…$"

Route117_Text_MegRematchNotEnoughMons:
	.string "MEG : Tu n'as qu'un seul POKéMON ?\n"
	.string "On ne peut pas combattre alors.\p"
	.string "On veut faire un combat à deux !$"

Route117_Text_MelinaIntro:
	.string "N'est-ce pas agréable ? Se battre tout en\n"
	.string "regardant de jolies fleurs !$"

Route117_Text_MelinaDefeat:
	.string "Oh, c'est vraiment impressionnant !$"

Route117_Text_MelinaPostBattle:
	.string "C'est merveilleux de faire un jogging\n"
	.string "en regardant les fleurs.$"

Route117_Text_BrandiIntro:
	.string "Laisse-moi te montrer la puissance\n"
	.string "cachée d'un POKéMON PSY !$"

Route117_Text_BrandiDefeat:
	.string "Étonnant !$"

Route117_Text_BrandiPostBattle:
	.string "Les POKéMON PSY sont complexes.\n"
	.string "Tu devrais essayer d'en attraper !$"

Route117_Text_AishaIntro:
	.string "Je me concentre pour gagner.\n"
	.string "C'est comme ça que je combats !$"

Route117_Text_AishaDefeat:
	.string "Je ne perds pas de temps à être en colère\n"
	.string "après une défaite--je préfère m'entraîner.$"

Route117_Text_AishaPostBattle:
	.string "Je pense que si tu t'inquiètes de perdre,\n"
	.string "tu as plus de chances de perdre.$"

Route118_Text_RoseIntro:
	.string "Le parfum des fleurs a un pouvoir\n"
	.string "magique. Il purifie le corps et l'âme.$"

Route118_Text_RoseDefeat:
	.string "Oh, mince alors.\n"
	.string "On dirait que j'ai perdu.$"

Route118_Text_RosePostBattle:
	.string "Les fleurs, les POKéMON…\n"
	.string "J'aime tout ce qui sent bon.\p"
	.string "Les choses qui puent…\n"
	.string "Très peu pour moi.$"

Route118_Text_RoseRegister:
	.string "Snif… Cette odeur--c'est un POKéNAV !\n"
	.string "On doit s'enregistrer mutuellement !$"

Route118_Text_RoseRematchIntro:
	.string "Tu as été attiré ici par le doux\n"
	.string "parfum ?$"

Route118_Text_RoseRematchDefeat:
	.string "Le pouvoir du parfum…\n"
	.string "Ça n'a pas eu beaucoup d'effet.$"

Route118_Text_RosePostRematch:
	.string "Si tu utilises bien un doux parfum,\n"
	.string "les POKéMON seront attirés par lui.$"

Route118_Text_PerryIntro:
	.string "Les POKéMON OISEAU qui VOLENT élégamment\n"
	.string "dans le ciel… Ce sont les meilleurs !$"

Route118_Text_PerryDefeat:
	.string "Ouf…\n"
	.string "Je me suis écrasé…$"

Route118_Text_PerryPostBattle:
	.string "Tu as de super POKéMON.\n"
	.string "Je vais devoir mieux entraîner les miens.$"

Route118_Text_ChesterIntro:
	.string "Envolez-vous !\n"
	.string "Mes POKéMON OISEAU !$"

Route118_Text_ChesterDefeat:
	.string "Ils se sont envolés…$"

Route118_Text_ChesterPostBattle:
	.string "S'ils devenaient plus forts, ils pourraient\n"
	.string "voler plus librement…$"

Route118_Text_BarnyIntro:
	.string "Je suis PÊCHEUR, mais aussi DRESSEUR.\n"
	.string "J'élève les POKéMON que j'ai attrapés.$"

Route118_Text_BarnyDefeat:
	.string "Je pensais que je m'en sortais bien\n"
	.string "à l'entraînement…$"

Route118_Text_BarnyPostBattle:
	.string "Je n'ai pas pu gagner en entraînant\n"
	.string "des POKéMON tout en pêchant…\p"
	.string "Est-ce que je faisais les choses à moitié ?$"

Route118_Text_WadeIntro:
	.string "Pour les PÊCHEURS, l'équipement est la clé.\p"
	.string "Mais pour les DRESSEURS, les ingrédients\n"
	.string "clés sont les POKéMON et le cœur, bien sûr !$"

Route118_Text_WadeDefeat:
	.string "J'ai été battu au niveau du cœur ?$"

Route118_Text_WadePostBattle:
	.string "En y repensant, la pêche est un combat\n"
	.string "entre un PÊCHEUR et un POKéMON.$"

Route118_Text_DaltonIntro:
	.string "Laisse ma mélodie faire vibrer ton âme !$"

Route118_Text_DaltonDefeat:
	.string "La-lalala…$"

Route118_Text_DaltonPostBattle:
	.string "Une guitare électrique n'est pas toujours\n"
	.string "bruyante…\p"
	.string "On peut en jouer doucement pour sortir\n"
	.string "une mélodie qui touche le cœur…$"

Route118_Text_DaltonRegister:
	.string "Quand je composerai de meilleures mélodies,\n"
	.string "tu devras venir écouter, d'accord ?$"

Route118_Text_DaltonRematchIntro:
	.string "Une mélodie de mes POKéMON et moi…\n"
	.string "Laisse-nous la livrer à ton âme.$"

Route118_Text_DaltonRematchDefeat:
	.string "La-lalala…$"

Route118_Text_DaltonPostRematch:
	.string "Quand je joue, mes émotions devraient\n"
	.string "t'atteindre à travers ma guitare électrique…$"

Route118_Text_DeandreIntro:
	.string "Allez, allez, allez !\n"
	.string "POKéMON 1, 2 et 3 !$"

Route118_Text_DeandreDefeat:
	.string "Venez, POKéMON ! Ça va ?\n"
	.string "POKéMON 1, 2 et 3 ?!$"

Route118_Text_DeandrePostBattle:
	.string "C'est cool d'avoir une équipe de\n"
	.string "combat POKéMON, non ?\p"
	.string "Tu peux faire comme moi--ça ne me dérange pas !$"

Route119_Text_BrentIntro:
	.string "Nous sommes le CERCLE MIMIQUE !\n"
	.string "On IMITE tout ce que tu fais !$"

Route119_Text_BrentDefeat:
	.string "Oups !\n"
	.string "J'ai perdu !$"

Route119_Text_BrentPostBattle:
	.string "Qu'y a-t-il de si bien dans l'imitation ?\p"
	.string "Fufufu…\n"
	.string "Tu ne comprendras jamais…$"

Route119_Text_DonaldIntro:
	.string "Enfin, on se rencontre !\n"
	.string "Mes POKéMON INSECTE vont te tenir compagnie !$"

Route119_Text_DonaldDefeat:
	.string "J'aurais préféré qu'on ne se rencontre jamais…$"

Route119_Text_DonaldPostBattle:
	.string "Je veux t'IMITER encore plus.\n"
	.string "Tu peux bouger plus vite ?$"

Route119_Text_TaylorIntro:
	.string "Si tu avances, on avance.\p"
	.string "Si tu tournes à droite, on tourne aussi…$"

Route119_Text_TaylorDefeat:
	.string "Mais si tu gagnes, je perds…$"

Route119_Text_TaylorPostBattle:
	.string "Je ne peux pas IMITER ta victoire.\n"
	.string "C'est impossible…\l"
	.string "Ça me ronge…$"

Route119_Text_DougIntro:
	.string "Oui, tu m'as enfin attrapé !\n"
	.string "Ou tu essayais de m'éviter ?$"

Route119_Text_DougDefeat:
	.string "Ouah, c'était un super match !$"

Route119_Text_DougPostBattle:
	.string "Nous sommes le CERCLE MIMIQUE !\n"
	.string "J'espère que tu as aimé notre performance.$"

Route119_Text_GregIntro:
	.string "Tu ne sais pas qui je suis, hein ?\p"
	.string "Mais moi non plus, je ne te connais pas.\n"
	.string "Alors, on va se battre !$"

Route119_Text_GregDefeat:
	.string "Tu es vraiment fort !$"

Route119_Text_GregPostBattle:
	.string "Tant que tu ne pars pas, on va\n"
	.string "continuer à imiter tous tes mouvements.$"

Route119_Text_KentIntro:
	.string "Le CERCLE MIMIQUE a été formé par des gens\n"
	.string "qui aiment IMITER.\p"
	.string "Un combat commence dès qu'on se rencontre !$"

Route119_Text_KentDefeat:
	.string "J'abandonne !$"

Route119_Text_KentPostBattle:
	.string "Tu ne veux pas rejoindre notre CERCLE MIMIQUE ?$"

Route119_Text_JacksonIntro:
	.string "Qui a la connaissance et la technique\n"
	.string "pour survivre ?\p"
	.string "Les RANGERS POKéMON, bien sûr !$"

Route119_Text_JacksonDefeat:
	.string "Je n'avais pas assez de savoir-faire\n"
	.string "POKéMON…$"

Route119_Text_JacksonPostBattle:
	.string "S'éloigner de la civilisation et\n"
	.string "réveiller l'esprit sauvage en soi !\p"
	.string "C'est notre vision.$"

Route119_Text_JacksonRegister:
	.string "J'espère que tu me donneras une revanche\n"
	.string "sans te moquer de mon manque de savoir.$"

Route119_Text_JacksonRematchIntro:
	.string "Je vais retrouver mon esprit sauvage en\n"
	.string "étant avec mes POKéMON.$"

Route119_Text_JacksonRematchDefeat:
	.string "Tu es resté fort !$"

Route119_Text_JacksonPostRematch:
	.string "Crois en tes POKéMON.\n"
	.string "Crois en toi.\p"
	.string "La route s'ouvrira devant toi.$"

Route119_Text_CatherineIntro:
	.string "Oh ? Regarde-toi.\p"
	.string "Pour quelqu'un en aventure,\n"
	.string "tu voyages très léger.$"

Route119_Text_CatherineDefeat:
	.string "Les accidents arrivent quand on n'est pas\n"
	.string "préparé !$"

Route119_Text_CatherinePostBattle:
	.string "Tu voyages léger mais tu as tout ce qu'il faut.\p"
	.string "Tu gères tout mentalement et\n"
	.string "physiquement aussi.$"

Route119_Text_CatherineRegister:
	.string "Tu as un POKéNAV ?\n"
	.string "C'est un outil indispensable pour tout DRESSEUR.\p"
	.string "Oh, tu en as un !\n"
	.string "Enregistrons-nous alors !$"

Route119_Text_CatherineRematchIntro:
	.string "Comment se passe ton voyage avec tes\n"
	.string "POKéMON ?$"

Route119_Text_CatherineRematchDefeat:
	.string "Il me manque encore quelque chose…$"

Route119_Text_CatherinePostRematch:
	.string "De la même façon que toi, en tant que DRESSEUR,\n"
	.string "tu comptes sur tes POKéMON, tes POKéMON\l"
	.string "comptent sur toi.$"

Route119_Text_HughIntro:
	.string "Le vaste ciel promet tant de choses !\p"
	.string "Rien n'égale l'exaltation du vol !$"

Route119_Text_HughDefeat:
	.string "À terre et vaincu !$"

Route119_Text_HughPostBattle:
	.string "Mes POKéMON OISEAU ont réalisé mon rêve\n"
	.string "de voler !$"

Route119_Text_PhilIntro:
	.string "Je vais te montrer le vrai potentiel de moi\n"
	.string "et de mes POKéMON OISEAU !$"

Route119_Text_PhilDefeat:
	.string "On manquait de potentiel…$"

Route119_Text_PhilPostBattle:
	.string "Depuis tout petit, j'ai toujours admiré\n"
	.string "les POKéMON OISEAU…$"

Route119_Text_YasuIntro:
	.string "Vivre dans l'ombre, dans les ténèbres…\n"
	.string "C'est mon destin.\p"
	.string "Je sors pour te défier !$"

Route119_Text_YasuDefeat:
	.string "J'admets ma défaite !$"

Route119_Text_YasuPostBattle:
	.string "Ceux qui perdent se retirent\n"
	.string "silencieusement dans l'ombre.\l"
	.string "C'est aussi le destin…$"

Route119_Text_TakashiIntro:
	.string "Si tu n'es pas sur tes gardes,\n"
	.string "tu vas avoir mal !$"

Route119_Text_TakashiDefeat:
	.string "Tu es étonnamment bon !$"

Route119_Text_TakashiPostBattle:
	.string "Mon attaque surprise a échoué…$"

Route119_Text_HideoIntro:
	.string "Pour cacher un arbre, utilise une forêt !$"

Route119_Text_HideoDefeat:
	.string "Je m'incline devant ta supériorité.$"

Route119_Text_HideoPostBattle:
	.string "Pour cacher un arbre, utilise une forêt !\n"
	.string "Pour cacher un POKéMON, utilise un POKéMON !\p"
	.string "Il n'y a pas de sens caché profond\n"
	.string "là-dedans.$"

Route119_Text_ChrisIntro:
	.string "Tu m'as parlé…\n"
	.string "Donc tu veux me défier !\p"
	.string "D'accord ! Je vais essayer les POKéMON\n"
	.string "que j'ai attrapés en SURFANT !$"

Route119_Text_ChrisDefeat:
	.string "Je n'ai aucune idée de ce qu'il faut\n"
	.string "pour gagner.$"

Route119_Text_ChrisPostBattle:
	.string "Faire du SURF sur mon POKéMON…\p"
	.string "Puis pêcher sur son dos…\p"
	.string "C'est un moment de luxe indescriptible !$"

Route119_Text_FabianIntro:
	.string "Balance-moi un accord puissant !\n"
	.string "La victoire est à moi !\l"
	.string "C'est notre moment de briller, ouais !$"

Route119_Text_FabianDefeat:
	.string "Tu m'as montré qui est le boss !\n"
	.string "On doit accepter la défaite, oh non !$"

Route119_Text_FabianPostBattle:
	.string "Balance-moi un autre accord puissant !\n"
	.string "Laisse-moi tranquille !\l"
	.string "Tu dois expier ta victoire !$"

Route119_Text_DaytonIntro:
	.string "Hohoho !\n"
	.string "J'aime les jeunes DRESSEURS !\l"
	.string "Faisons un bon combat !$"

Route119_Text_DaytonDefeat:
	.string "Tu es vraiment impressionnant !\n"
	.string "Hohoho !$"

Route119_Text_DaytonPostBattle:
	.string "Hohoho !\n"
	.string "Je vais essayer d'imiter l'énergie des jeunes\l"
	.string "DRESSEURS comme toi !$"

Route119_Text_RachelIntro:
	.string "Où que je sois, quand que ce soit,\n"
	.string "j'ai toujours mon ombrelle à la main.$"

Route119_Text_RachelDefeat:
	.string "Oh, mais…\n"
	.string "Ce n'est pas juste.$"

Route119_Text_RachelPostBattle:
	.string "Tu demandes si mon ombrelle est lourde ?\n"
	.string "Ton SAC est rempli de plus de bazar que\l"
	.string "ce que je porte jamais.$"

Route120_Text_ColinIntro:
	.string "As-tu des attaques qui peuvent toucher\n"
	.string "un POKéMON volant ?$"

Route120_Text_ColinDefeat:
	.string "Tu m'as survolé !$"

Route120_Text_ColinPostBattle:
	.string "La capacité VOL est pratique,\n"
	.string "tu ne trouves pas ?\p"
	.string "Quand le POKéMON vole,\n"
	.string "presque aucune attaque ne peut le toucher.$"

Route120_Text_RobertIntro:
	.string "Mon POKéMON est fort !\n"
	.string "Et le tien ?$"

Route120_Text_RobertDefeat:
	.string "Tes POKéMON étaient plus forts…$"

Route120_Text_RobertPostBattle:
	.string "Un POKéMON qui grandit régulièrement est\n"
	.string "un allié sur qui on peut compter.$"

Route120_Text_RobertRegister:
	.string "On peut compter sur toi pour t'améliorer.\n"
	.string "Je veux t'enregistrer dans mon POKéNAV !$"

Route120_Text_RobertRematchIntro:
	.string "Un POKéMON qui grandit régulièrement est\n"
	.string "un allié sur qui on peut compter.$"

Route120_Text_RobertRematchDefeat:
	.string "Tes POKéMON sont vraiment forts.$"

Route120_Text_RobertPostRematch:
	.string "Mes POKéMON deviennent plus forts.\n"
	.string "Je dois devenir plus fort aussi.$"

Route120_Text_LorenzoIntro:
	.string "Je vais vérifier si tes POKéMON sont\n"
	.string "prêts pour l'extérieur.$"

Route120_Text_LorenzoDefeat:
	.string "Avec des POKéMON aussi forts, tu n'as\n"
	.string "aucun risque d'avoir besoin de secours !$"

Route120_Text_LorenzoPostBattle:
	.string "Voyager où ton cœur le désire avec\n"
	.string "tes POKéMON…\l"
	.string "C'est la joie d'être DRESSEUR.$"

Route120_Text_JennaIntro:
	.string "Comment va ta forme physique ?\n"
	.string "Si tu n'es pas en forme, tu pourrais avoir\l"
	.string "des problèmes dans les situations critiques.$"

Route120_Text_JennaDefeat:
	.string "Je suis en pleine forme, mais…$"

Route120_Text_JennaPostBattle:
	.string "L'entraînement physique fait partie de ma routine.\n"
	.string "Je cours toujours avec mes POKéMON.$"

Route120_Text_JeffreyIntro:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Tu veux te battre ?$"

Route120_Text_JeffreyDefeat:
	.string "Perdu…$"

Route120_Text_JeffreyPostBattle:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Je vais essayer plus fort…$"

Route120_Text_JeffreyRegister:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Tu as un POKéNAV… ?$"

Route120_Text_JeffreyRematchIntro:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Tu veux te battre encore ?$"

Route120_Text_JeffreyRematchDefeat:
	.string "… … … … … …\n"
	.string "J'ai encore perdu…$"

Route120_Text_JeffreyPostRematch:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Je vais essayer plus fort…\l"
	.string "Pour mes précieux POKéMON INSECTE…$"

Route120_Text_JenniferIntro:
	.string "Les POKéMON ont beaucoup de capacités spéciales.\n"
	.string "Si tu veux devenir un DRESSEUR de premier ordre,\l"
	.string "apprends à les connaître.$"

Route120_Text_JenniferDefeat:
	.string "Tu réfléchis, ça se voit.$"

Route120_Text_JenniferPostBattle:
	.string "Les capacités spéciales des POKéMON\n"
	.string "changent les styles de combat.$"

Route120_Text_ChipIntro:
	.string "Qui es-tu donc ?\p"
	.string "Tu cherches peut-être des ruines anciennes\n"
	.string "qui, selon la légende, existeraient\l"
	.string "quelque part ?$"

Route120_Text_ChipDefeat:
	.string "Quel revers honteux…$"

Route120_Text_ChipPostBattle:
	.string "Ce gros rocher… J'aimerais croire qu'il\n"
	.string "contient vraiment des ruines anciennes.\l"
	.string "Mais je ne vois aucune entrée.$"

Route120_Text_ClarissaIntro:
	.string "Pourquoi je porte cette ombrelle ?\p"
	.string "Je te le dirai si tu arrives à me battre.$"

Route120_Text_ClarissaDefeat:
	.string "Une ombrelle ne protège pas des attaques\n"
	.string "de POKéMON…$"

Route120_Text_ClarissaPostBattle:
	.string "Je ne pense pas que le soleil fort soit bon\n"
	.string "pour mes POKéMON.\l"
	.string "Alors je les protège avec mon ombrelle.$"

Route120_Text_AngelicaIntro:
	.string "Moi, mes POKéMON et mon ombrelle…\p"
	.string "S'il manque l'un d'eux,\n"
	.string "le tableau de la beauté est gâché.$"

Route120_Text_AngelicaDefeat:
	.string "Tu as complètement ruiné ma beauté…$"

Route120_Text_AngelicaPostBattle:
	.string "Une ombrelle ne t'irait pas du tout.\p"
	.string "Ce genre de chose ne ferait que\n"
	.string "te gêner.$"

Route120_Text_KeigoIntro:
	.string "Je vais adopter les mouvements des POKéMON\n"
	.string "et créer de nouvelles techniques ninja.$"

Route120_Text_KeigoDefeat:
	.string "La création de nouvelles techniques ninja\n"
	.string "n'est qu'un rêve lointain…$"

Route120_Text_KeigoPostBattle:
	.string "Je devrais peut-être devenir l'élève\n"
	.string "d'un sensei ninja.$"

Route120_Text_RileyIntro:
	.string "Nous, les ninjas, nous nous cachons sous\n"
	.string "nos capes de camouflage.\l"
	.string "Je parie que tu ne savais pas où j'étais !$"

Route120_Text_RileyDefeat:
	.string "J'ai perdu !\n"
	.string "Je devrais camoufler ma honte !$"

Route120_Text_RileyPostBattle:
	.string "Nos capes de camouflage sont toutes\n"
	.string "faites à la main.$"

Route120_Text_CallieIntro:
	.string "Si tu ne fais pas attention,\n"
	.string "tu pourrais te blesser !$"

Route120_Text_CallieDefeat:
	.string "Aïe !\n"
	.string "C'est moi qui me suis blessée.$"

Route120_Text_CalliePostBattle:
	.string "Je me demande… Dois-je faire évoluer mes POKéMON ?\n"
	.string "Ils sont mignons comme ils sont, pourtant.$"

Route120_Text_LeonelIntro:
	.string "Tes POKéMON d'équipe…\n"
	.string "Tu as différents types ?$"

Route120_Text_LeonelDefeat:
	.string "J'ai vu ta stratégie en action !$"

Route120_Text_LeonelPostBattle:
	.string "Je trouve ça génial que tu sois si fort\n"
	.string "en combattant avec tes POKéMON préférés.$"

Route121_Text_VanessaIntro:
	.string "Veux-tu jouer avec mes POKéMON\n"
	.string "délicieusement jolis ?$"

Route121_Text_VanessaDefeat:
	.string "Ce n'est pas ce que je voulais !$"

Route121_Text_VanessaPostBattle:
	.string "Je vais à un CONCOURS à NENCRANOPOLIS.\p"
	.string "Mes POKéMON ne devraient avoir aucun mal\n"
	.string "à gagner la CLASSE MASTER.$"

Route121_Text_WalterIntro:
	.string "Avec mes POKéMON, j'ai voyagé\n"
	.string "aux quatre coins du monde.\p"
	.string "On peut dire que j'ai confiance\n"
	.string "en mes capacités.$"

Route121_Text_WalterDefeat:
	.string "Ah, bien joué.$"

Route121_Text_WalterPostBattle:
	.string "J'aimerais refaire le tour du monde\n"
	.string "avec mes POKéMON.$"

Route121_Text_WalterRegister:
	.string "Tes talents de DRESSEUR sont remarquables.\n"
	.string "Permets-moi de t'enregistrer en souvenir.$"

Route121_Text_WalterRematchIntro:
	.string "Avec mes POKéMON, j'ai voyagé\n"
	.string "aux quatre coins du monde.\p"
	.string "On peut dire que j'ai confiance\n"
	.string "en mes capacités.$"

Route121_Text_WalterRematchDefeat:
	.string "Ah, bien joué.$"

Route121_Text_WalterPostRematch:
	.string "Tes POKéMON et toi…\p"
	.string "Votre talent sera reconnu\n"
	.string "même à l'étranger.$"

Route121_Text_TammyIntro:
	.string "Il existe des pouvoirs au-delà de notre\n"
	.string "compréhension dans ce monde…$"

Route121_Text_TammyDefeat:
	.string "J'ai perdu…$"

Route121_Text_TammyPostBattle:
	.string "LE MONT MÉMORIAL…\n"
	.string "Il y a une force mystérieuse\l"
	.string "qui agit là-bas…$"

Route121_Text_KateIntro:
	.string "KATE : Ensemble, on n'a peur de rien !\n"
	.string "On va te montrer notre force !$"

Route121_Text_KateDefeat:
	.string "KATE : J'ai raté devant ma partenaire\n"
	.string "junior…$"

Route121_Text_KatePostBattle:
	.string "KATE : Quand quelqu'un compte sur moi,\n"
	.string "j'ai envie d'avoir l'air cool devant lui…$"

Route121_Text_KateNotEnoughMons:
	.string "KATE : Si tu n'as qu'un seul POKéMON,\n"
	.string "on ne peut pas se battre.\p"
	.string "Ce serait de l'intimidation.$"

Route121_Text_JoyIntro:
	.string "JOY : Ensemble, on n'a peur de rien !\n"
	.string "On va te montrer notre force !$"

Route121_Text_JoyDefeat:
	.string "JOY : Pardonne-moi, KATE !$"

Route121_Text_JoyPostBattle:
	.string "JOY : Ehehe, je vais devoir m'entraîner avec KATE,\n"
	.string "ma partenaire senior, encore une fois.$"

Route121_Text_JoyNotEnoughMons:
	.string "JOY : Il te faut au moins deux POKéMON\n"
	.string "si tu veux nous défier !$"

Route121_Text_JessicaIntro:
	.string "Stop ! Regarde bien mes précieux\n"
	.string "POKéMON !$"

Route121_Text_JessicaDefeat:
	.string "Oh, comment oses-tu !\n"
	.string "Ne prends pas ça si au sérieux !$"

Route121_Text_JessicaPostBattle:
	.string "Peut-être que j'irai attraper plus de POKéMON\n"
	.string "au SAFARI.$"

Route121_Text_JessicaRegister:
	.string "Je t'ai laissé gagner cette fois !\n"
	.string "La prochaine fois, ce ne sera pas pareil !$"

Route121_Text_JessicaRematchIntro:
	.string "Mes précieux POKéMON ont grandi !\n"
	.string "Regarde bien !$"

Route121_Text_JessicaRematchDefeat:
	.string "Oh, comment oses-tu !\n"
	.string "Tu ne me laisses toujours pas gagner !$"

Route121_Text_JessicaPostRematch:
	.string "Peut-être que j'irai attraper plus de POKéMON\n"
	.string "au SAFARI.$"

Route121_Text_CristinIntro:
	.string "J'ai une routine.\n"
	.string "Battre cinq DRESSEURS par jour.\l"
	.string "Devine quoi ? Tu es le cinquième !$"

Route121_Text_CristinDefeat:
	.string "Non !\n"
	.string "Tu es horrible !$"

Route121_Text_CristinPostBattle:
	.string "Je ne m'attendais pas à perdre aussi facilement…\n"
	.string "Je gagnerai la prochaine fois !$"

Route121_Text_CristinRegister:
	.string "C'était une humiliation totale !\n"
	.string "Je ne t'oublierai pas…\l"
	.string "Donne-moi ton POKéNAV !$"

Route121_Text_CristinRematchIntro:
	.string "J'ai une nouvelle routine.\n"
	.string "Battre dix DRESSEURS par jour.\l"
	.string "Devine quoi ? Tu es le dixième !$"

Route121_Text_CristinRematchDefeat:
	.string "Attends ! C'est méchant !\n"
	.string "Je veux une revanche !$"

Route121_Text_CristinPostRematch:
	.string "Un adversaire que je ne peux pas battre…\n"
	.string "Snif…\l"
	.string "Je n'arrive pas à y croire…$"

Route121_Text_CaleIntro:
	.string "Tu ne vois pas que j'ai plein de choses\n"
	.string "avec moi ?\p"
	.string "Malgré ça, tu insistes pour qu'on\n"
	.string "se batte ?$"

Route121_Text_CaleDefeat:
	.string "Évidemment que j'ai perdu !\n"
	.string "J'ai les mains pleines !$"

Route121_Text_CalePostBattle:
	.string "J'ai trop acheté au\n"
	.string "GRAND MAGASIN de NENCRANOPOLIS.\p"
	.string "C'est juste sur la route d'ici.\n"
	.string "J'aimerais avoir un SAC comme le tien.$"

Route121_Text_MylesIntro:
	.string "J'adore regarder les POKéMON des autres\n"
	.string "plus que tout !$"

Route121_Text_MylesDefeat:
	.string "Super génial !$"

Route121_Text_MylesPostBattle:
	.string "Ils sont super, tes POKéMON !\n"
	.string "Comment tu les élèves ?$"

Route121_Text_PatIntro:
	.string "Je veux que tout le monde voie les POKéMON\n"
	.string "que j'ai élevés !$"

Route121_Text_PatDefeat:
	.string "Wow !\n"
	.string "Spectaculaire !$"

Route121_Text_PatPostBattle:
	.string "J'élève chaque POKéMON avec le même amour\n"
	.string "et le même soin--je n'ai pas de favoris.$"

Route121_Text_MarcelIntro:
	.string "Mes POKéMON n'ont jamais connu la défaite !\n"
	.string "À leur prochaine victoire, je les inscris\l"
	.string "aux CONCOURS.$"

Route121_Text_MarcelDefeat:
	.string "Oh, que s'est-il passé ici ?$"

Route121_Text_MarcelPostBattle:
	.string "Je vais peut-être devoir entraîner mon équipe\n"
	.string "encore un peu avant d'aller aux CONCOURS.$"

Route123_Text_WendyIntro:
	.string "Tu veux savoir à quel point tu es fort ?\n"
	.string "Je vais te servir de test !$"

Route123_Text_WendyDefeat:
	.string "Tu as réussi haut la main !$"

Route123_Text_WendyPostBattle:
	.string "Me battre, moi…\n"
	.string "Ta force est merveilleuse !$"

Route123_Text_BraxtonIntro:
	.string "On dirait que tu as une belle collection\n"
	.string "de BADGES d'ARENE.\p"
	.string "Voyons si tu les mérites vraiment !$"

Route123_Text_BraxtonDefeat:
	.string "Oh, tu les mérites, c'est sûr !$"

Route123_Text_BraxtonPostBattle:
	.string "Tu as honoré tes BADGES dans ce\n"
	.string "combat !$"

Route123_Text_VioletIntro:
	.string "On dit que les bons moments sont remplis\n"
	.string "de bonnes odeurs.$"

Route123_Text_VioletDefeat:
	.string "Oh…\n"
	.string "Je sens l'odeur amère de la défaite…$"

Route123_Text_VioletPostBattle:
	.string "Le jardin du MAÎTRE DES BAIES est rempli\n"
	.string "de parfums enivrants.$"

Route123_Text_CameronIntro:
	.string "Être un psy, c'est une question de volonté.\p"
	.string "Je me suis juré de ne perdre contre\n"
	.string "personne. C'est ça, ma force !$"

Route123_Text_CameronDefeat:
	.string "Je me sens triste…$"

Route123_Text_CameronPostBattle:
	.string "Être un psy, c'est une question de volonté.\n"
	.string "Je pensais ne pas perdre contre toi…$"

Route123_Text_CameronRegister:
	.string "Je le sens !\n"
	.string "Toi et moi, on se battra encore !\l"
	.string "Je ne sais pas si je gagnerai…\p"
	.string "Montre-moi ton POKéNAV.$"

Route123_Text_CameronRematchIntro:
	.string "Je me suis convaincu que je ne perdrai plus.\n"
	.string "C'est ça, ma force !$"

Route123_Text_CameronRematchDefeat:
	.string "Je me sens triste…$"

Route123_Text_CameronPostRematch:
	.string "Je devrais m'entraîner au MONT MÉMORIAL…\n"
	.string "Je ne te battrai jamais comme ça…$"

Route123_Text_JackiIntro:
	.string "Ne sois pas trop content si tes POKéMON\n"
	.string "développent des pouvoirs psy.\p"
	.string "Il faut les affiner pour qu'ils soient\n"
	.string "vraiment utiles.$"

Route123_Text_JackiDefeat:
	.string "Submergée !$"

Route123_Text_JackiPostBattle:
	.string "On a tous des pouvoirs psy.\n"
	.string "On a juste oublié comment s'en servir.$"

Route123_Text_JackiRegister:
	.string "J'aimerais t'affronter à nouveau.\n"
	.string "Ça te va ?$"

Route123_Text_JackiRematchIntro:
	.string "As-tu éveillé les pouvoirs psy\n"
	.string "en toi ?$"

Route123_Text_JackiRematchDefeat:
	.string "Épatant !$"

Route123_Text_JackiPostRematch:
	.string "Ton pouvoir avec les POKéMON…\n"
	.string "C'est peut-être un pouvoir psy aussi.$"

Route123_Text_MiuIntro:
	.string "MIU : Bonjour, DRESSEUR. J'espère que tes\n"
	.string "POKéMON ne pleureront pas s'ils perdent.$"

Route123_Text_MiuDefeat:
	.string "MIU : Oh non, on a perdu.$"

Route123_Text_MiuPostBattle:
	.string "MIU : DRESSEUR, tes POKéMON sont forts\n"
	.string "parce que vous êtes amis.$"

Route123_Text_MiuNotEnoughMons:
	.string "MIU : Ce n'est pas drôle de combattre si tu\n"
	.string "n'as pas deux POKéMON.$"

Route123_Text_YukiIntro:
	.string "YUKI : D'accord !\n"
	.string "On va battre les POKéMON du DRESSEUR !$"

Route123_Text_YukiDefeat:
	.string "YUKI : Oh non, on a perdu.$"

Route123_Text_YukiPostBattle:
	.string "YUKI : Pourquoi es-tu si fort ?\n"
	.string "On n'a jamais perdu avant.$"

Route123_Text_YukiNotEnoughMons:
	.string "YUKI : Ce n'est pas drôle de combattre si tu\n"
	.string "n'as pas deux POKéMON.$"

Route123_Text_KindraIntro:
	.string "LE MONT MÉMORIAL…\n"
	.string "Là où dorment les esprits des POKéMON…\l"
	.string "Tes POKéMON vont-ils dormir ?$"

Route123_Text_KindraDefeat:
	.string "Débordant de vitalité…$"

Route123_Text_KindraPostBattle:
	.string "LE MONT MÉMORIAL…\n"
	.string "Là où dorment les esprits des POKéMON…\p"
	.string "Il doit y avoir une force qui apaise\n"
	.string "les esprits…$"

Route123_Text_FernandoIntro:
	.string "Je vais t'éteindre les lumières en\n"
	.string "déchirant ce morceau !$"

Route123_Text_FernandoDefeat:
	.string "Hé, attends !\n"
	.string "J'étais encore à l'intro !$"

Route123_Text_FernandoPostBattle:
	.string "Tu es solide comme le rock.\n"
	.string "Je vais écrire une chanson sur toi.$"

Route123_Text_FernandoRegister:
	.string "La prochaine fois, écoute toute la chanson,\n"
	.string "d'accord ?$"

Route123_Text_FernandoRematchIntro:
	.string "Aujourd'hui, c'est le jour !\n"
	.string "Je vais t'éteindre les lumières avant\l"
	.string "de finir ma chanson !$"

Route123_Text_FernandoRematchDefeat:
	.string "Hé, attends !\n"
	.string "Je n'ai même pas fait le refrain !$"

Route123_Text_FernandoPostRematch:
	.string "Je pensais que tu serais tellement captivé\n"
	.string "par ma chanson que tu perdrais.$"

Route123_Text_DavisIntro:
	.string "Voici mon super POKéMON INSECTE !\n"
	.string "C'est mon grand frère qui me l'a donné.$"

Route123_Text_DavisDefeat:
	.string "Waaaah !\n"
	.string "Tu es méchant !$"

Route123_Text_DavisPostBattle:
	.string "Ne dis pas à mon frère que j'ai perdu.\n"
	.string "C'est un secret !$"

Route123_Text_JazmynIntro:
	.string "Ma confiance va augmenter en battant\n"
	.string "quelqu'un d'aussi fort !$"

Route123_Text_JazmynDefeat:
	.string "Adieu, confiance…$"

Route123_Text_JazmynPostBattle:
	.string "On dit qu'il ne faut pas juger sur l'apparence.\p"
	.string "Mais souvent, les apparences ne trompent pas…$"

Route123_Text_FrederickIntro:
	.string "Bonjour, jeune !\n"
	.string "Tu as un peu de temps ?$"

Route123_Text_FrederickDefeat:
	.string "Ah, quel enfant talentueux !\n"
	.string "Laisse-moi contribuer à ton argent de poche.$"

Route123_Text_FrederickPostBattle:
	.string "Contribuer à ton argent de poche ?\n"
	.string "La récompense n'était pas suffisante ?$"

Route123_Text_AlbertoIntro:
	.string "Je dois te le dire, les POKéMON OISEAU\n"
	.string "sont ma passion !\p"
	.string "Les oiseaux, c'est cool !\n"
	.string "Ce sont les meilleurs !$"

Route123_Text_AlbertoDefeat:
	.string "Même vaincus, les POKéMON OISEAU sont cool !$"

Route123_Text_AlbertoPostBattle:
	.string "Je ramasse les plumes de POKéMON OISEAU\n"
	.string "qui tombent pendant les combats.\p"
	.string "Je vais me faire un chapeau avec\n"
	.string "des plumes de POKéMON OISEAU.$"

Route123_Text_EdIntro:
	.string "Quand il n'y a pas de DRESSEURS autour,\n"
	.string "je fais combattre mes POKéMON entre eux.\l"
	.string "Je les observe.$"

Route123_Text_EdDefeat:
	.string "J'aime bien tes POKéMON.$"

Route123_Text_EdPostBattle:
	.string "Héhé, je vais piquer tes idées de combat !\n"
	.string "Je pense que ça va m'aider.$"

Route123_Text_JonasIntro:
	.string "J'étais en embuscade, et un DRESSEUR\n"
	.string "est tombé dans mon piège !$"

Route123_Text_JonasDefeat:
	.string "Si tu ne perds pas, comment je peux\n"
	.string "m'amuser à jouer au ninja ?$"

Route123_Text_JonasPostBattle:
	.string "La prochaine fois, j'embusquerai un DRESSEUR\n"
	.string "qui a l'air plus faible.$"

Route123_Text_KayleyIntro:
	.string "Je viens d'acheter cette ombrelle.\n"
	.string "Ma mignonnerie a augmenté d'un tiers !$"

Route123_Text_KayleyDefeat:
	.string "Tu es cinq fois meilleur que moi !$"

Route123_Text_KayleyPostBattle:
	.string "Bien utiliser les accessoires, c'est\n"
	.string "le secret du style !$"

Route124_Text_SpencerIntro:
	.string "Hé, tu es perdu en mer ?\p"
	.string "Si tu bats mes POKéMON,\n"
	.string "je peux te guider.$"

Route124_Text_SpencerDefeat:
	.string "Je me suis perdu dans le combat !$"

Route124_Text_SpencerPostBattle:
	.string "Beaucoup de gens se perdent en mer.\p"
	.string "Si c'est ton cas, utilise la CARTE du POKéNAV.$"

Route124_Text_RolandIntro:
	.string "Hm ! Tu chevauches un POKéMON au lieu\n"
	.string "de nager toi-même…\p"
	.string "Je t'envie !$"

Route124_Text_RolandDefeat:
	.string "Oh !\n"
	.string "Je n'y arrive pas…$"

Route124_Text_RolandPostBattle:
	.string "J'ai froid…\n"
	.string "Je suis resté trop longtemps dans l'eau…\p"
	.string "J'aimerais pouvoir chevaucher un POKéMON comme toi…$"

Route124_Text_JennyIntro:
	.string "Si tu flottes dans la mer comme ça,\n"
	.string "les POKéMON viennent jouer.$"

Route124_Text_JennyDefeat:
	.string "Oh, zut.\n"
	.string "J'ai perdu.$"

Route124_Text_JennyPostBattle:
	.string "En nageant, j'ai remarqué que certains\n"
	.string "POKéMON attaquent, d'autres observent.\p"
	.string "Je suppose que les POKéMON ont leur propre\n"
	.string "personnalité.$"

Route124_Text_JennyRegister:
	.string "C'est juste sur un coup de tête, mais peut-être\n"
	.string "que je vais m'enregistrer dans ton POKéNAV.$"

Route124_Text_JennyRematchIntro:
	.string "Si tu flottes dans la mer comme ça,\n"
	.string "les DRESSEURS te défient !$"

Route124_Text_JennyRematchDefeat:
	.string "C'est étrange…\n"
	.string "J'ai encore perdu…$"

Route124_Text_JennyPostRematch:
	.string "Ça n'a rien à voir, mais peut-être que\n"
	.string "j'irai visiter la MAISON TRUC.$"

Route124_Text_GraceIntro:
	.string "Je commence à me lasser de nager…\n"
	.string "Un combat, ça te dit ?$"

Route124_Text_GraceDefeat:
	.string "Je ne savais pas que tu étais\n"
	.string "si fort !$"

Route124_Text_GracePostBattle:
	.string "Tout l'effort que tu as fourni t'a\n"
	.string "rendu aussi fort.$"

Route124_Text_ChadIntro:
	.string "Fufufufu… Je plonge en profondeur\n"
	.string "pour me cacher.\l"
	.string "Explorer les profondeurs, c'est mon truc !$"

Route124_Text_ChadDefeat:
	.string "Glou, glou, glou…\n"
	.string "Je coule…$"

Route124_Text_ChadPostBattle:
	.string "On m'a dit qu'il y a un endroit pour PLONGER ici.\p"
	.string "Ça me donne envie d'y retourner…$"

Route124_Text_LilaIntro:
	.string "LILA : Soupir…\p"
	.string "Je suis en mer, mais qui est avec moi ?\n"
	.string "Mon petit frère !\p"
	.string "Combattons pour que je n'y pense plus !$"

Route124_Text_LilaDefeat:
	.string "LILA : ROY ! C'est ta faute si on a perdu !\n"
	.string "Tu vas voir plus tard !$"

Route124_Text_LilaPostBattle:
	.string "LILA : Soupir…\p"
	.string "Si seulement ce n'était pas mon petit frère\n"
	.string "à côté de moi, mais un gentil copain…$"

Route124_Text_LilaNotEnoughMons:
	.string "LILA : Tu veux nous combattre ?\n"
	.string "Pas sans deux POKéMON !$"

Route124_Text_RoyIntro:
	.string "ROY : Ma grande sœur est forte en POKéMON !\p"
	.string "Ne pleure pas si tu perds !$"

Route124_Text_RoyDefeat:
	.string "ROY : Oh non…\n"
	.string "Ma grande sœur va me gronder…$"

Route124_Text_RoyPostBattle:
	.string "ROY : Ma grande sœur est vraiment effrayante\n"
	.string "quand elle est en colère.\p"
	.string "C'est pour ça qu'elle n'a pas de copain.$"

Route124_Text_LilaRoyRegister:
	.string "ROY : Tu veux te battre avec nous encore ?\n"
	.string "Mais vas-y doucement la prochaine fois !$"

Route124_Text_RoyNotEnoughMons:
	.string "ROY : Tu veux nous combattre ?\n"
	.string "Alors amène deux POKéMON.$"

Route124_Text_LilaRematchIntro:
	.string "LILA : Soupir…\p"
	.string "Je suis en mer, mais qui est avec moi ?\n"
	.string "Mon petit frère !\p"
	.string "Oh, salut, ça fait longtemps. Combattons\n"
	.string "pour que je n'y pense pas !$"

Route124_Text_LilaRematchDefeat:
	.string "LILA : ROY !\n"
	.string "C'est encore ta faute si on a perdu !\p"
	.string "On va s'entraîner après !$"

Route124_Text_LilaPostRematch:
	.string "LILA : Soupir…\p"
	.string "Si j'avais un gentil copain, on battrait\n"
	.string "tout le monde avec de belles combinaisons…$"

Route124_Text_LilaRematchNotEnoughMons:
	.string "LILA : Tu veux nous combattre ?\n"
	.string "Pas sans deux POKéMON !$"

Route124_Text_RoyRematchIntro:
	.string "ROY : Si on perd, je vais me faire gronder.\n"
	.string "Je vais tout donner !$"

Route124_Text_RoyRematchDefeat:
	.string "ROY : Oh non…\n"
	.string "Ma grande sœur va encore me gronder.$"

Route124_Text_RoyPostRematch:
	.string "ROY : Ma grande sœur est vraiment effrayante\n"
	.string "quand elle est en colère.\p"
	.string "Elle va me faire m'entraîner dur avec les POKéMON…$"

Route124_Text_RoyRematchNotEnoughMons:
	.string "ROY : Tu veux nous combattre ?\n"
	.string "Alors amène deux POKéMON.$"

Route124_Text_DeclanIntro:
	.string "Je nage tout seul sur cette mer vaste\n"
	.string "et magnifique.\p"
	.string "Il n'y a pas d'autre mot.\n"
	.string "C'est pathétique !$"

Route124_Text_DeclanDefeat:
	.string "J'ai le cafard.\n"
	.string "Aussi bleu que le ciel…$"

Route124_Text_DeclanPostBattle:
	.string "Je devrais discuter avec des NAGEUSES\n"
	.string "et les inviter à nager longtemps.$"

Route124_Text_IsabellaIntro:
	.string "Je ne vais pas perdre contre un DRESSEUR\n"
	.string "surfeur !$"

Route124_Text_IsabellaDefeat:
	.string "J'ai juste de la sueur dans les yeux !\n"
	.string "Je ne pleure pas !$"

Route124_Text_IsabellaPostBattle:
	.string "On peut trouver des éclats colorés\n"
	.string "par ici.$"

Route125_Text_NolenIntro:
	.string "Je t'ai entendu arriver, alors je t'ai\n"
	.string "attendu !$"

Route125_Text_NolenDefeat:
	.string "Je me rends !$"

Route125_Text_NolenPostBattle:
	.string "Le son voyage plus vite dans l'eau\n"
	.string "que dans l'air.$"

Route125_Text_StanIntro:
	.string "Hé, toi !\n"
	.string "Regarde mes super POKéMON !$"

Route125_Text_StanDefeat:
	.string "J'ai coulé…$"

Route125_Text_StanPostBattle:
	.string "J'ai été séduit par la grâce d'HYPOTREMPE,\n"
	.string "alors je me suis mis à nager aussi.$"

Route125_Text_TanyaIntro:
	.string "Je suis fatiguée de nager.\n"
	.string "Tu veux te battre avec moi ?$"

Route125_Text_TanyaDefeat:
	.string "Tu es trop fort !$"

Route125_Text_TanyaPostBattle:
	.string "Ouf…\n"
	.string "C'est par où NENUCRIQUE ?$"

Route125_Text_SharonIntro:
	.string "Veux-tu affronter les POKéMON EAU\n"
	.string "que j'ai élevés ?$"

Route125_Text_SharonDefeat:
	.string "Perdu…$"

Route125_Text_SharonPostBattle:
	.string "Ta puissance… Tu es vraiment fort.\n"
	.string "Je suis impressionnée !$"

Route125_Text_ErnestIntro:
	.string "Ohé ! Je suis un MARIN costaud !\n"
	.string "J'ai bravé toutes les mers du monde !$"

Route125_Text_ErnestDefeat:
	.string "Gwrroooar !\n"
	.string "Je n'ai pas pu gagner !$"

Route125_Text_ErnestPostBattle:
	.string "La marée monte et descend dans la\n"
	.string "GROTTE TRÉMIE.\p"
	.string "Au fait, il y a environ six heures entre\n"
	.string "marée haute et marée basse. Tu savais ?$"

Route125_Text_ErnestRegister:
	.string "Enregistre-moi dans ton POKéNAV,\n"
	.string "et je te dirai un truc sympa.$"

Route125_Text_ErnestRematchIntro:
	.string "Il est temps que je prenne ma revanche\n"
	.string "sur toi ! Allez, on se bat !$"

Route125_Text_ErnestRematchDefeat:
	.string "Je n'ai pas pu gagner !\n"
	.string "Impossible de gagner !$"

Route125_Text_ErnestRematchPostBattle:
	.string "La GROTTE TRÉMIE…\p"
	.string "Il y a des endroits accessibles ou non\n"
	.string "selon la marée.\p"
	.string "Au fait, il y a environ six heures entre\n"
	.string "marée haute et marée basse. N'oublie pas !$"

Route125_Text_KimIntro:
	.string "KIM : Un vieux monsieur rigolo vit dans la\n"
	.string "GROTTE TRÉMIE. On me l'a dit.\l"
	.string "Tu vas le voir, toi aussi ?$"

Route125_Text_KimDefeat:
	.string "KIM : Je pensais qu'on gagnerait.$"

Route125_Text_KimPostBattle:
	.string "KIM : Un vieux monsieur rigolo vit dans la\n"
	.string "GROTTE TRÉMIE, non ?\p"
	.string "Allons le voir, IRIS !$"

Route125_Text_KimNotEnoughMons:
	.string "KIM : Non, non, non ! Il te faut deux POKéMON,\n"
	.string "sinon ça ne va pas !$"

Route125_Text_IrisIntro:
	.string "IRIS : KIM, tu peux me dire ce qu'on cherche\n"
	.string "ici ?$"

Route125_Text_IrisDefeat:
	.string "IRIS : Oh, on n'était pas loin.$"

Route125_Text_IrisPostBattle:
	.string "IRIS : KIM, on va vraiment entrer dans la\n"
	.string "GROTTE TRÉMIE ?\l"
	.string "On va être tout mouillées.$"

Route125_Text_IrisNotEnoughMons:
	.string "IRIS : Oh, on ne pourrait jamais faire\n"
	.string "un combat à deux contre un.$"

Route125_Text_PresleyIntro:
	.string "Pourquoi un ÉLEVEUR D'OISEAUX comme moi\n"
	.string "vient à la mer ?$"

Route125_Text_PresleyDefeat:
	.string "D'accord.\n"
	.string "Je vais te dire pourquoi je suis là.$"

Route125_Text_PresleyPostBattle:
	.string "J'ai mis un message dans une bouteille\n"
	.string "et je l'ai jetée à la mer.\p"
	.string "Je suis sûr qu'une NAGEUSE la trouvera !$"

Route125_Text_AuronIntro:
	.string "Hé ! C'est toi qui jetais des déchets\n"
	.string "dans la mer ?$"

Route125_Text_AuronDefeat:
	.string "Ah, tu ne jetais pas de déchets dans\n"
	.string "la mer.$"

Route125_Text_AuronPostBattle:
	.string "J'ai trouvé une bouteille moche qui flottait\n"
	.string "dans les vagues tout à l'heure.\p"
	.string "Ça m'énerve que quelqu'un pollue la mer !$"

Route126_Text_BarryIntro:
	.string "Nager fait travailler tout le corps !\n"
	.string "Tu vas devenir en forme !$"

Route126_Text_BarryDefeat:
	.string "J'avoue !\n"
	.string "Tu as gagné !$"

Route126_Text_BarryPostBattle:
	.string "Grâce à ma routine de natation…\n"
	.string "Regarde ! Admire ce corps !$"

Route126_Text_DeanIntro:
	.string "Cette montagne blanche de roche,\n"
	.string "c'est ATALANOPOLIS.$"

Route126_Text_DeanDefeat:
	.string "Je me suis fait avoir ?$"

Route126_Text_DeanPostBattle:
	.string "Je ne trouve pas l'entrée d'ATALANOPOLIS.\n"
	.string "Où peut-elle bien être ?$"

Route126_Text_NikkiIntro:
	.string "Ufufufufu !\n"
	.string "Je suis une sirène !$"

Route126_Text_NikkiDefeat:
	.string "Mon rêve a éclaté comme une bulle !\n"
	.string "Bloup, bloup, bloup…$"

Route126_Text_NikkiPostBattle:
	.string "Tu m'as écrasée… Je veux disparaître\n"
	.string "dans une vague de désespoir…$"

Route126_Text_BrendaIntro:
	.string "Salut, petit !\n"
	.string "Tu veux te battre avec moi ?$"

Route126_Text_BrendaDefeat:
	.string "Oh, noooon !$"

Route126_Text_BrendaPostBattle:
	.string "J'adore m'amuser avec les POKéMON\n"
	.string "dans la mer comme ça !$"

Route126_Text_PabloIntro:
	.string "Regarde ce corps sculpté !\n"
	.string "Je suis plus musclé qu'un KARATÉKA !$"

Route126_Text_PabloDefeat:
	.string "Oups ! Trop fort !\n"
	.string "Pas mal du tout !$"

Route126_Text_PabloPostBattle:
	.string "Perdre contre toi m'a stimulé !\n"
	.string "Je vais m'entraîner encore plus, moi et mes POKéMON !$"

Route126_Text_PabloRegister:
	.string "Oui, tu n'es pas mal du tout !\n"
	.string "J'aimerais mieux te connaître !$"

Route126_Text_PabloRematchIntro:
	.string "Regarde ce beau corps !\n"
	.string "Je suis plus en forme qu'un NAGEUR !$"

Route126_Text_PabloRematchDefeat:
	.string "Oups ! Vraiment trop fort !\n"
	.string "Pas mal du tout !$"

Route126_Text_PabloPostRematch:
	.string "Je vais m'entraîner encore plus !\n"
	.string "Tu es une vraie source de motivation !\l"
	.string "Tu dois revenir !$"

Route126_Text_LeonardoIntro:
	.string "Je ne savais même pas nager l'an dernier,\n"
	.string "mais maintenant je suis un vrai NAGEUR.\p"
	.string "Je me sens capable de tout maintenant.$"

Route126_Text_LeonardoDefeat:
	.string "Vouloir trop, ça ne m'a pas aidé.$"

Route126_Text_LeonardoPostBattle:
	.string "Si tu t'entraînes, tu t'améliores.\n"
	.string "Tu es jeune--n'aie pas peur d'essayer\n"
	.string "plein de choses !$"

Route126_Text_IsobelIntro:
	.string "Quand l'eau de mer te monte au nez,\n"
	.string "ce n'est pas horrible ?$"

Route126_Text_IsobelDefeat:
	.string "Aïe ! Toi alors…\n"
	.string "Glou !$"

Route126_Text_IsobelPostBattle:
	.string "Ouh, j'ai avalé de l'eau !\n"
	.string "C'est amer ! C'est salé !!$"

Route126_Text_SiennaIntro:
	.string "Je mets tout mon cœur dans ce combat !$"

Route126_Text_SiennaDefeat:
	.string "Tu avais plus de cœur !$"

Route126_Text_SiennaPostBattle:
	.string "Je dois me calmer maintenant…\n"
	.string "Je vais aller plonger.$"

Route127_Text_CamdenIntro:
	.string "Je le vois sur ton visage.\n"
	.string "Tu veux me défier.$"

Route127_Text_CamdenDefeat:
	.string "Awawawawawa…$"

Route127_Text_CamdenPostBattle:
	.string "Un bon combat me laisse détendu\n"
	.string "et serein.$"

Route127_Text_DonnyIntro:
	.string "Tu as un rival que tu détestes perdre\n"
	.string "contre lui ?$"

Route127_Text_DonnyDefeat:
	.string "Arrrgh !\n"
	.string "Je déteste perdre !$"

Route127_Text_DonnyPostBattle:
	.string "Si tu as un rival, tu as envie de\n"
	.string "devenir toujours meilleur, non ?$"

Route127_Text_JonahIntro:
	.string "Grâce à la pêche, j'ai atteint un état\n"
	.string "de sérénité…\p"
	.string "Laisse-moi te le montrer…$"

Route127_Text_JonahDefeat:
	.string "Même si j'ai perdu, mon cœur reste\n"
	.string "calme…$"

Route127_Text_JonahPostBattle:
	.string "Peu importe si je n'attrape rien.\n"
	.string "La ligne reste dans l'eau…$"

Route127_Text_HenryIntro:
	.string "Oups ! Ne me dis pas que j'ai ferré\n"
	.string "un POKéMON SURFANT ?$"

Route127_Text_HenryDefeat:
	.string "Je ne peux pas suivre !$"

Route127_Text_HenryPostBattle:
	.string "Ce serait compliqué si j'attrapais\n"
	.string "tes POKéMON costauds !$"

Route127_Text_RogerIntro:
	.string "Hé ! C'est un match entre un fan de POKéMON\n"
	.string "et un passionné de pêche !$"

Route127_Text_RogerDefeat:
	.string "Non ! Ma ligne est toute emmêlée !\n"
	.string "La fête est finie !$"

Route127_Text_RogerPostBattle:
	.string "Ma ligne de pêche danse !\n"
	.string "Le tango des nœuds ! Hahaha, grrr !$"

Route127_Text_AidanIntro:
	.string "Les POKéMON OISEAU ont une excellente vue.\n"
	.string "Ils repèrent leurs proies de très haut.$"

Route127_Text_AidanDefeat:
	.string "Ouf… J'abandonne.$"

Route127_Text_AidanPostBattle:
	.string "Il y a plein d'endroits pour PLONGER\n"
	.string "dans la mer ici.\p"
	.string "On les repère facilement du ciel\n"
	.string "grâce à leur couleur plus sombre.$"

Route127_Text_KojiIntro:
	.string "Cours pieds nus.\n"
	.string "Ça va endurcir tes pieds !$"

Route127_Text_KojiDefeat:
	.string "Aïe !\n"
	.string "J'ai un caillou sous l'ongle !$"

Route127_Text_KojiPostBattle:
	.string "Marcher pieds nus, c'est super.\n"
	.string "Mais tes CHAUSSURES DE COURSE sont cool aussi.$"

Route127_Text_KojiRegister:
	.string "Voilà ce que je fais à ceux qui me battent !\n"
	.string "J'espère qu'on recommencera !$"

Route127_Text_KojiRematchIntro:
	.string "Je cours toujours pieds nus chaque jour.\n"
	.string "Mes pieds sont durs !$"

Route127_Text_KojiRematchDefeat:
	.string "Aïe !\n"
	.string "Des cailloux m'ont blessé la voûte plantaire !$"

Route127_Text_KojiPostRematch:
	.string "Tu veux essayer d'être pieds nus ?\n"
	.string "Comme ça, je pourrai tester tes CHAUSSURES !$"

Route127_Text_AthenaIntro:
	.string "On devrait faire un match lent et méthodique.$"

Route127_Text_AthenaDefeat:
	.string "Tu ne m'as pas laissé le temps de\n"
	.string "mettre en place une stratégie.$"

Route127_Text_AthenaPostBattle:
	.string "Quand je suis entourée de la mer bleue\n"
	.string "et du ciel, j'ai l'impression que le temps ralentit.$"

Route128_Text_IsaiahIntro:
	.string "ATALANOPOLIS est encore loin…$"

Route128_Text_IsaiahDefeat:
	.string "Ma première victoire semble aussi\n"
	.string "loin…$"

Route128_Text_IsaiahPostBattle:
	.string "J'ai toujours perdu dans la vie,\n"
	.string "mais je n'abandonnerai jamais !$"

Route128_Text_IsaiahRegister:
	.string "Je sais que je ne suis pas bon maintenant,\n"
	.string "mais je pense que je peux gagner un jour.\p"
	.string "Enregistre-moi dans ton POKéNAV.$"

Route128_Text_IsaiahRematchIntro:
	.string "Je me sens toujours bien. Je vais continuer\n"
	.string "à nager jusqu'à ATALANOPOLIS.$"

Route128_Text_IsaiahRematchDefeat:
	.string "Je n'ai toujours pas goûté à la victoire…$"

Route128_Text_IsaiahPostRematch:
	.string "J'atteindrai un jour ATALANOPOLIS\n"
	.string "où je pourrai enfin gagner…$"

Route128_Text_KatelynIntro:
	.string "Il faut nager, faire du vélo puis courir\n"
	.string "un marathon dans un triathlon.\p"
	.string "C'est une course éprouvante en trois épreuves.$"

Route128_Text_KatelynDefeat:
	.string "Un combat POKéMON, c'est éprouvant aussi…$"

Route128_Text_KatelynPostBattle:
	.string "Je dois prendre le VÉLO après, mais…\n"
	.string "Je vais abandonner…$"

Route128_Text_KatelynRegister:
	.string "Autant en profiter. J'aimerais une revanche un jour.$"

Route128_Text_KatelynRematchIntro:
	.string "Un triathlon, c'est long. Mais je pense que\n"
	.string "la route pour devenir MAÎTRE POKéMON\l"
	.string "est aussi longue et difficile.$"

Route128_Text_KatelynRematchDefeat:
	.string "Un combat POKéMON, c'est vraiment dur\n"
	.string "et impitoyable…$"

Route128_Text_KatelynPostRematch:
	.string "Tu devrais bien réfléchir aux défis\n"
	.string "de la ROUTE VICTOIRE.$"

Route128_Text_AlexaIntro:
	.string "On s'est tellement entraînées pour relever\n"
	.string "le défi de la LIGUE POKéMON…\p"
	.string "On ne peut pas se permettre de perdre !$"

Route128_Text_AlexaDefeat:
	.string "Oh !\n"
	.string "Comment ça a pu arriver ?!$"

Route128_Text_AlexaPostBattle:
	.string "Après tout ce que j'ai fait pour arriver ici,\n"
	.string "je n'abandonnerai pas après un échec.$"

Route128_Text_RubenIntro:
	.string "Il n'y a pas de DRESSEUR plus fort que moi !$"

Route128_Text_RubenDefeat:
	.string "Ce n'est pas possible !$"

Route128_Text_RubenPostBattle:
	.string "Il n'y a probablement pas de DRESSEUR\n"
	.string "plus fort que toi !$"

Route128_Text_WayneIntro:
	.string "Je veux aller à ATALANOPOLIS, alors j'ai\n"
	.string "attrapé un POKéMON qui connaît\l"
	.string "CASCADE pour franchir la chute !$"

Route128_Text_WayneDefeat:
	.string "Je suis abattu !$"

Route128_Text_WaynePostBattle:
	.string "Oh non !\p"
	.string "Mon POKéMON connaît CASCADE, mais\n"
	.string "je n'ai pas le BADGE d'ATALANOPOLIS !$"

Route128_Text_HarrisonIntro:
	.string "Tu as l'air vraiment fort.\n"
	.string "Je me demande si je peux gagner ?$"

Route128_Text_HarrisonDefeat:
	.string "Aïe !\n"
	.string "Je crois que c'était impossible de gagner.$"

Route128_Text_HarrisonPostBattle:
	.string "Il y a plein de DRESSEURS forts\n"
	.string "autour d'ATALANOPOLIS.\p"
	.string "Tu crois que je ne suis pas à la hauteur ?$"

Route128_Text_CarleeIntro:
	.string "Le soleil semble plus fort\n"
	.string "dans cette zone.$"

Route128_Text_CarleeDefeat:
	.string "Je ne voyais pas bien à cause\n"
	.string "de l'éblouissement du soleil.$"

Route128_Text_CarleePostBattle:
	.string "Je devrais rentrer bientôt.\n"
	.string "Je dois remettre de la crème solaire.$"

Route129_Text_ChaseIntro:
	.string "C'est mon premier triathlon.\n"
	.string "Je suis tout tendu et nerveux !$"

Route129_Text_ChaseDefeat:
	.string "Wroooaaar !\n"
	.string "J'ai perdu !$"

Route129_Text_ChasePostBattle:
	.string "Si je suis tendu, je ne pourrai pas\n"
	.string "donner le meilleur de moi-même.$"

Route129_Text_AllisonIntro:
	.string "Je suis en plein triathlon,\n"
	.string "mais bon, on se bat ?$"

Route129_Text_AllisonDefeat:
	.string "J'étais sûre de gagner !$"

Route129_Text_AllisonPostBattle:
	.string "Tu sais ce qu'il y a de mieux dans les triathlons ?\p"
	.string "Tester ses limites de force et d'endurance\n"
	.string "face à Mère Nature !$"

Route129_Text_ReedIntro:
	.string "Allez, allez !\n"
	.string "On y va !$"

Route129_Text_ReedDefeat:
	.string "Battre, je suis battu.\n"
	.string "C'est fini !$"

Route129_Text_ReedPostBattle:
	.string "Il n'y a rien pour un perdant.\n"
	.string "Il est temps de rentrer !$"

Route129_Text_TishaIntro:
	.string "Pourquoi se presser ?\n"
	.string "Prenons notre temps.$"

Route129_Text_TishaDefeat:
	.string "Oh, mince.\n"
	.string "Je voulais me détendre un peu plus…$"

Route129_Text_TishaPostBattle:
	.string "Tu n'aimes pas faire des erreurs quand\n"
	.string "tu es pressé ?\p"
	.string "C'est pour ça que je prends mon temps.$"

Route129_Text_ClarenceIntro:
	.string "Le surf, ce n'est pas si facile,\n"
	.string "n'est-ce pas ?$"

Route129_Text_ClarenceDefeat:
	.string "Gagner, ce n'est pas facile non plus.$"

Route129_Text_ClarencePostBattle:
	.string "Tu vises la LIGUE POKéMON ?\n"
	.string "Continue comme ça !$"

Route130_Text_RodneyIntro:
	.string "Quelle surprise ! Je ne m'attendais pas à\n"
	.string "voir un DRESSEUR en pleine mer.\p"
	.string "Je pense qu'on devrait se battre !$"

Route130_Text_RodneyDefeat:
	.string "Ce gamin est vraiment fort…$"

Route130_Text_RodneyPostBattle:
	.string "Tu as le regard de quelqu'un qui a vécu\n"
	.string "des épreuves difficiles\l"
	.string "et qui a gagné. Ça te va bien !$"

Route130_Text_KatieIntro:
	.string "Dans la mer bleue profonde,\n"
	.string "mon cœur brisé trouve\l"
	.string "du réconfort parmi les vagues.$"

Route130_Text_KatieDefeat:
	.string "Comme la vaste mer bleue,\n"
	.string "le monde des POKéMON est\l"
	.string "d'une profondeur incroyable.$"

Route130_Text_KatiePostBattle:
	.string "Les enfants du monde rêvent\n"
	.string "de devenir un jour\l"
	.string "MAÎTRE POKéMON.$"

Route130_Text_SantiagoIntro:
	.string "Flotter sur la mer comme ça…\n"
	.string "C'est paisible.$"

Route130_Text_SantiagoDefeat:
	.string "J'aurais dû être moins paisible !$"

Route130_Text_SantiagoPostBattle:
	.string "Nager et combattre comme ça…\n"
	.string "Je suis un homme heureux…$"

Route131_Text_RichardIntro:
	.string "La mer regorge de POKéMON.\n"
	.string "Nager n'est pas facile, tu sais.$"

Route131_Text_RichardDefeat:
	.string "Les POKéMON élevés par des DRESSEURS sont\n"
	.string "vraiment costauds…$"

Route131_Text_RichardPostBattle:
	.string "Ouf… Ouf…\n"
	.string "Je suis épuisé…\p"
	.string "Aller, c'est facile. C'est repartir\n"
	.string "qui est dur.\p"
	.string "Aurais-je assez d'énergie pour le retour ?$"

Route131_Text_HermanIntro:
	.string "La mer… La mer… La mer…\n"
	.string "La mer à perte de vue !\l"
	.string "J'en ai marre de la mer !$"

Route131_Text_HermanDefeat:
	.string "Beurk !$"

Route131_Text_HermanPostBattle:
	.string "La mer m'ennuie, mais je dois nager.\p"
	.string "Je suis né pour nager !\n"
	.string "C'est ce que je suis.$"

Route131_Text_SusieIntro:
	.string "Hé, chéri, attends !\n"
	.string "On devrait se battre, toi et moi !$"

Route131_Text_SusieDefeat:
	.string "Tu es fort malgré ton apparence !$"

Route131_Text_SusiePostBattle:
	.string "Tu as vu ce gars là-bas qui se plaint\n"
	.string "d'être lassé de la mer ?\p"
	.string "C'est du bluff.\n"
	.string "Il est fou amoureux de la mer !$"

Route131_Text_KaraIntro:
	.string "Pourquoi les hommes aiment-ils tant les maillots ?\p"
	.string "Ils me reluquent tous !$"

Route131_Text_KaraDefeat:
	.string "Je suis dépassée !$"

Route131_Text_KaraPostBattle:
	.string "Peut-être que ce n'est pas mon maillot qui\n"
	.string "attire les regards. C'est ma beauté !$"

Route131_Text_ReliIntro:
	.string "RELI : On va faire équipe entre frère et sœur\n"
	.string "pour t'affronter !$"

Route131_Text_ReliDefeat:
	.string "RELI : On n'a pas gagné même en travaillant\n"
	.string "ensemble…$"

Route131_Text_ReliPostBattle:
	.string "RELI : Les gens de PACIFIVILLE vivent\n"
	.string "avec la mer et les POKéMON depuis\l"
	.string "leur naissance.$"

Route131_Text_ReliNotEnoughMons:
	.string "RELI : Tu n'as pas deux POKéMON ?\n"
	.string "On ne peut pas s'amuser alors.$"

Route131_Text_IanIntro:
	.string "IAN : Je fais de mon mieux avec\n"
	.string "ma sœur !$"

Route131_Text_IanDefeat:
	.string "IAN : J'ai fait de mon mieux avec ma sœur,\n"
	.string "mais on n'a pas gagné…$"

Route131_Text_IanPostBattle:
	.string "IAN : Tu sais que PACIFIVILLE est\n"
	.string "une ville flottante ?\p"
	.string "Donc, partout où il y a la mer,\n"
	.string "c'est PACIFIVILLE !$"

Route131_Text_IanNotEnoughMons:
	.string "IAN : Si tu as deux POKéMON,\n"
	.string "on t'affronte !$"

Route131_Text_TaliaIntro:
	.string "Si tu me bats, je te donnerai\n"
	.string "une super info !$"

Route131_Text_TaliaDefeat:
	.string "Oh ?\n"
	.string "J'ai perdu ?$"

Route131_Text_TaliaPostBattle:
	.string "Il y a un endroit étrange pas loin.\n"
	.string "Il y a une grande tour là-bas.\l"
	.string "Pourquoi n'irais-tu pas voir ?$"

Route131_Text_KevinIntro:
	.string "Les gens de PACIFIVILLE sont\n"
	.string "très paisibles.\p"
	.string "Ils ne se mettent jamais en colère.\n"
	.string "Moi non plus !$"

Route131_Text_KevinDefeat:
	.string "Oups !$"

Route131_Text_KevinPostBattle:
	.string "Tch ! …Oh, attends.\n"
	.string "Je ne suis pas en colère. Vraiment !\p"
	.string "Mais, dis donc, tu es fort !\n"
	.string "Hahaha !$"

Route132_Text_GilbertIntro:
	.string "J'attrapais tout le temps froid enfant, mais\n"
	.string "je suis devenu super en forme après\l"
	.string "avoir commencé à nager.$"

Route132_Text_GilbertDefeat:
	.string "Je veux plus de puissance…$"

Route132_Text_GilbertPostBattle:
	.string "Les DRESSEURS voyagent dans les champs et\n"
	.string "les montagnes, ils doivent être en forme aussi.$"

Route132_Text_DanaIntro:
	.string "J'évite de nager là où le courant\n"
	.string "est trop fort.$"

Route132_Text_DanaDefeat:
	.string "Oh, non, pitié !$"

Route132_Text_DanaPostBattle:
	.string "Si je me fais emporter, je perdrai\n"
	.string "tous mes repères…$"

Route132_Text_RonaldIntro:
	.string "Gagner ou perdre, tu ne sauras jamais\n"
	.string "tant que tu n'essaies pas !$"

Route132_Text_RonaldDefeat:
	.string "Ouah !\n"
	.string "J'ai coulé !$"

Route132_Text_RonaldPostBattle:
	.string "Je ne combats jamais quand je sais que je vais gagner.\n"
	.string "J'aime me battre sur le fil du rasoir !$"

Route132_Text_KiyoIntro:
	.string "Je pense aux POKéMON 24h/24.\n"
	.string "Comment pourrais-tu me battre ?$"

Route132_Text_KiyoDefeat:
	.string "J'ai perdu.\n"
	.string "Je concède la défaite.$"

Route132_Text_KiyoPostBattle:
	.string "Urgh…\n"
	.string "Tu es un fanatique de POKéMON, non ?\p"
	.string "Tu dois penser aux POKéMON 24h/24, toi aussi !$"

Route132_Text_MakaylaIntro:
	.string "Je suis toujours avec mon mari,\n"
	.string "mais je peux gagner même sans lui.$"

Route132_Text_MakaylaDefeat:
	.string "Oh, je n'étais pas assez forte.$"

Route132_Text_MakaylaPostBattle:
	.string "Ce jeune homme là-bas ressemble à mon mari\n"
	.string "quand il était jeune.\p"
	.string "Ça me fait rougir !$"

Route132_Text_JonathanIntro:
	.string "Quelqu'un m'observe attentivement.\n"
	.string "C'est toi ?$"

Route132_Text_JonathanDefeat:
	.string "Ouah !\n"
	.string "Tu es vraiment fort !$"

Route132_Text_JonathanPostBattle:
	.string "Je n'arrive pas à me défaire de l'impression\n"
	.string "qu'on m'observe.\p"
	.string "Je n'arrive pas à me concentrer !$"

Route132_Text_PaxtonIntro:
	.string "Où est passée ma femme ?\n"
	.string "Je suis toujours avec elle.\l"
	.string "Je me demande si je peux gagner seul.$"

Route132_Text_PaxtonDefeat:
	.string "Ah, je vois que je n'ai pas pu gagner\n"
	.string "tout seul finalement.$"

Route132_Text_PaxtonPostBattle:
	.string "Ma femme doit me chercher.\n"
	.string "Je ferais mieux d'aller la retrouver vite.$"

Route132_Text_DarcyIntro:
	.string "J'aimais m'entraîner ici tout seul.\n"
	.string "C'est nul que tout le monde soit venu !$"

Route132_Text_DarcyDefeat:
	.string "D'accord ! Je ne me plaindrai plus\n"
	.string "de la présence des autres.$"

Route132_Text_DarcyPostBattle:
	.string "Je pourrais peut-être faire équipe avec ce\n"
	.string "vieux monsieur et défier l'autre duo.$"

Route133_Text_FranklinIntro:
	.string "Le courant t'a amené ici aussi ?\n"
	.string "C'était le destin.\l"
	.string "Combattons !$"

Route133_Text_FranklinDefeat:
	.string "Fort !\n"
	.string "Trop fort !$"

Route133_Text_FranklinPostBattle:
	.string "Il fallait que ce soit un DRESSEUR fort\n"
	.string "comme toi qui dérive ici…\l"
	.string "Je dois être maudit…$"

Route133_Text_DebraIntro:
	.string "J'ai eu une vie de malheur…\n"
	.string "J'ai été rejetée, et j'ai échoué ici…$"

Route133_Text_DebraDefeat:
	.string "Encore une défaite…$"

Route133_Text_DebraPostBattle:
	.string "Une vie à la dérive…\n"
	.string "Je n'en veux plus !$"

Route133_Text_LindaIntro:
	.string "Bienvenue !\n"
	.string "Je t'attendais !$"

Route133_Text_LindaDefeat:
	.string "Non ! Pitié !$"

Route133_Text_LindaPostBattle:
	.string "Un jeune DRESSEUR fort…\n"
	.string "C'est agaçant !$"

Route133_Text_WarrenIntro:
	.string "Je veux gagner comme tout le monde, mais\n"
	.string "je n'élèverai pas mes POKéMON comme les autres.$"

Route133_Text_WarrenDefeat:
	.string "Zut !\n"
	.string "Ma méthode est encore trop molle !$"

Route133_Text_WarrenPostBattle:
	.string "C'est bien plus amusant de faire à ma façon\n"
	.string "que d'imiter tout le monde.\l"
	.string "C'est évident !$"

Route133_Text_BeckIntro:
	.string "Je suis venu jusqu'ici avec mes\n"
	.string "POKéMON OISEAU.$"

Route133_Text_BeckDefeat:
	.string "Toi…\n"
	.string "Tu es incroyablement cool !$"

Route133_Text_BeckPostBattle:
	.string "J'aimerais retourner à CLEMENTI-VILLE,\n"
	.string "mais j'aime bien cet endroit aussi.$"

Route133_Text_MollieIntro:
	.string "J'ai dû combattre des milliers de fois.\n"
	.string "J'ai perdu le compte.$"

Route133_Text_MollieDefeat:
	.string "J'ai peut-être perdu des milliers de fois,\n"
	.string "mais une défaite fait toujours mal.$"

Route133_Text_MolliePostBattle:
	.string "Continue comme ça, jeune. Pour devenir\n"
	.string "comme mon mari et moi.$"

Route133_Text_ConorIntro:
	.string "Les jeunes suivent trop facilement le courant.\n"
	.string "Ils manquent de direction.$"

Route133_Text_ConorDefeat:
	.string "Tu as un vrai sens du but.$"

Route133_Text_ConorPostBattle:
	.string "Ne laisse pas les autres t'égarer.\n"
	.string "Ne perds pas ta direction en vieillissant.$"

Route134_Text_JackIntro:
	.string "Même les POKéMON qui savent nager sont\n"
	.string "emportés par les courants rapides.$"

Route134_Text_JackDefeat:
	.string "Aïe !$"

Route134_Text_JackPostBattle:
	.string "Je pense que les POKéMON aiment les courants\n"
	.string "rapides de cette région.$"

Route134_Text_LaurelIntro:
	.string "Mes LOVDISC cherchent un combat sympa.\n"
	.string "Tu veux nous rejoindre ?$"

Route134_Text_LaurelDefeat:
	.string "Oups !$"

Route134_Text_LaurelPostBattle:
	.string "Il y a un collectionneur qui veut\n"
	.string "les ÉCAILLES de LOVDISC.$"

Route134_Text_AlexIntro:
	.string "Allez, c'est fini la pause, tout le monde !\n"
	.string "C'est l'heure du combat !$"

Route134_Text_AlexDefeat:
	.string "Épuisé encore une fois…$"

Route134_Text_AlexPostBattle:
	.string "Mes POKéMON OISEAU se fatiguent vite après\n"
	.string "un long vol…$"

Route134_Text_HitoshiIntro:
	.string "Tu es un DRESSEUR POKéMON.\n"
	.string "Pas besoin de mots. On se bat maintenant !$"

Route134_Text_HitoshiDefeat:
	.string "… … … … … …\n"
	.string "… … … … … …$"

Route134_Text_HitoshiPostBattle:
	.string "C'est moi qui t'ai défié, et pourtant\n"
	.string "j'ai perdu. J'ai honte…$"

Route134_Text_AaronIntro:
	.string "La marée sauvage de cette zone nous rend\n"
	.string "plus forts que jamais.$"

Route134_Text_AaronDefeat:
	.string "J'accepte volontiers la défaite.$"

Route134_Text_AaronPostBattle:
	.string "On retournera s'entraîner à la CHUTE Météore.\p"
	.string "Si tu veux, viens aussi.\n"
	.string "Ça te rendra plus fort !$"

Route134_Text_KelvinIntro:
	.string "N-notre bateau !\n"
	.string "La marée l'a emporté !$"

Route134_Text_KelvinDefeat:
	.string "Awawawawah !\n"
	.string "Arrête, s'il te plaît !$"

Route134_Text_KelvinPostBattle:
	.string "Si on ne peut pas SURFER, comment rentrer ?\p"
	.string "En fait, je sais qu'un POKéMON K.O. peut\n"
	.string "quand même SURFER, mais ça me gêne.$"

Route134_Text_MarleyIntro:
	.string "Tes POKéMON peuvent-ils esquiver nos\n"
	.string "attaques ultra-rapides ?$"

Route134_Text_MarleyDefeat:
	.string "Je ne savais pas qu'une telle technique existait !\n"
	.string "Tu nous as complètement battus.$"

Route134_Text_MarleyPostBattle:
	.string "Je n'ai pas perdu ma passion pour la vitesse.\n"
	.string "Je vais m'entraîner plus dur.$"

Route134_Text_ReynaIntro:
	.string "Mes POKéMON ne se laissent pas\n"
	.string "battre facilement !$"

Route134_Text_ReynaDefeat:
	.string "Tu plaisantes !\n"
	.string "Explique-moi comment j'ai perdu !$"

Route134_Text_ReynaPostBattle:
	.string "Haha !\n"
	.string "Tu as gagné, c'est sûr !\p"
	.string "Je vais remonter la pente en affrontant\n"
	.string "tous les DRESSEURS que je croise !$"

Route134_Text_HudsonIntro:
	.string "Dis, tu as vu un autre MARIN\n"
	.string "dans le coin ?$"

Route134_Text_HudsonDefeat:
	.string "Ça alors !$"

Route134_Text_HudsonPostBattle:
	.string "Notre bateau a dérivé au large.\p"
	.string "Mon pote est un gars timide, alors je\n"
	.string "m'inquiète pour lui.$"
