EcruteakTheater_MapScripts::
	.byte 0


EcruteakTheater_Text_Rocket1:
	.string "Stop dancing such a serious\n"
	.string "dance! Show me something like\n"
	.string "a hula dance!$"

EcruteakTheater_Text_KimonoRocket1:
	.string "...You mustn't push such a\n"
	.string "request on me.$"

EcruteakTheater_Text_Rocket2:
	.string "Huh?\n"
	.string "Are you telling me you don't\l"
	.string "respect what the customer\n"
	.string "wants?$"

EcruteakTheater_Text_Rocket3:
	.string "Well, then I'll show you how\n"
	.string "to dance. I'll show you a\n"
	.string "great one.\n"
	.string "Wahahaha!$"

EcruteakTheater_Text_RocketSeen:
	.string "Huh? Who are you?\n"
	.string "You dare to get in my way?$"

EcruteakTheater_Text_RocketBeaten:
	.string "Oh, no!\n"
	.string "You make me look like a\n"
	.string "villain!$"

EcruteakTheater_Text_RocketAfter:
	.string "Oops! I have an important\n"
	.string "mission. If they find out I\l"
	.string "was wasting time here,\n"
	.string "they'll make me start over\l"
	.string "as the lowest Team Rocket\n"
	.string "Grunt!\p"
	.string "I better leave now!$"

EcruteakTheater_Text_KimonoGirlBeaten:
	.string "...$"

EcruteakTheater_Text_KimonoRocket3:
	.string "You must be {PLAYER},\n"
	.string "correct? That was indeed\l"
	.string "excellent.\p"
	.string "Kind and strong... Good at\n"
	.string "raising POKéMON as well...\p"
	.string "That person does know what\n"
	.string "to look for in people...\p"
	.string "Ohoho! That was just me\n"
	.string "talking to myself.\l"
	.string "Never mind.$"

EcruteakTheater_Text_Kimono:
	.string "For Kimono Girls like me,\n"
	.string "dancing is everything.\p"
	.string "I have never gone a day\n"
	.string "without a dance practice.\p"
	.string "POKéMON are the same.\n"
	.string "They grow with you little\n"
	.string "by little each day.$"

EcruteakTheater_Text_ZukiSeen:
	.string "Welcome. My name is ZUKI.\n"
	.string "I met you previously in\l"
	.string "VIOLET CITY.\p"
	.string "To bring back HO-OH, we\n"
	.string "needed someone with the\l"
	.string "right bond with POKéMON.\p"
	.string "We asked Mr. POKéMON to\n"
	.string "give this Mystery Egg to\l"
	.string "whoever showed potential.\p"
	.string "The Egg went from MR.\n"
	.string "POKéMON to PROF. ELM, then\l"
	.string "to you.\p"
	.string "But being pure alone is not\n"
	.string "enough to face the power\l"
	.string "of this POKéMON.\p"
	.string "I must test you.\n"
	.string "Are you ready? {PLAYER}$"

EcruteakTheater_Text_ZukiSeenAgain:
	.string "I will test you to see if\n"
	.string "you are a good Trainer.\n"
	.string "Are you ready? VAR(512, 0)$"

EcruteakTheater_Text_ZukiNo:
	.string "That is fine...\n"
	.string "I will wait for you to get\n"
	.string "ready.$"

EcruteakTheater_Text_NaokoSeen:
	.string "You are quite strong. You\n"
	.string "helped me in the ILEX FOREST.\p"
	.string "I'm NAOKO--not so good with\n"
	.string "directions.\p"
	.string "I saw you defeat Team Rocket\n"
	.string "when Kurt was in trouble at\l"
	.string "the SLOWPOKE Well.\p"
	.string "Let me challenge you and your\n"
	.string "POKéMON!$"

EcruteakTheater_Text_MikiSeen:
	.string "You're quite the Trainer. I\n"
	.string "remember you chased off that\l"
	.string "Rocket Grunt from right here.\p"
	.string "Thank you for that.\p"
	.string "Though, I'm a Trainer too.\n"
	.string "She who knows the most speaks\l"
	.string "the least!\p"
	.string "I am MIKI--the Kimono Girl!\p"
	.string "Let me challenge you and your\n"
	.string "POKéMON!$"

EcruteakTheater_Text_SayoSeen:
	.string "Excellent spirit! You got me\n"
	.string "off the ice by pushing me.\p"
	.string "I skate in sandals.\n"
	.string "I am SAYO--the Kimono Girl!\p"
	.string "I listened in the Dragon's Den\n"
	.string "when you passed the Elder's\l"
	.string "test.\p"
	.string "Let me challenge you and your\n"
	.string "POKéMON!$"

EcruteakTheater_Text_KuniSeen:
	.string "I'm the last one.\n"
	.string "You were dependable at the\n"
	.string "Goldenrod Tunnel.\p"
	.string "I'm the one who twirls even\n"
	.string "underground--Kuni!\p"
	.string "I saw you thwart Rocket's\n"
	.string "plan to take the Radio Tower.\p"
	.string "Now show me your strength!\n"
	.string "Let me challenge you and your\l"
	.string "POKéMON!$"

EcruteakTheater_Text_KuniAfter:
	.string "Talk to Zuki in the middle\n"
	.string "when you are ready.$"

EcruteakTheater_Text_ZukiDone:
	.string "We were not wrong about you.\n"
	.string "You are indeed worthy of this...\p"
	.string "Please take it.$"

EcruteakTheater_Text_GirlHooh:
	.string "Big sisters! I just saw the\n"
	.string "big shadow of a POKéMON over\n"
	.string "the Bell Tower!\p"
	.string "It could be...$"

EcruteakTheater_Text_GirlLugia:
	.string "Big sisters! I just saw the\n"
	.string "big shadow of a POKéMON in the\n"
	.string "Whirl Islands' waters!\p"
	.string "It could be...$"

EcruteakTheater_Text_ZukiHooh:
	.string "ZUKI: {PLAYER}!\n"
	.string "We'll be at the Bell Tower.\n"
	.string "See you there!$"

EcruteakTheater_Text_ZukiLugia:
	.string "ZUKI: {PLAYER}!\n"
	.string "We'll be at the Whirl Islands.\n"
	.string "See you there!$"

EcruteakTheater_Text_SurfGuyRocket:
	.string "What's the deal with that\n"
	.string "Team Rocket Grunt, messing\n"
	.string "with my Kimono Girl?\p"
	.string "You are a Trainer, right?\n"
	.string "Please help her!$"

EcruteakTheater_Text_SurfGuyGiveSurf:
	.string "Wonderful! You were so\n"
	.string "courageous for your age!\p"
	.string "It was a rare sight to see!\n"
	.string "I want you to have this.\p"
	.string "Don't be shy--take it!$"

EcruteakTheater_Text_SurfGuyGaveSurf:
	.string "That's Surf.\n"
	.string "It's a move that lets POKéMON\n"
	.string "swim across water with ease.$"

EcruteakTheater_Text_SurfGuyAfter:
	.string "Not only are the Kimono Girls\n"
	.string "great dancers, they're also\n"
	.string "skilled at POKéMON.\p"
	.string "But they battle only for good\n"
	.string "reasons.\p"
	.string "I don't know if you could beat\n"
	.string "them if they showed their skill...$"

EcruteakTheater_Text_Psyduck:
	.string "PSYDUCK: Dau dau!$"

EcruteakTheater_Text_BoyBefore:
	.string "eeeeek!$"

EcruteakTheater_Text_Boy:
	.string "I was supposed to be the hero...!\n"
	.string "So much for getting close to\n"
	.string "a Kimono Girl!$"

EcruteakTheater_Text_Granny:
	.string "That man's always with his\n"
	.string "PSYDUCK.\p"
	.string "Says he wants a POKéMON that\n"
	.string "can Surf and dance.\p"
	.string "Is he trying to make a POKéMON\n"
	.string "that stars in synchronized\n"
	.string "swimming?$"

EcruteakTheater_Text_GrannyBefore:
	.string "Oh... Ouch...!\n"
	.string "This stomachache!\p"
	.string "I wouldn't let this guy act like\n"
	.string "that if not for this pain...!$"

EcruteakTheater_Text_Gramps:
	.string "The Kimono Girls are so\n"
	.string "beautiful...\p"
	.string "But they have to go through\n"
	.string "rigorous training.\p"
	.string "And they have to learn to follow\n"
	.string "customs before appearing in\n"
	.string "public.\p"
	.string "But if you love something,\n"
	.string "anything is possible.$"

EcruteakTheater_Text_GrampsBefore:
	.string "Oh... Ouch...!\n"
	.string "This back pain!\p"
	.string "I wouldn't let this guy act like\n"
	.string "that if not for this pain...!$"

EcruteakTheater_Text_Girl:
	.string "The KIMONO GIRLS are my big\n"
	.string "sisters! I'll be like them one\l"
	.string "day!$"

EcruteakTheater_Text_GirlBefore:
	.string "I like that funny dance!$"

EcruteakTheater_Text_KimonoDone:
	.string "We are rehearsing a dance.$"

EcruteakTheater_Text_ZukiDone:
	.string "Thank you for your help the\n"
	.string "other day.\p"
	.string "You've shown the bond between\n"
	.string "people can grow with POKéMON...\p"
	.string "We appreciate how you lived up\n"
	.string "to our hopes, VAR(259, 0, 0)!\p"
	.string "If you learned anything from\n"
	.string "this, thank Mr. POKéMON and\n"
	.string "Professor Elm...$"
