SaffronCity_Mart_MapScripts::
	.byte 0

SafronMart_EventScript_CooltrainerM::
	msgbox SaffronMart_Text_CooltrainerM, MSGBOX_NPC
	end
SafronMart_EventScript_CooltrainerF::
	msgbox SaffronMart_Text_CooltrainerF, MSGBOX_NPC
	end
SaffronMart_Text_CooltrainerM:
	.string "Il y a une grande TOUR RADIO à\n"
	.string "LAVANVILLE.$"

SaffronMart_Text_CooltrainerF:
	.string "Je veux devenir plus forte, mais\n"
	.string "je ne suis pas encore très douée…\p"
	.string "Tu pourrais me montrer comment faire un jour ?$"
