NationalParkGates_MapScripts::
	.byte 0

Route35NationalParkGate_Text_OfficerAskToParticipate:
	.string "Hello Trainer! The Bug-Catching\n"
	.string "Contest is on today.\p"
	.string "The rules are simple.\p"
	.string "Using one of your POKéMON, catch a\n"
	.string "bug POKéMON to be judged.\p"
	.string "Would you like to give it a try?$"

Route35NationalParkGate_Text_OfficerGiveParkBalls:
	.string "Here are the PARK BALLS for the\n"
	.string "Contest.$"

Route35NationalParkGate_Text_ReceivedParkBalls:
	.string "{PLAYER} received SAFARI BALLS\n"
	.string "PARK BALLS.$"

Route35NationalParkGate_Text_OfficerExplainRules:
	.string "The person who gets the strongest\n"
	.string "bug POKéMON is the winner.\p"
	.string "You have minutes.\p"
	.string "If you run out of PARK BALLS, you're\n"
	.string "done.\p"
	.string "You can keep the last POKéMON you\n"
	.string "catch as your own.\p"
	.string "Go out and catch the strongest bug\n"
	.string "POKéMON you can find!$"

Route35NationalParkGate_Text_OfficerAskToUseFirstMon:
	.string "Uh-oh…\p"
	.string "You have more than one POKéMON.\p"
	.string "You'll have to use the\n"
	.string "first POKéMON in your party.\p"
	.string "Is that OK with you?$"

Route35NationalParkGate_Text_OfficerHoldYourMon:
	.string "Fine, we'll hold your other POKéMON\n"
	.string "while you compete.$"

Route35NationalParkGate_Text_MonLeftWithHelper:
	.string "{PLAYER}'s POKéMON were left with the\n"
	.string "CONTEST HELPER.$"

Route35NationalParkGate_Text_ChooseMonAndComeBack:
	.string "Please choose the POKéMON to be used\n"
	.string "in the Contest, then come see me.$"

Route35NationalParkGate_Text_TakePartInFuture:
	.string "OK. We hope you'll take part in the\n"
	.string "future.$"

Route35NationalParkGate_Text_FirstMonCantBattle:
	.string "Uh-oh… The first POKéMON in your\n"
	.string "party can't battle.\p"
	.string "Please switch it with the POKéMON\n"
	.string "you want to use, then come see me.$"

Route35NationalParkGate_Text_MakeRoom:
	.string "Uh-oh… Both your party and your\n"
	.string "PC BOX are full.\p"
	.string "You have no room to put the bug\n"
	.string "POKéMON you catch.\p"
	.string "Please make room in your party or\n"
	.string "your PC BOX, then come see me.$"

Route35NationalParkGate_Text_EggAsFirstMon:
	.string "Uh-oh… You have an EGG as the first\n"
	.string "POKéMON in your party.\p"
	.string "Please switch it with the POKéMON\n"
	.string "you want to use, then come see me.$"

Route35NationalParkGate_Text_WantToFinish:
	.string "You still have minute(s)\n"
	.string "left.\p"
	.string "Do you want to finish now?$"

Route35NationalParkGate_Text_WaitAtNorthGate:
	.string "OK. Please wait at the North Gate for\n"
	.string "the announcement of the winners.$"

Route35NationalParkGate_Text_OkGoFinish:
	.string "OK. Please get back outside and\n"
	.string "finish up.$"

Route35NationalParkGate_Text_ContestIsOver:
	.string "Today's Contest is over. We hope you\n"
	.string "will participate in the future.$"

Route35NationalParkGate_Text_WeHoldContests:
	.string "We hold Contests regularly in the\n"
	.string "PARK. You should give it a shot.$"

Route35NationalParkGate_Text_YoungsterWonders:
	.string "When is the next Bug-Catching Contest\n"
	.string "going to be?$"

Route35NationalParkGate_Text_ContestExplanation:
	.string "The Bug-Catching Contest is held on\n"
	.string "Tuesday, Thursday and Saturday.\p"
	.string "Not only do you earn a prize just\n"
	.string "for participating,\p"
	.string "you also get to keep the bug POKéMON\n"
	.string "you may have at the end of the contest.$"
