NationalParkGates_MapScripts::
	.byte 0

NationalParkGates_EventScript_Attendant::
	lock
	faceplayer
	goto_if_set FLAG_DAILY_BUG_CONTEST_COMPLETED, NationalParkGates_EventScript_AttendantAlreadyPlayed
	msgbox Route35NationalParkGate_Text_OfficerAskToParticipate, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, TRUE, NationalParkGates_EventScript_AttendantStart
	msgbox Route35NationalParkGate_Text_TakePartInFuture, MSGBOX_DEFAULT
	release
	end

NationalParkGates_EventScript_AttendantStart::
	msgbox Route35NationalParkGate_Text_OfficerAskToUseFirstMon, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, FALSE, NationalParkGates_EventScript_AttendantCancel
	getpartysize
	call_if_eq VAR_RESULT, 1, NationalParkGates_EventScript_OnlyOneMon
	msgbox Route35NationalParkGate_Text_OfficerHoldYourMon, MSGBOX_DEFAULT
	closemessage
	special SavePlayerParty
	remove5mons
	goto_if_eq VAR_RESULT, MON_CANT_GIVE, NationalParkGates_EventScript_AttendantFaint
	playfanfare MUS_OBTAIN_ITEM
	message Route35NationalParkGate_Text_MonLeftWithHelper
	waitfanfare
	closemessage
	msgbox Route35NationalParkGate_Text_OfficerGiveParkBalls, MSGBOX_DEFAULT
	closemessage
	giveitem ITEM_SAFARI_BALL, 30
	closemessage
	msgbox Route35NationalParkGate_Text_OfficerExplainRules, MSGBOX_DEFAULT
	closemessage
	call_if_eq VAR_FACING, DIR_WEST, NationalParkGates_EventScript_AttendantEnterTop
	call_if_eq VAR_FACING, DIR_NORTH, NationalParkGates_EventScript_AttendantEnterBot
	playse SE_EXIT
	clearflag FLAG_HIDE_BUG_CONTEST_ATTENDANT_SIDE
	special EnterBugContestMode
	warp MAP_NATIONAL_PARK2, 1
	setvar VAR_BUG_CONTEST_STATE, 1
	release
	end

NationalParkGates_EventScript_OnlyOneMon::
	special SavePlayerParty
	msgbox Route35NationalParkGate_Text_OfficerGiveParkBalls, MSGBOX_DEFAULT
	closemessage
	giveitem ITEM_SAFARI_BALL, 30
	closemessage
	msgbox Route35NationalParkGate_Text_OfficerExplainRules, MSGBOX_DEFAULT
	closemessage
	call_if_eq VAR_FACING, DIR_WEST, NationalParkGates_EventScript_AttendantEnterTop
	call_if_eq VAR_FACING, DIR_NORTH, NationalParkGates_EventScript_AttendantEnterBot
	playse SE_EXIT
	clearflag FLAG_HIDE_BUG_CONTEST_ATTENDANT_SIDE
	special EnterBugContestMode
	warp MAP_NATIONAL_PARK2, 1
	setvar VAR_BUG_CONTEST_STATE, 1
	release
	end

NationalParkGates_EventScript_AttendantEnterTop::
	applymovement OBJ_EVENT_ID_PLAYER, NationalParkGates_Movement_Player_EnterParkTop
	waitmovement 0
	return

NationalParkGates_EventScript_AttendantEnterBot::
	applymovement OBJ_EVENT_ID_PLAYER, NationalParkGates_Movement_Player_EnterParkBot
	waitmovement 0
	return


NationalParkGates_EventScript_AttendantFaint::	
	msgbox Route35NationalParkGate_Text_FirstMonCantBattle, MSGBOX_DEFAULT
	closemessage
	release
	end	

NationalParkGates_EventScript_AttendantCancel::	
	msgbox Route35NationalParkGate_Text_TakePartInFuture, MSGBOX_DEFAULT
	closemessage
	release
	end

NationalParkGates_EventScript_AttendantAlreadyPlayed::
	msgbox Route35NationalParkGate_Text_ContestIsOver, MSGBOX_DEFAULT
	closemessage
	release
	end

NationalParkGates_EventScript_AttendantExit::
	special LoadPlayerParty
	setvar VAR_BUG_CONTEST_STATE, 0
	release
	end

NationalParkGates_Movement_Player_EnterParkTop:
	walk_down
	walk_right
	walk_right
	walk_right
	walk_up
	walk_up
	step_end

NationalParkGates_Movement_Player_EnterParkBot:
	walk_right
	walk_right
	walk_right
	walk_right
	walk_up
	walk_up
	step_end

NationalParkGates_EventScript_BAttendant::
	lock
	faceplayer
	goto_if_set FLAG_DAILY_BUG_CONTEST_COMPLETED, NationalParkGates_EventScript_AttendantAlreadyPlayed
	msgbox Route35NationalParkGate_Text_OfficerAskToParticipate, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, TRUE, NationalParkGates_EventScript_BAttendantStart
	msgbox Route35NationalParkGate_Text_TakePartInFuture, MSGBOX_DEFAULT
	release
	end

NationalParkGates_EventScript_BAttendantStart::
	msgbox Route35NationalParkGate_Text_OfficerAskToUseFirstMon, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, FALSE, NationalParkGates_EventScript_AttendantCancel
	getpartysize
	call_if_eq VAR_RESULT, 1, NationalParkGates_EventScript_OnlyOneMonB
	msgbox Route35NationalParkGate_Text_OfficerHoldYourMon, MSGBOX_DEFAULT
	closemessage
	special SavePlayerParty
	remove5mons
	goto_if_eq VAR_RESULT, MON_CANT_GIVE, NationalParkGates_EventScript_AttendantFaint
	playfanfare MUS_OBTAIN_ITEM
	message Route35NationalParkGate_Text_MonLeftWithHelper
	waitfanfare
	closemessage
	msgbox Route35NationalParkGate_Text_OfficerGiveParkBalls, MSGBOX_DEFAULT
	closemessage
	giveitem ITEM_SAFARI_BALL, 30
	closemessage
	msgbox Route35NationalParkGate_Text_OfficerExplainRules, MSGBOX_DEFAULT
	closemessage
	call_if_eq VAR_FACING, DIR_EAST, NationalParkGates_EventScript_AttendantBEnterTop
	call_if_eq VAR_FACING, DIR_NORTH, NationalParkGates_EventScript_AttendantBEnterBot
	playse SE_EXIT
	special EnterBugContestMode
	setflag FLAG_HIDE_BUG_CONTEST_ATTENDANT_SIDE
	warp MAP_NATIONAL_PARK2, 2
	setvar VAR_BUG_CONTEST_STATE, 5
	release
	end

NationalParkGates_EventScript_OnlyOneMonB::
	special SavePlayerParty
	msgbox Route35NationalParkGate_Text_OfficerGiveParkBalls, MSGBOX_DEFAULT
	closemessage
	giveitem ITEM_SAFARI_BALL, 30
	closemessage
	msgbox Route35NationalParkGate_Text_OfficerExplainRules, MSGBOX_DEFAULT
	closemessage
	call_if_eq VAR_FACING, DIR_EAST, NationalParkGates_EventScript_AttendantBEnterTop
	call_if_eq VAR_FACING, DIR_NORTH, NationalParkGates_EventScript_AttendantBEnterBot
	playse SE_EXIT
	special EnterBugContestMode
	setflag FLAG_HIDE_BUG_CONTEST_ATTENDANT_SIDE
	warp MAP_NATIONAL_PARK2, 2
	setvar VAR_BUG_CONTEST_STATE, 5
	release
	end

NationalParkGates_EventScript_AttendantBEnterTop::
	applymovement OBJ_EVENT_ID_PLAYER, NationalParkGates_Movement_Player_EnterParkTopB
	waitmovement 0
	return

NationalParkGates_EventScript_AttendantBEnterBot::
	applymovement OBJ_EVENT_ID_PLAYER, NationalParkGates_Movement_Player_EnterParkBotB
	waitmovement 0
	return

NationalParkGates_Movement_Player_EnterParkTopB:
	walk_down
	walk_down
	walk_down
	walk_down
	walk_down
	walk_left
	walk_left
	walk_left
	walk_in_place_left
	step_end

NationalParkGates_Movement_Player_EnterParkBotB:
	walk_down
	walk_down
	walk_down
	walk_down
	walk_left
	walk_left
	walk_left
	walk_left
	walk_in_place_left
	step_end

Route35NationalParkGate_Text_OfficerAskToParticipate:
	.string "Hello Trainer! The Bug-Catching\n"
	.string "Contest is on today.\p"
	.string "The rules are simple.\p"
	.string "Using one of your POKéMON, catch a\n"
	.string "bug POKéMON to be judged.\p"
	.string "Would you like to give it a try?$"

Route35NationalParkGate_Text_OfficerGiveParkBalls:
	.string "Here are the SAFARI BALLS for the\n"
	.string "Contest.$"

Route35NationalParkGate_Text_ReceivedParkBalls:
	.string "{PLAYER} received SAFARI BALLS.$"

Route35NationalParkGate_Text_OfficerExplainRules:
	.string "The person who gets the strongest\n"
	.string "bug POKéMON is the winner.\p"
	.string "If you run out of SAFARI BALLS,\n"
	.string "you're done.\p"
	.string "You can catch up to 5 POKéMON. The\n"
	.string "last one caught will be the only\l"
	.string "one kept and placed in the contest.\p"
	.string "Go out and catch the strongest bug\n"
	.string "POKéMON you can find!$"

Route35NationalParkGate_Text_OfficerAskToUseFirstMon:
	.string "If you have more than one POKéMON,\n"
	.string "you'll have to use the\l"
	.string "first POKéMON in your party.\p"
	.string "Is that OK with you?$"

Route35NationalParkGate_Text_OfficerHoldYourMon:
	.string "Fine, we'll hold your other POKéMON\n"
	.string "while you compete.$"

Route35NationalParkGate_Text_MonLeftWithHelper:
	.string "{PLAYER}'s POKéMON were left with the\n"
	.string "CONTEST HELPER.$"

Route35NationalParkGate_Text_ChooseMonAndComeBack:
	.string "Please choose the POKéMON to be used\n"
	.string "in the Contest, then come see me.$"

Route35NationalParkGate_Text_TakePartInFuture:
	.string "OK. We hope you'll take part in the\n"
	.string "future.$"

Route35NationalParkGate_Text_FirstMonCantBattle:
	.string "Uh-oh… The first POKéMON in your\n"
	.string "party can't battle.\p"
	.string "Please switch it with the POKéMON\n"
	.string "you want to use, then come see me.$"

Route35NationalParkGate_Text_MakeRoom:
	.string "Uh-oh… Both your party and your\n"
	.string "PC BOX are full.\p"
	.string "You have no room to put the bug\n"
	.string "POKéMON you catch.\p"
	.string "Please make room in your party or\n"
	.string "your PC BOX, then come see me.$"

Route35NationalParkGate_Text_EggAsFirstMon:
	.string "Uh-oh… You have an EGG as the first\n"
	.string "POKéMON in your party.\p"
	.string "Please switch it with the POKéMON\n"
	.string "you want to use, then come see me.$"

Route35NationalParkGate_Text_ContestIsOver:
	.string "Today's Contest is over. We hope you\n"
	.string "will participate in the future.$"

Route35NationalParkGate_EventScript_Policeman::
	lock
	faceplayer
	msgbox Route35NationalParkGate_Text_WeHoldContests, MSGBOX_DEFAULT
	closemessage
	release
	end

Route35NationalParkGate_EventScript_BC1::
	lock
	faceplayer
	msgbox Route35NationalParkGate_Text_YoungsterWonders, MSGBOX_DEFAULT
	closemessage
	release
	end

Route35NationalParkGate_EventScript_BC2::
	lock
	faceplayer
	msgbox Route35NationalParkGate_Text_BC2, MSGBOX_DEFAULT
	closemessage
	release
	end

Route35NationalParkGate_EventScript_Rocker::
	lock
	faceplayer
	msgbox Route35NationalParkGate_Text_Rocker, MSGBOX_DEFAULT
	closemessage
	release
	end

Route35NationalParkGate_EventScript_Beauty::
	lock
	faceplayer
	msgbox Route35NationalParkGate_Text_Beauty, MSGBOX_DEFAULT
	closemessage
	release
	end

Route35NationalParkGate_Text_Rocker:
	.string "I love bird POKéMON! I found a\n"
	.string "DARK-TYPE bird in the park\l"
	.string "last night!$"

Route35NationalParkGate_Text_BC2:
	.string "I caught a whopping SCYTHER!$"

Route35NationalParkGate_Text_Beauty:
	.string "He always wins these contests!$"

Route35NationalParkGate_Text_WeHoldContests:
	.string "We hold Contests regularly in the\n"
	.string "PARK. You should give it a shot.$"

Route35NationalParkGate_Text_YoungsterWonders:
	.string "When is the next Bug-Catching Contest\n"
	.string "going to be?$"

Route35NationalParkGate_Text_ContestExplanation:
	.string "The Bug-Catching Contest is held on\n"
	.string "Tuesday, Thursday and Saturday.\p"
	.string "Not only do you earn a prize just\n"
	.string "for participating,\p"
	.string "you also get to keep the bug POKéMON\n"
	.string "you may have at the end of the contest.$"
