VermilionCityHouse2_MapScripts::
	.byte 0

VermilionCityHouse2_EventScript_PokefanF::
	msgbox VermilionCityHouse2_Text_PokefanF, MSGBOX_NPC
	end

VermilionCityHouse2_EventScript_Youngster::
	msgbox VermilionCityHouse2_Text_Youngster, MSGBOX_NPC
	end

VermilionCityHouse2_Text_PokefanF:
	.string "Do you know about the MAGNET\n"
	.string "TRAIN?\p"
	.string "It's a railway that goes to\n"
	.string "GOLDENROD in JOHTO.$"

VermilionCityHouse2_Text_Youngster:
	.string "I want to go to SAFFRON to see\n"
	.string "the MAGNET TRAIN.$"
