VermilionCityHouse1_MapScripts::
	.byte 0

VermilionCityHouse1_EventScript_Fisher::
	msgbox VermilionCityHouse1_Text_FishingDude, MSGBOX_NPC
	end
VermilionCityHouse1_EventScript_Photo::
	msgbox VermilionCityHouse1_Text_Photo, MSGBOX_NPC
	end
VermilionCityHouse1_Text_FishingDude:
	.string "I am the FISHING DUDE, the elder\n"
	.string "of the FISHING BROS.\p"
	.string "Have you met the FISHING GURU at\n"
	.string "LAKE OF RAGE?\p"
	.string "He dreams about seeing the\n"
	.string "world's greatest MAGIKARP.\p"
	.string "If you don't mind, could you show\n"
	.string "him any MAGIKARP you catch?\p"
	.string "Who knows, you may catch the\n"
	.string "MAGIKARP of his dreams.$"

VermilionCityHouse1_Text_Photo:
	.string "It's a photo of people fishing…\p"
	.string "They're having a great time…$"
