OldaleTown_House1_MapScripts::
	.byte 0

OldaleTown_House1_EventScript_Woman::
	msgbox OldaleTown_House1_Text_LeftPokemonGoesOutFirst, MSGBOX_NPC
	end

OldaleTown_House1_Text_LeftPokemonGoesOutFirst:
	.string "Quand un combat de POKéMON commence, celui\n"
	.string "à gauche de la liste sort en premier.\p"
	.string "Alors, quand tu as plus de POKéMON dans ton\n"
	.string "équipe, essaie de changer l'ordre\l"
	.string "de tes POKéMON.\p"
	.string "Cela pourrait te donner un avantage.$"

