CeladonCity_GameCorner_MapScripts::
	.byte 0

CeladonGameCorner_EventScript_PokefanM::
	msgbox CeladonGameCorner_Text_PokefanM, MSGBOX_NPC
	end

CeladonGameCorner_EventScript_Teacher::
	msgbox CeladonGameCorner_Text_Teacher, MSGBOX_NPC
	end

CeladonGameCorner_EventScript_FishingGuru::
	msgbox CeladonGameCorner_Text_FishingGuru, MSGBOX_NPC
	end

CeladonGameCorner_EventScript_Fisher1::
	msgbox CeladonGameCorner_Text_Fisher1, MSGBOX_NPC
	end

CeladonGameCorner_EventScript_Fisher2::
	msgbox CeladonGameCorner_Text_Fisher2, MSGBOX_NPC
	end

CeladonGameCorner_EventScript_GymGuide::
	msgbox CeladonGameCorner_Text_GymGuide, MSGBOX_NPC
	end

CeladonGameCorner_EventScript_Gramps::
	msgbox CeladonGameCorner_Text_Gramps, MSGBOX_NPC
	end

CeladonGameCorner_Text_PokefanM:
	.string "Les machines à sous sont toutes\n"
	.string "ultramodernes.$"

CeladonGameCorner_Text_Teacher:
	.string "C'est cette machine que je veux.\p"
	.string "Elle m'a tout pris hier, alors elle\n"
	.string "devrait payer aujourd'hui.$"

CeladonGameCorner_Text_FishingGuru:
	.string "Je pense que cette machine va\n"
	.string "payer…\p"
	.string "Les chances varient selon les machines.$"

CeladonGameCorner_Text_Fisher1:
	.string "Gahahaha!\p"
	.string "Les jetons ne cessent de sortir !\p"
	.string "Hein ? Quoi, gamin ? Tu veux jouer ?\p"
	.string "Je vais partager ma chance avec toi !$"

CeladonGameCorner_Text_Fisher2:
	.string "Gahahaha!\p"
	.string "Ça me fait plaisir de faire de bonnes\n"
	.string "actions pour les autres !$"

CeladonGameCorner_Text_GymGuide:
	.string "Hé ! CHAMPION en devenir !\p"
	.string "Tu joues aux machines à sous aussi ?\p"
	.string "J'essaie d'avoir assez de jetons pour\n"
	.string "un POKéMON en récompense.\p"
	.string "Mais je n'ai pas encore assez de jetons…$"

CeladonGameCorner_Text_Gramps:
	.string "Hmmm… Les chances sont sûrement\n"
	.string "meilleures sur la ligne de PIKACHU, mais…\n"
	.string "Que faire ?$"
