VermilionCityFanClub_MapScripts::
	.byte 0

PokemonFanClub_Text_Chairman_Intro:
	.string "I'm the CHAIRMAN of the POKéMON\n"
	.string "FAN CLUB.\p"
	.string "I've raised over 150 POKéMON.\p"
	.string "I'm very fussy when it comes to\n"
	.string "POKéMON.\p"
	.string "Did you visit just to hear about\n"
	.string "my POKéMON?$"

PokemonFanClub_Text_Chairman_Rapidash:
	.string "Good! Then listen up!\p"
	.string "So… my favorite RAPIDASH…\p"
	.string "It… cute… lovely… smart…\n"
	.string "unbearably…\l"
	.string "plus… amazing… oh… you think\n"
	.string "so?…\l"
	.string "Too much… wild… beautiful…\n"
	.string "kindly…\l"
	.string "love it!\p"
	.string "Hug it… when… sleeping… warm\n"
	.string "and cuddly…\l"
	.string "Oh, and… spectacular…\n"
	.string "ravishing… simply divine…\p"
	.string "Oops! Look at the time!\n"
	.string "I've kept you too long!$"

PokemonFanClub_Text_Chairman_Gift:
	.string "Thanks for hearing me out.\n"
	.string "I want you to have this!$"

PokemonFanClub_Text_Chairman_Candy:
	.string "It's a RARE CANDY that makes\n"
	.string "POKéMON stronger.\p"
	.string "I prefer making my POKéMON\n"
	.string "stronger by battling, so you\n"
	.string "can have it.$"

PokemonFanClub_Text_Chairman_MoreTales:
	.string "Hello, {PLAYER}!\p"
	.string "Did you come see me about my\n"
	.string "POKéMON again?\p"
	.string "No? Oh… I had more tales to\n"
	.string "tell…$"

PokemonFanClub_Text_Chairman_Disappointed:
	.string "How disappointing…\p"
	.string "Come back if you want to listen.$"

PokemonFanClub_Text_Receptionist:
	.string "Our CHAIRMAN is very vocal when\n"
	.string "it comes to POKéMON…$"

PokemonFanClub_Text_ClefairyGuy_Adorable:
	.string "I love the way CLEFAIRY waggles\n"
	.string "its finger when it's trying to\l"
	.string "use METRONOME.\p"
	.string "It's so adorable!$"

PokemonFanClub_Text_ClefairyGuy_MakingDo:
	.string "I love CLEFAIRY, but I could\n"
	.string "never catch one.\p"
	.string "So I'm making do with a\n"
	.string "POKé DOLL that I found.$"

PokemonFanClub_Text_ClefairyGuy_ReturnDoll:
	.string "Oh, I see now. The girl who lost\n"
	.string "this POKé DOLL is sad…\p"
	.string "OK. Could you take this POKé DOLL\n"
	.string "back to that poor little girl?\p"
	.string "I'll befriend a real CLEFAIRY on\n"
	.string "my own one day. No worries!$"

PokemonFanClub_Text_ReceivedDoll:
	.string "{PLAYER} received POKé DOLL.$"

PokemonFanClub_Text_ClefairyGuy_GoingToGetOne:
	.string "You watch. I'm going to get a\n"
	.string "real CLEFAIRY as my friend.$"

PokemonFanClub_Text_ClefairyGuy_PackFull:
	.string "Your PACK is jammed full.$"

PokemonFanClub_Text_Teacher:
	.string "Look at my darling BAYLEEF!\p"
	.string "The leaf on its head is so cute!$"

PokemonFanClub_Text_ClefairyDoll:
	.string "It's a CLEFAIRY! Huh?\p"
	.string "Oh, right. It's a CLEFAIRY POKé\n"
	.string "DOLL.$"

PokemonFanClub_Text_Bayleef:
	.string "BAYLEEF: Li liif!$"

PokemonFanClub_Text_Listen:
	.string "Let's all listen politely to\n"
	.string "other trainers.$"

PokemonFanClub_Text_Bragging:
	.string "If someone brags, brag right\n"
	.string "back!$"
