.set LOCALID_DRAGONSDEN3_CLAIR, 4
.set LOCALID_DRAGONSDEN3_ELDER, 1

DragonsDen3_MapScripts::
	@map_script MAP_SCRIPT_ON_FRAME_TABLE, DragonsDen3_OnFrame
	.byte 0

DragonsDen3_OnFrame::
	map_script_2 VAR_BLACKTHORN_CITY_STATE, 2, DragonsDen3_Trigger_ElderQuizTop
	.2byte 0

DragonsDen3_EventScript_Elder::
	lock
	faceplayer
	goto_if_ge VAR_BLACKTHORN_CITY_STATE, 4, DragonsDen3_EventScript_ElderChooseDratini
	msgbox DragonsDen3_Text_ComeAgain, MSGBOX_DEFAULT
	release
	end

DragonsDen3_Trigger_ElderQuizLeft::
	lock
	applymovement2 OBJ_EVENT_ID_PLAYER, DragonsDen3_Movement_PlayerWalkToElderLeft
	applymovement2 OBJ_EVENT_ID_FOLLOWER, DragonsDen3_Movement_MonWalkToElderLeft
	waitmovement OBJ_EVENT_ID_FOLLOWER
	waitmovement OBJ_EVENT_ID_PLAYER
	delay 10
	lockall
	goto DragonsDen3_EventScript_ElderOfferQuiz

DragonsDen3_Trigger_ElderQuizTop::
	lock
	applymovement2 OBJ_EVENT_ID_PLAYER, DragonsDen3_Movement_PlayerWalkToElderTop
	applymovement2 OBJ_EVENT_ID_FOLLOWER, DragonsDen3_Movement_PlayerWalkToElderTop
	waitmovement OBJ_EVENT_ID_FOLLOWER
	waitmovement OBJ_EVENT_ID_PLAYER
	delay 10
	lockall
	goto DragonsDen3_EventScript_ElderOfferQuiz

DragonsDen3_Trigger_ElderQuizRight::
	lock
	applymovement2 OBJ_EVENT_ID_PLAYER, DragonsDen3_Movement_PlayerWalkToElderRight
	applymovement2 OBJ_EVENT_ID_FOLLOWER, DragonsDen3_Movement_MonWalkToElderRight
	waitmovement OBJ_EVENT_ID_FOLLOWER
	waitmovement OBJ_EVENT_ID_PLAYER
	delay 10
	lockall
	goto DragonsDen3_EventScript_ElderOfferQuiz


DragonsDen3_Movement_PlayerWalkToElderLeft:
	walk_up
	walk_right
	walk_up
	walk_up
	walk_up
	walk_up
	walk_up
	step_end

DragonsDen3_Movement_MonWalkToElderLeft:
	walk_left
	walk_up
	walk_right
	walk_up
	walk_up
	walk_up
	walk_up
	step_end

DragonsDen3_Movement_PlayerWalkToElderTop:
	walk_up
	walk_up
	walk_up
	walk_up
	walk_up
	step_end

DragonsDen3_Movement_PlayerWalkToElderRight:
	walk_up
	walk_left
	walk_up
	walk_up
	walk_up
	walk_up
	walk_up
	step_end
DragonsDen3_Movement_MonWalkToElderRight:
	walk_right
	walk_up
	walk_left
	walk_up
	walk_up
	walk_up
	walk_up
	step_end

DragonsDen3_EventScript_ElderOfferQuiz::
	msgbox DragonsDen3_Text_ElderGreeting, MSGBOX_DEFAULT
	setvar VAR_DRAGONS_DEN_QUIZ, 0
	goto DragonsDen3_EventScript_ElderQuiz1

DragonsDen3_EventScript_ElderQuiz1::
	message DragonsDen3_Text_Question1
	multichoice 20, 6, MULTI_ELDERQUIIZ1, FALSE 
	switch VAR_RESULT
	case 0, DragonsDen3_EventScript_ElderQuiz1Correct
	case 2, DragonsDen3_EventScript_ElderQuiz1Correct
	case MULTI_B_PRESSED, DragonsDen3_EventScript_ElderQuiz1
	call DragonsDen3_EventScript_ElderWrong
	goto DragonsDen3_EventScript_ElderQuiz1

DragonsDen3_EventScript_ElderQuiz1Correct::
	msgbox DragonsDen3_Text_RightAnswer, MSGBOX_DEFAULT
	goto DragonsDen3_EventScript_ElderQuiz2

DragonsDen3_EventScript_ElderQuiz2::
	message DragonsDen3_Text_Question2
	multichoice 20, 6, MULTI_ELDERQUIIZ2, FALSE 
	switch VAR_RESULT
	case 0, DragonsDen3_EventScript_ElderQuiz2Correct
	case 1, DragonsDen3_EventScript_ElderQuiz2Correct
	case MULTI_B_PRESSED, DragonsDen3_EventScript_ElderQuiz2
	call DragonsDen3_EventScript_ElderWrong
	goto DragonsDen3_EventScript_ElderQuiz2

DragonsDen3_EventScript_ElderQuiz2Correct::
	msgbox DragonsDen3_Text_RightAnswer, MSGBOX_DEFAULT
	goto DragonsDen3_EventScript_ElderQuiz3

DragonsDen3_EventScript_ElderQuiz3::
	message DragonsDen3_Text_Question3
	multichoice 20, 6, MULTI_ELDERQUIIZ3, FALSE 
	switch VAR_RESULT
	case 1, DragonsDen3_EventScript_ElderQuiz3Correct
	case 2, DragonsDen3_EventScript_ElderQuiz3Correct
	case MULTI_B_PRESSED, DragonsDen3_EventScript_ElderQuiz3
	call DragonsDen3_EventScript_ElderWrong
	goto DragonsDen3_EventScript_ElderQuiz3

DragonsDen3_EventScript_ElderQuiz3Correct::
	msgbox DragonsDen3_Text_RightAnswer, MSGBOX_DEFAULT
	goto DragonsDen3_EventScript_ElderQuiz4

DragonsDen3_EventScript_ElderQuiz4::
	message DragonsDen3_Text_Question4
	multichoice 20, 6, MULTI_ELDERQUIIZ4, FALSE 
	switch VAR_RESULT
	case 0, DragonsDen3_EventScript_ElderQuiz4Correct
	case 2, DragonsDen3_EventScript_ElderQuiz4Correct
	case MULTI_B_PRESSED, DragonsDen3_EventScript_ElderQuiz4
	call DragonsDen3_EventScript_ElderWrong
	goto DragonsDen3_EventScript_ElderQuiz4

DragonsDen3_EventScript_ElderQuiz4Correct::
	msgbox DragonsDen3_Text_RightAnswer, MSGBOX_DEFAULT
	goto DragonsDen3_EventScript_ElderQuiz5

DragonsDen3_EventScript_ElderQuiz5::
	message DragonsDen3_Text_Question5
	multichoice 20, 6, MULTI_ELDERQUIIZ5, FALSE 
	switch VAR_RESULT
	case 2, DragonsDen3_EventScript_ElderQuizFinish
	case MULTI_B_PRESSED, DragonsDen3_EventScript_ElderQuiz5
	call DragonsDen3_EventScript_ElderWrong
	goto DragonsDen3_EventScript_ElderQuiz5

DragonsDen3_EventScript_ElderWrong::
	msgbox DragonsDen3_Text_WrongAnswer1, MSGBOX_DEFAULT
	addvar VAR_DRAGONS_DEN_QUIZ, 1
	return

DragonsDen3_EventScript_ElderQuizFinish::
	msgbox DragonsDen3_Text_RightAnswer, MSGBOX_DEFAULT
	delay 20
	msgbox DragonsDen3_Text_PassedTest, MSGBOX_DEFAULT
	closemessage
	goto DragonsDen3_EventScript_ClairEnter


DragonsDen3_Text_ElderGreeting:
    .string "Hm… Good to see you here.\p"
    .string "No need to explain why you came.\p"
    .string "CLAIR sent you here, didn't she?\p"
    .string "That girl is a handful…\p"
    .string "I am sorry, but I must test you.\p"
    .string "Not to worry, you are to answer\n"
    .string "only a few questions.\p"
    .string "Ready?$"

DragonsDen3_Text_Question1:
    .string "What are POKéMON to you?$"

DragonsDen3_Text_Question2:
    .string "What helps you to win battles?$"

DragonsDen3_Text_Question3:
    .string "What kind of trainer do you wish\n"
    .string "to battle?$"

DragonsDen3_Text_Question4:
    .string "What is most important for\n"
    .string "raising POKéMON?$"

DragonsDen3_Text_Question5:
    .string "Strong POKéMON. Weak POKéMON.\n"
    .string "Which is more important?$"

DragonsDen3_Text_WrongAnswer1:
    .string "Hah? I didn't quite catch that…$"

DragonsDen3_Text_WrongAnswer2:
    .string "What was it you said?$"

DragonsDen3_Text_RightAnswer:
    .string "Oh, I understand…$"

DragonsDen3_Text_PassedTest:
    .string "Hm… I see…\p"
    .string "You care deeply for POKéMON.\p"
    .string "Very commendable.\p"
    .string "That conviction is what is\n"
    .string "important!\p"
    .string "{PLAYER}, don't lose that belief.\p"
    .string "It will see you through at the\n"
    .string "POKéMON LEAGUE.$"

DragonsDen3_EventScript_ClairEnter::
	clearflag FLAG_HIDE_DRAGONS_DEN3_CLAIR
	addobject LOCALID_DRAGONSDEN3_CLAIR
	playse SE_DOOR
	delay 40
	playse SE_PIN
	applymovement2 OBJ_EVENT_ID_PLAYER, Common_Movement_ExclamationMark
	turnobject OBJ_EVENT_ID_PLAYER, DIR_SOUTH
	delay 20
	turnobject OBJ_EVENT_ID_FOLLOWER, DIR_SOUTH
	applymovement2 LOCALID_DRAGONSDEN3_CLAIR, DragonsDen3_Movement_ClairEnter
	waitmovement 0
	turnobject LOCALID_DRAGONSDEN3_ELDER, DIR_WEST	
	turnobject OBJ_EVENT_ID_PLAYER, DIR_WEST
	turnobject OBJ_EVENT_ID_FOLLOWER, DIR_NORTH
	msgbox DragonsDen3_Text_ClairYouPassed, MSGBOX_DEFAULT
	applymovement2 LOCALID_DRAGONSDEN3_CLAIR, DragonsDen3_Movement_ClairBackup1
	waitmovement 0
	msgbox DragonsDen3_Text_ClairThatCantBe, MSGBOX_DEFAULT
	applymovement2 LOCALID_DRAGONSDEN3_CLAIR, DragonsDen3_Movement_ClairBackup2
	waitmovement 0
	msgbox DragonsDen3_Text_ClairYoureLying, MSGBOX_DEFAULT
	applymovement2 LOCALID_DRAGONSDEN3_ELDER, DragonsDen3_Movement_ElderWalkToClair
	waitmovement 0
	turnobject LOCALID_DRAGONSDEN3_CLAIR, DIR_NORTH
	msgbox DragonsDen3_Text_MustIInformLance, MSGBOX_DEFAULT
	playse SE_PIN
	applymovement2 LOCALID_DRAGONSDEN3_CLAIR, Common_Movement_ExclamationMark
	msgbox DragonsDen3_Text_IUnderstand, MSGBOX_DEFAULT
	applymovement2 LOCALID_DRAGONSDEN3_CLAIR, DragonsDen3_Movement_ClairReturnToPlayer
	waitmovement 0
	msgbox DragonsDen3_Text_HereRisingBadge, MSGBOX_DEFAULT

	message DragonsDen3_Text_PlayerReceivedRisingBadge
	waitmessage
	call Common_EventScript_PlayGymBadgeFanfare
	msgbox DragonsDen3_Text_RisingBadgeExplanation, MSGBOX_DEFAULT
	setflag FLAG_BADGE08_GET
	setflag FLAG_DEFEATED_BLACKTHORN_GYM
	addvar VAR_NUM_BADGES, 1
	setvar VAR_0x8008, 8
	call Common_EventScript_SetGymTrainers

	applymovement2 LOCALID_DRAGONSDEN3_ELDER, DragonsDen3_Movement_ElderReturnToPlayer
	waitmovement 0
	turnobject OBJ_EVENT_ID_PLAYER, DIR_NORTH
	turnobject LOCALID_DRAGONSDEN3_CLAIR, DIR_NORTH
	msgbox DragonsDen3_Text_ElderScoldsClair, MSGBOX_DEFAULT
	closemessage
	delay 20
	msgbox DragonsDen3_Text_Speechless, MSGBOX_DEFAULT
	closemessage
	applymovement2 LOCALID_DRAGONSDEN3_CLAIR, DragonsDen3_Movement_ClairLeave
	waitmovement 0
	playse SE_EXIT
	setflag FLAG_HIDE_DRAGONS_DEN3_CLAIR
	removeobject LOCALID_DRAGONSDEN3_CLAIR
	clearflag FLAG_HIDE_DRAGONS_DEN2_CLAIR
	setvar VAR_BLACKTHORN_CITY_STATE, 3
	release
	end

DragonsDen3_Movement_ClairEnter:
	walk_up
	walk_up
	walk_up
	walk_up
	walk_up
	walk_up
	face_right
	step_end

DragonsDen3_Movement_ClairBackup1:
	lock_facing_direction
	walk_fast_left
	unlock_facing_direction
	step_end

DragonsDen3_Movement_ClairBackup2:
	lock_facing_direction
	walk_slow_left
	unlock_facing_direction
	step_end

DragonsDen3_Movement_ElderWalkToClair:
	walk_left
	walk_left
	walk_left
	face_down
	step_end

DragonsDen3_Movement_ClairReturnToPlayer:
	walk_right
	walk_right
	step_end

DragonsDen3_Movement_ElderReturnToPlayer:
	walk_slow_right
	walk_slow_right
	walk_slow_right
	face_down
	step_end

DragonsDen3_Movement_ClairLeave:
	walk_fast_down
	walk_fast_down
	walk_fast_down
	walk_fast_right
	walk_fast_down
	walk_fast_down
	walk_fast_down
	walk_fast_down
	step_end

DragonsDen3_Text_ClairYouPassed:
    .string "So how did it go?\p"
    .string "I guess there's no point in\n"
    .string "asking.\p"
    .string "You did fail?\p"
    .string "..................................\p"
    .string "…What? You passed?$"

DragonsDen3_Text_ClairThatCantBe:
    .string "That can't be!$"

DragonsDen3_Text_ClairYoureLying:
    .string "You're lying!\p"
    .string "Even I haven't been approved!$"

DragonsDen3_Text_MustIInformLance:
    .string "CLAIR!\p"
    .string "This child is impeccable, in\n"
    .string "skill and spirit!\p"
    .string "Admit defeat and confer the\n"
    .string "RISINGBADGE!\p"
    .string "…Or must I inform LANCE of this?$"

DragonsDen3_Text_IUnderstand:
    .string "I-I understand…$"

DragonsDen3_Text_HereRisingBadge:
    .string "Here, this is the RISINGBADGE…\p"
    .string "Hurry up! Take it!$"

DragonsDen3_Text_PlayerReceivedRisingBadge:
    .string "{PLAYER} received RISINGBADGE.$"

DragonsDen3_Text_RisingBadgeExplanation:
    .string "RISINGBADGE will enable your\n"
    .string "POKéMON to use the move for\l"
    .string "climbing waterfalls.\p"
    .string "Also, all POKéMON will recognize\n"
    .string "you as a trainer and obey your\l"
    .string "every command without question.$"

DragonsDen3_Text_ElderScoldsClair:
    .string "CLAIR…\p"
    .string "Reflect upon what it is that you\n"
    .string "lack and this child has.$"

DragonsDen3_Text_Speechless:
    .string "..................................$"

DragonsDen3_Text_ComeAgain:
    .string "Come again, if you so desire.$"

DragonsDen3_Text_SilverIsInTraining:
    .string "A boy close to your age is in\n"
    .string "training here.\p"
    .string "He is much like CLAIR when she was\n"
    .string "younger. It is a little worrisome…$"

DragonsDen3_EventScript_Elder2::
	msgbox DragonsDen3_Text_Elder2, MSGBOX_NPC
	end

DragonsDen3_EventScript_Elder3::
	msgbox DragonsDen3_Text_Elder3, MSGBOX_NPC
	end

DragonsDen3_Text_Elder2:
    .string "It's been quite some time since a\n"
    .string "trainer has gained our MASTER's\l"
    .string "rare approval.\p"
    .string "In fact, not since Master LANCE.$"

DragonsDen3_Text_Elder3:
    .string "You know young Master LANCE?\p"
    .string "He looks so much like our MASTER\n"
    .string "did in his youth.\p"
    .string "It's in their blood.$"

DragonsDen3_EventScript_ElderChooseDratini::
	goto_if_eq VAR_DRAGONS_DEN_QUIZ, 0, DragonsDen3_EventScript_ElderGiveSpecialDratini
	goto DragonsDen3_EventScript_ElderGiveBasicDratini

DragonsDen3_EventScript_ElderGiveBasicDratini::
	goto_if_set FLAG_GOT_DRATINI, DragonsDen3_EventScript_ElderAlreadyGotDratini
	msgbox DragonsDen3_Text_TakeThisDratini, MSGBOX_DEFAULT

	setvar VAR_TEMP_TRANSFERRED_SPECIES, SPECIES_DRATINI
	bufferspeciesname STR_VAR_1, SPECIES_DRATINI
	givemon SPECIES_DRATINI, 15
	call Common_EventScript_GiftMon

	msgbox DragonsDen3_Text_SymbolicDragon, MSGBOX_DEFAULT
	setflag FLAG_GOT_DRATINI
	release
	end

DragonsDen3_EventScript_ElderGiveSpecialDratini::
	goto_if_set FLAG_GOT_DRATINI, DragonsDen3_EventScript_ElderAlreadyGotDratini
	msgbox DragonsDen3_Text_TakeThisDratini, MSGBOX_DEFAULT

	setvar VAR_TEMP_TRANSFERRED_SPECIES, SPECIES_DRATINI
	bufferspeciesname STR_VAR_1, SPECIES_DRATINI
	givenamedmon 4
	call Common_EventScript_GiftMonNamed

	msgbox DragonsDen3_Text_SymbolicDragon, MSGBOX_DEFAULT
	setflag FLAG_GOT_DRATINI
	release
	end

DragonsDen3_EventScript_ElderAlreadyGotDratini::
	msgbox DragonsDen3_Text_ClairsGrandfather, MSGBOX_DEFAULT
	release
	end

DragonsDen3_Text_TakeThisDratini:
    .string "Hm… Good to see you here.\p"
    .string "Your arrival is most fortunate.\p"
    .string "I have something for you.\p"
    .string "Take this DRATINI as proof that I\n"
    .string "have recognized your worth.$"

DragonsDen3_Text_SymbolicDragon:
    .string "Dragon POKéMON are symbolic of our\n"
    .string "clan.\p"
    .string "You have shown that you can be\n"
    .string "entrusted with one.$"

DragonsDen3_Text_ClairsGrandfather:
    .string "CLAIR appears to have learned an\n"
    .string "invaluable lesson from you.\p"
    .string "I thank you as her grandfather.$"
