Common_EventScript_SetGymTrainers::
	switch VAR_0x8008
	case 1, VioletCity_Gym_SetGymTrainers
	case 2, AzaleaTown_Gym_SetGymTrainers
	case 3, GoldenrodCity_Gym_SetGymTrainers
	case 4, EcruteakCity_Gym_SetGymTrainers
	case 5, CianwoodCity_Gym_SetGymTrainers
	case 6, OlivineCity_Gym_SetGymTrainers
	case 7, MahoganyTown_Gym_SetGymTrainers
	case 8, BlackthornCity_Gym_SetGymTrainers
	case 9, PewterCity_Gym_SetGymTrainers
	case 10, CeruleanCity_Gym_SetGymTrainers
	case 11, VermilionCity_Gym_SetGymTrainers
	case 12, CeladonCity_Gym_SetGymTrainers
	case 13, SaffronCity_Gym_SetGymTrainers
	case 14, FuchsiaCity_Gym_SetGymTrainers
	case 15, CinnabarIsland_Gym_SetGymTrainers
	case 16, ViridianCity_Gym_SetGymTrainers
	end

VioletCity_Gym_SetGymTrainers::
	settrainerflag TRAINER_ROD
	settrainerflag TRAINER_ABE
	return

AzaleaTown_Gym_SetGymTrainers::
	settrainerflag TRAINER_BENNY
	settrainerflag TRAINER_AL
	settrainerflag TRAINER_JOSH
	settrainerflag TRAINER_AMY_AND_MAY
	return

GoldenrodCity_Gym_SetGymTrainers::
	settrainerflag TRAINER_CARRIE
	settrainerflag TRAINER_BRIDGET
	settrainerflag TRAINER_VICTORIA
	settrainerflag TRAINER_SAMANTHA
	return

EcruteakCity_Gym_SetGymTrainers::
	settrainerflag TRAINER_JEFFREY
	settrainerflag TRAINER_PING
	settrainerflag TRAINER_MARTHA
	settrainerflag TRAINER_GRACE
	return

CianwoodCity_Gym_SetGymTrainers::
	settrainerflag TRAINER_YOSHI
	settrainerflag TRAINER_LAO
	settrainerflag TRAINER_NOB
	settrainerflag TRAINER_LUNG
	return

OlivineCity_Gym_SetGymTrainers::

	return

MahoganyTown_Gym_SetGymTrainers::
	settrainerflag TRAINER_ROXANNE
	settrainerflag TRAINER_RONALD
	settrainerflag TRAINER_CLARISSA
	settrainerflag TRAINER_BRAD
	settrainerflag TRAINER_DOUGLAS
	return

BlackthornCity_Gym_SetGymTrainers::
	settrainerflag TRAINER_MIKE
	settrainerflag TRAINER_PAUL
	settrainerflag TRAINER_LOLA
	settrainerflag TRAINER_CODY
	settrainerflag TRAINER_FRAN
	return

PewterCity_Gym_SetGymTrainers::
	settrainerflag TRAINER_JERRY
	return

CeruleanCity_Gym_SetGymTrainers::
	settrainerflag TRAINER_DIANA
	settrainerflag TRAINER_BRIANA
	settrainerflag TRAINER_PARKER
	return

VermilionCity_Gym_SetGymTrainers::
	settrainerflag TRAINER_GREGORY
	settrainerflag TRAINER_VINCENT
	settrainerflag TRAINER_HORTON
	return

CeladonCity_Gym_SetGymTrainers::
	settrainerflag TRAINER_MICHELLE
	settrainerflag TRAINER_TANYA
	settrainerflag TRAINER_JULIA
	settrainerflag TRAINER_JO_AND_ZOE
	return

SaffronCity_Gym_SetGymTrainers::
	settrainerflag TRAINER_REBECCA
	settrainerflag TRAINER_FRANKLIN
	settrainerflag TRAINER_DORIS
	settrainerflag TRAINER_JARED
	return

FuchsiaCity_Gym_SetGymTrainers::
	settrainerflag TRAINER_ALICE
	settrainerflag TRAINER_LINDA
	settrainerflag TRAINER_CINDY
	settrainerflag TRAINER_BARRY
	return

CinnabarIsland_Gym_SetGymTrainers::
	return

ViridianCity_Gym_SetGymTrainers::
	return
