AquaHideout_UnusedRubyMap3_MapScripts::
	map_script MAP_SCRIPT_ON_TRANSITION, AquaHideout_UnusedRubyMap3_OnTransition
	.byte 0

AquaHideout_UnusedRubyMap3_OnTransition::
	end

AquaHideout_UnusedRubyMap3_BonslyMunchEvo::
	msgbox AquaHideout_UnusedRubyMap3_BonslyMunchEvo_Text, MSGBOX_NPC
	end

AquaHideout_UnusedRubyMap3_BonslyMunchEvo_Text:
	.string "As-tu déjà vu ces arbres étranges\n"
	.string "qui bougent ? Ce sont des POKéMON\l"
	.string "appelés SIMULARBRE ! Tu le savais ?\p"
	.string "C'est un POKéMON qui se déguise en\n"
	.string "petit arbre.\p"
	.string "Et il y a aussi MANZAÏ, qui fait la même\n"
	.string "chose… mais il n'a pas l'air aussi\l"
	.string "réaliste, je trouve.\p"
	.string "D'ailleurs, je les ai déjà vus évoluer en\n"
	.string "essayant d'imiter d'autres SIMULARBRE.\p"
	.string "C'est comme ça qu'ils évoluent ?\p"
	.string "Si je ne me trompe pas, MIME JR. évolue\n"
	.string "aussi en IMITANT d'autres POKéMON.\p"
	.string "Très différent de mon GOINFREX, qui a\n"
	.string "évolué par AMITIÉ, tu ne trouves pas ?$"
