WhirlIslands3_MapScripts::
	.byte 0

WhirlIslands3_EventScript_Item_Big_Nugget::
	finditem ITEM_BIG_NUGGET
	end

WhirlIslands3_EventScript_Item_Full_Restore::
	finditem ITEM_FULL_RESTORE
	end

WhirlIslands3_EventScript_Item_Carbos::
	finditem ITEM_CARBOS
	end

WhirlIslands3_EventScript_Item_Calcium::
	finditem ITEM_CALCIUM
	end

WhirlIslands3_EventScript_Item_Escape_Rope::
	finditem ITEM_ESCAPE_ROPE
	end
