DragonsDen2_MapScripts::
	.byte 0

DragonsDen2_Text_ClairGiveDragonbreath:
    .string "CLAIR: I'm sorry about this.\p"
    .string "Here, take this as my apology.$"

DragonsDen2_Text_ReceivedTM24:
    .string "{PLAYER} received TM24\n"
    .string "DRAGONBREATH.$"

DragonsDen2_Text_ClairDescribeDragonbreath:
    .string "That contains DRAGONBREATH.\p"
    .string "No, it doesn't have anything to\n"
    .string "do with my breath.\p"
    .string "If you don't want it, you don't\n"
    .string "have to take it.$"

DragonsDen2_Text_ClairNoRoom:
    .string "Oh? You don't have any room for\n"
    .string "this.\p"
    .string "I'm going back to the GYM, so\n"
    .string "make room, then come see me there.$"

DragonsDen2_Text_ClairWhatsTheMatter:
    .string "CLAIR: What's the matter? Aren't\n"
    .string "you going on to the POKéMON\l"
    .string "LEAGUE?\p"
    .string "After you become CHAMPION, you\n"
    .string "can rematch any GYM LEADER you\l"
    .string "want.\p"
    .string "Go to the POKéMON LEAGUE.\p"
    .string "Do you know how to get there?\p"
    .string "From here, go to NEW BARK TOWN.\p"
    .string "Then SURF east to POKéMON LEAGUE.\p"
    .string "The route there is very tough.\p"
    .string "Don't you dare lose at the POKéMON\n"
    .string "LEAGUE!\p"
    .string "If you do, I'll feel even worse\n"
    .string "about having lost to you!\p"
    .string "Give it everything you've got.$"

DragonsDen2_Text_DragonShrineSign:
    .string "DRAGON SHRINE\p"
    .string "A shrine honoring the dragon\n"
    .string "POKéMON\p"
    .string "said to have lived in DRAGON'S\n"
    .string "DEN.$"

DragonsDen2_Text_SilverTraining1:
    .string "…\n"
    .string "What? {PLAYER}?\p"
    .string "…No, I won't battle you now…\p"
    .string "My POKéMON aren't ready to beat\n"
    .string "you.\p"
    .string "I can't push them too hard now.\p"
    .string "I have to be dis-\n"
    .string "ciplined to become the greatest\l"
    .string "POKéMON trainer…$"

DragonsDen2_Text_SilverTraining2:
    .string "…\p"
    .string "Whew…\p"
    .string "Learn to stay out of my way…$"

DragonsDen2_Text_CooltrainermDarinSeen:
    .string "You! How dare you enter\n"
    .string "uninvited!$"

DragonsDen2_Text_CooltrainermDarinBeaten:
    .string "S-strong!$"

DragonsDen2_Text_CooltrainermDarinAfter:
    .string "The SHRINE ahead is home to the\n"
    .string "MASTER of our dragon-user clan.\p"
    .string "You're not allowed to just go in!$"

DragonsDen2_Text_CooltrainerfCaraSeen:
    .string "You shouldn't be in here!$"

DragonsDen2_Text_CooltrainerfCaraBeaten:
    .string "Oh yikes, I lost!$"

DragonsDen2_Text_CooltrainerfCaraAfter:
    .string "Soon I'm going to get permission\n"
    .string "from our MASTER to use dragons.\p"
    .string "When I do, I'm going to become an\n"
    .string "admirable dragon trainer and gain\l"
    .string "our MASTER's approval.$"

DragonsDen2_Text_TwinsLeaandPia1Seen:
    .string "It's a stranger we don't know.$"

DragonsDen2_Text_TwinsLeaandPia1Beaten:
    .string "Ouchies.$"

DragonsDen2_Text_TwinsLeaandPia1After:
    .string "It was like having to battle\n"
    .string "LANCE.$"

DragonsDen2_Text_TwinsLeaandPia2Seen:
    .string "Who are you?$"

DragonsDen2_Text_TwinsLeaandPia2Beaten:
    .string "Meanie.$"

DragonsDen2_Text_TwinsLeaandPia2After:
    .string "We'll tell on you.\p"
    .string "MASTER will be angry with you.$"

DragonsDen2_Text_FoundDragonFang:
    .string "{PLAYER} found "
    .string "!$"

DragonsDen2_Text_NoRoomForDragonFang:
    .string "But {PLAYER} can't carry any more\n"
    .string "items.$"
