NationalPark_MapScripts::
	.byte 0


NationalPark_Text_Lass:
	.string "Look! Check out my bag!\p"
	.string "I printed out my favorites from my\n"
	.string "POKéDEX and stuck them on my bag.$"

NationalPark_Text_PokefanF:
	.string "This is MAIL I got from my daughter.\n"
	.string "It cheers me up.$"

NationalPark_Text_Teacher1:
	.string "Pay attention, please!\p"
	.string "…Oops, I have to quit thinking like\n"
	.string "a teacher all the time.\p"
	.string "You must be a POKéMON trainer.\p"
	.string "Since you're working so hard, I\n"
	.string "want you to have this.$"

NationalPark_Text_Teacher1_QuickClaw:
	.string "Let a POKéMON hold that QUICK CLAW.\p"
	.string "Sometimes it will strike first\n"
	.string "during battle.$"

NationalPark_Text_Youngster1:
	.string "I'm playing with stickers I printed\n"
	.string "from my POKéDEX.$"

NationalPark_Text_Youngster2:
	.string "I get the other guy's POKéDEX sticker\n"
	.string "if I win.$"

NationalPark_Text_Teacher2:
	.string "I take walks in the PARK, but I\n"
	.string "never go into the grass.\p"
	.string "Trainers always want to battle…$"

NationalPark_Text_Persian:
	.string "PERSIAN: Fufushaa!$"

NationalPark_Text_GameboyKid:
	.string "I'm printing out my POKéDEX.\p"
	.string "You can also print out stuff like\n"
	.string "MAIL and your PC BOXES.$"

NationalPark_Text_SchoolboyJack1_Seen:
	.string "The world of POKéMON is deep.\p"
	.string "There are still lots of things we\n"
	.string "don't know.\p"
	.string "But I know more than you do!$"

NationalPark_Text_SchoolboyJack1_Beaten:
	.string "Wha-wha-what?$"

NationalPark_Text_SchoolboyJack_TradeMon:
	.string "There is a lot to learn.\p"
	.string "For example…\p"
	.string "There are 50 kinds of TMs.\p"
	.string "Traded POKéMON level up faster.$"

NationalPark_Text_PokefanFBeverly1_Seen:
	.string "My POKéMON are simply darling.\p"
	.string "Let me tell you how proud my\n"
	.string "darlings make me.$"

NationalPark_Text_PokefanFBeverly1_Beaten:
	.string "I can beat you in pride, but…$"

NationalPark_Text_PokefanFBeverly_CuteMon:
	.string "I must say, your POKéMON are quite\n"
	.string "cute, too.$"

NationalPark_Text_PokefanmWilliam_Seen:
	.string "We adore our POKéMON, even if they\n"
	.string "dislike us.\p"
	.string "That's what being a FAN is about.$"

NationalPark_Text_PokefanmWilliam_Beaten:
	.string "M-my POKéMON!$"

NationalPark_Text_PokefanmWilliam_After:
	.string "I lost the battle, but my POKéMON win\n"
	.string "the prize for being most lovely.$"

NationalPark_Text_PokefanFBeverly_Marill:
	.string "My friend keeps a MARILL!\p"
	.string "I find them very endearing.\p"
	.string "Oh, I wish for a MARILL of my own…$"

NationalPark_Text_LassKrise_Seen:
	.string "Hello? Why are you staring at me?\p"
	.string "Oh, a battle?$"

NationalPark_Text_LassKrise_Beaten:
	.string "…Hmmm…$"

NationalPark_Text_LassKrise_After:
	.string "I thought you were staring at me\n"
	.string "because I'm cute!$"

NationalPark_Text_Sign_RelaxationSquare:
	.string "RELAXATION SQUARE\n"
	.string "NATIONAL PARK$"

NationalPark_Text_Sign_BattleNotice:
	.string "What is this notice?\p"
	.string "Please battle only in the grass.\p"
	.string "NATIONAL PARK WARDEN'S OFFICE$"

NationalPark_Text_TrainerTips:
	.string "TRAINER TIPS\p"
	.string "Print out MAIL by opening it then\n"
	.string "pressing START.$"
