FuchsiaCityHouse1_MapScripts::
	.byte 0

FuchsiaCityHouse1_EventScript_BillsOlderSister::
	msgbox FuchsiaCityHouse1_Text_BillsOlderSister, MSGBOX_NPC
	end

FuchsiaCityHouse1_EventScript_Youngster::
	msgbox FuchsiaCityHouse1_Text_Youngster, MSGBOX_NPC
	end

FuchsiaCityHouse1_Text_BillsOlderSister:
	.string "My grandpa is at my brother BILL's\n"
	.string "on CERULEAN CAPE.$"

FuchsiaCityHouse1_Text_Youngster:
	.string "I saw these weird, slow POKéMON on\n"
	.string "CYCLING ROAD.$"

