FortreeCity_House3_MapScripts::
	.byte 0

FortreeCity_House3_EventScript_Maniac::
	msgbox FortreeCity_House3_Text_MetStevenHadAmazingPokemon, MSGBOX_NPC
	end

FortreeCity_House3_EventScript_SchoolKidM::
	msgbox FortreeCity_House3_Text_OhYouHavePokedex, MSGBOX_NPC
	end

FortreeCity_House3_Text_MetStevenHadAmazingPokemon:
	.string "En parlant de POKéDEX,\n"
	.string "je me suis souvenu de quelque chose.\p"
	.string "J'ai rencontré ce DRESSEUR, STEVEN, quand\n"
	.string "je cherchais des pierres rares.\p"
	.string "Ouh là, il avait des POKéMON incroyables\n"
	.string "avec lui.\p"
	.string "Ils n'étaient pas seulement rares, ils étaient\n"
	.string "entraînés à des niveaux terrifiants !\p"
	.string "Il est peut-être même plus fort que le\n"
	.string "CHAMPION d'ARÈNE de cette ville…$"

FortreeCity_House3_Text_OhYouHavePokedex:
	.string "Qu'est-ce que tu as là ?\p"
	.string "… … … … … …\p"
	.string "Oh, ça s'appelle un POKéDEX ?\n"
	.string "C'est vraiment génial !$"

