LilycoveCity_House4_MapScripts::
	.byte 0

LilycoveCity_House4_EventScript_Man1::
	msgbox LilycoveCity_House4_Text_MysteriesAtBottomOfSea, MSGBOX_NPC
	end

LilycoveCity_House4_EventScript_Man2::
	msgbox LilycoveCity_House4_Text_UnderwaterTrenchMossdeepSootopolis, MSGBOX_NPC
	end

LilycoveCity_House4_Text_MysteriesAtBottomOfSea:
	.string "Les plus grands mystères de cette planète\n"
	.string "se trouvent au fond de la mer.\p"
	.string "C'est ce que quelqu'un a dit, mais je ne sais pas…$"

LilycoveCity_House4_Text_UnderwaterTrenchMossdeepSootopolis:
	.string "Il y a une profonde tranchée sous-marine\n"
	.string "entre ALGATIA et SOOTOPOLIS.\p"
	.string "C'est ce que quelqu'un m'a dit, en tout cas.$"

